### ISSUE TITLE
[Dashboard] Filter test results

### ISSUE THREAD

**Issue by beniamin-kis** [zalando/zalenium#100]
Another neat feature that I'd like to see in the dashboard, is the ability to search for/filter out test results:
- by test execution date (today, last 3 days, last week etc)
- by test name (I only want to see the results for 'Test xy')

**Comment by diemol** [comment]
This was just released https://github.com/zalando/zalenium/releases/tag/3.3.1g, only simple text search though. We don't have enough resources to do the date search now, our FE skills are not that great :/ (PRs are welcome of course!)

@beniamin-kis please check it and feel free to reopen the issue if it does not work properly.
