### ISSUE TITLE
Number as build name breaks dashboard search

### ISSUE THREAD

**Issue by pschuermann** [zalando/zalenium#1007]
If the build name is just a number without a string prefix, it will break the search in the Dashboard. The search will just return all results. You can see the problem in the Console:

<img width="1128" alt="zalenium_query_bug" src="https://user-images.githubusercontent.com/55157/61277567-8e2b8e00-a806-11e9-9690-40a8d2b70805.png">

To reproduce:
1) create a test with build name=build_12345
2) create a test with build name=6789
3) search in dashboard for 6789 or build_12345 (it will return all tests in either case)

**Comment by diemol** [comment]
Fixed via #1008
