### ISSUE TITLE
Disconnect timeout

### ISSUE THREAD

**Issue by aalgarme** [zalando/zalenium#101]
I keep seeing this, what's this mean?
![image](https://cloud.githubusercontent.com/assets/10726943/25200001/cb201ae0-251a-11e7-8f33-356a9a546dbf.png)

**Comment by diemol** [comment]
@aalgarme That happens when the node is shutdown after the test execution, the VNC viewer cannot connect to the container anymore. It is the normal behaviour.

**Comment by diemol** [comment]
I'll close this one since it was a question which already has an answer. Please feel free to open more issues in case of errors or more questions.

**Comment by rajesh-kumar** [comment]
Hi @diemol this issue is occuring for us after every test execution i.e. after each scenario execution container is killed. Can you provide a hint on how/when test can cause container to die (considering cpu/memory is not the problem)?

**Comment by diemol** [comment]
@rajesh-kumar that is the default behaviour, one test and the container is thrown away.

**Comment by rajesh-kumar** [comment]
Thanks @diemol for quick response. is it possible to override this behaviour? or this is enforced?

**Comment by diemol** [comment]
Please check the docs for `--maxTestSessions`

**Comment by rajesh-kumar** [comment]
Great. Sorry, I missed reading about all these available configuration. Thank you so much.
