### ISSUE TITLE
Question about desiredContainers

### ISSUE THREAD

**Issue by axozoid** [zalando/zalenium#1017]
## 🐛 Bug Report

Not sure if that's a bug or desired/expected behaviour - please explain.

It turns out that containers set by `desiredContainers` are not being used for tests.

How it looks like:
1. let's say we have `desiredContainers = 2` and `maxDockerSeleniumContainers = 6`;
2. we send `1` test to Zalenium;
3. straight away we can see that **none of those 2 containers** (created at startup) have been used and instead - a new container has been created and presumably, our test started on that new container.

So, the questions here:
* Is that by design? 
* What's a purpose of having those `desiredContainers` ? 

I though that was done in order to speed up the testing, like if you have for example `desiredContainers = 6` and from time to time you throw 2-6 test to the grid - you don't need to wait for containers to be created at your first run or when you increase a number or tests because you always have enough of ready containers..

Please explain.

## To Reproduce
1. Do `kubectl get pods` for Zalenium namespace;
2. Send a test to the grid;
3. Do `kubectl get pods` for Zalenium namespace again and you'll see that a new container has been created;

Another way to prove that new tests disregard idle containers - if you set `DESIRED_CONTAINERS` == `MAX_DOCKER_SELENIUM_CONTAINERS` then no tests ever will be executed and all requests just go to a queue.

## Expected behavior

If we have idle containers running, I'd expect new tests to start on them instead of waiting for new containers.

## Environment

OS: 
Zalenium Image Version(s): dosel/zalenium:3.141.59r
Selenium image: elgalu/selenium:3.141.59-p14
Docker version: 17.03.2-ce
Kubernetes version: v1.10.13

**Comment by diemol** [comment]
@axozoid 
What are the capabilities offered by the 2 nodes already running and what are the capabilities being sent in the WebDriver test?

**Comment by ahuemmer** [comment]
@diemol 
We are experiencing the same issue and as each and every test is using the same set of capabilities (which, of course, is also the one offered by Zalenium), I'm quite sure it's rather kind of a bug than desired behavior. :)

**Comment by diemol** [comment]
Well, it all depends on the capabilities sent.
Zalenium has by default some available capabilities
- browserName
- platform
- screen resolution
- time zone

If the test is requesting any different capability from the configured ones, it will create a container with the requested ones.

Closing the issue since this is how Zalenium should behave.
