### ISSUE TITLE
Prestarted containers

### ISSUE THREAD

**Issue by madfromplay** [zalando/zalenium#1018]
## 🚀 Feature Proposal

It would be usefull if you can set up a number of containers zalenium keep on stand by, like desired containers, despite of current running tests

## Motivation

Spinup of new selenium container is fast, but not instant. It would be great if we have a standby container entire time, which can accept incoming test. 
This could decrease time consumed in total during automation test flow.

## Example

Current flow:

We have 3 desired containers. 
Jenkins job launches 5 parallel tests. 
3 of them assigned to free containers almost instantly.
Zalenium spin up 2 additional containers. (8-10 seconds)
2 tests assigned to new containers. 
another jenkins job launches 2 another tests.
zalenium spin up new containers
etc...

Desired flow:
We have 3 pre-launched containers.
Jenkins job launches 5 parralel tests.
Zalenium assign 3 tests to pre-launched containers and spin up 5 new one
2 of them are utilized by tests and 3 are kept in standby, ready to be utilized for tests. 

Thanks in advance. Semyon.

**Comment by diemol** [comment]
@madfromplay You can already do that with the configuration options that exist, if you start 10 tests, then set `desiredContainers` to 13. You can always measure how many tests are executed in parallel and set the `desiredContainers` to something above.
