### ISSUE TITLE
There is no yaml file to create kubernetes cluster

### ISSUE THREAD

**Issue by AnuvrathElastica** [zalando/zalenium#1021]
## 🐛 Bug Report

As per this description, i am trying to set up `Kubernetes` cluster on my local machine with `minikube`. But there is no yaml file to deploy the cluster and also when i run the shell scripts present under `zalenium/kubernetes/` its corrupting my whole `kubectl` and `minikube` setup. 

## Environment

OS: Mac 10.14.5
Zalenium Image Version(s): latest
Docker version: 2.0.0.3
Kubernetes version: v1.10.11

**Comment by diemol** [comment]
@AnuvrathElastica, we use [Helm](https://helm.sh/) for Kubernetes deployments.
Please check https://opensource.zalando.com/zalenium/#kubernetes
