### ISSUE TITLE
Unable to start zalenium in GKE.

### ISSUE THREAD

**Issue by ashkaps** [zalando/zalenium#1026]
I am following instructions on https://opensource.zalando.com/zalenium/#usage to try and setup zelenium cluster using helm chart.

I dont get the url to selenium grid when I try `minikube service --namespace zalenium zalenium`.
Is there any elaborate doc available on how to setup and use zalenium on GKE (not minikube).
Although, I was able to manually expose zalenium as a service to get an external ip url to get a link to the grid server. 
Am I missing something obvious?

kubectl version
`Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.9-gke.7", GitCommit:"b6001a5d99c235723fc19342d347eee4394f2005", GitTreeState:"clean", BuildDate:"2019-06-24T19:
27:39Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20
:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}`

helm version
`Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}`

docker info
`Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://asia-mirror.gcr.io/
 Live Restore Enabled: false
 Product License: Community Engine
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled`

**Comment by diemol** [comment]
@ashkaps why are you using `minikube` to deploy in GKE? Is that even possible?

As the documentation says, please use [helm](https://helm.sh/)
