### ISSUE TITLE
File download path

### ISSUE THREAD

**Issue by cnealaccela** [zalando/zalenium#1027]
This is a question

We have mapped a shared driver to each docker contain
In this shared drive is where we want the chrome instances to download files to
When we execute chrome locally, this can be done by setting option:

ChromeOptions chromeOptions = new ChromeOptions();
HashMap<String, Object> prefs = new HashMap<>();
prefs.put("download.default_directory", "path to directory");
chromeOptions.setExperimentalOption("prefs", prefs);

i.e. by using the "downloads.default_directory" option to the chrome driver

When trying to do the same with Zalenium its not working
I'm assuming this is because the containers are already executing and the chrome driver is already running and its options cannot be changed

Can you confirm please

Regards

p.s. Im not on slack

**Comment by diemol** [comment]
@cnealaccela please check "Mounting volumes/folders across containers" at https://opensource.zalando.com/zalenium/#docker.

If you have more questions, join us in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y) or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
