### ISSUE TITLE
Use REMOTE_DASHBOARD_HOST env which causes no execution history in http://localhost:4444/dashboard/

### ISSUE THREAD

**Issue by luisxiaomai** [zalando/zalenium#1029]
## 🐛 Bug Report

When using REMOTE_DASHBOARD_HOST env to send video and logs to some external system for storage, the http://localhost:4444/dashboard/ does not show any execution history. It seems executedTestsInfo.json will not be generated?

Can anyone help on this?

**Comment by diemol** [comment]
No, because everything is sent to the remote dashboard, nothing is handled by Zalenium.
