### ISSUE TITLE
Need help with using Zalenium

### ISSUE THREAD

**Issue by alan-Khadir** [zalando/zalenium#1030]
## 💬 Questions and Help

Hi,

Great work guys for creating this flexible and scalable container.

I'm not that familiar with selenium grid, docker or zalenuim so I would like a bit help please to be able to run my test in parallel using Zalenium.

I have used Zalenium in one of my personal specflow projects before and it was working fine however I have recently created another project which uses Ocaramba framework but I'm keep an error when running my tests. see below screenshot of the error. 
Link to Ocaramba framework if needed https://github.com/ObjectivityLtd/Ocaramba

I have set the following properties in app.config but I'm not sure if I need to set any additional DriverCapabilities for this to work.

 in App.config file.
    <add key="browser" value="RemoteWebDriver" />
    <add key="DriverCapabilities" value="Chrome" />
    <add key="RemoteWebDriverHub" value="http://localhost:4444/wd/hub" />

![falied to run error](https://user-images.githubusercontent.com/51816882/62539960-5edccf80-b84e-11e9-87ba-5d9cc660424b.PNG)

I have also attached the Browser Driver Log and Selenium Log.
![BrowserDriverLog](https://user-images.githubusercontent.com/51816882/62540608-ea0a9500-b84f-11e9-82d0-3d05e9586fd2.PNG)
![seleniumLog](https://user-images.githubusercontent.com/51816882/62540706-1d4d2400-b850-11e9-8093-e8e41cacc081.png)

**Comment by diemol** [comment]
Hi @alan-Khadir 
This is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.

**Comment by alan-Khadir** [comment]
Thanks for the above information.
