### ISSUE TITLE
Need help in understanding that how can I export my html reports after the execution of my UI tests on Zalenium

### ISSUE THREAD

**Issue by akshattambe** [zalando/zalenium#1033]
## 💬 Questions and Help
Hi,
Before I share my issue, I would like to say that this may be irrelevant to Zalenium forum. But I think you guys are the best people to solve this.

I am using Zalenium for running my selenium UI tests on the grid. when the execution is done I generate Cucumber HTML report using below maven configuration-

```
<cucumber.report.json.location>${project.basedir}/target/json</cucumber.report.json.location>
<generated.report.location>${project.basedir}/target/generated-report</generated.report.location>
```
And here is how it looks the logs when the reports are generated successfully - 
```
[INFO] ------------------------------------------------------------------------
[INFO]  Cluecumber Report Maven Plugin, version 1.10.2
[INFO] ------------------------------------------------------------------------
[INFO] - source JSON report directory                : /home/jenkins/agent/workspace/tie-ui-tests_develop/tie-ui-tests/sel-grid-tool/target/json
[INFO] - generated HTML report directory             : /home/jenkins/agent/workspace/tie-ui-tests_develop/tie-ui-tests/sel-grid-tool/target/generated-report
[INFO] ------------------------------------------------------------------------
[INFO] - fail scenarios with pending/undefined steps : false
[INFO] - expand before/after hooks                   : false
[INFO] - expand step hooks                           : false
[INFO] - expand doc strings                          : false
[INFO] ------------------------------------------------------------------------
[INFO] => Cluecumber Report: /home/jenkins/agent/workspace/tie-ui-tests_develop/tie-ui-tests/sel-grid-tool/target/generated-report/index.html
[INFO] ------------------------------------------------------------------------
```

But when I try to access the path above, it just does not exist. I know that it might not exist. But I am trying to explore, if HTML reports are getting generated, how can I get hold of them

If anyone can help me here, I really appreciate it and it will be a great help. I am new to Dockers and Kubernetes so it a black box for me to so it on my own. 

If you need any more details I will be happy to share.

Thanks in advance
Akshat

**Comment by pearj** [comment]
Hi @akshattambe,

As stated in the questions and help template, this is not a help forum.

For questions or help please see:

- [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium)
- [Slack channel - #zalenium channel](https://seleniumhq.herokuapp.com/)

However, your question doesn't seem related selenium at all, so you're probably best to use stackoverflow, with a cucumber tag or something to that effect.
