### ISSUE TITLE
Can we use different Chrome or Firefox version?

### ISSUE THREAD

**Issue by vhoang1102** [zalando/zalenium#1042]
Hi Zalenium team,

Thanks for greate product. I would like to ask whether we can create mutiple instances that run different browser version? And do we support Safari browser?

Thanks,
Hoang

**Comment by diemol** [comment]
Not really, at the moment Zalenium only supports one docker image with a given version of Firefox and Chrome.
Safari is not possible due to hardware limitations and licensing.

**Comment by diemol** [comment]
And thanks for the kind words!
