### ISSUE TITLE
Too much DNS load on pod readiness with kubernetes

### ISSUE THREAD

**Issue by jlamaille** [zalando/zalenium#1049]
## 🐛 Bug Report
We use zalenium with kubernetes, the readiness status causes a heavy load on our DNS.
Indeed the use of the method "getent" causes calls to the DNS which tries to solve urls of the type:
disulfur-40000-c757p.google.internal
disulfur-40000-c757p.x.c.f ..... internal
etc.
A call made by the readiness status generates at least 4 calls on the DNS times the number pods with a short frequency, the load is very important.

## To Reproduce
Deploy a Zalenium infrastructure with a service account in a kubernetes environment and a corporate dns.
There are load peaks on the DNS due to the readiness of Selenium nodes.

## Expected behavior
No load peaks on the DNS.

## Environment
OS: Linux
Zalenium Image Version(s): last version
Version Docker : 18.09
Version Kubernetes : 1.13.7-gke.8

**Comment by jlamaille** [comment]
I made a PR to fix that issue : #1048

**Comment by diemol** [comment]
Closed via #1048
