### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by TestAutomation85** [zalando/zalenium#105]
Can we please have support for Windows? 
Thanks

**Comment by diemol** [comment]
Hi @TestAutomation85,
It should work on Windows, someone in the Gitter chat told me that this command works for Windows 8.1 (please check local paths)

```
docker run --rm -ti --name zalenium -p 4444:4444 -p 5555:5555 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /c/Users/raj/temp/videos:/home/seluser/videos \
    dosel/zalenium start
```

**Comment by TestAutomation85** [comment]
Thanks @diemol for your quick response. In case of Windows, would it run Internet Explorer locally in addition to Chrome and Firefox?

**Comment by diemol** [comment]
Ah ok, are you asking about:
* Supporting Internet Explorer directly in Zalenium with docker? -> This is not possible yet since it is not possible to run Windows with a UI in docker, yet.
or
* You have your own machine with Internet Explorer and you want to connect it to Zalenium?

**Comment by TestAutomation85** [comment]
Oh ok @diemol. Can you tell me a little more about adding your machine to the Zalenium grid? Does this mean I can have a mix of Docker containers and regular VMs connected to the Zalenium grid? 
What advantages does the Zalenium grid offer over the regular Selenium grid? Thanks for answering my queries.

**Comment by diemol** [comment]
Sure @TestAutomation85 

> Can you tell me a little more about adding your machine to the Zalenium grid?

Just like registering a normal node to the grid, but please avoid using port `5555` if the node is in the same machine since we use it for something else. E.g. with Safari, please adapt for IE.
```java -jar selenium-server-standalone-3.3.1.jar -role node -port 5556 -browser browserName=safari -hub http://localhost:4444/grid/register```

> Does this mean I can have a mix of Docker containers and regular VMs connected to the Zalenium grid?

In theory yes, but we have not tested it enough. If you can help us with that, it would be cool. Also with some documentation :)

> What advantages does the Zalenium grid offer over the regular Selenium grid? 

TL:DR -> To avoid the headache of setting up and maintaining a grid. Plus taking advantage of the "immutable infrastructure" promise by Docker.
Longer version, it is well explained in our [_Why_](https://github.com/zalando/zalenium#why-zalenium).

**Comment by diemol** [comment]
@TestAutomation85 I'll close this issue due to inactivity.
If you have more questions you can create a new one or just join our Gitter chat https://gitter.im/zalando/zalenium
We can also discuss these things there :)

**Comment by charmi25** [comment]
> ```
> docker run --rm -ti --name zalenium -p 4444:4444 -p 5555:5555 \
>     -v /var/run/docker.sock:/var/run/docker.sock \
>     -v /c/Users/raj/temp/videos:/home/seluser/videos \
>     dosel/zalenium start
> ```


@diemol  and @VigneshVRP  
I tried above command on windows but I am getting below error:

Single Line Commad:
docker run --rm -ti --name zalenium -p 4444:4444 -p 5555:5555 -v /var/run/docker.sock:/var/run/docker.sock  -v /c/Users/503173907/temp/videos:/home/seluser/videos  dosel/zalenium start



C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: invalid volume specification: '/var/run/docker.sock:/var/run/docker.sock'.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.

I tried searching for the problem a lot but not getting any proper solution.
