### ISSUE TITLE
Unable to pull elgalu/selenium and dosel/zalenium images into my Kubernestes cluster

### ISSUE THREAD

**Issue by sayom88** [zalando/zalenium#1050]
## 🐛 Bug Report

Hello,
I have set up a Kubernetes cluster.(not via Minikube) using our company cloud. Now I want to implement Zalenium by pulling the  elgalu/selenium and dosel/zalenium images into my Kubernestes cluster. 

Can you please let me know the exact command in order to do the same,since in the Zalenium portal, it is being shown only via Minikube.

## Environment

OS:  Windows 10
Zalenium Image Version(s):  Latest
Docker version:  2.1.0.2

**Comment by diemol** [comment]
This is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
