### ISSUE TITLE
Possibility to create nodes with modified /etc/hosts via DesiredCapabilities.

### ISSUE THREAD

**Issue by sanchek** [zalando/zalenium#1054]
## 🚀 Feature Proposal
Feature request similar to https://github.com/zalando/zalenium/issues/182.

## Motivation
So it will be great if we can create nodes with modified /etc/hosts via DesiredCapabilities in runtime.

## Example
`DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
            desiredCapabilities.setCapability(CapabilityType.BROWSER_NAME, BrowserType.FIREFOX);
            desiredCapabilities.setCapability(CapabilityType.PLATFORM, Platform.LINUX);
            desiredCapabilities.setCapability("extra_hosts", "google.com:127.0.0.1");`

**Comment by diemol** [comment]
Closing this as it is being treated in #1060
