### ISSUE TITLE
zalenium-3.141.59t.tgz doesn't contain a valid tarball

### ISSUE THREAD

**Issue by ahuemmer** [zalando/zalenium#1057]
## 🐛 Bug Report

After downloading the helm chart [zalenium-3.141.59t.tgz](https://github.com/zalando/zalenium/blob/master/charts/zalenium/zalenium-3.141.59t.tgz) you'll find that there's no valid tarball inside the gz archive, but an HTML page from GitHub.

## To Reproduce

1. Download the archive from here: https://github.com/zalando/zalenium/blob/master/charts/zalenium/zalenium-3.141.59t.tgz
2. Try to unpack it using e. g. `tar -xvzf` or 7zip. &rarr; No valid tarball inside the gzip archive.
3. Unpack the "outer" gzip archive only and examine the content - you will see, that it's an HTML page from GitHub instead of a tarball (nevertheless it is named `.tar`).

## Expected behavior

The archive should contain a valid tarball, extractable e. g. by the means described above.

## Test script reproducing this issue (when applicable)

(See steps above.)

## Environment

OS: Windows 10 / Ubuntu
Zalenium Image Version(s): 3.141.59u
Docker version: not applicable

**Comment by diemol** [comment]
@ahuemmer of course,
when you go to that page, there is a `download` button, which has this link
https://github.com/zalando/zalenium/raw/master/charts/zalenium/zalenium-3.141.59t.tgz
and that is the correct one.
