### ISSUE TITLE
unable to create the mount points on nodes in zelenium docker swarm setup

### ISSUE THREAD

**Issue by manikantha-tadi** [zalando/zalenium#1058]
Hi Team,

We setup zelenium docker swarm setup for the selenium hub- node topology as per the documentation.

we followed the "Mounting volumes/folders across containers" section on https://opensource.zalando.com/zalenium/ " on https://opensource.zalando.com/zalenium/

but we are unable to see the mount points being created on selenium nodes to local folder of hub .

could you please help us whether this is supported on zelenium docker swarm setup. ?

**Comment by yosserO** [comment]
Hi @manikantha-tadi,

This is actually not supported in the docker swarm implementation.

**Comment by diemol** [comment]
Thanks for replying @yosserO!
Closing as this is a not supported feature
