### ISSUE TITLE
Getting a error while checking the logs for the Zalenium service running in Kubernetes....Trapped SIGTERM/SIGINT so shutting down Zalenium gracefully...

### ISSUE THREAD

**Issue by sayom88** [zalando/zalenium#1062]
I am running the command to check what is happening in the zalenium service in the kubernetes....**kubectl logs -f zalenium-6d96f4f6b-5tvs5 -n zalenium** and then I am getting the logs as below:
**Kubernetes service account found.
Copying files for Dashboard...
Starting Nginx reverse proxy...
Starting Selenium Hub...
................16:07:26.095 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium server version: 3.141.59, revision: unknown
..16:07:27.426 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
.........16:07:32.038 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - Initialising Kubernetes support
....................16:07:43.001 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - Kubernetes support initialised.
       Pod name: zalenium-6d96f4f6b-5tvs5
       app label: zalenium
       zalenium service name: zalenium
       Selenium Pod Resource Limits: {memory=Quantity(amount=2Gi, format=null, additionalProperties={}), cpu=Quantity(amount=1000m, format=null, additionalProperties={})}
       Selenium Pod Resource Requests: {memory=Quantity(amount=500Mi, format=null, additionalProperties={}), cpu=Quantity(amount=250m, format=null, additionalProperties={})}
16:07:43.002 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - About to clean up any left over docker-selenium pods created by Zalenium
....16:07:44.940 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Starting poller.
.............16:07:53.307 [main] INFO  d.z.ep.zalenium.aspect.HubAspect - Registering custom Zalenium servlets
...16:07:54.902 [main] INFO  org.openqa.grid.web.Hub - Selenium Grid hub is up and running
*16:07:54.904 [main] INFO  org.openqa.grid.web.Hub - Nodes should register to http://172.30.13.202:4445/grid/register/*
*16:07:54.904 [main] INFO  org.openqa.grid.web.Hub - Clients should connect to http://172.30.13.202:4445/wd/hub*
Selenium Hub started!
Sauce Labs not enabled...
Browser Stack not enabled...
TestingBot not enabled...
CBT not enabled...
LambdaTest not enabled...
Zalenium is now ready!
*************************************** Data Processing Agreement ***************************************
By using this software you agree that the following non-PII (non personally identifiable information)
data will be collected, processed and used by Zalando SE for the purpose of improving our test
infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
of the IP address are collected.
*See the complete license at https://github.com/zalando/zalenium/blob/master/LICENSE.md*
*************************************** Data Processing Agreement ***************************************
*16:10:15.103 [Thread-10] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.30.13.199:40000*
Trapped SIGTERM/SIGINT so shutting down Zalenium gracefully...
Stopping Hub...
*************************************** Data Processing Agreement ***************************************
By using this software you agree that the following non-PII (non personally identifiable information)
data will be collected, processed and used by Zalando SE for the purpose of improving our test
infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
of the IP address are collected.
*See the complete license at https://github.com/zalando/zalenium/blob/master/LICENSE.md*
*************************************** Data Processing Agreement ***************************************
16:10:39.710 [KubernetesContainerClient shutdown hook] INFO  d.z.e.z.c.k.KubernetesContainerClient - About to clean up any left over docker-selenium pods created by Zalenium
16:10:40.096 [Saving dashboard.] INFO  d.z.ep.zalenium.dashboard.Dashboard - Saving dashboard...**

As a result of this, I am not able to open the Zalenium dashboard nor the grid console ....any help will be much appreciated....

**Comment by diemol** [comment]
This is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
