### ISSUE TITLE
Placeholder in popup when trying to cleaning up the dashboard

### ISSUE THREAD

**Issue by PeterNgTr** [zalando/zalenium#1069]
## 🐛 Bug Report

Trying to clean up the dashboard by clicking `Cleanup` button and observing that there is placeholder in popup.

<img width="551" alt="Screenshot 2019-10-18 at 11 27 52" src="https://user-images.githubusercontent.com/7845001/67083020-a65ed080-f19a-11e9-8118-575d1ab8825d.png">

## To Reproduce

1. Open dashboard
2. Click cleanup button
3. Observe the popup

## Expected behavior

The placeholder shouldn't be there.

## Environment

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 53.04 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Virtualization:
    Docker: 19.03.2 - /usr/local/bin/docker
  Browsers:
    Chrome: 77.0.3865.120
```

**Comment by diemol** [comment]
Yes, if no tests have been executed, then the popup will have that placeholder. Not an elegant solution but ok enough for us. 
Would you like to give us a hand and send us a PR to fix it @PeterNgTr?

**Comment by PeterNgTr** [comment]
@diemol seems like after you clicked the reset button, the text on cleanup popup will work fine.

**Comment by diemol** [comment]
Yeah, that is expected, so if it is ok I will just close this issue and in case someone wants to help us with a more elegant solution, we will be happy to accept a PR.

Thanks, @PeterNgTr for raising this, an issue also serves as documentation 🙌!
