### ISSUE TITLE
[Live Preview] Add "Stop now" link

### ISSUE THREAD

**Issue by elgalu** [zalando/zalenium#107]
![image](https://cloud.githubusercontent.com/assets/111569/25524284/3cb97930-2c0a-11e7-9277-32c934cc56e8.png)

**Comment by jayeshchandorkar** [comment]
Hi Leo,

I was trying to setup zalenium dev environment on my local machine.
I was able to clone, build and run the docker image on my machine. However I am facing issue while running the Integration tests on it.

Details about the Environment:
I am using PC with Window 10 Home edition. Hence Docker is running in Oracle Virtualbox.
The docker is running on different IP and can not be accessed using localhost.

Am I missing something obvious for this setup?

Thanks,
Jayesh

**Comment by elgalu** [comment]
Hi @jayeshchandorkar ! thanks for giving a shot to this feature request.

Can we move this conversation to a chat? I created this room: https://gitter.im/zalenium-issue-107

**Comment by elgalu** [comment]
ping @jayeshchandorkar
