### ISSUE TITLE
Basic auth on Google Cloud Kubernetes - Backend service in UNHEALTHY state

### ISSUE THREAD

**Issue by monkpit** [zalando/zalenium#1071]
I am not able to get basic auth working on Google Cloud kubernetes with the zalenium helm charts. The zalenium pods all get created correctly, but it looks like the loadbalancer thinks the backend service is down with 401/unauthorized errors. Any tips?

I have tried changing the livenessProbe and readinessProbe from httpGet to tcpSocket on port 4444 to try and circumvent the auth requirement, but it did not work.

The issue I am seeing is essentially the same issue seen by the OP here: https://stackoverflow.com/questions/42967763/kubernetes-ingress-gce-keeps-returning-502-error/42971328

EDIT: I have also tried adding Authorization headers to the backend healthcheck via Google Cloud GUI but it continues to say the backend is unhealthy.

**Comment by monkpit** [comment]
@diemol any advice?

**Comment by diemol** [comment]
@monkpit no clue, sorry. 
Really hard to say something since we do not have an environment to try out that configuration, and we also are lacking the time to do that.

I will close this issue since it is more a question related to a given environment instead of a Zalenium bug/issue.
