### ISSUE TITLE
Zalenium pass the environment parameter to  elgalu/selenium image

### ISSUE THREAD

**Issue by qalinn** [zalando/zalenium#1072]
## 🚀 Feature Proposal

When you start Zalenium you must be able to pass the environment parameter for elgalu/selenium image

## Motivation

For the advanced users, they can configure how they want the elgalu/selenium image without to broke something on zalenium.  It is much bad if they will create their own image just because they want to set an environment variable. 
The effort cannot be big, because we can use a parameter like  --setEnvVarOnNodes "VAR1=Val1;VAR2=Val2"

## Example
You can start the nodes exactly how they were designed to be used.

@diemol 
@elgalu

**Comment by fbrandao** [comment]
To add to @qalinn request this would be extra valuable if you want to pass capabilities to the node containers.
In some situations you might end up with very similar node capabilities which leads tot the capability matcher to not use the desired one.

**Comment by diemol** [comment]
This is already possible through the env var `ZALENIUM_NODE_PARAMS`
https://github.com/zalando/zalenium/blob/9dbcb5d7505ccd6c0f16ecc42bc797e2c0d1e795/scripts/zalenium.sh#L438
