### ISSUE TITLE
The download file in zalenium node will be automatically rename like video name, is there anyway to let it just like the same when it was downloaded ?

### ISSUE THREAD

**Issue by loudDD** [zalando/zalenium#1075]
the file name will automatically changed if i download file in the zalenium node like below :
![image](https://user-images.githubusercontent.com/33220071/67826443-70f5a380-fb07-11e9-9ff1-5db43ad5454c.png)
Is ther anyway to make the name just same with download name in the node?

**Comment by loudDD** [comment]
such a emergency, pls let me know ,if there is any advise

**Comment by diemol** [comment]
It is not clear what you mean, can you please explain a bit more in detail?

**Comment by loudDD** [comment]
the file i download in the node is named 123.txt  and it was downloaded in the /home/seluser/videos which was mapped . but when i check the file in the local , its name changed like the screenshot

**Comment by diemol** [comment]
Yeah, that is the normal behavior. Otherwise we would have name conflicts when colleting the files from all the containers.

**Comment by loudDD** [comment]
is there anything i can avoid that ? i add other mapping like -v /tmp/download : /home/download; but the file does't show in my local. It looks like the mapping isn't established successfully

**Comment by diemol** [comment]
Not really, the idea is to make it simple for users. I think this is the first time some asks to change this behaviour. 
What are you trying to solve?

**Comment by loudDD** [comment]
i am trying to download some file and i can see the file in my machine ,so i can check the file content is right or wrong

**Comment by diemol** [comment]
Then we are talking about different things, what you see there are the recorded videos of the tests. If you want to access the downloaded files, check `Mounting volumes/folders across containers` on https://opensource.zalando.com/zalenium/

**Comment by rakeshnambiar** [comment]
@loudDD Have you find the answer for this question - `where the downloaded files will be saved by default?`

Like @diemol  mentioned above the volume has been mounted `/home/seluser/videos`  folder and I set the default chrome download path to `/home/seluser/videos`. However, I cannot see the file name inside the Zalenium/node container by using the command `find /home/seluser -name myfile.txt`. 

I think the question is pretty clear here - Does zalenium provides any provision to define the browser download location ? If yes - how and where that will be stored?

Appreciate both of your response - thanks
