### ISSUE TITLE
selenium container exited  in 120s

### ISSUE THREAD

**Issue by iblfw** [zalando/zalenium#1076]
## 🐛 Bug Report

There are so many same problems. such as "cannot forward the request'", "connect reset"...
I meet the question too. After read your source code, i find out it is a bug.  In "zalenium/src/main/java/de/zalando/ep/zalenium/proxy/DockeredSeleniumStarter.java
":

in function: "private Map<String, String> buildEnvVars"
     
        You set selenium node WAIT_TIMEOUT = 120s by
                               "envVars.put("WAIT_TIMEOUT", "120s");"
        
It means the selenium node container will exit in 120s. When the test case spend time more than 120s, the selenium node container will exit, so zalenium will disconnect with the node and lead to different errors. You should  let us set "WAIT_TIMEOUT" by env variable.

## To Reproduce

Select a test case which spend time more than 120s and  run it in node 

## Expected behavior

The test case undone, but the node container have already exited 

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Zalenium Image Version(s): 
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
If using Kubernetes, specify your environment, and if relevant your manifests:

**Comment by ls-sergii-buchovskyi** [comment]
can we increase this timeout by passing environment variable? In default values I haven't seen any 120s...

**Comment by iblfw** [comment]
No. "WAIT_TIMEOUT" is environment variable of  "elgalu/docker-selenium". I try it  work on selenium grid. But zalanium don't provide the  environment variable.  Their team only set the variable in their code.  So we have two choice. 1, wait them fix it . 2. we fix the code and rerun the dockfile

**Comment by iblfw** [comment]
```
private Map<String, String> buildEnvVars(TimeZone timeZone, Dimension screenSize, String hostIpAddress,
                                             boolean sendAnonymousUsageInfo, String nodePolling, String nodeRegisterCycle,
                                             String seleniumNodeParams, String seleniumNodeHost, int containerPort) {
        final int noVncPort = containerPort + NO_VNC_PORT_GAP;
        final int vncPort = containerPort + VNC_PORT_GAP;
        Map<String, String> envVars = new HashMap<>();
        envVars.put("ZALENIUM", "true");
        envVars.put("SELENIUM_HUB_HOST", hostIpAddress);
        envVars.put("SELENIUM_HUB_PORT", "4445");
        envVars.put("SELENIUM_NODE_HOST", seleniumNodeHost);
        envVars.put("GRID", "false");
        **envVars.put("WAIT_TIMEOUT", "120s");**
        envVars.put("PICK_ALL_RANDOM_PORTS", "false");
        envVars.put("VIDEO_STOP_SLEEP_SECS", "1");
        envVars.put("WAIT_TIME_OUT_VIDEO_STOP", "20s");
        envVars.put("SEND_ANONYMOUS_USAGE_INFO", String.valueOf(sendAnonymousUsageInfo));
        envVars.put("BUILD_URL", env.getStringEnvVariable("BUILD_URL", ""));
        envVars.put("NOVNC", "true");
        envVars.put("NOVNC_PORT", String.valueOf(noVncPort));
        envVars.put("VNC_PORT", String.valueOf(vncPort));
        envVars.put("SCREEN_WIDTH", String.valueOf(screenSize.getWidth()));
        envVars.put("SCREEN_HEIGHT", String.valueOf(screenSize.getHeight()));
        envVars.put("TZ", timeZone.getID());
        envVars.put("SELENIUM_NODE_REGISTER_CYCLE", nodeRegisterCycle);
        envVars.put("SEL_NODEPOLLING_MS", nodePolling);
        envVars.put("SELENIUM_NODE_PROXY_PARAMS", "de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy");
        envVars.put("MULTINODE", "true");
        envVars.put("SELENIUM_MULTINODE_PORT", String.valueOf(containerPort));
        envVars.put("CHROME", "false");
        envVars.put("FIREFOX", "false");
        envVars.put("SEL_BROWSER_TIMEOUT_SECS", String.valueOf(getBrowserTimeout()));
        if (ZALENIUM_RUNNING_LOCALLY) {
            envVars.put("SELENIUM_NODE_PARAMS", String.format("-remoteHost http://%s:%s", hostIpAddress, containerPort));
        } else {
            envVars.put("SELENIUM_NODE_PARAMS", seleniumNodeParams);
        }

        if (SwarmUtilities.isSwarmActive()) {
            envVars.put("SELENIUM_NODE_HOST", "__CONTAINER_IP__");
        }

        // Add the proxy vars
        envVars.putAll(zaleniumProxyVars);
        return envVars;
    }
```

**Comment by iblfw** [comment]
In elgalu/docker-selenium:
ENV FIREFOX_VERSION="${FF_VER}" \
  USE_SELENIUM="3" \
  CHROME_FLAVOR="stable" \
  DEBUG="false" \
  PICK_ALL_RANDOM_PORTS="false" \
  RANDOM_PORT_FROM="23100" \
  RANDOM_PORT_TO="29999" \
  USER="seluser" \
  HOME="/home/seluser" \
  VNC_STORE_PWD_FILE="/home/seluser/.vnc/passwd" \
  BIN_UTILS="/usr/bin" \
  MEM_JAVA_PERCENT=80 \
  WAIT_FOREGROUND_RETRY="2s" \
  WAIT_VNC_FOREGROUND_RETRY="6s" \
  XVFB_STARTRETRIES=0 \
  XMANAGER_STARTSECS=2 \
  XMANAGER_STARTRETRIES=3 \
  WAIT_TIMEOUT="45s" \

**Comment by diemol** [comment]
@iblfw I am sure that the behavior is not the one you mention, `WAIT_TIMEOUT` is used in `elgalu/selenium` to wait until some processes start, not to shut down the container. 

Nevertheless, if you think I am wrong, we are happy to receive a PR making that value configurable, where its default value is `120s`.

**Comment by iblfw** [comment]
@diemol  In fact, i use your default value to run selenium case, all selenium container will exit in 120s.  I just run the "elgalu/docker-selenium" without zalenium. Selenium container will exit in 45s. Like below:
"docker run -d --name=grid -p 4444:24444 -p 5900:25900 ^
     -e TZ="Asia/Shanghai" -v /dev/shm:/dev/shm ^
     -e "http_proxy=proxy-sifi.rd.corpintra.net:3128" ^
     -e "https_proxy=proxy-sifi.rd.corpintra.net:3128" ^
     -e "no_proxy=*.local, localhost, 127.0.0.1" ^
     --privileged elgalu/selenium"

If i modify the value to 1800s, container will exit in 1800s, like below:
"docker run -d --name=grid -p 4444:24444 -p 5900:25900 ^
     -e TZ="Asia/Shanghai" -v /dev/shm:/dev/shm ^
     -e "http_proxy=proxy-sifi.rd.corpintra.net:3128" ^
     -e "https_proxy=proxy-sifi.rd.corpintra.net:3128" ^
     -e "no_proxy=*.local, localhost, 127.0.0.1" ^
     -e WAIT_TIMEOUT="1800s" ^
     --privileged elgalu/selenium"

After setting the value = 1800s, compile to DockeredSeleniumStarter.class, copy to zalenium-3.141.59u,jar, and commit to a new image. All selenium container will exit in 1800s. Like below:
"docker run --rm -ti --name zalenium -p 4444:4444 ^
    -v /var/run/docker.sock:/var/run/docker.sock ^
    -v /tmp/videos:/home/seluser/videos ^
    -e "zalenium_http_proxy=proxy-sifi.rd.corpintra.net:3128" ^
    -e "zalenium_https_proxy=proxy-sifi.rd.corpintra.net:3128" ^
    -e "zalenium_no_proxy=*.local, localhost, 127.0.0.1" ^
    --privileged ivan/zalenium start --timeZone "Asia/Shanghai" ^
    --desiredContainers 1 ^
    --maxDockerSeleniumContainers 1"

You can set it = 10s, you will find selenium container exit in 10s. Try it , it will work.
So i believe WAIT_TIMEOUT  is used to wait some event. But maybe some parameter was wrong. The timeout will kill container.

**Comment by diemol** [comment]
The please send us a PR making that value configurable and we will be happy to accept it.
I will close this issue since there is no hard evidence and we are also open to receive a change to allow this variable's configuration to be changed. 
Thanks @iblfw and we'll be waiting for your PR 🎉
