### ISSUE TITLE
New way to keep dashboard history (relates to #99 and #100)

### ISSUE THREAD

**Issue by robertzett** [zalando/zalenium#108]
Further thinking about how make progress to solve #99 and prepare for #100 I would like to offer the following approach:

The basic idea is to store the history data in a json file instead of html.
This would provide the following advantages:
- easily parseable and changeable, like remove entries
- can be used to create the dashboard html via javascript on the client on demand

For this I had to do the following changes:
- Enhance TestInformation class to store some data which previously has been generated on the fly like the date and time and browser+version
- Add a new class TestInformationRepository responsible for storing and reading a list of tests as json and only some of the List interface methods, which are currently used. We might want to implement the complete List interface, if more List interface methods are going to be needed
- Remove class Dashboard and add a new class DashboardDataHandler which is responsible to take care of all files copied and created for the dashboard functionality
- Add mustache.min.js which is  a templating library used to render the dashboard html
- Rename dashboard_template.html to dashboard.html and add the ability to create the list of tests out of the dashboardData.json
- Changed CommonProxyUtilities slightly to better support new dashboard style
- In short the dashboard state has been kept in `list.html` and `executedTestsInfo.json` and is now combined in `dashboardData.json`. The number of tests with video which, if I am not mistaken, has not been used up to now is also part of dashboardData.json and could be calculated easily any time.

What did I change else?:
- pom.xml: I changed the phase to validate for the resources plugin to have all dashboard data in place when the unit-tests are running and thus being more close to the way it is running in the docker container later and also to save some extra mocking which would be needed otherwise
- Re-add the cleanup feature as it has been previously on my other branch

What is currently missing compared to the previous version?:
- The previous Dashboard class always removed some dashboard data files older than a day. This is currently not included anymore because we most likely will add some kind of periodic removal configuration shortly

Where would we go next with this?
- We need to think about periodic removal of video- and log-files. My proposal would be to add a configuration option to be used at Zalenium startup and specify the retention policy there. Like remove data older than a day
- For #100 we only need to filter the dashboardData json. Shouldn’t be too hard. Most time will go into thinking how we provide those configuration in the UI. 

Here is my current work: https://github.com/robertzett/zalenium/tree/new-dashboard-data
Please have a look at this and please tell me if it looks ok for you so far. I’ll create a pull request as soon as I had time to check why it can’t currently be merged automatically.

**Comment by diemol** [comment]
Thanks for the effort @robertzett! 
I just saw that you created the PR, so I would write my comments over there.

**Comment by diemol** [comment]
This is handled in the PR being merged #111 
Therefore I'll close this issue.
