### ISSUE TITLE
The CleanUp doesn't work

### ISSUE THREAD

**Issue by loudDD** [zalando/zalenium#1083]
After i click Cleanup , the history of video still exists in the dashboard. and even i delete the file in the  linux /tmp/videos , the video cannnot play, but the items still exists in the dashboard.
![image](https://user-images.githubusercontent.com/33220071/68463677-22a07d00-024a-11ea-8940-4707187e74be.png)
am i misunderstand the Cleanup function ?

**Comment by diemol** [comment]
Cleanup just deletes tests, videos and logs older than X days.
