### ISSUE TITLE
how to delete partial video recordings?

### ISSUE THREAD

**Issue by loudDD** [zalando/zalenium#1086]
e.g. i have 40 recordings in dashboard , can i delete the first 3 of them ? it looks like just delete the mp4 file doesn't work. is there some config file mapping the file and records in dashboard ?

**Comment by diemol** [comment]
This is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://seleniumhq.herokuapp.com/)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
