### ISSUE TITLE
Disconnect timeout in Zalenium Live Preview

### ISSUE THREAD

**Issue by sayom88** [zalando/zalenium#1097]
## 🐛 Bug Report

When my automation scripts are running, I am unable to see the live view as you can see below in the picture
![Untitled](https://user-images.githubusercontent.com/16284729/69526986-07d14680-0f74-11ea-8706-5155133a6a48.png)
,,...it is showing disconnect timeout....can you please suggest how to be able to connect so that I can see the live view please....

**Comment by diemol** [comment]
This is the normal behavior, after the test finishes the container are destroyed, therefore the VNC connection ends.
