### ISSUE TITLE
Can zalenium update browser versions from time to time?

### ISSUE THREAD

**Issue by Niyarlatotep** [zalando/zalenium#1098]
## 🚀 Feature Proposal

Make Zalenium able to update selenium containers to the latest version, on a schedule, or at intervals or on recreating. If param is set.

## Motivation

I'd like to have new versions of browsers containers for testing without manual update and without using additional scripts.

## Example

--pullLatestOnContainerRecreate

**Comment by diemol** [comment]
When we started the project we thought about doing that, nevertheless, we prefer that users have full control over their environment and we discarded implementing it.

**Comment by Niyarlatotep** [comment]
@diemol Thank you for responce. It could be set by an option it shouldn't work by default.

**Comment by diemol** [comment]
Understood, feel free to send us a PR for this 🙌
