### ISSUE TITLE
zalenium is reallocating the new request to hub nodes only.

### ISSUE THREAD

**Issue by kumar1210** [zalando/zalenium#1100]
## 🐛 Bug Report

we have created a grid where hub is running in machine and there are few selenium nodes running in other machines. With the latest zalenium image, image is not able to allocate requests to the other machine selenium nodes

## To Reproduce

Create a hub with desiredContainer 5 and create 10 selenium nodes in other machine pointing to hub machine. Now run your selenium tests pointing to the grid. With the older version it use to start allocating the request to the nodes in its registration order. But with the latest image of the zalenium this is not the case.

## Expected behavior

Ideally the hub should distribute the request to the different register nodes, not only to the hub nodes

## Test script reproducing this issue (when applicable)

command to start hub : 
docker run --rm -ti --name zalenium --hostname zalenium_hub --shm-size=2g -p 4444:4444 -e zalenium_no_proxy="localhost,127.0.0.1,172.17.0.*" -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start --desiredContainers 5 --maxDockerSeleniumContainers 15 --screenWidth 2144 --screenHeight 1154

commant to start selenium nodes : 
docker run -d --name `hostname`_node_0 -h `hostname`_node_0 -p 5550:5555 -e HUB_HOST=<hub_machine> -e HUB_PORT=4444 -e REMOTE_HOST="http://`hostname --long`:5550" selenium/node-firefox ;

## Environment

OS:  Linux
Zalenium Image Version(s): 
Docker version: 1.12.6
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
command to start hub : 
docker run --rm -ti --name zalenium --hostname zalenium_hub --shm-size=2g -p 4444:4444 -e zalenium_no_proxy="localhost,127.0.0.1,172.17.0.*" -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start --desiredContainers 5 --maxDockerSeleniumContainers 15 --screenWidth 2144 --screenHeight 1154

commant to start selenium nodes : 
docker run -d --name `hostname`_node_0 -h `hostname`_node_0 -p 5550:5555 -e HUB_HOST=<hub_machine> -e HUB_PORT=4444 -e REMOTE_HOST="http://`hostname --long`:5550" selenium/node-firefox ;

If using Kubernetes, specify your environment, and if relevant your manifests:

**Comment by diemol** [comment]
Hi @kumar1210,

Could you please provide the images you are using to start the containers? What Zalenium version? 

Where are the other nodes coming from? 

There is not enough information to troubleshoot this.

**Comment by diemol** [comment]
Closing as the issue went stale.
