### ISSUE TITLE
Redirect Test execution logs into Zalenium dashboard

### ISSUE THREAD

**Issue by Pooja-prog** [zalando/zalenium#1106]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium)
- [Slack channel - #zalenium channel](https://seleniumhq.herokuapp.com/)

**Comment by diemol** [comment]
This is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://seleniumhq.herokuapp.com/)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
