### ISSUE TITLE
Build Failing on DockerHub

### ISSUE THREAD

**Issue by sumanthnarayanrajurssap** [zalando/zalenium#1114]
Hello,

when i try to build the project on docker hub it is throwing error as 
Step 42/53 : ENV ZAL_VER="${project.build.finalName}" BROWSER_STACK_TUNNEL_OPTS="-skipCheck -v -forcelocal" BROWSER_STACK_TUNNEL_ID="zalenium" BROWSER_STACK_TUNNEL="false" BROWSER_STACK_WAIT_TIMEOUT="2m" SAUCE_TUNNEL_MAX_RETRY_ATTEMPTS="1" SAUCE_TUNNEL_READY_FILE="/tmp/sauce-connect-ready" SAUCE_TUNNEL_ID="zalenium" SAUCE_TUNNEL_DOCTOR_TEST="false" SAUCE_WAIT_TIMEOUT="2m" SAUCE_TUNNEL="false" TESTINGBOT_TUNNEL_OPTS="--se-port 4447" TESTINGBOT_TUNNEL="false" TESTINGBOT_WAIT_TIMEOUT="2m" CBT_TUNNEL_ID="zalenium" CBT_TUNNEL="false" LT_TUNNEL_ID="zalenium" LT_TUNNEL="false" SELENIUM_HUB_PARAMS="" SELENIUM_NODE_PARAMS="" SELENIUM_CONTAINER_LABELS="" SELENIUM_WAIT_FOR_CONTAINER="true"
failed to process "\"${project.build.finalName}\"": missing ':' in substitution

kindly help me to resolve the issue

Thanks & Regards,
Sumanth

**Comment by diemol** [comment]
Please follow the steps provided at https://opensource.zalando.com/zalenium/#contributing
