### ISSUE TITLE
the download popup in the chrome though the related setting already update

### ISSUE THREAD

**Issue by loudDD** [zalando/zalenium#1115]
chromePrefs.put("profile.default_content_setting_values.automatic_downloads", 1);
		chromePrefs.put( "profile.content_settings.pattern_pairs.*.multiple-automatic-downloads", 1 );
		chromePrefs.put("profile.content_settings.exceptions.automatic_downloads.*.setting", 1 );
		chromePrefs.put("download.prompt_for_download", false);
		chromePrefs.put("download.directory_upgrade", true);
![image](https://user-images.githubusercontent.com/33220071/70519765-6ce18a80-1b77-11ea-8b43-b17959e18cfb.png)

but when the download element was clicked , still, there is a download popup 
Most importantly , sometimes ,there is no popup
![image](https://user-images.githubusercontent.com/33220071/70519720-5cc9ab00-1b77-11ea-895a-e5768167cca9.png)

**Comment by diemol** [comment]
Hi @Sharathn27,

I will close this is a question, please join the #zalenium channel at [Slack](https://seleniumhq.herokuapp.com/) or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.

**Comment by anirbandan** [comment]
I started getting the same pop up while executing the scripts but on passing parameters 
download.directory_upgrade=${TRUE} 
download.default_directory=${zalenium.tempDir} 
in chrome options the download started working without any issue

but the file is not getting downloaded in the mentioned folder ${zalenium.tempDir}, infact i cant find it anywhere on my zalenium container nor in the server i have hosted zalenium
