### ISSUE TITLE
Does this project need volunteer for performing automation testing?

### ISSUE THREAD

**Issue by tanwangw** [zalando/zalenium#1119]
## 💬 Questions and Help
Someone with strong manual testing and limited coding experience. She would like provide her automation experience. Would this project need anyone to perform automation testing?

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium)
- [Slack channel - #zalenium channel](https://seleniumhq.herokuapp.com/)

**Comment by diemol** [comment]
As any open source project, this one would benefit from any type of testing. Please read our contribution guidelines and send contributions in any possible way. Thank you! 🙇
