### ISSUE TITLE
Is there Zalenium docker image available for a Linux ppc architecture ?

### ISSUE THREAD

**Issue by sujata00** [zalando/zalenium#1121]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium)
- [Slack channel - #zalenium channel](https://seleniumhq.herokuapp.com/)

**Comment by diemol** [comment]
There is only one docker image for Zalenium, which should work in all environments.

**Comment by sujata00** [comment]
> There is only one docker image for Zalenium, which should work in all environments.

Hi @diemol ,

The image available in docker hub is for x86 systems.If it works for all the ARCHS the same way then why i am getting the below error:

**Docker command:**

root@b64-linux1:~# docker run --rm -ti --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start

**Output:**
standard_init_linux.go:211: exec user process caused "exec format error"


**System Details:**
root@b64-linux1:~# uname -m
ppc64le

Can u please help me on this? 

Regards,
sujata
