### ISSUE TITLE
Using Zalenium without using Helm

### ISSUE THREAD

**Issue by topproto** [zalando/zalenium#1122]
Hi, 

I would like to start working with Zalenium

I have a Kubernetes cluster that connects to a private repository. We would never access any external repos such as docker.io. All images we used go though a strict set of guidelines before they can be used.

The Kubernetes install you offer from what I can tell is only using Helm.

Do you have a non Helm install for those who are not able to use public repos?

**Comment by diemol** [comment]
@topproto you can always provide your own image. E.g., push `elgalu/selenium` to your private docker registry and use it from there. Of course, you would need to adjust the helm chart values.
