### ISSUE TITLE
Frequent test disconnection while using proxy variables

### ISSUE THREAD

**Issue by vinotharuchamy** [zalando/zalenium#1125]
Hi,

When i run Zalenium without any proxy variables (: zalenium_http_proxy, zalenium_https_proxy, and zalenium_no_proxy), it works stable. But when I add these proxy variables to connect outside my org, it terminate after few seconds (say approx. 60 seconds) of exectution with "Java.net.connectexpection: connection refused" error. Please note this happens afer few seconds of running test and this causes all the tests to fail.

Let me know if there is a solution for this....

**Comment by diemol** [comment]
This is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
