### ISSUE TITLE
Is there a Zalenium image available for a linux ppc architecture ? The official zalenium image works only for x86 ARCH. 

### ISSUE THREAD

**Issue by sujata00** [zalando/zalenium#1129]
The Zalenium image available in the docker hub is for x86 systems. It does not work on linux ppc ARCH system.

**Docker command:**

root@b64-linux1:~# docker run --rm -ti --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start

**Output:**
standard_init_linux.go:211: exec user process caused "exec format error"

**System Details:**
root@b64-linux1:~# uname -m
ppc64le

I had raised this issue long back for which @diemol replied that there is a single image that can be used on all systems. However, the claim is a farce.

Using docker manifest I can create ARCH specific images. But I want an image from Zalenium team. So that it can be used by other teams as well.

Regards,
Sujata

**Comment by diemol** [comment]
@sujata00 there is not. We do not plan to add more docker images to support that. But as any open source project, feel free to contribute 👍
