### ISSUE TITLE
How to Dynamically Select Chrome Browser or Driver Version

### ISSUE THREAD

**Issue by mohitbansal-gep** [zalando/zalenium#1137]
I am using Zalenium in Kubernetes . I Couldnt find a way to change chrome browser viersion , statically or dynamilcaly.
Please what to do if i need to change chrome browser version

**Comment by diemol** [comment]
You need to choose the specific `elgalu/selenium` image that fits your needs and configure it via the `--seleniumImageName` parameter. It is all in the docs.
