### ISSUE TITLE
Grid hangs due to hanging docker ps

### ISSUE THREAD

**Issue by davidtorssell** [zalando/zalenium#1143]
OS: RHEL 7.7
Zalenium version: 3.141.59y
Docker version: 1.13.1
docker-compose version: 1.24.1
way of starting Zalenium: docker-compose

Hi 

I am running Zalenium on a single server and experience that the grid stops taking new sessions after a while under high load (10 parallel sessions with video recording, all 6 cores max out). Sometimes "a while" is half an hour, sometimes several hours . The hub states that it has several nodes available but when the hub forward the session request to them they all state that "No more sessions are allowed". 

One clue is that when the hub hangs, the docker ps command also hangs. docker ps -n x works though, up to some limit, displaying some of the grid nodes. So for example docker ps -n 3 may work but docker ps -n 4 may not. Docker info reports that the number of containers running is less than what is defined by maxNumberOfSeleniumContainers and desiredContainers but the hub is not starting new ones because it thinks it has reached max. Furthermore there seems to be a docker ps process initiated by the zalenium container, I sometimes (not every time) have seen it hanging, checking the processes. Of course it may well be a docker issue but since it starts working again if I restart the zalenium container, it seems suspicious.

Some nodes that are visible in the dashboard are responsive and I can both use the vnc interface and log onto the containers, they have a Test name in the preview so I guess a test has run but the container could not be killed. If I kill node containers manually, Zalenium experiences "DockerSeleniumRemoteProxy unknown version, No route to host (Host unreachable)"  (from the live preview) but does not try to create new ones. 

Unfortunately I have no perfect way of reproducing this rather than just hammering the grid with tests.

There are also some suspicious log entries which I am not sure whether they are related, several of each can be seen in the logs:

Error opening file /home/seluser/videos/vid_chrome_or_firefox_40281.mp4: Invalid IsoMedia File
MP4Box got errors meaning the mp4 video file is corrupted, trying again...

time="2020-01-30T15:15:52.141185399+01:00" level=error msg="Handler for GET /containers/2d02056dc4a3c949ab3e15d951a7372fc976c3434531961f52ec31a96828f54a/json returned error: No such container: 2d02056dc4a3c949ab3e15d951a7372fc976c343

Jan 30 15:18:01 xsebyggd003.se.shb.biz dockerd-current[16368]: 15:18:01.434 [AutoStartProxyPoolPoller] DEBUG d.z.e.z.c.DockerContainerClient - Error while getting node status, probably the node is still starting up...

java.net.ConnectException: Connection refused (Connection refused)

 Any suggestions on how to investigate this further? 

[docker-compose.yml.txt](https://github.com/zalando/zalenium/files/4134714/docker-compose.yml.txt)
[logsnippet.txt](https://github.com/zalando/zalenium/files/4134716/logsnippet.txt)

**Comment by pierluigicdc** [comment]
Hi all,

i'm facing the same issue.

@davidtorssell, in the meantime did you find some other info, workaround or anything else?

**Comment by prom3t3us** [comment]
Same issue also for me.

**Comment by davidtorssell** [comment]
No, not really a solution. I ended up turning off video recording which almost solved the problem. I have only seen it once since. I ran 10 parallel sessions constantly during working hours and it worked for over a week which obviously is a big improvement but I was kind of bummed out when it hung again. Without video the cpu load is around 50% for 10 parallel sessions btw. 

Some things I have tested without finding a correlation to the problem:

- number of open files, no errors in kernel logs, lsof-values seem reasonable. Although restarting the server seems more effective than just restarting the container, it is no silver bullet. It seems to be running better after service restart but I have not found conclusive behavior around this. 
- amount of video files in videos directory or test result entries, should not matter and does not seem to matter.
- same issue with both vfs and overlay2 docker storage driver. 
- cpu load during test run, problem has manifested itself with low load as well as high although not sure if some cpu load related problem has led up to a bad state which make the low load test to fail. Only saw that once, otherwise it was always high load. 
- length of test runs. Problem has been identified even if only short tests have been run.
- once I saw a zombie process in a node container but that was only once. Have not seen any other suspicious processes.

Inside the node containers, everything looks normal, processes wait for input signals as it does when the node is idling. I don´t know if there are any way of extracting the state of the process, it seems that the hub container has not received the end of test signal to stop the container.  

I pulled the container id from looking at the processes on the host and killed all containers and tried to do docker ps between every container kill as to identify which container caused docker ps to hang and it was the zalenium container. So it seems like a zalenium bug to me, somehow it ends up in a bad state but unfortunately I have not identified exactly what it is or a bullet proof way to reproduce it.

**Comment by diemol** [comment]
Well, at the bottom of https://opensource.zalando.com/zalenium/, there is this link https://github.com/zalando/zalenium/blob/master/docs/performance.md

The problem here is that we want to execute 10 parallel tests with video and we only have 6 cores. The rule of thumb is for a stable execution: 
* The Zalenium container needs between 0.5 and 1 core.
* Each container running a test needs 1 core. 
* If you are using video, add one core per test.

10 parallel tests with video would need around 20 cores.
With only 6 cores is normal to get resource exhaustion. Try running 3 tests, and then 4, until you find the number that works for you.
