### ISSUE TITLE
Names of Log files sent to Remote Dashboard doesn't include the testFileNameTemplate 

### ISSUE THREAD

**Issue by anuradha24** [zalando/zalenium#1148]
## 🐛 Bug Report

Zalenium has the capability of sending the Video and Log files to remote dashboard, there is a small issue that needs to be fixed. The TEST_FILE_NAME_TEMPLATE which can be set through the browser's DesiredCapabilities is not being used for the name of the log files. 

## Details
DesiredCapabilities for the below example were set as follows : 
```desired_capabilities['testFileNameTemplate'] = "myID_{browser}_{platform}_{testStatus}"```

The fileName is set as follows for the video file being sent :
```json 
fieldname: 'video',
originalname: 'myID_chrome_LINUX_COMPLETED.mp4'
```

## Expected
fileName details for the log files will include the testFileNameTemplate as well like it does for the video file ie., something like : 
```json
fieldname: 'driverlog',
originalname: 'myID_chrome_LINUX_COMPLETED.log'
```

## Actual
fileName details for both the driver and server logs do not include the testFileNameTemplate, the details received for both the log files are as follows : 
```json
fieldname: 'driverlog',
originalname: 'chrome_driver.log'

fieldname: 'seleniumlog',
originalname: 'chrome_driver.log'
```

## Impact
Without the testFileNameTemplate in the name details it becomes very difficult to map the selenium and driver logs to a given test case that was run

**Comment by anuradha24** [comment]
Created PR to fix this issue : https://github.com/zalando/zalenium/pull/1149/files please review and merge

**Comment by anuradha24** [comment]
Hi All, Could you please take a look at this issue and merge the changes in PR : https://github.com/zalando/zalenium/pull/1149/files. We require this change merged to integrate zalenium with our internal dashboard

**Comment by tokarthik** [comment]
@diemol @elgalu Please have a look above one and merge it, please

**Comment by diemol** [comment]
PR merged, thanks.
