### ISSUE TITLE
Getting "Unable to parse remote response" chrome driver error while launching chrome browser with latest Zalenium image.

### ISSUE THREAD

**Issue by sujata00** [zalando/zalenium#1151]
## 🐛 Bug Report
While running TCs through Jenkins  in a linux node I am facing the below issue:

"linux:lib/chromedriver org.openqa.selenium.WebDriverException: Unable to parse remote response: <!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Zalenium - 504
  
    - Gateway Timeout
  
  </title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    h1 { text-align: center; }
    address { text-align: center; }
  </style>
</head>
<body>
  <h1>504
  
    - Gateway Timeout
  
  </h1>
<hr>
<address>nginx/1.10.3 - Zalenium 3.141.59y</address>
</body>
</html>"

## To Reproduce

Run the below command on the remote host:
docker run --rm -d --name Selenium_Grid_is5q5HXeOQ -p 4444:4444 -e PULL_SELENIUM_IMAGE=true -e NEW_SESSION_WAIT_TIMEOUT=6000000 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start.

The chrome browser fails to launch with the error message pasted on the top.

## Expected behavior
This issue is happening with the latest chromedriver.It was working fine with the old chrome drivers.

## Environment

OS:  Ubuntu 18.04.3 LTS (GNU/Linux 5.0.0-36-generic x86_64)
Zalenium Image Version(s): latest available in docker hub
Docker version: Docker version 18.09.9, build 1752eb3

Please update on this at the earliest.

**Comment by diemol** [comment]
I tried to reproduce the issue with the tests that are part of Zalenium's test suite and I was not able to see the issue.
Feel free to open a new issue with a clear way to reproduce it, please avoid narrative descriptions and provide a test script that can be used to reproduce the situation.
