### ISSUE TITLE
Zalenium hangs up/frozen on screen but runs in the background

### ISSUE THREAD

**Issue by sirishag08** [zalando/zalenium#1152]
## 🐛 Bug Report

Test method running on Zalenium runs fine for few minutes and then hangs up/frozen with no UI movement on screen yet the information notifications on the top right corner gets updated showing that its moving forward in the test process. On completion, verified that the test was indeed complete. But recording doesn't have that information as it just shows the frozen screen all along.

![image](https://user-images.githubusercontent.com/60796053/74063418-ff56ac80-49b5-11ea-9750-03cad3edb5a5.png)

## Environment

**OS:** Windows 10 Pro - 64 bit Operation system, with Core i7-8650U CPU
**Zalenium Image Version:** (dosel/zalenium)  zalenium-3.141.59x (downloaded with latest tag)
**Selenium Image Version:** (elgalu/selenium) 
	selenium_chrome_version: 79.0.3945.117
	selenium_firefox_version: 72.0.1
	selenium_version: 3.141.59
**Docker version:** 
	Server: Docker Engine - Community
	 Engine:
	  Version:          19.03.5
	  API version:      1.40 (minimum version 1.12)
	  Go version:       go1.12.12
	  Git commit:       633a0ea
	  Built:            Wed Nov 13 07:29:19 2019
	  OS/Arch:          linux/amd64
	  Experimental:     false
	DockerSeleniumRemoteProxy (version : 3.141.59)

**Configuration information from Zalenium Live Preview Container:**
	browserTimeout: 16000
	debug: false
	host: X.X.0.3
	port: 40043
	role: node
	timeout: 19000
	cleanUpCycle: 5000
	maxSession: 1
	capabilities: Capabilities {acceptSslCerts: true, browserName: chrome, maxInstances: 1, platform: LINUX, platformName: LINUX, resolution: 1600x900, screen-resolution: 1600x900, screenResolution: 1600x900, seleniumProtocol: WebDriver, server:CONFIG_UUID: 446d7659-9d3b-48a0-a0d3-80f..., tz: America/Chicago, version: 79.0.3945.117}
	capabilities: Capabilities {acceptSslCerts: true, browserName: firefox, maxInstances: 1, platform: LINUX, platformName: LINUX, resolution: 1600x900, screen-resolution: 1600x900, screenResolution: 1600x900, seleniumProtocol: WebDriver, server:CONFIG_UUID: 27c705d1-7c5b-4c7d-b9fd-577..., tz: America/Chicago, version: 72.0.1}
	downPollingLimit: 2
	hub: http://X.X.0.2:4445/grid/register
	id: http://X.X.0.3:40043
	nodePolling: 94000
	nodeStatusCheckTimeout: 5000
	proxy: de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy
	register: true
	registerCycle: 81000
	remoteHost: http://X.X.0.3:40043	
	unregisterIfStillDownAfter: 2500

**Exact Docker command to start the containers:**
    docker run --restart always -ti --name zalenium -p 4444:4444 -p 5555:5555 -e ZALENIUM_EXTRA_JVM_PARAMS="-Dwebdriver.http.factory=apache" -v /var/run/docker.sock:/var/run/docker.sock -v C:\inetpub\wwwroot\dashboard:/home/seluser/videos -v C:\Automation\UploadFiles:/tmp/node/home/seluser/UploadFiles -v C:\Automation\Downloads:/tmp/node/home/seluser/Downloads --privileged dosel/zalenium start --screenWidth 1600 --screenHeight 900 --timeZone "America/Chicago" --desiredContainers 4 --maxDockerSeleniumContainers 4 --maxTestSessions 1 --videoRecordingEnabled true

**Comment by diemol** [comment]
I kind of understand the idea of the issue, however there is not a hint on how I could actually reproduce it, which makes troubleshooting very hard.
I am going to close this, but feel free to open a new issue and provide all the information (automation scripts, public website, and detailed startup commands) to reproduce it.
