### ISSUE TITLE
nullPointer Exception in Kubernetes again

### ISSUE THREAD

**Issue by dbwest** [zalando/zalenium#1155]
## 💥 Regression Report

A clear and concise description of what the regression is.
Before tests send JSON wire to the grid, the grid is failing at http://host:nodeport/wd/hub with the following
![image](https://user-images.githubusercontent.com/1122691/74345365-0564d880-4d7c-11ea-95b3-c5f2d1d27210.png)

## Last working version
Worked up to version:
3.141.59w

Stopped working in version:
3.141.59y

## To Reproduce

Steps to reproduce the behavior (including the docker command/docker-compose/Kubernetes manifests to start Zalenium):

Deploy the new Zalenium Helm chart.

## Expected behavior

After deployment, wd/hub should not show a nullPointer Exception. 

## Actual behavior

wd/hub is showing a nullPointer exception even after adjusting container security policies.
After rollback to a previous version of Zalenium the problem persists.

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: CentOS
Zalenium Image Version(s): 3.141.59y
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
If using Kubernetes, specify your environment, and if relevant your manifests:
kubernetes version 1.11
manifests from latest stable for release 3.141.59y

**Comment by diemol** [comment]
@dbwest but that is what normally you get when you do a GET to that URL.
Usually, you just do POSTs

**Comment by dbwest** [comment]
Good to know. If that is the case I will close this. I think our tests may be running. Earlier I was experiencing issues running tests and thought this was the cause. if it is normal I am closing this. Thanks for that info @diemol

**Comment by dbwest** [comment]
reopening this. We used to do a get on this and get json with `ready` in it not a stack trace.

**Comment by dbwest** [comment]
was there a change to the project that now necessitates doing a `POST` instead of a `GET` and what headers does it need if so?

**Comment by diemol** [comment]
I guess the URL you want to check is `http://localhost:4444/wd/hub/status`

**Comment by dbwest** [comment]
wait it was Test Engineer PEBCAK. sorry @diemol it is working. They had the wrong nodeport coming from a submodule. And.... yes they check `wd/hub/status`. Thank you for your time and excellent project.
