### ISSUE TITLE
[Feature] Enable the capablity flag  to store the vidoe only the test case fails. 

### ISSUE THREAD

**Issue by Pratish89** [zalando/zalenium#1159]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

The zalenium provide to store the video for the test run but it would nice to have the flag to store the video only if the test fail. 

## Motivation

Please outline the motivation for the proposal.

## Example

Please provide an example for how this feature would be used.

**Comment by diemol** [comment]
Please search for `--keepOnlyFailedTests` at https://opensource.zalando.com/zalenium/, this feature already exists.
