### ISSUE TITLE
Zalenium nodes do not get disclosed

### ISSUE THREAD

**Issue by labordoc** [zalando/zalenium#1162]
Hi @diemol :

We recently started using Zalenium and we are facing the same issue reported in [this thread](https://github.com/zalando/zalenium/issues/833): for some executions everything goes fine (all tests run and nodes get disclosed and available again), but in other cases, there are some nodes that do not get disclosed and become unavailable, so tests do not use those nodes anymore, and the only solution we saw is to restart Zalenium, so all nodes get available again.

After reading all comments [here](https://github.com/zalando/zalenium/issues/833), I understand the issue has not been fixed. @diemol : do you know if there is a way to detect automatically the "unavailable" nodes and restart them individually?

Thanks!

**Comment by diemol** [comment]
Hi @labordoc,

I am sorry, but if you provide a way to reproduce the issue, I would be happy to have a look, but the comments in the referenced issue and in this one, are not offering any information on how to reproduce this problem and help me to troubleshoot the issue.

I will close this, but feel free to open a new issue and provide all the required infomation from the template.
