### ISSUE TITLE
Can you provide documentation to start Zalenium grid on Windows 10?

### ISSUE THREAD

**Issue by djangofan** [zalando/zalenium#1163]
## 💬 Questions and Help

I don't have access to Slack via my work firewall .  So, I am wondering:

Can you provide documentation somewhere to start Zalenium grid on Windows 10?   Or is this not supported?   Documentation has an example that doesn't work for me.

Here is what I get:

```
PS C:\WINDOWS\system32> docker run --rm -ti --name zalenium -p 4444:4444 
  -v /var/run/docker.sock:/var/run/docker.sock -v /c/Users/%USERNAME%/temp/videos:
  /home/seluser/videos --privileged dosel/zalenium start
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: error during 
  connect: Post http://0.0.0.0:2375/v1.39/containers/create?name=zalenium: read tcp 
  172.20.50.130:55022->192.168.100.70:8080: wsarecv: A connection attempt failed 
  because the connected party did not properly respond after a period of time, or 
  established connection failed because connected host has failed to respond.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```
Is there a missing pre-requisite that the documentation does not mention?   Is it trying to connect to the windows docker sock.

This command works fine for me:
docker run --rm -ti -p 4444:4444 -p 5555:5555 selenium/node-chrome

**Comment by djangofan** [comment]
I get the same error with `docker ps` command.  Sorry. Closing this.

**Comment by charmi25** [comment]
can you share the command to start Zalenium on windows 10.

I used below command  which I found on (https://opensource.zalando.com/zalenium/)

Command :
docker run --rm -ti --name zalenium -p 4444:4444 ^
 -v /var/run/docker.sock:/var/run/docker.sock ^
 -v /c/Users/your_user_name/temp/videos:/home/seluser/videos ^
 --privileged dosel/zalenium start

Error:
At line:4 char:3
+ --privileged dosel/zalenium start
+   ~
Missing expression after unary operator '--'.
At line:4 char:3
+ --privileged dosel/zalenium start
+   ~~~~~~~~~~
Unexpected token 'privileged' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

**Comment by djangofan** [comment]
I don't think I needed to use the **--priviledged** option to start mine.   You may notice that if you run the 'hello-world' container, you don't need to use --priviledged
