### ISSUE TITLE
Some test cases don't have video

### ISSUE THREAD

**Issue by loudDD** [zalando/zalenium#1164]
docker-compose.yml:
![image](https://user-images.githubusercontent.com/33220071/76738642-fbccf700-67a5-11ea-9156-edac2cbe6b26.png)

i have 5 test case run at the same time, 24 in total . But after the test execute finish , some test cases don't have video and it's randomly occur in different cases, and the performance of the docker machine is far from insufficient. also , i try different zalenium version , still ,doesn't work. what extra info should i provide to track the problem ?

**Comment by xiazhao2015** [comment]
More info: We continously encountered the absence for recorded videos on 4 different zalenium clusters, the auto execution was triggered by jenkins on specific time each day and we've kept on observing it for about 1 month, the average missing rate is about 20%

**Comment by diemol** [comment]
Hi all,
I am sorry, but this is not enough information to troubleshoot the issue. There is a full issue template with different sections that ask for specific information (automation scripts, detailed commands to starts Zalenium, etc...), but all that was ingnored. Therefore there is not much that I could do.
Please feel free to open a new issue with all the required information.

**Comment by xiazhao2015** [comment]
@diemol Got it, thanks for comment.
@loudDD Please help create a new one with necessary info to trouble shoot this issue, can follow this template: https://github.com/zalando/zalenium/issues/1154
