### ISSUE TITLE
Is there a way user can control the containers that spin up for an execution

### ISSUE THREAD

**Issue by Chinnuganga** [zalando/zalenium#1172]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium)
- [Slack channel - #zalenium channel](https://seleniumhq.herokuapp.com/)

**Comment by Chinnuganga** [comment]
My use case is as follows
I have 10 test cases where each takes 1sec for execution.
So by having 10 containers in parallel I will be able to complete the execution in the required time.
Now the 2nd scenario is that I have the same 10 test cases where each takes 1sec for executon and I have infinite time to complete the execution. So, my question here, is there a user can configure/control the containers that spin up in a particular time frame.

**Comment by pearj** [comment]
Questions not permitted as an issue
