### ISSUE TITLE
zalenium image on AWS EB

### ISSUE THREAD

**Issue by SachinB75** [zalando/zalenium#1173]
## 💬 Questions and Help
getting the below error trying to connect to the zalenium image on EB instance

  **org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. 
Possible causes are invalid address of the remote server or browser start-up failure.**

### Please note that this issue tracker is not a help form and this issue will be closed.
ran the zalenium image on an eb instance
  
   docker run --rm -ti --name zalenium -p 443:443 \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v /tmp/videos:/home/seluser/videos \
      --privileged dosel/zalenium start 
	  
	  
   2. From my local browser i am able to see the grid and admin page.
    **https://xxx-devl-eb-06-webapp.e003.e003.com/grid/console**

   3. On my Selenium script I have the below settings
      
	                                 System.setProperty("http.proxyHost", xxx.xxx.com);
                                     System.setProperty("http.proxyPort", 1111);
     
                            	  String URL = ""https://xxx-devl-eb-06-webapp.e003.com:443/wd/hub"";

                                DesiredCapabilities desiredCapabilities = DesiredCapabilities.chrome();
                                desiredCapabilities.setCapability(CapabilityType.PLATFORM, Platform.LINUX);

                                // Create a new instance of the remote web driver
                                WebDriver driver = new RemoteWebDriver(new URL(URL), desiredCapabilities);
	
			     driver.get("goole.com");
	  
	  Any help is really appreciated
	 
For questions or help please see:

- [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium)
- [Slack channel - #zalenium channel](https://seleniumhq.herokuapp.com/)

**Comment by evgenyfedorenko** [comment]
let me know when you fix it - having the same issue :)

**Comment by diemol** [comment]
This is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
