### ISSUE TITLE
Is Chrome Browser Version Updating even if Zalenium not being developed anymore?

### ISSUE THREAD

**Issue by alexeykozlov1** [zalando/zalenium#1177]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium)
- [Slack channel - #zalenium channel](https://seleniumhq.herokuapp.com/)

**Comment by diemol** [comment]
Yes, just keep an eye on the releases from elgalu/selenium
