### ISSUE TITLE
View dashboard even if Zalenium container pulled down.  

### ISSUE THREAD

**Issue by vickyru** [zalando/zalenium#1179]
## 🚀 Feature Proposal
It will  be much appreciated if a Zalenium user can view the dashboard's recording from remote host machine once he/she stops all running Zalenium containers after test execution.

## Motivation
We have proposed Zalenium into our organisation but DevOps team is having a concern that they can not let keep running Zalenium containers after test execution completed to make it cost effective over cloud and which very genuine concern. 

So, **cost cutting** is main motivation behind this proposal

## Example
Once all Zalenium containers pulled down then certainly we can not view Dashboard over url http://<server-ip>:<some-port>/dashboard/# 
So, if there is any way to view dashboard like below one will be much appreciated.
http://<server-ip>/dashboard/#

**Comment by diemol** [comment]
@vickyru you can run Zalenium with `--desiredContainers 0` and containers will be created on demand, while the hub still runs and the dashboard is still available.
In the end, the main Zalenium container needs to be running in order to show the dashboard.
