### ISSUE TITLE
/tmp/mounted not mounting on browser nodes

### ISSUE THREAD

**Issue by Chip067** [zalando/zalenium#118]
As stated on the title, the multi-purpose folder is not mounting correctly on browser containers.

I can share files between host - zalenium just fine but zalenium - node is not mounted.

As I understood from the: [https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md](url) this should be possible.

**Comment by diemol** [comment]
Hi @Chip067,

Can you share with us how you start Zalenium? (docker command).

**Comment by Chip067** [comment]
docker run --rm -d -ti --name zalenium -p 4444:4444 -p 5555:5555 -v /var/run/docker.sock:/var/run/docker.sock -v /c/Users/user/tmp/videos:/home/seluser/videos -v /c/Users/user/tmp/mounted:/tmp/mounted dosel/zalenium:3 start

I use windows 7

**Comment by diemol** [comment]
Hi @Chip067,

How are you checking that the files are present in the docker-selenium containers? They should be present also in the `/tmp/mounted` folder of each container.

**Comment by Chip067** [comment]
Hello,

`docker -ti zalenium /bin/bash`
`ls /tmp/mounted`  Here I can see my test.txt file.

and

`docker -ti zalenium_40001 /bin/bash`
`ls /tmp/mounted` the folder exists but does not contain test.txt, 

Also I installed xubuntu on VirtualBox and in that environment everything works fine. So this seems to be windows problem.

**Comment by diemol** [comment]
> When mounting using: -v /tmp/mounted:/tmp/mounted everything works,

Is this done in a Windows machine?

The thing is that I don't have a Windows machine right now, so I cannot debug that issue now. Is there a way that you could help us pointing to a solution?

**Comment by diemol** [comment]
Is there maybe a chance that the volume is in a different drive and Windows is not letting the mount due to missing permissions?

I was just reading this https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c

**Comment by Chip067** [comment]
Hello, 

> Is this done in a Windows machine?

No that was done using the linux virtual machine. I also found that when I link folder like this:
`-v /home/user/tmp/mounted:/tmp/mounted` the browser container is still looking files on `/tmp/mounted` folder of my host machine and not in the assigned one `/home/user/tmp/mounted`!

How to test (on linux environment) :

- Create file (example.txt) on folder `/tmp/mounted`
- Start Zalenium with `-v /home/<username>/tmp/mounted:/tmp/mounted`
- Create file (this_file_not_showing.txt) on folder `/home/<username>/tmp/mounted` 
- Go to zalenium browser node, e.g `docker exec -ti zalenium_40000 /bin/bash`
- List files on /tmp/mounted `ls /tmp/mounted`
- File showed is the example.txt and not the one in our defined folder in `/home/<username>/tmp/mounted`
- Exit from node, and go to zalenium container `docker exec -ti zalenium /bin/bash`
- List files on /tmp/mounted and now right file is shown (this_file_not_showing.txt)

I think this is the main problem. Our test server is running linux so windows support, for me, is not needed, but binding that folder to another would be nice.

With atleast on windows 7 which uses VirtualBox to run docker since there is no /tmp folder it's always something like c/tmp because of how VirtualBox shares folders. I dont have the chance to test on windows 10 machine which supporst Docker natively.

Maybe take a look at DockerSeleniumStarterRemoteProxy.java file on line 471 where HostConfig is built. There it binds the volume to `/tmp/mounted:/tmp/mounted` ? Just guessing.

Hope this helps.

**Comment by diemol** [comment]
OK, I think that now I get it.

The folder in the host can have any name, in your command it is: `/home/<username>/tmp/mounted`
But inside all containers, the mapped volumes are all `/tmp/mounted`

So, if you are looking for a file in your test, you should look for it in `/tmp/mounted`. I hope that it works like that for you.

We could try to find a way to make it configurable, but for now we are spending our efforts in the k8s feature.

**Comment by diemol** [comment]
Hi again @Chip067,

I was talking with @elgalu and now we understand it better. 

We'll find a way to change that hardcoded part, because in Windows it is not possible to have `/tmp/mounted`. I'll leave this issue opened and we'll work on that soon.

**Comment by diemol** [comment]
Hi @Chip067,

I've just added a fix, which basically takes the folder given in the host to be used as well for the new containers. It is part of #128, which should be released next week, perhaps Monday or Tuesday.

**Comment by diemol** [comment]
This was just released https://github.com/zalando/zalenium/releases/tag/3.3.1g

@Chip067 please check it and feel free to reopen the issue if it does not work properly.
