### ISSUE TITLE
WebDriver detection

### ISSUE THREAD

**Issue by gvojtko** [zalando/zalenium#1180]
Hi, I have issue with WebDrive detection. I exchanged selenium/standalone-chrome for dosel/zalenium and during testing I came across WebDrive detection.

URL for tests:
- https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html
- https://intoli.com/blog/making-chrome-headless-undetectable/chrome-headless-test.html

My capabilities options:

'--headless',
'--no-sandbox',
'--start-maximized',
'--window-size=1920,1080',
'--disable-blink-features',
'--disable-blink-features=AutomationControlled',
'--disable-setuid-sandbox',
'--lang=en-US',
'--disable-infobars',
'--disable-notifications',
'--window-position=0,0',
'--ignore-certifcate-errors',
 '--ignore-certifcate-errors-spki-list',

And

$capabilitiesOptions->setExperimentalOption('useAutomationExtension', false);
$capabilitiesOptions->setExperimentalOption('excludeSwitches', ['enable-automation']);

With selenium/standalone-chrome working fine. Im tried to:

$client->executeScript("
    Object.defineProperty(navigator, 'webdriver', {
        get: () => undefined
    })
    Object.defineProperty(navigator, 'plugins', {
        get: () => [1,2,3,4,5]
    })
");

But not working. How I can stop detect WebDriver?

**Comment by diemol** [comment]
This is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
