### ISSUE TITLE
Selenium hub is not responding on running in swarm mode

### ISSUE THREAD

**Issue by ReddyNitheeesh** [zalando/zalenium#1185]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium)
- [Slack channel - #zalenium channel](https://seleniumhq.herokuapp.com/)

**Comment by ReddyNitheeesh** [comment]
https://github.com/zalando/zalenium/issues/1087#issuecomment-644157734

**Comment by diemol** [comment]
Closing as the links to request help and ask questions are provided in the issue template.
