### ISSUE TITLE
New browser window causing org.openqa.selenium.WebDriverException: Session was terminated due to ORPHAN

### ISSUE THREAD

**Issue by rakeshium** [zalando/zalenium#1190]
Script in zalenium running fine till the point a new browser window (not tab) getting opened, after which the next lines of code are not working as expected i.e script is not able to find web elements. 
Locally it is working fine where after validation in current tab, driver is switched to new window, closes new window and comes back to last working tab.
Error-
org.openqa.selenium.WebDriverException: Session was terminated due to ORPHAN

**Comment by diemol** [comment]
Closing since the issue template was completely ignored.
