### ISSUE TITLE
502 Bad Gateway ngnix

### ISSUE THREAD

**Issue by Johnbalaji** [zalando/zalenium#1192]
Team,

I have been facing this odd issue where the zalenium runs perfectly fine for a couple of weeks and all of sudden it goes to bad gateway issue and stops processing request.

When i dig into it the dosel/zalenium container seem to UP but the elgalu/selenium containers are not available.
I reached our endpoint http://localhost:4444 and it throws 502 bad gateway.

I have seen this issue couple of times, all i do as a remedy is kill it and start fresh.

This time i have disabled the video recording checking out #777 as it might use another 1vCPU

I am using Amazon Linux - 2vCPU and 8GB RAM with desired containers set to default 2 

This request is also invoked for every 30 mins so the scaling does not happen much as it runs only on 2 containers max.

Do you suggest to upgrade the specs or what could be the issue?

**Comment by Johnbalaji** [comment]
@diemol - Can you please help me?

**Comment by diemol** [comment]
It could be many many different thigs, I have no clue based on the information supplied. I will close this issue because I think it is easier if you go to the Slack channel #zalenium in the Selenium workspace. You can find the link here https://www.selenium.dev/support/
