### ISSUE TITLE
Video Recording and VNC not getting turn off 

### ISSUE THREAD

**Issue by mohitbansal-gep** [zalando/zalenium#1193]
We have Deployed Zalenium Through Helm in our Azure Kubernetes Cluster and in the Values.yaml we have turned of the video recording (videoRecordingEnabled: true) . However we are not able to turn Off the Video recording and VNC through Desired Capabilities in our Java code below is the snipet.

                         desiredCapabilities.setCapability("enableVNC", false);
			    desiredCapabilities.setCapability("enableVideo", false);
			    desiredCapabilities.setCapability("recordVideo", false);

Please let us know if this an open issue or any more settings are required.

**Comment by diemol** [comment]
Hi. I don't know where `enableVNC` and `enableVideo` come from.

I will close this because the whole template was deleted.

Feel free to join the Slack channel for #zalenium at the Selenium workspace, the link can be found at https://www.selenium.dev/support/

**Comment by mohitbansal-gep** [comment]
I guess its mentioned in the  https://opensource.zalando.com/zalenium/#usage 

If this template is deleted , can you guide/help us for the same. What should we do to enable and disable the video/vnc/recording through capabilities or is there any other way

**Comment by diemol** [comment]
It is easier if you join the Slack channel, there are more people there who can help and we avoid the back-and-forth for questions here.
Besides, GitHub issues is not a forum for Zalenium, is for actual issues.
