### ISSUE TITLE
testFileNameTemplate and cookie injection is not working when using browserstack

### ISSUE THREAD

**Issue by hemanthsridhar** [zalando/zalenium#1195]
## Steps

Adding 
when running with browserstack with the below capability
`
dc.setCapability("testFileNameTemplate", "{testName}")
`

it does not work.
the testFileNameTemplate is still
`
"testFileNameTemplate": "{proxyName}_{testName}_{browser}_{platform}_{timestamp}_{testStatus}" 
`
           
The below code does not working either.

```
Cookie nameCookie = new Cookie("zaleniumTestName", new RandomStringUtils().randomAlphanumeric(20))
Cookie startCookie = new Cookie("zaleniumVideo", "true")
Cookie stopCookie = new Cookie("zaleniumVideo", "false")
getDriver().manage().addCookie(nameCookie)
getDriver().manage().addCookie(startCookie)
getDriver().manage().addCookie(stopCookie)
```

OS: OSX
Zalenium Image Version(s): latest
Docker version: 19

**Comment by diemol** [comment]
Those capabilities only work with tests running locally, not in any of the cloud integrations.
