### ISSUE TITLE
Video recording per session rather than per test

### ISSUE THREAD

**Issue by dchourasia** [zalando/zalenium#1197]
## 🚀 Feature Proposal

in case when maxTestSessions is more than one, we should be able to have one video recording per session rather than per test

## Motivation

This will help us in case when we have too many cases, we will have fewer recordings to manage and search

## Example

we can have --videoRecordingForEach "test/session"

**Comment by diemol** [comment]
@dchourasia no more features are developed, Zalenium is not under development anymore.

However, please check the documentation and look for the feature
>Change video recording status while in session

https://opensource.zalando.com/zalenium/
It should show you a way to achieve what you want.
