### ISSUE TITLE
Copy Video File From volume of zalenium to External Storage

### ISSUE THREAD

**Issue by amiluslu** [zalando/zalenium#1214]
## 🚀 Feature Proposal

Copy video file from zalenium to storage 

## Motivation

This application based on JAVA Spring Boot with Maven, log4j for logging.. Aim of this app, takes .mp4 files from openshift zalenium volume, sends to external storage using rest services. Getting .mp4 files from /home/seluser/videos, putting into videos folder in my storage. However, you need another service that runs in your server to upload a file into server storage.

## Example

For ex; you have zalenium_Test.mp4 video file in  /home/seluser/videos folder,  this spring application takes video file from volume, put it into http upload service which is related with external storage. 

If you have a upload service for external storage, this application send video file to that service. You can check the project in this link : **https://github.com/amiluslu/CopyFileFromOpenshiftVolume**

You can modify this project, for your environment.

**Comment by mookkiah** [comment]
@amiluslu if you already in openshift (Kubernetes) you can have different kind of external storage as pvc by using [volume plugins](https://kubernetes.io/docs/concepts/storage/persistent-volumes/). Why do we need another program to do this.

**Comment by pearj** [comment]
This project is no longer maintained. Closing issue
