### ISSUE TITLE
 Could not find Angular on page http://localhost:4200/ 

### ISSUE THREAD

**Issue by haolong7** [zalando/zalenium#1217]
### Error msg from ng e2e
[11:30:43] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
Started
[11:30:56] E/protractor - Could not find Angular on page http://localhost:4200/ : retries looking for angular exceeded

### Host Env
MacOS

### Description
Web app is freshly generated by @angular/cli v11. The only thing added is 
```ts
  seleniumAddress: 'http://localhost:4444/wd/hub',
```
at protractor.conf.ts

Zalenium is run by docker run CMD, which is copied from the site TRY IT section.

At http://localhost:4444/dashboard/# or /live, the video shows angular app triggers  Zalenium to run the app at http://localhost:4200/. However, the browser says "This site cannot be reached; localhost refused to connect."

**Comment by pearj** [comment]
this is not a support forum. Use stackoverflow or slack for this purpose. 

However, this is because localhost refers to the selenium docker container and not localhost on your machine.
