### ISSUE TITLE
Zalenium with multiple dynamic vms on kubernetes  - Goal to execute around 15-20 testcases in parallel for out of 2500 for each job

### ISSUE THREAD

**Issue by tbhatt-conga** [zalando/zalenium#1220]
Hi @diemol 

I have around 4000 testcases to be executed.  I have kubernetes  setup for Jenkins, where dynamic machine is created for each job. I have around 50+ jobs and each job has around 2000 to 3000 testcases. 

How should be setup of zalenium on it. As of now using testng i am able to do parallel execution with 10 threads. Can I triggered execution in multiple machines of same job using Zalenium? If yes , can you help me how to do it? Can I run 20-25 testcases in parallel using zalenium where i have around 2500+ testcases.  What should be system configuration and approach?

**Comment by pearj** [comment]
Please use slack or stackoverflow for help

**Comment by tbhatt-conga** [comment]
Can you provide me slack link?
