### ISSUE TITLE
(HTTP code 500) server error - Ports are not available: listen tcp 0.0.0.0:80: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

### ISSUE THREAD

**Issue by bpurohitRKCI** [zalando/zalenium#1223]
## 💬 Questions and Help
I am unable to load LIVE preview or zalenium dash board
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium)
- [Slack channel - #zalenium channel](https://seleniumhq.herokuapp.com/)

**Comment by pearj** [comment]
This is not a support forum. Use slack
