### ISSUE TITLE
What version of python is compatible for selenium image

### ISSUE THREAD

**Issue by rajesh9383** [zalando/zalenium#1229]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium)
- [Slack channel - #zalenium channel](https://seleniumhq.herokuapp.com/)

**Comment by pearj** [comment]
Selenium grids are managed in another project: https://github.com/elgalu/docker-selenium raise an issue there.
