### ISSUE TITLE
idleTimeout not respected

### ISSUE THREAD

**Issue by ylavoie** [zalando/zalenium#123]
zalenium    | 13:08:17.575 INFO - Got a request to create a new session: Capabilities [{acceptSslCerts=true, idleTimeout=600, browserName=firefox, javascriptEnabled=true, version=, platform=LINUX}]
zalenium    | 13:08:17.586 INFO - Trying to create a new session on test slot {firefox_binary=/home/seluser/firefox-for-sel-3/firefox, seleniumProtocol=WebDriver, acceptSslCerts=true, screen-resolution=1930x1090, tz=America/Montreal, browserName=firefox, maxInstances=1, screenResolution=1930x1090, resolution=1930x1090, version=52.0.2, platform=LINUX}
zalenium    | 13:10:49.651 INFO - http://localhost:40000 Marking the node as down because the test has been idle for more than 90 seconds.
zalenium    | 13:10:49.651 WARN - Cleaning up stale test sessions on the unregistered node http://localhost:40000

**Comment by diemol** [comment]
Hi @ylavoie, thanks for using Zalenium! 

Could you please elaborate a bit more? What is your expected behaviour?

The current behaviour is that when you set a `idleTimeout=600`, the node will shutdown **after the test started** and it has been **idle for 600 seconds or more**.

**Comment by ylavoie** [comment]
That was indeed my expected behaviour and if you look in my initial message, I asked for 600 and it shut after 90.

**Comment by diemol** [comment]
OK, @ylavoie 
Let me check it and I'll let you know.

**Comment by diemol** [comment]
I was able to reproduce it @ylavoie, it is a bug indeed, we will look into it. Thanks for reporting.

**Comment by diemol** [comment]
@ylavoie just added a fix that will be released soon. 
Basically I made the mistake to assume that "idleTimeout" was coming always as a number and never as a String.
`desiredCapabilities.setCapability("idleTimeout", 600);` 
instead of
`desiredCapabilities.setCapability("idleTimeout", "600");`

**Comment by diemol** [comment]
Hi @ylavoie,
This fix was just released https://github.com/zalando/zalenium/releases/tag/3.3.1h 

Please give it a try and let us know if it works now, feel free to reopen this issue if you find any problems.

**Comment by rohansingh97** [comment]
Hello @diemol 
So we should use string for idle timeout or integer works or both.

Regards
Rohan
