### ISSUE TITLE
Does Zalenium is supported on Openshift 4.6?We are working on deploying it in our 4.6 environment.Kindly provide the steps for doing the same.

### ISSUE THREAD

**Issue by ksrinathme** [zalando/zalenium#1230]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium)
- [Slack channel - #zalenium channel](https://seleniumhq.herokuapp.com/)

**Comment by pearj** [comment]
Issues are not a support forum.

**Comment by ksrinathme** [comment]
Hi Joel,

Kindly let me know where can I raise a help request or could you please
direct for installing zalenium on open shift 4.6 ???

Thanks,
Srinath.K
