### ISSUE TITLE
Feature: Allow user to specify a subdirectory for videos, in desiredCapabilities

### ISSUE THREAD

**Issue by borisivan** [zalando/zalenium#125]
I was hoping to use this on a Jenkins build agent, where multiple jobs might run various suites. Some of those jobs might run in parallel. I was looking to automate archiving the videos, which are currently successfuly copied by zalenium to /tmp/videos of the host running docker.

But they all get stored in that one directory. At the end of the suite, if I attempt to automate copying and clearing the videos relevant to that suite, I might copy (and clean) videos from a different suite that was running in parallel.

If I were able to set a videoSubdirectory name in the desiredCapabilities, then each suite could have it's videos "organized", if Zalenium were to copy videos to /tmp/videos/$videoSubdirectory/<video file>

Then we can reliably manipulate that specific subdirectory at the end of our suite, without worrying about stepping on any other suite's activity.

I did see that we could set the test name, which gets incorporated into the filename of the video file, but that's not sufficient if I have more than one instance of the suite (with the same tests) running at the same time.

**Comment by elgalu** [comment]
Good point @borisivan but instead of `videoSubdirectory` I would add some grouping capability.

Sauce Labs for example has the `build` capability and in the dashboard they can group the tests by this `build` name or id.

Within Zalenium we could use the `build` as `videoSubdirectory` IMO instead of adding a new capability that will only work for Zalenium.

**Comment by borisivan** [comment]
Sounds great -- the $build value in desiredCapabilities would work for me -- if I understand correctly, it could be leveraged for dashboard organization, as well as subdirectory organization (I automate copying the videos out, not manually via the dashboard UI).

**Comment by borisivan** [comment]
I did also just realize that I can cross reference the selenium session ID (i.e. save that to a variable at test launch, and then use it to copy the "correct" video out of the directory) as a workaround until you implement the $build functionality.

**Comment by borisivan** [comment]
actually I take that back -- I'm able to get a sessionID from webDriver, but it never seems to match the sessionID in the filename, though they both seem to be of the same format.

For example, from the Java test, I can execute the command:
SessionId session = ((RemoteWebDriver)webDriver).getSessionId();
and session.toString() is: 2cd41569-f3b8-465a-89ba-c4e21ef1831a

But the sessionID in the filename for the video is something different. Tried 3 times, and they were always different. So, maybe I don't have a workaround, and will be eagerly awaiting the implementation of the $build functionality discussed above. :)

**Comment by diemol** [comment]
This has been just released https://github.com/zalando/zalenium/releases/tag/3.5.3b
