### ISSUE TITLE
Free up Browserstack instances if tests fail or don't issue a quit()

### ISSUE THREAD

**Issue by raroraupgrade** [zalando/zalenium#127]
We had a few tests that were doing a driver.close() instead of driver.quit() at the end. Which left the BrowserStack sessions running. BrowserStack times out orphan sessions after 90s of inactivity but Zalenium still shows the instance in use and never times out. 
This queues up any further tests requiring BrowserStack capabilities.
There might be a timeout configuration missing for BrowserStack. 

I can help retest or provide further details to repro. Let me know!

**Comment by diemol** [comment]
Hi @raroraupgrade,

Yeah, this is probably a bug, there is room for improvement in the integration with these platforms. I'll look into that and I'll let you know. 

If you spot the problem earlier, a PR would be much appreciated.

**Comment by raroraupgrade** [comment]
Sure, will keep an eye out for the problem here.

Btw, I see same behavior with SauceLabs so it's probably the code that interacts with both external platforms.

**Comment by diemol** [comment]
Yeah, I was able to reproduce it earlier today. 
I think we need to implement the "killing orphan sessions" in Zalenium for the external platforms as well.
I'll look into that in the following days.

**Comment by diemol** [comment]
Hi @raroraupgrade,

We just released https://github.com/zalando/zalenium/releases/tag/3.3.1m, so please give it a try.

I'll close this issue now but feel free to reopen if a related issue comes up.
