### ISSUE TITLE
Video recording failure with Java exception

### ISSUE THREAD

**Issue by AronNovak** [zalando/zalenium#131]
We have Travis integration of Zalenium and recently we faced with this:
```
hub_1           | 17:47:38.653 INFO - http://localhost:40000 [bash, -c, start-video]

hub_1           | 17:47:39.133 ERROR - http://localhost:40000java.lang.RuntimeException: java.io.IOException: Connection reset by peer

hub_1           | java.lang.RuntimeException: java.io.IOException: Connection reset by peer

hub_1           | 	at com.google.common.base.Throwables.propagate(Throwables.java:240)

hub_1           | 	at com.spotify.docker.client.DefaultLogStream.computeNext(DefaultLogStream.java:58)

hub_1           | 	at com.spotify.docker.client.DefaultLogStream.computeNext(DefaultLogStream.java:35)

hub_1           | 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)

hub_1           | 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)

hub_1           | 	at com.spotify.docker.client.DefaultLogStream.readFully(DefaultLogStream.java:77)
```

The log is available here:
https://travis-ci.org/Gizra/drupal-elm-starter/jobs/237544124

That's how we start the things:
https://github.com/Gizra/drupal-elm-starter/blob/master/ci-scripts/docker_files/docker-compose.yml

**Comment by elgalu** [comment]
How many tests in parallel do you run @AronNovak ?

**Comment by billagee** [comment]
I started seeing this same error yesterday - every once in a while, a video would be successfully saved, but mostly I would see no video saved, along with this `Connection reset by peer` error in the zalenium container log.

**Comment by elgalu** [comment]
Thanks for reporting this guys, @diemol is looking into it now.

**Comment by diemol** [comment]
Hi @AronNovak,

That basically comes from a docker-client issue https://github.com/spotify/docker-client/issues/513

We were refactoring to prepare Zalenium for Kubernetes, and this was a bug introduced in that refactoring. We were catching the exception before and I made the mistake to remove it.

We just fixed it and we'll release between today and tomorrow.

**Comment by AronNovak** [comment]
@elgalu we always execute a single test at a time. Thanks for the fix, that was truly swift!

**Comment by diemol** [comment]
Hi @AronNovak,
This fix was just released https://github.com/zalando/zalenium/releases/tag/3.3.1h 

Please give it a try and let us know if it works now, feel free to reopen this issue if you find any problems.

**Comment by AronNovak** [comment]
@diemol our full Travis workflow works again as expected, we have the videos! Thanks again!
