### ISSUE TITLE
enhancement: need some kind of video/log qty limit (sliding window, etc)

### ISSUE THREAD

**Issue by borisivan** [zalando/zalenium#134]
Hi,

Our implementation would have zalenium running for a long time in a CI environment, with quite a few tests and videos. I'm handling archiving them to an external share (the subdirectory enhancement I logged will help keep things organized in /tmp/videos, but that's different than the issue I'm describing here).

If I understand things correctly, Zalenium doesn't currently limit the qty of videos & logs retained -- it just goes on forever until the container is rebuilt. For a CI environment with lots of tests, this could be a problem.

I see the URL for the "cleanAll", but I'm not looking to delete everything, as that might step on others currently recording. What I'm really looking for is options like:

maxNmberOfTestVideosAndLogsToKeep = <x>

or, when the 'builds' functionality is implemented,

maxNumberOfBuildsToRetain = <x> (regardless of how many videos and logs are in each "build" (suite)

Both could be a sliding window, any > x, oldest are deleted first. And would hope that the index.html could be adjusted so that it reflects these changes.

**Comment by diemol** [comment]
I am going to close this one since we haven't seen interest from the users and it is not a relevant feature for us internally.

If someone wants to contribute, please send us a pull request.
