### ISSUE TITLE
exited containers not removed

### ISSUE THREAD

**Issue by borisivan** [zalando/zalenium#137]
Hi,

I'm running on SLES 12, docker 1.12.6.

None of my containers remove themselves, Not sure how much memory/disk that's wasting. Starting zalenium on Windows (via docker-toolbox) via the same command, doesn't show the same problem.

After some tests:

# docker ps -a
...
...
19d9dfb077dd        elgalu/selenium:latest   "entry.sh"          6 hours ago         Exited (0) 6 hours ago                                                             zalenium_40032
dbbbd5f36aed        elgalu/selenium:latest   "entry.sh"          6 hours ago         Exited (0) 6 hours ago                                                             zalenium_40031
d0ff3621efb7        elgalu/selenium:latest   "entry.sh"          6 hours ago         Exited (0) 6 hours ago                                                             zalenium_40030
20789b75a880        elgalu/selenium:latest   "entry.sh"          6 hours ago         Exited (0) 6 hours ago                                                             zalenium_40029
c63534dcd72b        elgalu/selenium:latest   "entry.sh"          6 hours ago         Exited (0) 6 hours ago                                                             zalenium_40027
71e8a22007fc        elgalu/selenium:latest   "entry.sh"          6 hours ago         Exited (0) 6 hours ago                                                             zalenium_40028
fa74af59c06a        elgalu/selenium:latest   "entry.sh"          6 hours ago         Exited (0) 6 hours ago                                                             zalenium_40026
c3aacc940a90        elgalu/selenium:latest   "entry.sh"          2 days ago          Up 2 days (healthy)                                                                zalenium_40001
24a6709de78d        elgalu/selenium:latest   "entry.sh"          2 days ago          Up 2 days (healthy)                                                                zalenium_40000
7e565869e7d1        dosel/zalenium           "entry.sh start"    2 days ago          Up 2 days                         0.0.0.0:4444->4444/tcp, 0.0.0.0:5555->5555/tcp   zalenium

Not sure if it's related, but some containers show exit (137), (is that container OOM)?

This is a 16G VM, as a Jenkins slave.

I'm launching zalenium as a command within the Jenkins job itself (which is a maven project) (after it detects it's not already running):

docker run --rm -tid --name zalenium -p 4444:4444 -p 5555:5555 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos dosel/zalenium start

But I've tried running it manually outside of the Jenkins process (this time, without the -d parameter), and when the tests run from the maven job in Jenkins, I get the same results -- zalenium/docker isn't able to remove the containers after they exit. If I manually execute the docker rm <container name> it works just fine.

Hoping this is something you've seen before, and is an easy one, because I'm running into various performance problems even just running tests sequentially... nothing in parallel!!

**Comment by elgalu** [comment]
Hi @borisivan please wait for the upcoming release in which we target perf issues. Around this week.

You may want to upgrade docker also, in the meantime.

**Comment by borisivan** [comment]
Hi,

I can confirm that the latest version of docker (17.3.x) on Ubuntu auto-removes the exited containers. My other location is a SLES machine that is very restrictive about me upgrading docker. If you're pretty certain that it's a docker bug as opposed to something about the way this project is requesting the delete, please go ahead and close this issue.

Thanks!

Looking forward to checking the new release of zalenium to see the performance improvements. Whether it's something wrong with my docker setup, or something here, I can't seem to run anything in parallel, and sometimes even sequential tests have trouble. Have seen several remoteDriver exceptions re; session terminated due to ORPHAN, etc. Video termination and copying seems VERY slow too, like 10-15 seconds after closing & quit the browser.

**Comment by diemol** [comment]
Hi @borisivan,

Yeah, the auto-remove feature was implemented on the docker client side, and they only added it some versions ago to the API. In Zalenium we create the containers with the auto-remove flag, that is why in previous docker versions it won't work. Nevertheless, exiting Zalenium should clean those exited containers.

On the performance side, we will release tomorrow (latest Friday). We want to release but also provide a small performance document with our findings and some data from running Zalenium in our machines, and also some guidelines. We expect that people help us to complement that document via PRs.

If it is OK for you, I will close this issue and please follow the performance part in #103.
