### ISSUE TITLE
[question] Is it normal for the zalenium/selenium containers to consume 2x memory on SLES?

### ISSUE THREAD

**Issue by borisivan** [zalando/zalenium#141]
Hi,

I've upgraded Ubuntu and SLES 12 to run the same version of docker.

Pulling the same version of dosel/zalenium and elgalu/selenium and running zalenium with the same arguments:

docker run --rm -ti --name zalenium -p 4444:4444 -p 5555:5555 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos dosel/zalenium start

The zalenium container and two default elgalu/selenium containers seem to take approx 2x the memory, when run on SLES vs Ubuntu, Is this normal/explained?

Apologies in advance if this is common knowledge, I'm fairly new to docker.

After starting zalenium and letting it settle for a minute or two WITHOUT RUNNING any tests:

**Ubuntu**:
CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O           PIDS
23b5fb5964d3        0.27%               208.8 MiB / 15.67 GiB   1.30%               16.9 kB / 7.51 kB   0 B / 14.3 MB       45
62fd035856e3        0.25%               218.2 MiB / 15.67 GiB   1.36%               16.9 kB / 7.51 kB   0 B / 14.2 MB       45
96ee1efbc808        5.92%               382.6 MiB / 15.67 GiB   2.38%               16.9 kB / 7.51 kB   0 B / 852 kB        70

**SLES 12:**
CONTAINER           CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O           PIDS
460385b85482        0.56%               454.6MiB / 15.6GiB   2.85%               16.9kB / 7.1kB      0B / 32.3kB         0
ddeea54a66b1        0.60%               463.5MiB / 15.6GiB   2.90%               16.9kB / 7.1kB      0B / 21.5kB         0
9461cbc44618        2.22%               785.7MiB / 15.6GiB   4.92%               16.9kB / 7.1kB      0B / 0B             0

The mem usage of each container is a little less than 2x on SLES 12 compared to Ubuntu.

**Comment by diemol** [comment]
Hi @borisivan,

To be honest, I don't know. Do you see the same behaviour with other docker containers? Perhaps you can try a simple nginx container on both OS, or even better, try the official [docker-selenium](https://github.com/seleniumhq/docker-selenium).

Please let us know how it goes.

**Comment by diemol** [comment]
Hi @borisivan,

Were you able to check that? Unfortunately we don't have a SLES 12 env to check it.

Would be cool to have your feedback.

**Comment by borisivan** [comment]
I was able to load elgalu/selenium and see that it was 2x on SLES12, than Ubuntu. Just noticed that your request was for me to try official, let me give that a shot..

**Comment by borisivan** [comment]
Ya, something is weird with my docker on SLES, clearly this isn't a zalenium issue.

Just loading selenium/hub, and not doing anything (no tests, etc):

SLES 12
**
CONTAINER           CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O           PIDS
8ce43b4e9a23        0.06%               149.1MiB / 15.6GiB   0.93%               0B / 0B             57.5MB / 0B         0

Ubuntu
**
CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O           PIDS
05d3140608b4        0.12%               74.79 MiB / 15.67 GiB   0.47%               0 B / 648 B         0 B / 8.19 kB       26

**Comment by elgalu** [comment]
So is a general docker problem on SLES versus Ubuntu? if so I guess we can close this issue.

**Comment by diemol** [comment]
Thanks for the feedback @borisivan!
I'll close this issue since it is not related to Zalenium.
