### ISSUE TITLE
Videos dashboard leaks memory

### ISSUE THREAD

**Issue by pearj** [zalando/zalenium#142]
I've noticed that if you leave the videos dashboard open for a long time it leaks a lot of memory to the point where Google Chrome kills it for using too much memory.

When I first open it the Google Chrome task manager says it's using about 180MB, then after an hour it was up to 700MB, and that's without any new tests running through Zalenium.

**Comment by diemol** [comment]
Hi @pearj,

Thanks for reporting, we'll look into that.

**Comment by diemol** [comment]
Hey @pearj,

Is this still happening? I wanted to reproduce it but I couldn't. I've had the dashboard open for ~3 hours and it is using ~200MB the whole time.

**Comment by pearj** [comment]
How many videos did you have there? Maybe it only happens when there are a few thousand videos.

**Comment by diemol** [comment]
I just had around 40 videos. I've never had so many. 

Seems like a extreme/corner case, it is kind of hard for me to reproduce. 

I will google a bit to see if I can find some fix, if not then I guess I'll close the issue unless you have any suggestion.

**Comment by pearj** [comment]
I guess we run a lot of tests, I guess it highlights other issues with how to automatically clean up videos after a certain period. 3,000 videos is probably a few weeks woth.

Here are some snapshots from chrome:

![zalenium-number-of-tests](https://user-images.githubusercontent.com/237821/30304744-75712a02-97b2-11e7-8b4d-5561db3aa687.png)

I reloaded the dashboard and it went like this:

9:59:02 am
![12-09-2017 9-59-02 am](https://user-images.githubusercontent.com/237821/30304765-7ecc81d2-97b2-11e7-8905-d78fa1b009b8.png)

9:59:27 am
![12-09-2017 9-59-27 am](https://user-images.githubusercontent.com/237821/30304761-7e9c95bc-97b2-11e7-8187-aca13cf30cf6.png)

9:59:48 am
![12-09-2017 9-59-48 am](https://user-images.githubusercontent.com/237821/30304762-7eb229a4-97b2-11e7-8765-8c8f6ffe1cec.png)

10:00:15 am
![12-09-2017 10-00-16 am](https://user-images.githubusercontent.com/237821/30304763-7eba7942-97b2-11e7-827c-97065be4a780.png)

To me, it seems that because it continuously reloads the videos page and refreshes the content, it must leak memory that way.  I suppose the easiest way to solve this is to implement some sort of automatic eviction mechanism of old tests.
