### ISSUE TITLE
Session timeout error

### ISSUE THREAD

**Issue by ryudice** [zalando/zalenium#145]
I'm not sure if this is related to zalenium but seems to happen only with it.

Session [fb9f2fb9-97c9-49f7-a470-c2887a3893c2] was terminated due to ORPHAN Command duration or timeout: 47 milliseconds

We get this error randomly.

Any ideas?

**Comment by diemol** [comment]
Hi @ryudice,

Which Zalenium version are you using? I also saw it a few times while working on #116, and we fixed it for the last release 3.3.1i.

Please let me know.

**Comment by ryudice** [comment]
Seems fine @diemol , Thanks!
