### ISSUE TITLE
Node creation stuck after latest release

### ISSUE THREAD

**Issue by AronNovak** [zalando/zalenium#147]
![egyenleg1](https://user-images.githubusercontent.com/114076/26970834-059bebfa-4d0b-11e7-9805-e4b54bb11d6f.png)

Since yesterday, the Travis builds started to stall:
https://travis-ci.org/Gizra/drupal-elm-starter/jobs/240576849

At the point where it would create a new node for test execution, it happens on multiple projects consistently.

```
Request has waited 30 attempts for a node, something went wrong with the previous attempts, creating a new node for {rotatable=true, tz=Asia/Jerusalem, locationContextEnabled=true, name=login, loggingPrefs={driver=ALL, browser=ALL}, browserName=chrome, javascriptEnabled=true, waitingFor_CHROME_Node=29, handlesAlerts=true, maxInstances=1, screenResolution=1930x1090, requestOrigins={name=webdriverio, version=4.6.2, url=http://webdriver.io}}.
```

The config:
https://github.com/Gizra/drupal-elm-starter/blob/master/ci-scripts/docker_files/docker-compose.yml

**Comment by diemol** [comment]
Hi @AronNovak,

Sorry if we broke something again 😟 
It could be related to the network mode change that we did. We will use your docker-compose file to check it.

**Comment by diemol** [comment]
I was able to reproduce it, we are looking into it.

**Comment by elgalu** [comment]
Sorry @AronNovak , we are also adding some docker-compose tests so it doesn't break again :)

**Comment by diemol** [comment]
Hi @AronNovak

We just released a fix and we also added some integration tests to check that docker-compose keeps working for future releases.

Please check it and let us know,
