### ISSUE TITLE
Chrome Cert Support, Add Ability to Mount Arbitrary Folders in Node File System

### ISSUE THREAD

**Issue by ReservedDeveloper** [zalando/zalenium#148]
This closely mimics #64, but I'd like to expand on it. More specifically, I'm looking to configure Chrome's cert store at `~/.pki/nssdb`.

Being able to mount a volume via, say, `-v /my-host-dir:/tmp/node/node-file-path`, might be the most straightforward. Though it is handing library users a loaded gun, so to speak.

Expanding the mount behavior to a more general scope seems like the most versatile solution, but I'd also be thrilled just to see `$HOME/.pki/nssdb/` modification ability.

**Comment by ReservedDeveloper** [comment]
For context, [this link](https://chromium.googlesource.com/chromium/src/+/lkcr/docs/linux_cert_management.md) details the cert process for Chrome a little more in depth.

**Comment by pearj** [comment]
Instead of editing the chrome certs db, why don't you just set the "[acceptSslCerts](https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities)" capability to true?

**Comment by ReservedDeveloper** [comment]
@pearj A valid question. I'm actually interested in utilizing client/personal certs that are being presented _to_ the server for authentication purposes. The setting you mention is for handling CA certs presented _from_ the server. Because of the way it's entangled in OS-level security (esp. on Windows), it's not something Selenium presents an easy way to handle.

There _is_ a setting for presenting certificates based on certain criteria ([AutoSelectCertificateForUrls](https://www.chromium.org/administrators/policy-list-3#AutoSelectCertificateForUrls)), but it still requires a cert be loaded in the store.

**Comment by pearj** [comment]
Ahh mutual ssl. Fair enough

**Comment by pearj** [comment]
I was thinking on kubernetes this could be fairly easily supported by mounting any persistent volume that is mounted on zalenium that has an access mode of ReadOnlyMany or ReadWriteMany. 

See:
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

But you're not using kubernetes are you?

**Comment by ReservedDeveloper** [comment]
No, I'm using Docker. But I'll keep that in mind for the PR I'm putting together.

**Comment by diemol** [comment]
Released https://github.com/zalando/zalenium/releases/tag/3.3.1l

Thanks for contributing @ReservedDeveloper!
