### ISSUE TITLE
Filtering videos by test failure status

### ISSUE THREAD

**Issue by pearj** [zalando/zalenium#151]
I was thinking about an enhancement that would be useful to us, and that is being able to filter the list of videos showing only videos that show test failures.

I realise that Zalenium is one step removed from the test framework, however, I was thinking that it should be possible to send a message to Zalenium via the Selenium API that could tell Zalenium the test status.

At first, I thought about creating a completely new selenium command, but then I realised that although Zalenium is a proxy, it can't prevent the calls from being proxied; it can only run before or after the command, it can't decide to respond itself without actually proxying.  Meaning that new commands would make it all the way to the node and they might not like getting commands they don't understand.

So, I started hunting through the selenium API for a command that I could abuse without any side effects, and I think that `org.openqa.selenium.remote.RemoteWebDriver.RemoteWebDriverOptions.addCookie(Cookie)` is the winner.  Because you could basically add an expired cookie from a [TestNG Listener](http://testng.org/doc/documentation-main.html#logging-listeners) inside the onFailure callback with a name of say, `zaleniumTestFailed`, with a value of `true` or something like that.

When we run Selenium tests, we store the WebDriver in a ThreadLocal so that the TestNG Listener can access the WebDriver when tests fail to grab a screenshot (not exactly necessary with video recording anymore).

This could probably further be extended to have a mode where Zalenium can be configured to auto-delete videos that haven't failed or something like that.

I also remember reading in #146 that @elgalu said that there was the possibility of recording videos without compression.  If only failed videos are kept, then maybe uncompressed is a bit more workable, especially if zelenium compresses the videos in the background.

So, would you guys accept a PR that abuses `addCookie` and adds a show only failed videos checkbox to the videos dashboard?

**Comment by elgalu** [comment]
I don't have a yes/now answer to the `addCookie` idea right now but regarding having videos only for the failed tests... I think that's the right thinking.

What I've been suggesting Zalenium users is to always run the tests with `recordVideo` in false the first time, and if the test fails then run it again with video recording enabled so it should only record videos for debugging failed tests.

What do you think about that approach?

**Comment by pearj** [comment]
Hi @elgalu, I think that not recording first up would work if you had a high degree of confidence in your tests and the environments in which they are running. Neither of which we have at the moment. We get random failures due to low quality tests and environmental issues. 
Although, there are some circumstances where your approach could work well for us, when we use tests to generate some load on our application. In that case the test is so simple we know it's not the fault of the test but the application underneath. So, rerunning the test with the same input data and video recording on could work well.

**Comment by diemol** [comment]
Somehow I thought I commented here, but I did not.

This is something that many people have asked. It is nice to have your tests recorded, and it could be useful if you want to do a demo or something like that. But in reality what people most of the time need, is to see the video of the test that failed.

I didn't want to implement an endpoint for this, and I also checked the Selenium API after reading your comment @pearj. Maybe it could be a hack, but for me it sounds like a good idea. We could include it in Zalenium the way you suggest if you want :)

In the meantime, you can also check @AronNovak's [post](https://www.gizra.com/content/travis-wdio/) with a different approach.

**Comment by pearj** [comment]
So, with @AronNovak's post it wasn't clear how it decided what videos had failed and that it should upload them to google drive. But I presume it must be via file name? I guess if you use the `name` capability and you include the build number in that name. Then you find all the matching file names for the build number or something?

**Comment by AronNovak** [comment]
@pearj Yes, it's based on the filename. These are the key points of being able to do that:
https://github.com/Gizra/drupal-elm-starter/blob/master/ci-scripts/docker_files/run_webdriverio.sh#L28
https://github.com/Gizra/drupal-elm-starter/blob/master/client/wdio.conf.travis.js#L48

And then the exit status of the test tool, but that's the obvious part.

**Comment by diemol** [comment]
Yeah, I just wanted to share what @AronNovak did since I thought the approach was very creative and cool. Maybe he has also a thought on this one?

So far I like @pearj's idea since we could use that info to mark the test as failed or passed in the dashboard.

**Comment by TomLarrow** [comment]
> What I've been suggesting Zalenium users is to always run the tests with recordVideo in false the first time, and if the test fails then run it again with video recording enabled so it should only record videos for debugging failed tests. 

If Zalenium can get to the point where it identifies tests passing or failing, can this be done automatically?  I'm reluctant to implement this resubmit with video recording on in my CI as our tests are highly parallelized, spinning up 20 nodes at once and running through a total of 80+ features, if one test in one of those fail, I don't want to resubmit all of the tests with video recording on, I just want to resubmit the one that failed

**Comment by pearj** [comment]
Remember that zalenium is simply a fancy selenium grid, it is too far removed from test execution to be able to replay tests by itself.  You'd have to implement the retry in your test framework.

The only thing that zalenium could do in theory, is replay the selenium commands exactly as it received them, but that would be rather meaningless as it has no idea what constitutes a test failure.

The best that zalenium can do is be told when a test has failed, which is what this issue is about.

**Comment by diemol** [comment]
[WIP]

![image](https://user-images.githubusercontent.com/5992658/30597148-70fb2a82-9d56-11e7-85ad-e1249146e0ab.png)

**Comment by pearj** [comment]
@diemol this looks really cool! One thing I was pondering was the ability to treat all the videos in the same build as one in terms of whether it should keep them around or not.

For example, we have a selenium test that creates multiple selenium sessions throughout the same test.  Eg:

1. Login as user A create some data
1. Login as user B assign the task to user C
1. Login as user C and progress the task

We had a scenario once, where the selenium test didn't wait for long enough before it closed the browser and the assignment step 2 didn't complete.  Then when it went to step 3, the data was missing, so the test failed. However, the video for step 3 was not useful, because all that video showed was that the data was missing. It wasn't till I watched video 2 that I noticed the test ended abruptly (I needed to add a selenium waitFor condition to fix that particular issue, nothing to do with zalenium).

So I think it would be cool to have another flag that would expand the behaviour of `--keepOnlyFailedTests` to include keeping all videos with the same build id, if any one of the videos failed.  This probably belongs in another ticket, but it would be interesting to know your thoughts.

**Comment by diemol** [comment]
Thanks @pearj!

With this one, I have also implemented #125. This allows you to group tests by passing a capability called `build`. If this capability is passed, then it will be shown in the dashboard. When the build is shown in the dashboard, it is possible to filter all the tests from one build by just typing the build name in the search field. (In addition, all the videos and logs are placed in a sub-folder with the build name).

Now, to keep all the videos of the same build id if one of the test fails is not in the scope of this one. It is a cool idea, I am just afraid of adding too much logic to the core proxy that handles the actual tests, and how it could affect the performance. Also to know how if this is a common case or more if this is a feature that only a few ones would use.

**Comment by diemol** [comment]
This has been just released https://github.com/zalando/zalenium/releases/tag/3.5.3b
