### ISSUE TITLE
Improve unit tests for Kubernetes

### ISSUE THREAD

**Issue by diemol** [zalando/zalenium#156]
After merging #155 the coverage decreased.

Perhaps @pearj could give us a hand here :) 

Coverage report https://codecov.io/gh/zalando/zalenium

**Comment by pearj** [comment]
Nice one! Sorry I didn't get to this.  I really want to work on zalenium, but I haven't been able to schedule time at work yet.

**Comment by diemol** [comment]
No worries @pearj! You already helped us a lot, but more help is always appreciated :)
I plan to write a small blog post about the k8s part in the following days, where I'll mention your help, I hope that's ok.

**Comment by pearj** [comment]
Sure @diemol, that's fine to mention me.
