### ISSUE TITLE
Improve Zalenium-Kubernetes documentation

### ISSUE THREAD

**Issue by diemol** [zalando/zalenium#159]
The current documentation demands the user to check extra resources to learn how to get started. We should change the document in a way that anyone could follow a step by step guide to run Zalenium in Kubernetes, documenting the guide with Minikube is enough for now.

**Comment by pearj** [comment]
Ahh, so we don't want to assume any level of proficiency in kubernetes in order to use zalenium? Can we assume they have minikube installed? Or should it include that too?

**Comment by diemol** [comment]
In general we can assume that the user knows what Kubernetes is, but the less clicks around they need to do to understand how to start Zalenium in Kubernetes, the more they will be engaged I think.

I'll try to restructure the document pointing out the main resources and giving a small step by step guide.

**Comment by pearj** [comment]
Ok sounds good. I ended up finishing the first draft of the doco at like 11pm, and I really just wanted to go to bed... it probably shows ;)

**Comment by diemol** [comment]
No worries! It was more than enough to start. If we waited until it was perfect we wound't have released yet. Thanks again for the effort!

**Comment by diemol** [comment]
I'll close this one based on this [commit](https://github.com/zalando/zalenium/commit/e2003839a2cfa0279ff9ecd965159cfc1b7d7d8c). The docs will improve as we move on.
