### ISSUE TITLE
Excessive logging inside container

### ISSUE THREAD

**Issue by skisel** [zalando/zalenium#162]
Hello,

We have an issue with disk space inside docker container of zaleniem:
root@42992dd3d63f:/home/seluser/logs# ls
stdout.zalenium.docker.node.log  stdout.zalenium.hub.log
root@42992dd3d63f:/home/seluser/logs# du -h
13G	.

Within a day we create too many logs. How can we reduce the amount of logs there?

**Comment by diemol** [comment]
Hi @skisel,

You are right, this is something we saw some weeks ago but we have not had time to work on that. 

Nevertheless the plan is to spend a couple of days during the next two weeks to improve the logging. Right now is logging a lot of stuff and it is sometimes difficult to read it. We'll make that better and also add some rotation strategy.

Thanks for reporting.

**Comment by diemol** [comment]
This has been fixed in #222, which will be released during the week.

**Comment by diemol** [comment]
We just released this fix with https://github.com/zalando/zalenium/releases/tag/3.3.1r, I'll close this issue now. 
Please let us know if it doesn't work as expected.
