### ISSUE TITLE
Add Node Mounting Support to Kubernetes

### ISSUE THREAD

**Issue by ReservedDeveloper** [zalando/zalenium#164]
Related to #148, as mentioned by @pearj in [one of the comments](https://github.com/zalando/zalenium/issues/148#issuecomment-310227707), propose adding node mounting support to Kubernetes similar to Docker.

**Comment by diemol** [comment]
This was added to the most recent release, please check the latest tag https://github.com/zalando/zalenium/releases/tag/3.6.0d

The way it works is straightforward, just add more mounted folders and they will be mapped to the newly created pods. 

If any problem comes from this change, please create a new issue.
