### ISSUE TITLE
Add .Gitattributes File To Protect Line Endings on Windows

### ISSUE THREAD

**Issue by ReservedDeveloper** [zalando/zalenium#165]
Propose adding a `.gitattributes` file [similar to this](https://github.com/oracle/docker-images/blob/master/.gitattributes) for the purposes of protecting the project's various shell scripts on Windows checkout.

**Comment by diemol** [comment]
@ReservedDeveloper 
If you want to be shown in the contributors, please check your git config. This is what I see when I check the commit:

![image](https://user-images.githubusercontent.com/5992658/27473061-07d7db6a-57fe-11e7-80ad-1b6d0ad25071.png)

**Comment by ReservedDeveloper** [comment]
Ah nuts, I really thought I'd updated my local config to change that email. Ah well. I'll update it for the remaining stuff. Thanks!

**Comment by diemol** [comment]
If you do it in your Github profile it will just recognise it, unless you don't want to add that email of course :)
