### ISSUE TITLE
iOS and Android node support

### ISSUE THREAD

**Issue by kahyalar** [zalando/zalenium#167]
Hello everyone, I'm just curious about how can we create node into this, like Android and iOS and are you going to be implement this feature ?

Thanks

**Comment by diemol** [comment]
Hi @kahyalar,

We have plans to integrate https://github.com/butomo1989/docker-android in the 2nd semester. Support for iOS is not feasible right now, the way the OS is licensed requires that it runs in an Apple machine, so you could not use that image anywhere.

**Comment by kahyalar** [comment]
Hi @diemol , first, thank you for quick comment. 
I just trying to clear my mind, if you implement something like iOS node, only mac users can be able to use that node 
OR
It can't be implemented via license restriction.

If you check the link, I'll be happy.
[ios-driver repo](https://github.com/ios-driver/ios-driver)

**Comment by diemol** [comment]
We haven't really checked in detail, but for us it would be more like option 1, from the ones you mention.

The project looks interesting, do you know if there is a docker version of it?

**Comment by kahyalar** [comment]
I just searched but, this driver is depracated. Beacuse I'm using appium-xcuitest driver. I saw [appium's Android docker](https://github.com/appium/appium-docker-android) version but not iOS version.

**Comment by diemol** [comment]
I think we need to wait for a change in the licensing model or look for different approaches. As I said, we only have in our roadmap is to integrate the docker-android solution we currently have. Lets hope that some iOS magic happens in the 2nd semester and perhaps we have something there.

For now, I will close this issue since we will address this in our internal planning but we will make the progress visible when we start working on it.

**Comment by DowneyTung** [comment]
Hey Diemol,
Just want to follow up on this issue. Is the Android node support implemented already for this project ?
https://github.com/butomo1989/docker-android

**Comment by diemol** [comment]
@DowneyTung no, this is the same as #217, which no one has implemented yet, all feature requests are now consolidated in #654 
Any help is appreciated.
