### ISSUE TITLE
On-demand browser container node startsup takes +- 5 minutes on Kubernetes

### ISSUE THREAD

**Issue by thasherwin** [zalando/zalenium#170]
I have Zalenium installed in kubernetes and when trying to run a tests on a on-demand browser container node of chrome the startup takes around +- 5 min. Also my tests fails before the node is started. I get the following error message:

```
Unable to parse remote response: <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Do you know why it takes so long and is it possible to always have at least 4 nodes up and running without being shut down after a test is executed on a node?

**Comment by diemol** [comment]
Hi @thanasisk, 
Hm, that's strange. We are in beta but still that should not happen.

Can you share with me the yaml file you used to start Zalenium?

**Comment by thanasisk** [comment]
Hi @diemol - wrong mention - I think you need to ask @thasherwin

**Comment by thasherwin** [comment]
I looked deeply with a developer into this issue and we noticed the following: We get a nullPointerException as soon as a test is started to create a new chrome container:

```
09:13:02.551 ERROR - [DS] java.lang.NullPointerException
java.lang.NullPointerException
        at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.getRunningContainers(KubernetesContainerClient.java:292)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumStarterRemoteProxy.validateAmountOfDockerSeleniumContainers(DockerSeleniumStarterRemoteProxy.java:633)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumStarterRemoteProxy.startDockerSeleniumContainer(DockerSeleniumStarterRemoteProxy.java:434)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumStarterRemoteProxy.startDockerSeleniumContainer(DockerSeleniumStarterRemoteProxy.java:428)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumStarterRemoteProxy.lambda$getNewSession$2(DockerSeleniumStarterRemoteProxy.java:386)
        at java.lang.Thread.run(Thread.java:748)
```

Below the yaml file:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: zalenium
    role: grid
  name: zalenium
  namespace: zalenium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zalenium
      role: grid
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zalenium
        role: grid
    spec:
      containers:
      - args:
        - start
        - --firefoxContainers
        - "0"
        - --chromeContainers
        - "4"
        - '--videoRecordingEnabled '
        - '"false"'
        image: dosel/zalenium
        imagePullPolicy: Always
        name: zalenium
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /tmp/mounted
          name: data-zalenium
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      serviceAccount: zalenium
      serviceAccountName: zalenium
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/zalenium
        name: data-zalenium
```

**Comment by diemol** [comment]
Sorry @thanasisk!

**Comment by diemol** [comment]
@thasherwin, 

I will check it tomorrow, right now I only have access to minikube. Can you tell me which version of Kubernetes you are running, how you are mounting the volumes, and how you create the service account?

Thanks

**Comment by thasherwin** [comment]
@diesel
I will reply tomorrow. Tomorrow I can check with the developer.

**Comment by thasherwin** [comment]
@diemol 
- kubernetes (on-site installation) version 1.5.2 
- we are mounting a hostPath volume, zalenium main POD is fixed on a node using a nodeSelector
- all PODs that are created by zalenium are (it seems) not using the nodeSelector, therefore are placed on different hosts (and cannot access the same volume mount)
- service account "zalenium" was created using "kubectl create sa zalenium" (no further configuration was done)

**Comment by thasherwin** [comment]
We upgraded kubernetes and downgraded the Selenium version from 3.4.0  to 3.3.0 and all issues are now solved. So I will close this issue.

**Comment by diemol** [comment]
@thasherwin thanks for reporting back! I am glad it works for you now.
I am sorry but it has been a bit busy and we didn't have time to check it.

To what version of k8s did you upgrade?

**Comment by thasherwin** [comment]
@diemol 
1.6.4
