### ISSUE TITLE
Support multiple browser version

### ISSUE THREAD

**Issue by zhenjunz** [zalando/zalenium#180]
Hi, I just setup one environment with zalenium, it works fine, thanks for your efforts. After starting zalenium with below command:
docker run --rm -ti --name zalenium -p 4444:4444 -p 5555:5555     -v /var/run/docker.sock:/var/run/docker.sock     -v /tmp/videos:/home/seluser/videos     --privileged dosel/zalenium start --screenWidth 1920 --screenHeight 1080

I can only run tests with one version of Firefox and one version of Chrome, do you have a guideline to add more versions for each browser? so testers can select specific browser version as they like?

**Comment by diemol** [comment]
Hi @zhenjunz,

Thanks for the nice words!

Well, this is something we have discussed internally and also with some people outside... Among the discussed things, we have:
* How much are browsers changing between versions? If there is a breaking change, then people keep the current [docker-selenium](https://github.com/elgalu/docker-selenium) image and not update until they adapt to the changes.
* How to handle the overhead to support the versions combination? For example, Selenium 3.3.1 only works with some versions of ChromeDriver and GeckoDriver, and subsequently ChromeDriver and GeckoDriver only work with some versions of Chrome and Firefox respectively.  

In general we saw that in most of the situations people test with the latest version available in the images and if they needed to stay with an specific version, they keep the [docker-selenium](https://github.com/elgalu/docker-selenium) image that they need. The use case is not that common to invest all the effort needed to implement and maintain the extra logic.

To answer your question (and I hope to not disappoint :)), the current guideline is for you to handle this on your local environment. This means, for example, to test with Chrome 58 you would pull the [3.3.1-p11](https://github.com/elgalu/docker-selenium/releases/tag/3.3.1-p11) release and run your tests with it, and so on.

If you have any ideas that could help us to handle that in a simple way, please let us know, or even better, send us a pull request.

**Comment by zhenjunz** [comment]
Thanks, Is that possible to run different version of zalenium on different host, in same selenium-grid environment? it means being transparent to tests, they use current UI and current 4444 api, we use different hosts to support different version of browsers.

**Comment by diemol** [comment]
You could run more than one instance of Zalenium on the same host, or different hosts. You just need to check what image you are using, and also what image of elgalu/docker-selenium you are using.

What I didn't understand was this:
> in same selenium-grid environment?

What do you mean by that?

**Comment by zhenjunz** [comment]
@diemol , with Zalenium runs on multiple hosts, I just want to give testers' one hub path, for example:
http://zalenium:4444/wd/hub

How to make Zalenium instances to join the same hub? and I have one Windows host(with selenium node installed), can I join it to the same hub either?

**Comment by diemol** [comment]
For this:
> with Zalenium runs on multiple hosts, I just want to give testers' one hub path, for example:
http://zalenium:4444/wd/hub

Maybe you can try this https://github.com/seleniumkit/gridrouter, or its evolution https://github.com/aerokube/ggr from the Aerokube guys. 

And for this:
> How to make Zalenium instances to join the same hub? and I have one Windows host(with selenium node installed), can I join it to the same hub either?

You can do it in a normal way, Zalenium is running a standard grid so you can add new nodes that support IE or Safari. Just take into account to set the port of the node to something different from `5555`, since that is the default port for nodes but we are using it for the dashboard.

**Comment by zhenjunz** [comment]
Got it.  @diemol , thanks for your help!

**Comment by diemol** [comment]
You are welcome! 
I'll close this issue then. Feel free to reopen if any related problems arise, or please open a new one in case you bump into a different problem.
