### ISSUE TITLE
Is there anyway to pass `--add-host` (or `extra_hosts` in compose file) options to node containers in the latest zalenium

### ISSUE THREAD

**Issue by toshiya** [zalando/zalenium#182]
Hi, we are using zalenium for running our UI test suites. It is pretty good. Thank you so much for the development.

My question here is that how to pass  `--add-host` option value to node containers in the latest zalenium. In our test suites, we want to add special `/etc/hosts` settings in node containers.

As shown in the following log,  it seems that,  `--add-host` options (`extra_hosts` option is equivalent in compose file) do not work properly for node containers. 

docker-compose.yml (set google.co.jp to 127.0.0.1 with extra_hosts)

```
# cat docker-compose.yml
version: '2.1'

services:
  zalenium_stg:
    image: "dosel/zalenium:3.3.1n"
    container_name: zalenium_stg
    hostname: zalenium_stg
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 4444:4444
      - 5556:5555
    command: >
      start --screenWidth 1930 --screenHeight 1090
            --timeZone "Asia/Tokyo"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
            --sendAnonymousUsageInfo false
    extra_hosts:
      - "google.co.jp:127.0.0.1"
```

zalenium starts. zalenium_stg is hub, zalenium_stg_40000 is node.

```
# docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                                      NAMES
c5528a38bad9        elgalu/selenium:latest   "entry.sh"               4 minutes ago       Up 4 minutes        0.0.0.0:40000->40000/tcp, 0.0.0.0:50000->50000/tcp         zalenium_stg_40000
0d042390067e        dosel/zalenium           "entry.sh start --..."   4 minutes ago       Up 4 minutes        0.0.0.0:4444->4444/tcp, 4445/tcp, 0.0.0.0:5556->5555/tcp   zalenium_stg
```

Then, in the hub container,  the extra_hosts (--add-hosts) option works properly.
```
# docker exec -it zalenium_stg  /bin/bash
root@zalenium_stg:/home/seluser# ping google.co.jp
PING google.co.jp (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.057 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.064 ms
^C
--- google.co.jp ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1046ms
rtt min/avg/max/mdev = 0.057/0.060/0.064/0.008 ms
```

However, in the node container, the extra_hosts(--add-hosts) option does not work.
```
# docker exec -it zalenium_stg_40000  /bin/bash
seluser@c5528a38bad9:~$ ping google.co.jp
PING google.co.jp (172.217.27.67) 56(84) bytes of data.
64 bytes from nrt12s15-in-f67.1e100.net (172.217.27.67): icmp_seq=1 ttl=37 time=0.404 ms
64 bytes from nrt12s15-in-f67.1e100.net (172.217.27.67): icmp_seq=2 ttl=37 time=0.377 ms
64 bytes from nrt12s15-in-f67.1e100.net (172.217.27.67): icmp_seq=3 ttl=37 time=0.281 ms
^C
--- google.co.jp ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2022ms
rtt min/avg/max/mdev = 0.281/0.354/0.404/0.052 ms
```

I guess  handling of `--add-hosts` option in zalenium has not been well defined yet because we could use the above docker-compose.yml properly before 3.3.1h. 

Is there someway to set `/etc/hosts` settings in node containers in the latest zalenium?

**Comment by diemol** [comment]
Hi @toshiya, thanks for the nice words!

That makes completely sense. It was working before 3.3.1h because we were using the docker network mode "container". This meant that everything created by Zalenium was considered as "localhost".

While this was very practical in many situations (like yours), it was a "hardcoded concept" that was blocking us to allow Zalenium scale horizontally. Therefore we removed that network mode so we could receive a PR implementing the integration with Kubernetes.

What we can do is to add it as a feature. We can look into that in the following days, it should not be a huge change. If you feel like, you can also send a PR for it :)

I will leave this issue open until we make it work again.

**Comment by toshiya** [comment]
Hi, @diemol.

Thank you very much for your detailed explanation. I got the situation about the docker network mode used in old and current versions of zalenium.

As you mentioned,  I think it's very cool to add a feature to control the "/etc/hosts" settings of node containers.  

> I will leave this issue open until we make it work again.

Thank you very much. I will also look at the related code in this weekend.

**Comment by diemol** [comment]
This has just been released https://github.com/zalando/zalenium/releases/tag/3.3.1o
Thanks @toshiya for your contribution!

Closing the issue...

**Comment by toshiya** [comment]
@diemol 

Thank you so much !
