### ISSUE TITLE
Feature: Add live preview to dashboard

### ISSUE THREAD

**Issue by dkalaria** [zalando/zalenium#185]
Instead of having 2 different URLs to route to if we could have the live preview in the dashboard that could be a really good feature.
I would like to contribute to add this feature.

**Comment by diemol** [comment]
Hi @dkalaria,

That sounds like a good idea. We'd be happy to receive a PR addressing that :)

**Comment by diemol** [comment]
I'll close this one to clean up a bit. 

Please send us a PR whenever you feel like implementing this feature, thanks!
