### ISSUE TITLE
Unable to start the Zalenium

### ISSUE THREAD

**Issue by anurajsl** [zalando/zalenium#187]
Hi, I am unable to start Zalenium. 

I used the folowing command in cmd:

> docker run --rm -ti --name zalenium -p 4444:4444 -p 5555:5555 \
>     -v /var/run/docker.sock:/var/run/docker.sock \
>     -v /tmp/videos:/home/seluser/videos \
>     --privileged dosel/zalenium start

But it's not working. Kindly help.

**Comment by diemol** [comment]
Hi @anurajsl,

Can you provide us more info? What type of error are you getting? Some console logs could help.

**Comment by anurajsl** [comment]
It's fixed now. :)
