### ISSUE TITLE
My test is passed, but I could not see the preview video. 

### ISSUE THREAD

**Issue by anurajsl** [zalando/zalenium#190]
Even though my test is passed, The video preview is not available. How can I get this viewed ?

> No video with supported format and MIME type found.

![image](https://user-images.githubusercontent.com/111569/28363704-d3d782be-6c81-11e7-8577-77fbeee8b13f.png)

**Comment by elgalu** [comment]
Which browser are you using to open the dashboard @anurajsl ?

Try Firefox

**Comment by anurajsl** [comment]
I have tried both firefox and chrome. Doesn't work in both :(

**Comment by elgalu** [comment]
Do you have latest Chrome? Which operating system?

**Comment by anurajsl** [comment]
Yes. Windows 10

**Comment by anurajsl** [comment]
Also if you have a slack channel I would like to join you guys there. Please mention it also.

**Comment by elgalu** [comment]
Chat channel: https://gitter.im/zalando/zalenium

**Comment by elgalu** [comment]
What about with Internet Explorer / Microsoft Edge? Seems to be solved: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11005755/

**Comment by elgalu** [comment]
If you go to the downloaded folder, can you open the mp4 files there?

We are not really testing this on Windows though some users reported it also works there.

**Comment by mNantern** [comment]
I have the same issue (video preview is not available) with Firefox (54.0.1 (64 bits)) on Mac OS X.

Works fine with Chrome though

**Comment by diemol** [comment]
I think this is a known issue, for me it always works in Chrome, it does not work in any other browser.

Should we work on something that makes videos reproducible in other browsers @elgalu?

**Comment by diemol** [comment]
Seems we didn't get any feedback, if this is still and issue please feel free to reopen.
