### ISSUE TITLE
Nodes creation is looping creating new nodes if you send caps name: nil

### ISSUE THREAD

**Issue by MiluchOK** [zalando/zalenium#191]
Just as an accident I send name capability as nil and got very interesting behavior from zalenium, it started looping and creating containers until it ran out of resources and stalled.

**Comment by diemol** [comment]
Hi @MiluchOK,

How does the capability exactly look like? Can you paste a few lines of code so we can reproduce it?

Thanks,

**Comment by diemol** [comment]
OK, I was able to reproduce it in Python using `'name': None`, we will fix it and release it soon.

**Comment by diemol** [comment]
Fixed via #197, will be released next week.
Thanks for reporting it @MiluchOK

**Comment by diemol** [comment]
Hi @MiluchOK, this was just released.
https://github.com/zalando/zalenium/releases/tag/3.3.1p

Closing the issue.
