### ISSUE TITLE
Feature: Add ability to specify http_proxy/https_proxy environment variables of spawned Selenium nodes

### ISSUE THREAD

**Issue by SVPA-BetsyFox** [zalando/zalenium#198]
# Need the ability to set OS level environment variables for http/https proxy
I need the ability to set, at the OS level, http/https proxy environment variables in order to get through a very strict corporate network- I'm struggling to find an easy way of specifying values for HTTP_PROXY and HTTPS_PROXY in the spawned node containers.

Is there currently any mechanism in place for this sort of feature?

**Comment by diemol** [comment]
Hi @SVPA-BetsyFox,

That sounds interesting and I think it makes sense... so if I understand correctly, you want to do something like:

```
docker run -e "http_proxy=http://myproxy.example.com:8080" \
        -e "https_proxy=https://myproxy.example.com:8080" \
        ... \
        dosel/zalenium start
``` 

and then have those http/https values from the env vars in the spread containers?

**Comment by SVPA-BetsyFox** [comment]
Essentially, yeah- it's been the main sticking point I've found with each of the Docker/Selenium projects I've tried out so far.

I wouldn't need the env vars set in the main hub container- just the selenium nodes (I've actually found this to cause issues between the hub and selenium nodes in most of the other solutions I've played with)

In most use cases, you'd also likely be setting `no_proxy=172.16/12, 10.0.0.0/8, *.local, 169.254/16, 192.168.99.*, localhost, 127.0.0.1` at the same time.

I'm otherwise really liking how close Zalenium comes without nearly as much effort on my part- some fine work.

**Comment by TomLarrow** [comment]
I faced the same issue, and solved it by building my own selenium image with a 2 line Dockerfile

FROM elgalu/selenium
ENV http_proxy=http://myproxy.example.com:8080 https_proxy=http://myproxy.example.com:8080 no_proxy=172.16/12, 10.0.0.0/8, *.local, 169.254/16, 192.168.99.*, localhost, 127.0.0.1

a hack, for sure, but it would at least it would give you a container that would work in your environment

**Comment by diemol** [comment]
I think the clean solution would be to check the `http_proxy` and `http_proxys`env vars and then pass them to the docker-selenium containers.

This seems to become a common thing, since we did recently something similar to add hosts across all containers.

We'll look into that.

**Comment by diemol** [comment]
Hi @SVPA-BetsyFox,

This was just released in https://github.com/zalando/zalenium/releases/tag/3.6.0e

Please check the [documentation](https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#adding-proxy-configuration-to-the-containers) to see how to use it.

If there are any problems while using this feature, please open a new issue.

**Comment by SVPA-BetsyFox** [comment]
Thank you very much- works like a charm, and clears so many headaches for me! :)

**Comment by diemol** [comment]
Thanks for the feedback @SVPA-BetsyFox, I am happy it works well!
