### ISSUE TITLE
JUnit Test Run : Localhost

### ISSUE THREAD

**Issue by DeChrish** [zalando/zalenium#204]
Hi,
while executing the test in localhost using junit runner it works perfect in local machine.
After setting up the zalenium images, when is execute the test in node the test fails because of the ip address.

I need to pass `local ip address:port` instead of `localhost:port`
Ex: `xxx.xx.xxx.xx:80`  not `localhost:80`

How to tunnel the localhost with the selenium node for JUnit Runner?

**Comment by elgalu** [comment]
Hi, please take a look at [Accessing the host](https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#accessing-the-host)

**Comment by DeChrish** [comment]
@elgalu can you give me the command line for OSx.

`docker run --rm -ti --name zalenium -p 4444:4444 -p 5555:5555  --net=mac.host.local -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos  --privileged dosel/zalenium start`

**Comment by diemol** [comment]
@DeChrish you do not need to change the `docker run...` command for this if you are in OSX.

If you were using `http://localhost:port` in your test, when using Zalenium you just need to switch to `http://mac.host.local:port`.

Please try it and let us know how it goes.

**Comment by DeChrish** [comment]
@diemol  thanks; but i am not using any url in my test; we are using an open source framework for test suites. i have raised the issue in their repo. lets wait for their reply. i will still find out the source for the junit url : https://github.com/Cognifide/bobcat/issues/211

**Comment by DeChrish** [comment]
@diemol  it is junit runner the localhost info in taken from `/etc/host`

**Comment by DeChrish** [comment]
@diemol found it
