### ISSUE TITLE
Not able to access dashboard

### ISSUE THREAD

**Issue by DeChrish** [zalando/zalenium#209]
`http://localhost:4444/dashboard  `
`Whoops! The URL specified routes to this help page.`

READ ME - URL

`[BETA] Dashboard, see all the videos and aggregated logs after your tests completed`

**Comment by diemol** [comment]
Hi, @DeChrish 
Seems like you are not using the latest image released yesterday?

Please try again `docker pull dosel/zalenium` to get the latest one and check the url again.

**Comment by DeChrish** [comment]
@diemol thanks!!!

**Comment by luisxiaomai** [comment]
@diemol , I used the latest images, but it seems navigate to http://localhost:4444/dashboard will link to the URL specified routes to this help page.

**Comment by diemol** [comment]
@luisxiaomai please try http://localhost:4444/dashboard/ (with a "/" at the end).

This is something known and we hope to fix it soon.

**Comment by luisxiaomai** [comment]
@diemol , thanks for your help. It need a "/" at the end. Hope it can be fixed asap because is not consistent with related document.
