### ISSUE TITLE
OLD MAC Mini Node

### ISSUE THREAD

**Issue by DeChrish** [zalando/zalenium#213]
Hi, 
I have bunch of old mac mini's. Is it possible to add as docker nodes to zalenium?

**Comment by Legionivo** [comment]
You should first read what is docker and what is Selenium Grid

**Comment by diemol** [comment]
Hi @DeChrish, 
Somehow I never saw this issue, but yes, assuming you got the knowledge on how to start a node in each mac mini, you can register them in Zalenium. 
I did a small experiment with my mac a few months ago, and I was able to register and use Safari via Zalenium.

If you are able to do it, feel free to send us a PR with documentation!
