### ISSUE TITLE
Error forwarding request from HUB to Node

### ISSUE THREAD

**Issue by srinuuk** [zalando/zalenium#219]
Running tests behind corporate firewall proxy on AWS.
org.openqa.selenium.WebDriverException: cannot forward the request XXX.XX.X.X:40004 failed to respond
Command duration or timeout: 125.94 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'acbc32bd441d', ip: 'fe80:0:0:0:14a8:c128:de65:5f99%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.remote.RemoteWebDriver

**Comment by diemol** [comment]
Hi @srinuuk,

Can you please describe the scenario more?
Where is Zalenium deployed, where are the tests running? Is it like a big EC2 instance?

**Comment by srinuuk** [comment]
Hi @diemol,
It's due to internal proxy issue. I was able to resolve it. Closing this issue.

**Comment by diemol** [comment]
Nice, thanks for reporting back!

**Comment by Fmdv** [comment]
Hi, @srinuuk 
How you fixed this issue? I have the same problem

**Comment by srinuuk** [comment]
I have updated selenium docker image with our internal proxy and it worked.

**Comment by diemol** [comment]
Did you rebuild the elgalu/docker-selenium image with the appropriate env vars for the http_proxy?

**Comment by Fmdv** [comment]
thanks, I will update here too
