### ISSUE TITLE
Question, is there a way to ensure all the mp4 files have been saved

### ISSUE THREAD

**Issue by jayudey-wf** [zalando/zalenium#220]
First, thanks a lot for this project. It has been straight forward to implement and is very feature rich.

My question comes from trying to run this as part of CI and encountering an issue where my tests complete exit my ci runner prior to zalenium saving off the last / all of the .mp4 video(s). I was hoping to use some programatic way to verify all the videos had been captured but couldn't derive one and just wanted to see if you or any others had come across this.

Thanks

**Comment by diemol** [comment]
Sorry for the late reply @jayudey-wf,

The bash script that starts and stops Zalenium tries to make sure that all the files are present before stopping the process. We have a text file with the number of tests that have a video, and we wait a while until they are there.

So you could run into the situation where some files are missing depending on the way you stop Zalenium. How are you shutting it down in your CI env?

**Comment by jayudey-wf** [comment]
Oh ok, I was just sending a kill command after my tests complete to all active processes and then exiting the docker container at that point. I can just wait for the `docker-compose down` command to complete though.

Thanks again for the project and the response!

**Comment by diemol** [comment]
Thanks for the nice words :)
> Thanks again for the project and the response!

Give the `docker-compose down` a try and let us know how it went, so we could potentially close this issue.

**Comment by diemol** [comment]
@jayudey-wf I assume it went well for you. I'll close this one, but feel free to reopen in case something didn't work.
