### ISSUE TITLE
Chrome driver ignores screenWidth and screenHeight parameters

### ISSUE THREAD

**Issue by afail** [zalando/zalenium#227]
docker run --rm -ti --name zalenium -p 4444:4444 -p 5555:5555 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start --screenWidth 1920 --screenHeight 1080 --timeZone “America/Chicago”

The screenWidth and screenHeight values are considered using the firefox driver, but not chrome

**Comment by elgalu** [comment]
I copy pasted your docker run command and the resolution is consistent with the provided options.

Can you try the one-liner? this example will set a very small screen to make it obvious:

```
curl -sSL https://raw.githubusercontent.com/dosel/t/i/p | bash -s start -i --screenWidth 300 --screenHeight 150
```

Then check it out at http://localhost:4444/grid/admin/live/preview

e.g. with the small resolution sample:

![image](https://user-images.githubusercontent.com/111569/30162042-6abd1b30-93d3-11e7-8348-6ec753a0b89c.png)

Also the dashboard shows that both browsers looks good, after running some tests.

You can also try setting the resolutions through the capabilities:

```
desiredCapabilities.setCapability("screenResolution", "300x150");
```

What could also be happening is that you are not connecting to the grid and running chromedriver locally, in which case you are not using Zalenium at all. So double check in Zalenium dashboard to ensure the tests are running there: http://localhost:4444/dashboard

![image](https://user-images.githubusercontent.com/111569/30162243-58c2daf4-93d4-11e7-9825-aceee91306b3.png)

**Comment by afail** [comment]
Thanks for the reply. It looks like the site I was testing was rendering a mobile layout despite the resolution.
