### ISSUE TITLE
can't get test using chrome to use existing container, always spawns new

### ISSUE THREAD

**Issue by borisivan** [zalando/zalenium#240]
Hi,

This isn't related to the new performance improvements, I've noticed this before the recent changes.

When I run a test RemoteWebDriver: Chrome, it always spins up a new container (and the new container works). But if there is an existing container capable of running chrome, it won't use it. For example, running Zalenium at it's defaults, which spins up 2 containers -- when I run the test, those two containers are never used. A new container is spun up as soon as I start the first step.

I just tried adding the 2 lines in bold, and that doesn't work either. Any ideas?

    if (browser.toLowerCase().contains("chrome")) {
                    System.setProperty("webdriver.chrome.driver", webDriverPath);
                    cap = DesiredCapabilities.chrome();
                    **cap.setCapability(CapabilityType.BROWSER_NAME, BrowserType.CHROME);
                    cap.setCapability(CapabilityType.PLATFORM, Platform.LINUX);**
                    ChromeOptions options = new ChromeOptions();
                    options.addArguments("disable-infobars");
                    Map<String, Object> prefs = new HashMap<String, Object>();
                    prefs.put("credentials_enable_service", false);
                    prefs.put("profile.password_manager_enabled", false);
                    prefs.put("profile.default_content_settings.popups", 0);
                    prefs.put("download.prompt_for_download", false);
                    options.setExperimentalOption("prefs", prefs);
                    cap.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
                    cap.setCapability(ChromeOptions.CAPABILITY, options);

                    LoggingPreferences logPrefs = new LoggingPreferences();
                    logPrefs.enable(LogType.BROWSER, Level.WARNING);
                    cap.setCapability(CapabilityType.LOGGING_PREFS, logPrefs);

                    cap.setCapability("screenResolution", "1920x1080");
                    webDriver = new RemoteWebDriver(new URL(hubUrl), cap);

**Comment by diemol** [comment]
Hi @borisivan,

Zalenium has as a default screen resolution `SCREEN_WIDTH=1900` x `SCREEN_HEIGHT=1880`.
https://github.com/zalando/zalenium/blob/master/scripts/zalenium.sh#L15 

And I see that you set:
```
cap.setCapability("screenResolution", "1920x1080")
```

Since the existing nodes don't have that screen resolution, a new one is started for you.

Check this to start Zalenium with a given screen resolution https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#with-screen-width-and-height-and-time-zone

**Comment by borisivan** [comment]
awesome, will give that a shot, thx!

**Comment by borisivan** [comment]
When adding these arguments to starting the container::

 --screenWidth 1920
 --screenHeight 1080

zalenium starts. I've asked it to start with 3 containers, and they start, but then when the tests start, new containers are spun up. But instead of the tests working, each remoteWebDriver instantiation attempt now throws an exception:

Is there a set of logs I can obtain? Not sure how to grab those from the command line.

org.openqa.selenium.WebDriverException: Error forwarding the new session The listener threw an exception ( listener bug )
Command duration or timeout: 6.99 seconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$22(ProtocolHandshake.java:365)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:368)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:159)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:174)

**Comment by borisivan** [comment]
Logs -- does this help identify the problem?

21:26:30.199 INFO - Registering the node to the hub: http://localhost:4444/grid/register
....21:26:31.132 INFO - [DS] Capabilities grabbed from the docker-selenium image
21:26:31.137 INFO - Registered a node http://172.17.0.1:30000
21:26:31.137 INFO - [DS]  Setting up 3 nodes...
21:26:31.137 INFO - The node is registered to the hub and ready to use
21:26:31.140 INFO - 3 containers were created, it will take a bit more until all get registered.
DockerSeleniumStarter node started!
Sauce Labs not enabled...
Browser Stack not enabled...
TestingBot not enabled...
Zalenium is now ready!
*************************************** Data Processing Agreement ***************************************
By using this software you agree that the following non-PII (non personally identifiable information)
data will be collected, processed and used by Zalando SE for the purpose of improving our test
infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
of the IP address are collected.

See the complete license at https://github.com/zalando/zalenium/blob/master/LICENSE.md
*************************************** Data Processing Agreement ***************************************
21:26:37.777 INFO - Mismatched capabilities. Creating a synthetic w3c capability.
21:26:37.782 INFO - Got a request to create a new session: Capabilities [{acceptSslCerts=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@243a12b4, name=Sep17-15-26-25-defaultTestName, browserName=chrome, chromeOptions={
args=[disable-infobars], extensions=[], prefs={credentials_enable_service=false, profile.default_content_settings.popups=0, download.prompt_for_download=false, profile.password_manager_enabled=false}}, screenResolution=1920x1080, platfor
mName=LINUX, version=, platform=LINUX, group=Sep17-15-26-25}]
21:26:37.785 INFO - [DS] Starting new node for {acceptSslCerts=true, loggingPrefs={browser=WARNING}, name=Sep17-15-26-25-defaultTestName, browserName=chrome, chromeOptions={args=[disable-infobars], extensions=[], prefs={credentials_enabl
e_service=false, profile.default_content_settings.popups=0, download.prompt_for_download=false, profile.password_manager_enabled=false}}, screenResolution=1920x1080, platformName=LINUX, version=, platform=LINUX, group=Sep17-15-26-25}.
21:26:44.661 INFO - Registered a node http://172.17.0.4:40002
21:26:44.663 INFO - Trying to create a new session on test slot {chrome_binary=/usr/bin/google-chrome-stable, seleniumProtocol=WebDriver, acceptSslCerts=true, screen-resolution=1920x1080, tz=Europe/Berlin, browserName=chrome, maxInstance
s=1, screenResolution=1920x1080, resolution=1920x1080, version=61.0.3163.91, platform=LINUX}
21:26:44.674 ERROR - Error running the beforeSessionListener : null
java.lang.UnsupportedOperationException
        at com.google.common.collect.ImmutableMap.put(ImmutableMap.java:495)

**Comment by diemol** [comment]
Strange.

Can you please give me the docker command you use to start the containers and a code snippet showing how you run the tests? (with capabilities as well)

**Comment by borisivan** [comment]
I thought the extra containers were being started when my tests started... but it might be simpler than that. To make sure I could paste the exact docker command for you, I started zalenium from the command line (I normally start via automation), and it did the same thing, without even running a test!! It starts 2 containers instantly, and then exactly 1 minute later, complains that those two containers weren't ready in time, and then starts 2 more. That matches the pattern I was seeing when my suite launches zalenium automatically, and my tests start ~ 1 minute after my suite starts, so I had assumed the second 2 containers were being started due to my tests. If I do run tests, they successfully use the most recently started containers.

But as shown below, if I launch zalenium from the command line and don't do any tests... the same thing happens:

docker run --rm -ti --name=zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start

Docker binary already present, will use that one.
Docker version 17.04.0-ce, build 78d1802
-- LOG 00:49:38:465458007 Ensuring docker works...
-- LOG 00:49:38:512224032 Ensuring no stale Zalenium related containers are still around...
-- LOG 00:49:38:531887441 Ensuring docker-selenium is available...
-- LOG 00:49:38:574632460 Running additional checks...
haveged: haveged starting up
Copying files for Dashboard...
Starting Nginx reverse proxy...
Starting Selenium Hub...
....00:49:39.590 INFO - Selenium build info: version: '3.5.3', revision: 'a88d25fe6b'
00:49:39.595 INFO - Launching Selenium Grid hub
...00:49:40.420 INFO - binding de.zalando.ep.zalenium.servlet.LivePreviewServlet to /grid/admin/LivePreviewServlet/*
00:49:40.423 INFO - binding de.zalando.ep.zalenium.servlet.ZaleniumConsoleServlet to /grid/admin/ZaleniumConsoleServlet/*
00:49:40.425 INFO - binding de.zalando.ep.zalenium.servlet.ZaleniumResourceServlet to /grid/admin/ZaleniumResourceServlet/*
00:49:40.427 INFO - binding de.zalando.ep.zalenium.dashboard.DashboardCleanupServlet to /grid/admin/DashboardCleanupServlet/*
..00:49:40.720 INFO - Will listen on 4445
.00:49:40.874 INFO - Nodes should register to http://172.17.0.1:4445/grid/register/
00:49:40.876 INFO - Selenium Grid hub is up and running
Selenium Hub started!
Starting DockerSeleniumStarter node...
..00:49:41.557 INFO - Selenium build info: version: '3.5.3', revision: 'a88d25fe6b'
00:49:41.559 INFO - Launching a Selenium Grid node
.2017-09-18 00:49:41.921:INFO::main: Logging initialized @638ms to org.seleniumhq.jetty9.util.log.StdErrLog
.00:49:41.975 INFO - Driver class not found: com.opera.core.systems.OperaDriver
00:49:42.003 INFO - Driver provider class org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
 registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform LINUX
00:49:42.003 INFO - Driver provider class org.openqa.selenium.edge.EdgeDriver registration is skipped:
 registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform LINUX
00:49:42.004 INFO - Driver provider class org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform LINUX
00:49:42.024 INFO - Using the passthrough mode handler
2017-09-18 00:49:42.048:INFO:osjs.Server:main: jetty-9.4.5.v20170502
2017-09-18 00:49:42.072:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@2e005c4b{/,null,STARTING} has uncovered http methods for path: /
2017-09-18 00:49:42.076:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@2e005c4b{/,null,AVAILABLE}
2017-09-18 00:49:42.086:INFO:osjs.AbstractConnector:main: Started ServerConnector@10e31a9a{HTTP/1.1,[http/1.1]}{0.0.0.0:30000}
2017-09-18 00:49:42.086:INFO:osjs.Server:main: Started @803ms
00:49:42.087 INFO - Selenium Grid node is up and ready to register to the hub
00:49:42.099 INFO - Registering the node to the hub: http://localhost:4444/grid/register
....00:49:43.091 INFO - [DS] Capabilities grabbed from the docker-selenium image
00:49:43.096 INFO - Registered a node http://172.17.0.1:30000
00:49:43.097 INFO - [DS]  Setting up 2 nodes...
00:49:43.097 INFO - The node is registered to the hub and ready to use
00:49:43.099 INFO - 2 containers were created, it will take a bit more until all get registered.
DockerSeleniumStarter node started!
Sauce Labs not enabled...
Browser Stack not enabled...
TestingBot not enabled...
Zalenium is now ready!
*************************************** Data Processing Agreement ***************************************
By using this software you agree that the following non-PII (non personally identifiable information)
data will be collected, processed and used by Zalando SE for the purpose of improving our test
infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
of the IP address are collected.

See the complete license at https://github.com/zalando/zalenium/blob/master/LICENSE.md
*************************************** Data Processing Agreement ***************************************
00:49:53.000 INFO - Registered a node http://172.17.0.2:40001
00:49:53.415 INFO - Registered a node http://172.17.0.3:40000
00:50:45.680 INFO - [DS] Container zalenium_40001 took longer than 60 seconds to be up and ready, this might be a signal that you have reached the hardware limits for the number of concurrent threads that you want to execute.
00:50:45.877 INFO - [DS] Container zalenium_40000 took longer than 60 seconds to be up and ready, this might be a signal that you have reached the hardware limits for the number of concurrent threads that you want to execute.
00:50:54.676 INFO - Registered a node http://172.17.0.5:40003
00:50:54.677 INFO - Registered a node http://172.17.0.4:40002
00:51:46.685 INFO - [DS] Container zalenium_40002 took longer than 60 seconds to be up and ready, this might be a signal that you have reached the hardware limits for the number of concurrent threads that you want to execute.
00:51:46.686 INFO - [DS] No container was created, will try again in a moment...
00:51:46.694 INFO - [DS] Container zalenium_40003 took longer than 60 seconds to be up and ready, this might be a signal that you have reached the hardware limits for the number of concurrent threads that you want to execute.
00:51:46.695 INFO - [DS] No container was created, will try again in a moment...

Log from zalenium_40000:

# docker logs zalenium_40000
-- INFO: Docker Img. Version: 3.3.1-p27
-- INFO: Chrome..... Version: 61.0.3163.91
-- INFO: Firefox.... Version: 55.0.3
-- INFO: Using Selenium.....: 3.3.1
***************** BEGIN: Data Processing Agreement *****************
By using this software you agree that the following non-PII
(non personally identifiable information) data will be collected,
processed and used by Docker-selenium for the purpose of improving
our test infrastructure tools. Anonymisation with respect of the IP
address means that only the first two octets of the IP address are
collected. See the complete license at:
https://github.com/elgalu/docker-selenium/blob/master/LICENSE.md
****************** END: Data Processing Agreement ******************
supervisord --version=4.0.0.dev0
2017-09-18 00:49:48,418 CRIT Set uid to user 1000
2017-09-18 00:49:48,418 INFO Included extra file "/etc/supervisor/conf.d/novnc.conf" during parsing
2017-09-18 00:49:48,418 INFO Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
2017-09-18 00:49:48,418 INFO Included extra file "/etc/supervisor/conf.d/selenium-multinode.conf" during parsing
2017-09-18 00:49:48,418 INFO Included extra file "/etc/supervisor/conf.d/selenium-node-chrome.conf" during parsing
2017-09-18 00:49:48,418 INFO Included extra file "/etc/supervisor/conf.d/selenium-node-firefox.conf" during parsing
2017-09-18 00:49:48,418 INFO Included extra file "/etc/supervisor/conf.d/video-rec.conf" during parsing
2017-09-18 00:49:48,418 INFO Included extra file "/etc/supervisor/conf.d/vnc.conf" during parsing
2017-09-18 00:49:48,418 INFO Included extra file "/etc/supervisor/conf.d/xmanager.conf" during parsing
2017-09-18 00:49:48,418 INFO Included extra file "/etc/supervisor/conf.d/xterm.conf" during parsing
2017-09-18 00:49:48,432 INFO RPC interface 'supervisor' initialized
2017-09-18 00:49:48,433 INFO RPC interface 'supervisor' initialized
2017-09-18 00:49:48,433 INFO supervisord started with pid 241
2017-09-18 00:49:49,436 INFO spawned: 'xmanager' with pid 244
2017-09-18 00:49:49,440 INFO spawned: 'vnc' with pid 245
2017-09-18 00:49:49,444 INFO spawned: 'novnc' with pid 246
2017-09-18 00:49:49,447 INFO spawned: 'selenium-node-firefox' with pid 247
2017-09-18 00:49:49,448 INFO spawned: 'xterm' with pid 250
2017-09-18 00:49:49,452 INFO success: xterm entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2017-09-18 00:49:51,451 INFO success: xmanager entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
2017-09-18 00:49:51,451 INFO success: vnc entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
2017-09-18 00:49:51,451 INFO success: novnc entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
2017-09-18 00:49:52,457 INFO success: selenium-node-firefox entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)

**Comment by diemol** [comment]
@borisivan 
It should work now, there was a mistake from my part, I released and we didn't release elgalu/selenium yet.

Please pull elgalu/selenium and try it again.

**Comment by borisivan** [comment]
That did the trick!! Thanks. Much better now -- the total time to instantiate the browser has gone down from ~14 seconds to ~3. Multiply that x ~80 tests that average ~ 30 seconds runtime each, and it's an enormous improvement.

One last question on the performance improvement:

Is the new: --maxTestSessions parameter simply the number of tests that will be run (in sequence, since another test attempted in parallel would be in a different container...), in a container before that container will stop and remove itself? The way I use Zalenium today, I start it @ suite begin, and stop it @ suite end. If I have 3 parallel execution groups, (--chromeContainers 3), and they each have a varying number of tests (which can grow without my knowledge), I'm thinking I should just set --maxTestSessions at a very high number, since I don't really need those to shut down, as they'll shut down when I stop Zalenium at the end of the suite. Just wanted to make sure there wasn't some large set of resources I'd be reserving if I set that number arbitrarily high.

**Comment by diemol** [comment]
>--maxTestSessions parameter simply the number of tests that will be run (in sequence, since another test attempted in parallel would be in a different container...), in a container before that container will stop and remove itself?

exactly

The only downside I see from setting a high number for `--maxTestSessions` is perhaps exhausting a container, but that should not happen often. In the end, it should work fine. It is a matter of tuning the appropriate values.

I'll close this issue since we resolved it together.
