### ISSUE TITLE
framerate to reduce CPU strain re: video

### ISSUE THREAD

**Issue by borisivan** [zalando/zalenium#241]
Hi,

In the elgalu container, there is an option to specify the frame rate, which I assume that if lowering, will reduce strain on CPU (and file size). Is this possible to configure as an option for Zalenium so that Zalenium will pass that configuration through?

**Comment by diemol** [comment]
Hi @borisivan,

That option is not available. I think that is a very detailed level of configuration. 

Maybe you can change the option in the elgalu/selenium image rebuild, then try it and see if reduces  CPU usage.

What do you think?

**Comment by borisivan** [comment]
Not sure I understand -- are you asking if I can confirm that CPU usage is lowered when I provide that parameter when using elgalu/selenium? Or are you asking if I can rebuild elgalu/selenium with the default changed, so that zalenium uses it that way? If the latter, that's not really a solution since I always pull the latest elgalu/selenium before running the suite, to get browser updates, bug fixes, etc.

For what it's worth, as it relates to performance -- video is by far and away the biggest consumption of CPU (and disk I/O). The browser manipulation and even container spinup is nothing compared to the CPU usage of ffmpeg for just 1 test with video recording. let alone 2 or 3. in parallel.

**Comment by diemol** [comment]
More the latter. Because I think elgalu/selenium does not have that as a configurable parameter, so it is better to try that first and if it works perhaps send a PR. 
If it works well, then we can include it as an option in the future.

**Comment by borisivan** [comment]
It does have that as a configurable parameter. From [elgalu/selenium:](https://github.com/elgalu/docker-selenium)

Record Videos

Step by step guide at docs/videos.md

If you create the container with -e VIDEO=true it will start recording a video through the vnc connection run upon start. It is recommended to create first a local folder videos in your current directory, and mount the videos directory for an easy transfer with -v $(pwd)/videos:/videos.

Once your tests are done you can either manually stop the recording via docker exec grid /bin-utils/stop-video where grid is just the arbitrary container chosen name in docker run command. Or simply stop the container and that will stop the video recording automatically.

Relevant environment variables to customize it are:

FFMPEG_FRAME_RATE=25
VIDEO_FILE_NAME="test"
VIDEO_FILE_EXTENSION=mp4
FFMPEG_CODEC_ARGS=""
FFMPEG_DRAW_MOUSE=1

**Comment by elgalu** [comment]
That's correct, docker-selenium side you can configure this settings however the README.md is outdated.

Since Zalenium we lowered the `FFMPEG_FRAME_RATE` from 25 to only 10. Less than 10 will give you very poor video results IMHO but the option is there if you want to tweak it:
https://github.com/elgalu/docker-selenium/blob/3.5.3-p0/Dockerfile#L877

As Diego said, you could build your own docker-selenium image with your customizations:

```
FROM elgalu/selenium
ENV FFMPEG_FRAME_RATE=10
```

You will still get updates as your image is based on the upstream one and you only change what you need.

Another possibility is to allow Zalenium to pass-in arbitrary environment variables to docker-selenium, instead of allowing them 1 by 1 however with our current load not sure if we can promise we will implement that.

**Comment by borisivan** [comment]
Glad to hear it was lowered to 10 by default, I think that addresses my concern. When testing with elgalu/selenium, I had set -e FFMPEG_FRAME_RATE=12 a long time ago, and had assumed that with Zalenium, there was no way to pass that along, and elgalu/selenium was defaulting back to 25.

Since that alone addresses my issue, I'll close this issue, and if someone else feels the importance to have Zalenium pass an option through to elgalu/selenium, they can reopen this if desired.

Thanks!
