### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by mojsha** [zalando/zalenium#243]
Scenario:

Hub spins up fine without error messages. 

Reproduce steps:

1. Execute test:

`	@Test(timeout=100000000)
	public void executeChrome() throws MalformedURLException {
		this.execute(DesiredCapabilities.chrome());
	}

	private void execute(DesiredCapabilities capability) throws MalformedURLException {

		capability.setCapability(CapabilityType.ACCEPT_INSECURE_CERTS, true);
		capability.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
		capability.setCapability("recordVideo", false);
		WebDriver driver = new RemoteWebDriver(
				new URL("https://url-to-zalenium/wd/hub"), capability
		);
		driver.get("https://www.google.com/");
		assertThat(
				driver.getTitle(),
				is("Google")
		);
		driver.close();
		driver.quit();
	}`

2. Returns:

executeChrome(eu.nets.selenium.SeleniumStandaloneServerTest)  Time elapsed: 31.708 sec  <<< ERROR!
org.openqa.selenium.WebDriverException: Unable to parse remote response: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>

3. Log from hub:

15:46:53.255 INFO - Got a request to create a new session: Capabilities [{acceptSslCerts=true, acceptInsecureCerts=true, recordVideo=false, browserName=chrome, platformName=ANY, version=, platform=ANY}]
--
  | 15:46:53.255 INFO - [DS] Starting new node for {acceptSslCerts=true, acceptInsecureCerts=true, recordVideo=false, browserName=chrome, platformName=ANY, version=, platform=ANY}.
  | 15:46:53.265 INFO - Pods in the list 0
  | 2017-09-18 15:47:32 INFO  RetryExec:97 - I/O exception (java.net.SocketException) caught when processing request to {s}->https://www.google-analytics.com:443: Network is unreachable (connect failed)
  | 2017-09-18 15:47:32 INFO  RetryExec:113 - Retrying request to {s}->https://www.google-analytics.com:443
  | 2017-09-18 15:47:32 INFO  RetryExec:97 - I/O exception (java.net.SocketException) caught when processing request to {s}->https://www.google-analytics.com:443: Network is unreachable (connect failed)
  | 2017-09-18 15:47:32 INFO  RetryExec:113 - Retrying request to {s}->https://www.google-analytics.com:443
  | 15:47:42.948 INFO - Registered a node http://10.128.6.2:40002
  | 15:47:42.949 INFO - Trying to create a new session on test slot {seleniumProtocol=WebDriver, acceptSslCerts=true, screen-resolution=1900x1880, tz=Europe/Berlin, browserName=chrome, maxInstances=1, screenResolution=1900x1880, resolution=1900x1880, version=61.0.3163.91, platform=LINUX}
  | 15:47:44.564 INFO - [DS] Container zalenium_40002 is up after ~17 seconds...
  | 15:47:44.856 INFO - http://10.128.6.2:40002 start-video: Video recording is disabled

4. Log from Chrome pod:

- INFO: Docker Img. Version: 3.5.3-p0
--
  | -- INFO: Chrome..... Version: 61.0.3163.91
  | -- INFO: Firefox.... Version: 55.0.3
  | -- INFO: Using Selenium.....: 3.5.3
  | ***************** BEGIN: Data Processing Agreement *****************
  | By using this software you agree that the following non-PII
  | (non personally identifiable information) data will be collected,
  | processed and used by Docker-selenium for the purpose of improving
  | our test infrastructure tools. Anonymisation with respect of the IP
  | address means that only the first two octets of the IP address are
  | collected. See the complete license at:
  | https://github.com/elgalu/docker-selenium/blob/master/LICENSE.md
  | ****************** END: Data Processing Agreement ******************
  | supervisord --version=4.0.0.dev0
  | 2017-09-18 15:47:38,820 CRIT Set uid to user 1000
  | 2017-09-18 15:47:38,820 INFO Included extra file "/etc/supervisor/conf.d/novnc.conf" during parsing
  | 2017-09-18 15:47:38,820 INFO Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
  | 2017-09-18 15:47:38,820 INFO Included extra file "/etc/supervisor/conf.d/selenium-multinode.conf" during parsing
  | 2017-09-18 15:47:38,820 INFO Included extra file "/etc/supervisor/conf.d/selenium-node-chrome.conf" during parsing
  | 2017-09-18 15:47:38,820 INFO Included extra file "/etc/supervisor/conf.d/selenium-node-firefox.conf" during parsing
  | 2017-09-18 15:47:38,820 INFO Included extra file "/etc/supervisor/conf.d/video-rec.conf" during parsing
  | 2017-09-18 15:47:38,820 INFO Included extra file "/etc/supervisor/conf.d/vnc.conf" during parsing
  | 2017-09-18 15:47:38,820 INFO Included extra file "/etc/supervisor/conf.d/xmanager.conf" during parsing
  | 2017-09-18 15:47:38,820 INFO Included extra file "/etc/supervisor/conf.d/xterm.conf" during parsing
  | 2017-09-18 15:47:38,910 INFO RPC interface 'supervisor' initialized
  | 2017-09-18 15:47:38,918 INFO RPC interface 'supervisor' initialized
  | 2017-09-18 15:47:38,918 INFO supervisord started with pid 201
  | 2017-09-18 15:47:39,921 INFO spawned: 'xmanager' with pid 204
  | 2017-09-18 15:47:39,923 INFO spawned: 'vnc' with pid 205
  | 2017-09-18 15:47:39,925 INFO spawned: 'novnc' with pid 206
  | 2017-09-18 15:47:39,926 INFO spawned: 'selenium-node-chrome' with pid 207
  | 2017-09-18 15:47:39,928 INFO spawned: 'xterm' with pid 208
  | 2017-09-18 15:47:39,948 INFO success: xterm entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
  | 2017-09-18 15:47:41,972 INFO success: xmanager entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
  | 2017-09-18 15:47:41,973 INFO success: vnc entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
  | 2017-09-18 15:47:41,973 INFO success: novnc entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
  | 2017-09-18 15:47:42,948 INFO success: selenium-node-chrome entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)

**Comment by diemol** [comment]
Did you find something about it @mojsha?

**Comment by dennisgranath** [comment]
If you run zalenium in openshift and have a route set up you should most probably set the timeout on the route to 60s which corresponds to nginx timeout for zalenium. The default timeout for the router in openshift is set to 30 seconds.  Ex:
`apiVersion: v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 60s
  name: zalenium
spec:
  host: zalenium.example.com
  port:
    targetPort: 4444-tcp
  to:
    kind: Service
    name: zalenium`

**Comment by diemol** [comment]
I didn't know that @dennisgranath, if you want you can send a PR to add that in the docs we have for Openshift.

**Comment by dennisgranath** [comment]
Yes me neither @diemol. I just figured it out since it was always happining after 30 seconds. Then I looked at nginx conf where timeout is set to 60s. That's when i thought that it was maybe related to openshift. I will do a pull request tomorrow. Do I need to create a issue?

**Comment by diemol** [comment]
Not all, the PR is enough. Thanks!

**Comment by mohitsh08** [comment]
@diemol @dennisgranath @mojsha 

Hi All,

I am also facing the same issue. Docker is up and running on aws server which is a linux server.
Zalenium is running on aws server. But getting 504 timemout error very frequently.
Please let me know what all config changes i need to do and how can i do those changes
Could you guys please help me with this. Its a urgent request.

Thanks
