### ISSUE TITLE
Question about maxDockerSeleniumContainers

### ISSUE THREAD

**Issue by evertsc** [zalando/zalenium#245]
Hi,

Great project! I have some questions.

Is there a way to read the number of maxDockerSeleniumContainers remotely? For example for the docker-selenium hub you can find MaxSessions on the console page under config.

And is there a way to set the browser timeout?

Thanks you. 
Regards,
Charlie

**Comment by evertsc** [comment]
Sorry, already found it on the console page under Configuration (instead of config). Not sure how I missed that the first time.

Thanks anyways.

**Comment by diemol** [comment]
Hi,

Not really, there is not a way to retrieve that value.

The value you see in the console comes from the nodes config itself.
