### ISSUE TITLE
Ability to group videos

### ISSUE THREAD

**Issue by ryudice** [zalando/zalenium#255]
Is there a way at the moment to group videos by a constant? like for example, the date, or the build server build number?

**Comment by diemol** [comment]
Hi @ryudice,

You can use this https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#build-name

And then videos and logs will be grouped in a folder, the build will be shown in the dashboard, and with the text search you can filter them as well.

**Comment by diemol** [comment]
I'll close this issue since the question was answered.

Feel free to reopen in case you bump into any problem.
