### ISSUE TITLE
[Question] Best practice for parallel testing

### ISSUE THREAD

**Issue by victorMerlis** [zalando/zalenium#256]
I'm using pytest to run the tests (command: `pytest -d --tx ${NUMBER_OF_SELENIUM_NODES}*popen//python=python2.7`) on Linux and Docker version: 17.03.1-ce

I'm starting docker with the following command (4 cpus, 8G mem):
docker run -d -p 4444:4444 \
    -c $number_of_cpus \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --privileged dosel/zalenium:3.3.1i start \
    --timeZone "`cat /etc/timezone 2> /dev/null || ls -l /etc/localtime|/usr/bin/cut -d"/" -f7,8`" \
    --firefoxContainers 0 \
    --chromeContainers 1 \
    --videoRecordingEnabled false

When i'm executing more than 2 tests in parallel the machine almost stuck and work very slow (I tried several machines)

Docker stats screen-shot:
![docker_stats](https://user-images.githubusercontent.com/29833162/30854447-501e85fc-a2ba-11e7-8207-8bda4e87099b.png)

Any suggestions how can I improve the parallelism?

**Comment by laszlocph** [comment]
Are you running the pytest and Zalenium on the same node? Is that your laptop?

To judge parallelism I think best to compare execution times. 

Run on 1 threads, then on 2 and record the execution times. As long as you find improvement in running things in parallel, parallelism makes sense. At some point, though it will tip over and it becomes slower than with lower thread count. Then you maxed out your hardware, what you can confirm CPU usage % and load number.

On my Dell XPS13 two threads run my test suite in 900 seconds and make my laptop unusable during the test. While on my office server CoreI7 4 physical cores(8 threads) I run 6 pytest threads and finish the test in 330seconds.

Tried the same suit on a crazy 24cores (48 threads) machine, with 24x paralelism and finished in 90 seconds.

So back to the original question, 2 threads is pretty much what a laptop can do today.

**Comment by victorMerlis** [comment]
Pytest and Zalenium are running on the machine but pytest isn't running inside the zalenium container.
I executed the test suite on several machine (all of them are 4 cores), I found that I'm getting the execution time when executing 3 tests in parallel.

I found that it is important to change the number of cores to be used by the docker container (--cpu-shares)
I thought that it possible to execute more tests in parallel :\
Thanks :)

**Comment by diemol** [comment]
@victorMerlis you got to the same conclusion, to give more CPU and RAM when needed.

We created some sort of a guideline about this, check https://github.com/zalando/zalenium/blob/master/docs/performance.md, and if you want to add your findings, feel free to send us a PR.
