### ISSUE TITLE
Question: Pinning versions of elgalu/selenium

### ISSUE THREAD

**Issue by dforrest88** [zalando/zalenium#261]
It seems like Zalenium always uses elgalu/selenium:latest. Is there a way to pin specific versions of that container so that latest pulls of one without the other don't cause issues? I'm moving towards an ephemeral grid model and want some predictability around which versions will be there, so I'd like to pin the image tags for these two.

**Comment by akvsh** [comment]
You can specify a version using the `--seleniumImageName` configuration parameter, seen [here](https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#more-configuration-parameters)

**Comment by elgalu** [comment]
thanks for answering @akvsh , so cool to see the community helping each other :)

**Comment by diemol** [comment]
The way @akvsh suggests is the easiest one. 
The other way is to keep the image you want locally, Zalenium does not pull any images, it just looks for one locally, and if it is not present, it does not start.

I'll close this issue since the answer was provided.
