### ISSUE TITLE
Don't upload video if test passes.

### ISSUE THREAD

**Issue by mitchellmaler** [zalando/zalenium#270]
Is there a way to skip the video upload to the hub if the test passed or just remove it after a passed test and keep the failures? Usually we just want to see the video if there is a failure and it would save disk space.

**Comment by diemol** [comment]
Hi @mitchellmaler,

This option already exists, but I forgot to document it in the startup parameters. I just added #273 for that.
Anyway, please try to start Zalenium with `--keepOnlyFailedTests true`, so only videos of failed tests are kept (you need to send a cookie)

**Comment by diemol** [comment]
OK, merged, you can check the docs here:
https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#more-configuration-parameters

I'll close this issue now, but if you find any problems, let us know and feel free to reopen it.

**Comment by CJStroud** [comment]
Hey,

What is the key/value of the cookie that you need to send to flag a test as failed? I might be missing something but I can't see it in the docs anywhere?

**Comment by CJStroud** [comment]
In case anyone else needs to know the cookie should be 

```
name: "zaleniumTestPassed"
value: "false"
```

**Comment by diemol** [comment]
Exactly, thanks @CJStroud for pointing it out.
