### ISSUE TITLE
issue: "test completed" notify showing at the beginning of the next test video

### ISSUE THREAD

**Issue by borisivan** [zalando/zalenium#271]
Hi,

When running tests in parallel across 6 containers, I'm seeing the default notify ("TEST COMPLETED") show up at the beginning of the video for the next test.

What looks to be occurring:

For a given container with max tests still not yet exceeded:

- test <n> runs
- at the time we close the browser, you're putting a "TEST COMPLETED" notify on the desktop
- test <n+1> runs on that same container, starts a new browser and therefore, new video
- the "TEST COMPLETED" message from the previous test still shows for the first second or two of this new test.

When Zalenium is stopping existing video and/or starting the new video, it may want to clear any existing notify banners that haven't timed out yet. (or some other solution). But it would be good to fix this somehow, as the "TEST COMPLETED" at the beginning of most test videos is something that we'll really want out of there.

P.S. I've always assumed that closing the browser is what stimulates zalenium to clean things up. If there is any kind of explicit action I'm supposed to take to denote test begin/end, please let me know.

Thanks!

**Comment by diemol** [comment]
Hi @borisivan,

That's a good point, I really didn't check that. And it does make sense that no popup is present at the beginning of a test.

We'll look into it.

**Comment by diemol** [comment]
Hi @borisivan,

This was fixed on docker-selenium's side, please pull the latest image when the 3.6.0-p6 tag is released.

**Comment by borisivan** [comment]
Yep, looks good! Thx.
