### ISSUE TITLE
nodeSelector for selenium pods in kubernetes

### ISSUE THREAD

**Issue by fmatoss** [zalando/zalenium#282]
I am looking for a way to set the `nodeSelector` for selenium pods, but I couldn't find.

**Comment by mickfeech** [comment]
Wouldn't you do this in the kubernetes namespace?  You could also apply labels and selectors to the hub

**Comment by diemol** [comment]
Hi @fmatoss,

Do you mean this? https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

**Comment by fmatoss** [comment]
Yes @diemol

**Comment by diemol** [comment]
OK, a change is needed because it is possible to specify the node selector for the Zalenium pod, but not for the on-demand created pods. Should not be that hard.

Do you think you can help us with a PR? I could give you some hint where to start. Otherwise we can only check this in several weeks.

**Comment by fmatoss** [comment]
I can do @diemol, just tell me where this should be implemented.

**Comment by diemol** [comment]
Nice! Thanks willing to help.

This could be implemented in a similar way as how the `hostAliases` feature was implemented (#246). A method to retrieve the `hostAliases` was [implemented](https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/container/kubernetes/KubernetesContainerClient.java#L157), then added to the [config](https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/container/kubernetes/KubernetesContainerClient.java#L343), and finally added to the pod [creation](https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/container/kubernetes/KubernetesContainerClient.java#L585).

I checked briefly and in theory the api has the necessary methods to retrieve and add nodeSelectors.

Let me know if you need any help. Thanks again.

**Comment by diemol** [comment]
This has just been released, check https://github.com/zalando/zalenium/releases/tag/3.6.0f

Thanks for contributing @fmatoss!
