### ISSUE TITLE
Dashboard - pass search text as parameter in the URL

### ISSUE THREAD

**Issue by rvarum** [zalando/zalenium#284]
Hi,

I would be great to add a parameter in the URL of the dashboard to pass the Search text.
I'm requesting this because I would like to put a link in Jenkins for a specific build, to the Zalenium Dashboard, with the relevant tests only for that build (I pass "build" capability with Jenkins build number so it can be filtered this way).
any other suggestions how to achieve this are welcome.

thanks guys for awesome work!

**Comment by diemol** [comment]
Hi @rvarum, thanks for the nice words!

It sounds like something helpful, but to be honest, we don't have the capacity to implement that right now (I'm not sure when).

Do you think that you can help us with a PR for this?

**Comment by diemol** [comment]
Closing, as it is consolidated in #645
If development starts, we'll reopen the issue.
