### ISSUE TITLE
Unable to run zalenium. Invalid reference format error.

### ISSUE THREAD

**Issue by Aznariy** [zalando/zalenium#285]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
**docker says latest, not sure about version**
Docker Version:  
**17.09.0-ce**
If using docker-compose, version:  
**1.16.1**
OS: 
**Windows 10 Enterprise**
Docker Command to start Zalenium:  
**docker run --rm -ti --name zalenium -p 4444:4444 \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /tmp/videos:/home/seluser/videos \
 --privileged dosel/zalenium start**

**Comment by elgalu** [comment]
Try to put everything in 1 line. You are using multilines without backslashes.

**Comment by diemol** [comment]
Hi @Aznariy,

As @elgalu says, you need to either write the command in one single line, or use an appropriate line breaker for Windows, e.g.:

 ```
docker run --rm -ti --name zalenium -p 4444:4444 ^
-v /var/run/docker.sock:/var/run/docker.sock ^
-v /tmp/videos:/home/seluser/videos ^
--privileged dosel/zalenium start
```

**Comment by Aznariy** [comment]
Hello @diemol
 
I've figured that yes, thanks. I was actually copying => pasting from Zalenium GitHub home page to my cmd.exe Didn't captured at first that no backslashes needed if one line is used.

**Comment by diemol** [comment]
No worries, it is just that we are not using Windows normally so all the commands we put are the ones that work in our environments. They usually need little tweaking in Windows.

Thanks for reporting back!
