### ISSUE TITLE
hi，cant change date and change timezone with GMT+8,where is  {project.build.finalName}.jar.please teach me how to solve it,thanks.

### ISSUE THREAD

**Issue by jamesz2011** [zalando/zalenium#302]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  

Docker Version:  

If using docker-compose, version:  

OS: 

Docker Command to start Zalenium:  

If using Kubernetes, specify your environment, and if relevant your manifests:

**Comment by jamesz2011** [comment]
the problem was solved.thanks

**Comment by FantomX1** [comment]
I still can not find jar file inside docker build
