### ISSUE TITLE
Zalenium container stops after sometime after it has been started.

### ISSUE THREAD

**Issue by kvrvaidya** [zalando/zalenium#304]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

When I try to run the container it is up & running for sometime and getting terminated after few minutes.

Zalenium Image Version(s):  
latest version- 3.7
Docker Version:  
17.04

OS: 
Ubuntu 16.04

Docker Command to start Zalenium:  

docker run --rm -ti -d --name zalenium -p 4444:4444 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/videos:/home/seluser/videos \
    --privileged dosel/zalenium start

**Comment by diemol** [comment]
HI @kvrvaidya,

Can you describe a bit more please? Is it terminated after you run some tests? Or you just start Zalenium, don't do anything else and the containers are stopped after a while?

Please attach the logs if possible.

**Comment by diemol** [comment]
Closing this one due to inactivity, please reopen if more information is available.
