### ISSUE TITLE
[feature] Loading spinner and refresh for cleanup

### ISSUE THREAD

**Issue by simplyageek** [zalando/zalenium#306]
Currently if you press "Cleanup", you have to wait a few seconds (depending on the number of tests you had) and then manually refresh the page, to see the result of the cleanup.

It would be nice to have a loading spinner of some sort, while the cleanup process is in place, and automatically refresh the page afterwards. I don't know if/how is this possible, but it'd be a nice feature.

**Comment by diemol** [comment]
Hi @simplyageek!

It sounds like something helpful, but to be honest, we don't have the capacity to implement that right now (I'm not sure when).

Do you think that you can help us with a PR for this?

**Comment by diemol** [comment]
Closing, as it is consolidated in #645
If development starts, we'll reopen the issue.
