### ISSUE TITLE
Live Preview not working in OpenShift

### ISSUE THREAD

**Issue by mojsha** [zalando/zalenium#323]
Currently, Live Preview is not working in OpenShift because OpenShift uses routes to access an application. The route is URL based and is pointing to a service, which in turn points to the Pod on a specific port. 

Zalenium Live preview is dependent on specific ports to be opened up to access Live Preview. 

One suggestion would be to move away from using ports and use sub-URLs instead. But this is just an idea. The main thing is that we would like to have the feature Live Preview working in OpenShift.

**Comment by diemol** [comment]
Hi @mojsha,

Yes, I think this was discussed in the Gitter chat, some approach based on Ngnix could be a solution.

Right now we are focusing on different improvements and bug fixes (#323, #320, #275) and we don't have so much capacity for this now. We would be really thankful if someone sends a PR for this.

**Comment by diemol** [comment]
This was released in https://github.com/zalando/zalenium/releases/tag/3.7.1g
Thanks for contributing @pearj!

**Comment by mojsha** [comment]
It seems like this fix only applies to HTTP-routes. 

For secure (HTTPS) routes, it does not seem to work. 

I have tried it in our enterprise instance where HTTP is disabled at the network level and HTTPS fails, and in MiniShift where I could see HTTP working.

**Comment by pearj** [comment]
@mojsha I tried https on OpenShift 3.6.1 running on AWS and it worked fine. So not sure what issue you’re having.
