### ISSUE TITLE
Possible to run on multiple hosts?

### ISSUE THREAD

**Issue by richotaylor** [zalando/zalenium#329]
I'm wondering if it's possible to run Zelenium across multiple hosts?  I have it running well on one server but I'm looking to scale horizontally to support running more tests in parallel.  I don't see any references to this in the docs but it feels like it might be possible.  Would that be accomplished using kubernetes or are there other options for doing this? Thanks.

**Comment by diemol** [comment]
Hi @richotaylor,

The current option for horizontal scaling is [Kubernetes](https://github.com/zalando/zalenium/blob/master/docs/k8s/kubernetes.md). We plan in the future to add support for docker Swarm, but this looks more like 2018 plans.

**Comment by richotaylor** [comment]
Great thanks.  We're working on getting going on Kubernetes as well. So hoping to have a cluster to deploy too soon.

**Comment by diemol** [comment]
Cool!
You can give it a try on Minikube to get a grasp of it, and let us know if you into any issues. Join the [Gitter channel](https://gitter.im/zalando/zalenium) in case you have more questions.
