### ISSUE TITLE
Spin up new containers on demand fails 

### ISSUE THREAD

**Issue by tedel88** [zalando/zalenium#336]
Zalenium Image Version(s):  
3.7.1e
Docker Version:  
17.05.0-ce
If using docker-compose, version:  
2.0
OS: 
Ubuntu 17.04
Docker Command to start Zalenium:  
docker-compose up (see compose file attached)
[docker-compose.txt](https://github.com/zalando/zalenium/files/1501962/docker-compose.txt)

## Expected Behavior -
With desiredContainers 1 and maxTestSessions it should be possible to run two tests successively.
E.g : docker-compose up, wait for zalenium to start, run first test, wait for test to be finished, run the second test. 
After the first test container should be shut down and in the second test a new one should be created.

PS: This worked with 3.7.1c and Start Parameters: 
--chromeContainers 0
--firefoxContainers 0

## Actual Behavior -
Initially a Container is created, after the first test it will be removed (as expected). For the second test no new container is created (not expected).  

In addition we noticed different appearance of the :4444/grid/console:
Before runnig first test:
![image](https://user-images.githubusercontent.com/33958083/33215247-5f9b94fe-d12f-11e7-9417-b5b31ba1d545.png)

While Runnig second Test:
![image](https://user-images.githubusercontent.com/33958083/33215265-6ea712f2-d12f-11e7-8ff6-977e92cf9cb7.png)

So in the Starter Node there is actually no Version Info for Chrome or Firefox which seems to be part of the problem.

When second test is startet docker log zalenium points out following message:
12:58:42.395 INFO - Got a request to create a new session: Capabilities {browserName: chrome, chromeOptions: {args: [..., version: 62.0.3202.94}
12:58:42.395 INFO - Error forwarding the new session cannot find : Capabilities {browserName: chrome, chromeOptions: {args: [..., version: 62.0.3202.94}

I will try to give an example test later on but i'm convinced a basic hello world test should do the trick as well.

**Comment by diemol** [comment]
Hi @tedel88,

Can you please show me how the capabilities for your tests look like?

**Comment by tedel88** [comment]
Hi @diemol,

Seems that its not just the capabilites..i'm working on something reproducable.

**Comment by tedel88** [comment]
Hi @diemol,

completed basic test for reprodutcion : 

https://github.com/tedel88/zal3.7.1e-Test

As you mentioned before we tracked it down to Capabilitie "version:". I#m not sure why i missed this one on friday. Problem is that we use a bunch of Zalenium Servers in a grid. In fornt of the grid there is a load balancer or more specific a grid router which distributes the request to the grid according to the browser version specified in the capabilites. We do that to support Tests for different browser Versions. 

I'm not sure how to do that with the verison Parameter no longer supported (and again it worked with 3.7.1c), espacially because it works when zalenium is started for the first time (check out the basic test). 
Looks like a bug.

**Comment by diemol** [comment]
Thanks! I will check it soon and hopefully we'll fix it and release as well.
It definitively looks like a bug.

**Comment by diemol** [comment]
HI @tedel88,

We just released a new version with this fix https://github.com/zalando/zalenium/releases/tag/3.7.1f
Thanks for reporting this bug!

Please give it a try and let us know how it went. (I used your test case to try it).

If you find any problems, feel free to reopen this issue.

**Comment by tedel88** [comment]
Hi @diemol ,

tried it out works fine with our normal tests :)

Thanks for the quick fix 👍. You guys do a realy good job there at Zalando!
