### ISSUE TITLE
seleniumImageName does not work anymore since 3.7.1a

### ISSUE THREAD

**Issue by timm-gs** [zalando/zalenium#349]
I wanted to update to a newer Zalenium version to make use of the `--desiredContainers` flag. It seems like I hit an issue similar to #296, though for me it was working before and it not anymore.

**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
3.7.1d, 3.8.1a

Docker Version:  
17.09.0-ce
If using docker-compose, version:  
none

OS: 
OS X Sierra 10.12.6

Docker Command to start Zalenium:  

```sh
Timms-MacBook-Pro:~ l1-gs-timm$ docker pull elgalu/selenium:3.8.1-p0
3.8.1-p0: Pulling from elgalu/selenium
Digest: sha256:0b635d1d1bbe715dab2d272623791f9c93882ca33672f7720d3ffe6847e503b8
Status: Image is up to date for elgalu/selenium:3.8.1-p0
Timms-MacBook-Pro:~ l1-gs-timm$ docker run --rm -ti --name zalenium -p 4444:4444     -v /var/run/docker.sock:/var/run/docker.sock     dosel/zalenium:3.8.1a start --seleniumImageName elgalu/selenium:3.8.1-p0 --desiredContainers 0
Docker version 17.06.2-ce, build cec0b72
-- LOG 11:03:55:616833927 Ensuring docker works...
-- LOG 11:03:55:647744642 Ensuring no stale Zalenium related containers are still around...
-- LOG 11:03:55:663295815 Ensuring docker-selenium is available...
Seems that docker-selenium's image has not been pulled yet
Please run 'docker pull elgalu/selenium', or use your own compatible image via --seleniumImageName
```

or

```sh
Timms-MacBook-Pro:~ l1-gs-timm$ docker pull registry.hub.docker.com/elgalu/selenium:3.8.1-p0
3.8.1-p0: Pulling from elgalu/selenium
Digest: sha256:0b635d1d1bbe715dab2d272623791f9c93882ca33672f7720d3ffe6847e503b8
Status: Downloaded newer image for registry.hub.docker.com/elgalu/selenium:3.8.1-p0
Timms-MacBook-Pro:~ l1-gs-timm$ docker run --rm -ti --name zalenium -p 4444:4444     -v /var/run/docker.sock:/var/run/docker.sock     dosel/zalenium:3.8.1a start --seleniumImageName registry.hub.docker.com/elgalu/selenium:3.8.1-p0 --desiredContainers 0
Docker version 17.06.2-ce, build cec0b72
-- LOG 11:06:40:017834208 Ensuring docker works...
-- LOG 11:06:40:051888792 Ensuring no stale Zalenium related containers are still around...
-- LOG 11:06:40:066287384 Ensuring docker-selenium is available...
Seems that docker-selenium's image has not been pulled yet
Please run 'docker pull elgalu/selenium', or use your own compatible image via --seleniumImageName
```

## Expected Behavior -

I would expect Zalenium grid to start up (as before with 3.7.1a) and use the image I specified.

## Actual Behavior -

Zalenium refuses to start, citing that it can't find the specific image.

**Comment by timm-gs** [comment]
Going back to using 3.7.1a the following works fine:

```sh
docker run --rm -ti --name zalenium -p 4444:4444 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    dosel/zalenium:3.7.1a start --seleniumImageName elgalu/selenium:3.7.1 --chromeContainers 0 --firefoxContainers 0
```

**Comment by diemol** [comment]
Hi @timm-gs,

Good catch! Yes, when you put a tag in  `--seleniumImageName` it does not work as expected. We changed things after 3.7.1a to make it work for docker versions, it was only working before for k8s.

I'll double check it and fix it soon.

Thanks for reporting!

**Comment by timm-gs** [comment]
Thanks for looking into this :)

>  it was only working before for k8s.

You mean from 3.7.1b and onwards it only works on k8s? Because I am using plain Docker for Mac if that has any bearing.

**Comment by diemol** [comment]
Maybe I didn't say the whole phrase I had in my head. Before it had `elgalu/selenium` hardcoded, which was ok for people using only k8s, but if someone wanted to have a different image in docker it was not working.

**Comment by diemol** [comment]
OK, fixed it, PR is open and if all the CI stuff goes well, we'll release later.

**Comment by diemol** [comment]
Just merged to master, release will come soon. @timm-gs

**Comment by diemol** [comment]
Hi @timm-gs, just released https://github.com/zalando/zalenium/releases/tag/3.8.1b
Please give it a try and let us know how it went. 
If you want to support us, just please star ⭐️ the project :)

**Comment by timm-gs** [comment]
Just updated and got our test suite passing on the latest version with the fixed image name :)

🌟 given; least I could do
