### ISSUE TITLE
Console Autorefresh issue when using Firefox

### ISSUE THREAD

**Issue by mitchellmaler** [zalando/zalenium#356]
When running Zalenium and navigating to the console using Firefox the page continuously refreshes even with the refresh param not set. When using Chrome the page does not auto refresh unless specified manually.

**Comment by diemol** [comment]
Hi @mitchellmaler,

Good catch, I'll go over a few open issues today, and this one will be one of them.

Thanks for reporting it.

**Comment by diemol** [comment]
Just merged this to master and will be released soon.

**Comment by diemol** [comment]
This was released in https://github.com/zalando/zalenium/pull/360

**Comment by mitchellmaler** [comment]
Hey @diemol this did fix the console but it also happens on the live preview window as well. My fault for not mentioning this.

https://github.com/zalando/zalenium/blob/212bd699f9d35e2c12ffb5696d9604625b5fb150/src/main/java/de/zalando/ep/zalenium/servlet/LivePreviewServlet.java#L70

**Comment by diemol** [comment]
Oh, no worries, I can fix it and release again. I should have noticed that as well, sorry!

**Comment by mitchellmaler** [comment]
Awesome thanks!

**Comment by diemol** [comment]
Sorry for the delay, this is being released now as well https://github.com/zalando/zalenium/releases/tag/3.8.1d

I'll check the other issues you opened soon, thanks!

**Comment by diemol** [comment]
No, it did not fix it, I screwed it up and didn't check it. Will fix it and release again soon.

**Comment by mitchellmaler** [comment]
Let me know if you want me to test it out for you. Thanks for checking into this.

**Comment by diemol** [comment]
Thanks @mitchellmaler I'll let you know soon
