### ISSUE TITLE
maxTestSessions is ignored

### ISSUE THREAD

**Issue by mehrdad-abdoli** [zalando/zalenium#357]
Zalenium Image Version(s):
3.8.1
Docker Version:
17.09.0-ce, build afdb6d4
If using docker-compose, version:
1.17.1, build 6d101fb
OS:
ubuntu 16
Docker Command to start Zalenium:
docker-compose up --force-recreate

Expected Behavior -
3 tests will run in each node/container  because we set --maxTestSessions 3
no error when running docker-compose

Actual Behavior -
only 1 test is run on every node and --maxTestSessions 3 is ignored by zalenium
error:
haveged: error while loading shared libraries: libhavege.so.1: cannot stat shared object: Permission denied

here is docker-compose.yaml:

version: '2.2'

services:
  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    tty: true
    privileged: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 8899:4444
    command: >
       start --desiredContainers 2
            --maxTestSessions 3
            --maxDockerSeleniumContainers 7
            --screenWidth 1600
            --screenHeight 900
            --timeZone "Asia/Tehran"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
            --keepOnlyFailedTests true

    environment:
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
      - GRID_BROWSER_TIMEOUT=60
      - GRID_TIMEOUT=60
      - SE_OPTS=-browserTimeout 60
      - timeout 60

**Comment by diemol** [comment]
Hi @mehrdad-abdoli,

Can you show me the logs please?

**Comment by mehrdad-abdoli** [comment]
@diemol  
<script src="https://gist.github.com/mehrdad-abdoli/0314ef6f3ed1f318757577a48298f2c7.js"></script>

**Comment by diemol** [comment]
I am not sure if the docker compose file posted above is really the one being used to start Zalenium, because I see in the log [here](url) that 16 nodes are being started, but the parameter `--desiredContainers` says 2.

Additionally, the `--screenWidth 1600` and `--screenHeight 900` are set, but the test are sent with `screenResolution: 1280x720`, so this is not actually using the containers created in advance.

Can you please double check which docker compose file is being used?

**Comment by mehrdad-abdoli** [comment]
here is the compose file although there is no diffrence with any change : 
version: '2.2'

services:
  #--------------#
  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    tty: true
    privileged: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 8899:4444
    command: >
      start --desiredContainers 0
            --maxDockerSeleniumContainers 20
            --screenWidth 1600
            --screenHeight 900
            --timeZone "Asia/Tehran"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
            --keepOnlyFailedTests true


    environment:
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
      - GRID_BROWSER_TIMEOUT=60
      - GRID_TIMEOUT=60
      - SE_OPTS=-browserTimeout 60
      - timeout 60

**Comment by mehrdad-abdoli** [comment]
some parameteres are set again in selenium compabilities .but that is not my problem.Zalenium handle node registeration badly sometimes

**Comment by diemol** [comment]
Sorry, I am confused. 
The issue is about `--maxTestSessions` being ignored, right?

First, I see that the logs you showed me in this [comment](https://github.com/zalando/zalenium/issues/357#issuecomment-350458813) do not really correspond to the docker-compose file posted in the first comment.

And the docker-compose file shown in this [comment](https://github.com/zalando/zalenium/issues/357#issuecomment-350526835) is not setting `--maxTestSessions`, so that is where my confusion comes from :)
I think somehow Zalenium was running without setting `--maxTestSessions` and perhaps you were expecting it to be set?

About the environment variables, let me add some comments:
> environment:
>  - HOST_UID
>  - HOST_GID
>  - SAUCE_USERNAME **-> If you are not using Sauce Labs, this is not needed**
>  - SAUCE_ACCESS_KEY **-> If you are not using Sauce Labs, this is not needed**
>  - BROWSER_STACK_USER **-> If you are not using BrowserStack, this is not needed**
>  - BROWSER_STACK_KEY **-> If you are not using BrowserStack, this is not needed**
>  - TESTINGBOT_KEY **-> If you are not using TestingBot, this is not needed**
>  - TESTINGBOT_SECRET **-> If you are not using TestingBot, this is not needed**
>  - GRID_BROWSER_TIMEOUT=60 **-> This env var does not exist in Zalenium, it will be ignored**
>  - GRID_TIMEOUT=60 **-> This env var does not exist in Zalenium, it will be ignored**
>  - SE_OPTS=-browserTimeout 60 **-> This env var does not exist in Zalenium, it will be ignored**
>  - timeout 60 **-> This env var does not exist in Zalenium, it will be ignored**

And, lastly, I didn't understand completely the previous comment:
What do you mean by this?
>some parameteres are set again in selenium compabilities

Do you mean when many nodes want to register at the same time?
>Zalenium handle node registeration badly sometimes

**Comment by mehrdad-abdoli** [comment]
some parameteres are set again in selenium compabilities as https://github.com/zalando/zalenium/blob/05ed9e001b82fc09a0a32ce9c904eb9b9b51345d/docs/usage_examples.md#screen-resolution

It hold some test request although the nodes are free to response

--maxTestSessions  any number is not working :  

version: '2.2'
services:
  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    tty: true
    privileged: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 8899:4444
    command: >
      start --desiredContainers 0
            --maxTestSessions  3
            --maxDockerSeleniumContainers 10
            --screenWidth 1600
            --screenHeight 900
            --timeZone "Asia/Tehran"
            --videoRecordingEnabled false
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
            --keepOnlyFailedTests true
    environment:
      - HOST_UID
      - HOST_GID

**Comment by diemol** [comment]
@mehrdad-abdoli ok, I understood what you meant by that.

I am sorry, I tried to reproduce it during the weekend and also with the latest release but I was not able to see the failure you mention.

I apologise if I ask for this again, but so far I was not able to see the docker-compose file that matches the log you provided. Could you please post that? A docker compose file and the log from it where I can see that `--maxTestSessions` is not being used?

**Comment by mcafeerun** [comment]
@diemol, You mention this in above comment. 
GRID_BROWSER_TIMEOUT=60 -> This env var does not exist in Zalenium, it will be ignored
SE_OPTS=-browserTimeout 60 -> This env var does not exist in Zalenium, it will be ignored

My question is, how do we set the browser timeout. Right now it is browserTimeout : 0 (means it will never terminate the sessions which are inactive). This ended by clocking the nodes the container keeps growing & finally reaching the threshold. Any help is much appreciated.

**Comment by diemol** [comment]
@mcafeerun that is not the purpose of `browserTimeout`.
`browserTimeout` is the timeout that gets triggered when a request takes to long. E.g.: if a `driver.get()` takes longer than `browserTimeout`, then it will stop the session.

`timeout` is the one you are talking about, which stops inactive sessions. Zalenium does not use the standard one because you can have a custom one per test. See `Idle Timeout` 
 in https://opensource.zalando.com/zalenium/

**Comment by nagendra-devireddy** [comment]
I have tried setting the max sessions per container to 4 with below **command** (in windows 10)
docker run --rm -ti --name zalenium -p 4444:4444 ^
      -v /var/run/docker.sock:/var/run/docker.sock ^
      -v /c/Users/test_user/temp/videos:/home/seluser/videos ^
      --privileged dosel/zalenium start --maxTestSessions 4

**here are the logs**
---------------------------------------------------
> docker run --rm -ti --name zalenium -p 4444:4444 ^
More?       -v /var/run/docker.sock:/var/run/docker.sock ^
More?       -v /c/Users/test_user/temp/videos:/home/seluser/videos ^
More?       --privileged dosel/zalenium start --maxTestSessions 4
Docker version 18.09.0, build 4d60db4
-- LOG 17:37:52:108161400 Ensuring docker works...
-- LOG 17:37:52:261904000 Ensuring docker-selenium is available...
haveged: haveged starting up
Copying files for Dashboard...
Starting Nginx reverse proxy...
Starting Selenium Hub...
.....17:37:55.839 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium server version: 3.141.59, revision: unknown
.17:37:56.039 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
....17:37:56.992 [main] INFO  d.z.e.z.c.DockerContainerClient - About to clean up any left over DockerSelenium containers created by Zalenium
........17:37:58.830 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Starting poller.
...17:37:59.817 [main] INFO  d.z.ep.zalenium.aspect.HubAspect - Registering custom Zalenium servlets
.17:38:00.117 [main] INFO  org.openqa.grid.web.Hub - Selenium Grid hub is up and running
17:38:00.120 [main] INFO  org.openqa.grid.web.Hub - Nodes should register to http://172.17.0.2:4445/grid/register/
17:38:00.120 [main] INFO  org.openqa.grid.web.Hub - Clients should connect to http://172.17.0.2:4445/wd/hub
Selenium Hub started!
Sauce Labs not enabled...
Browser Stack not enabled...
TestingBot not enabled...
Zalenium is now ready!
*************************************** Data Processing Agreement ***************************************
By using this software you agree that the following non-PII (non personally identifiable information)
data will be collected, processed and used by Zalando SE for the purpose of improving our test
infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
of the IP address are collected.


**Grid Console**
http://localhost:4444/grid/console?config=true&configDebug=true
In the grid console always showing it as 1 for maxSession
![image](https://user-images.githubusercontent.com/5219581/52802809-ac9a2b80-30a6-11e9-9769-bf60ae637c11.png)

I have tried with below command as well in Rancher 1.x
command: >
          start --maxTestSessions 5                
                --timeZone "Asia/Calcutta"

Even we have passed  ZALENIUM_MAX_TEST_SESSIONS as environment variable while starting the zalenium server.

After doing all(ignoring console maxSessions :1 message),we went ahead and run the script still captured only 1 test case per video.

**Comment by sumeet7298** [comment]
> I have tried setting the max sessions per container to 4 with below **command** (in windows 10)
> docker run --rm -ti --name zalenium -p 4444:4444 ^
> -v /var/run/docker.sock:/var/run/docker.sock ^
> -v /c/Users/test_user/temp/videos:/home/seluser/videos ^
> --privileged dosel/zalenium start --maxTestSessions 4
> 
> ## **here are the logs**
> > docker run --rm -ti --name zalenium -p 4444:4444 ^
> > More?       -v /var/run/docker.sock:/var/run/docker.sock ^
> > More?       -v /c/Users/test_user/temp/videos:/home/seluser/videos ^
> > More?       --privileged dosel/zalenium start --maxTestSessions 4
> > Docker version 18.09.0, build 4d60db4
> > -- LOG 17:37:52:108161400 Ensuring docker works...
> > -- LOG 17:37:52:261904000 Ensuring docker-selenium is available...
> > haveged: haveged starting up
> > Copying files for Dashboard...
> > Starting Nginx reverse proxy...
> > Starting Selenium Hub...
> > .....17:37:55.839 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium server version: 3.141.59, revision: unknown
> > .17:37:56.039 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
> > ....17:37:56.992 [main] INFO  d.z.e.z.c.DockerContainerClient - About to clean up any left over DockerSelenium containers created by Zalenium
> > ........17:37:58.830 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Starting poller.
> > ...17:37:59.817 [main] INFO  d.z.ep.zalenium.aspect.HubAspect - Registering custom Zalenium servlets
> > .17:38:00.117 [main] INFO  org.openqa.grid.web.Hub - Selenium Grid hub is up and running
> > 17:38:00.120 [main] INFO  org.openqa.grid.web.Hub - Nodes should register to http://172.17.0.2:4445/grid/register/
> > 17:38:00.120 [main] INFO  org.openqa.grid.web.Hub - Clients should connect to http://172.17.0.2:4445/wd/hub
> > Selenium Hub started!
> > Sauce Labs not enabled...
> > Browser Stack not enabled...
> > TestingBot not enabled...
> > Zalenium is now ready!
> > *************************************** Data Processing Agreement ***************************************
> > By using this software you agree that the following non-PII (non personally identifiable information)
> > data will be collected, processed and used by Zalando SE for the purpose of improving our test
> > infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
> > of the IP address are collected.
> 
> **Grid Console**
> http://localhost:4444/grid/console?config=true&configDebug=true
> In the grid console always showing it as 1 for maxSession
> ![image](https://user-images.githubusercontent.com/5219581/52802809-ac9a2b80-30a6-11e9-9769-bf60ae637c11.png)
> 
> I have tried with below command as well in Rancher 1.x
> command: >
> start --maxTestSessions 5
> --timeZone "Asia/Calcutta"
> 
> Even we have passed ZALENIUM_MAX_TEST_SESSIONS as environment variable while starting the zalenium server.
> 
> After doing all(ignoring console maxSessions :1 message),we went ahead and run the script still captured only 1 test case per video.

Any Update on this... Mee too getting the same issue... The maxSession always show as 1.

**Comment by diemol** [comment]
Those parameters are not related. `maxTestSessions` are the number of tests per container before it shuts down, each container will only execute one test concurrently.

I am going to lock this issue and if there are more questions, please head to the Slack channel shown in the docs.
