### ISSUE TITLE
Zalenium Browser Container Time Out issue

### ISSUE THREAD

**Issue by adishreepaliwal** [zalando/zalenium#364]
Zalenium Image Version(s):  
Image: Tag : Image Id
dosel/zalenium : latest : c023c440df4a
elgalu/selenium : latest : 55c7735ba192

Docker Version:  17.09.0-ce, build afdb6d4

OS: CentOS 7

Docker Command to start Zalenium:  
docker run --rm -i --name zalenium -p 4444:4444 \
  -v $(which docker):/usr/bin/docker \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/videos:/home/seluser/videos \
  -v /dev/shm:/dev/shm \
  --privileged dosel/zalenium start --chromeContainers 6 --firefoxContainers 6 --maxTestSessions 2500 --maxDockerSeleniumContainers 20

## Expected Behavior -
The browser container should not time out as soon as I create one
In the midst of the execution of test cases , the browser time out issue should not happen

## Actual Behavior -

I am running 12 test cases simultaneously over 12 browser containers(6 for firefox and 6 for chrome) using testng and java/selenium based code.
I am facing the following issues 
1) When the containers are up after running the docker run command , sometimes I face the issue that the container is Disconnected with 502 Bad Gateway error in the /grid/admin/live view

2) Also , I am facing a lot of time out issues of the container due to which the execution of test cases stop. I saw this is in the dashboard view , that there is time out
![timeout](https://user-images.githubusercontent.com/33953608/34038623-fc2c23c2-e1b2-11e7-81c8-73a70dff542d.PNG)

**Comment by diemol** [comment]
Hi @adishreepaliwal,

Could you please tell me how much available memory and CPU does the docker daemon have? When running 12 threads/tests concurrently a small machine is not enough and those issues could happen.

There is a short guideline about performance [here](https://github.com/zalando/zalenium/blob/master/docs/performance.md), give it a look and perhaps adjust on your end to see better results. Let us know how it went.

**Comment by diemol** [comment]
I'll close this issue because we didn't get more information. If you have more info and the issue still happens, please feel free to reopen.

**Comment by adishreepaliwal** [comment]
I apologize for the late reply.Adding memory space worked for me. I also disabled recording of videos so that they do not occupy memory. Thank you @diemol  so much for your help.

**Comment by diemol** [comment]
Thanks for reporting back @adishreepaliwal, glad it worked out!
