### ISSUE TITLE
Unable to execute testng based test cases from jenkins

### ISSUE THREAD

**Issue by adishreepaliwal** [zalando/zalenium#397]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
elgalu/selenium     latest              457f3efdb843        10 days ago         1.38GB
dosel/zalenium      latest              4a78c25423c7        2 weeks ago         757MB

Docker Version:  
17.12.0-ce

OS: 
CentOS 7

Docker Command to start Zalenium:  
docker run --rm -i --name zalenium -p 4444:4444 \
  -v $(which docker):/usr/bin/docker \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/videos:/home/seluser/videos \
  -v /dev/shm:/dev/shm \
  --privileged dosel/zalenium start --chromeContainers 6 --firefoxContainers 6 --maxTestSessions 250 --maxDockerSeleniumContainers 250 --videoRecordingEnabled false

Initialization of wed driver -
String firefoxExePath="some path";
System.setProperty("webdriver.gecko.driver", firefoxExePath);
DesiredCapabilities dcap = DesiredCapabilities.firefox();
driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"),dcap);

## Expected Behavior -
The testng based test case should execute both from jenkins job and from the machine

## Actual Behavior -
When I execute my java/testng based test cases through jenkins , only the docker container is created but the test cases donot execute.
While , if I run the same test case from the actual machine , the test cases are executed.

**Comment by diemol** [comment]
Hi @adishreepaliwal,

You do not need to specify 
```
String firefoxExePath="some path";
System.setProperty("webdriver.gecko.driver", firefoxExePath);
```

Since this values are already configured in the docker images, when you set them, you are overwriting the values specified in the images and this is causing that the browser does not start properly.

Please run your tests without those options, let us know how it went.

**Comment by adishreepaliwal** [comment]
Hi @diemol 

How should we initialize the web drivers both for chrome and firefox ?

Thanks,
Adishree

**Comment by diemol** [comment]
You can do it in the normal way, just like when you use a regular grid, for example:

Firefox
```
URL gridUrl = new URL("http://localhost:4444/wd/hub");
DesiredCapabilities desiredCapabilities = new DesiredCapabilities(new FirefoxOptions());
WebDriver webDriver = new RemoteWebDriver(gridUrl, desiredCapabilities);
// your test 
webDriver.quit();
```

and for Chrome is the same
```
URL gridUrl = new URL("http://localhost:4444/wd/hub");
DesiredCapabilities desiredCapabilities = new DesiredCapabilities(new ChromeOptions());
WebDriver webDriver = new RemoteWebDriver(gridUrl, desiredCapabilities);
// your test 
webDriver.quit();
```

**Comment by adishreepaliwal** [comment]
Hi @diemol 
This still didnot solved the purpose. The test cases are still not executing through jenkins.
Thanks,
Adishree

**Comment by diemol** [comment]
OK, maybe we can go one step back.
How is your infrastructure placed? Where are you running your tests now?
Can you please show us the commands to start Zalenium.

If you run Zalenium locally in your laptop, and point your tests there, does ir work?

**Comment by adishreepaliwal** [comment]
I am running the test cases via jenkins on a CentOS based machine which has docker installed and is acting as a slave.
 Zalenium command -
docker run --rm -i --name zalenium -p 4444:4444 \
  -v $(which docker):/usr/bin/docker \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/videos:/home/seluser/videos \
  -v /dev/shm:/dev/shm \
  --privileged dosel/zalenium start --chromeContainers 6 --firefoxContainers 6 --maxTestSessions 2500 --maxDockerSeleniumContainers 2500 --videoRecordingEnabled false

Java command to execute testcases -
java -cp ".:dist:<some java jars>:" org.testng.TestNG testng.xml

Webdriver initialization -
if (browser.equalsIgnoreCase("firefox")) {
	DesiredCapabilities dcap = DesiredCapabilities.firefox();
	driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"),dcap);
} else if (browser.equalsIgnoreCase("chrome")) {
	DesiredCapabilities dcap = DesiredCapabilities.chrome();
	driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"),dcap);
}

If i execute the test cases directly from the machine , they work as expected.

**Comment by diemol** [comment]
Hi @adishreepaliwal,

OK, so Zalenium is in a slave machine, different from the one where you are running your tests, right?

If that is like that, of course `localhost` won't work. You need to put in the RemoteWebDriver the  name or IP of that slave machine. I don't remember how it is done, but I am pretty sure this should be possible in Jenkins.

**Comment by adishreepaliwal** [comment]
Hi @diemol 
It has started working for me now. The issue was jenkins assumed that the job is completed even though my test case just began executing there.
Is there any API/method to determine if the container over the machine is idle or is there any test case running ?

Thanks,
Adishree

**Comment by diemol** [comment]
Hi @adishreepaliwal,

Well, that's good, I am happy it works for you now!

What do you mean by that? Determine if the container is idle?
Do you want to join us in the chat? Maybe it'll go faster there.
https://gitter.im/zalando/zalenium

PS: Don't forget to star the repo to support us! :)

**Comment by diemol** [comment]
@adishreepaliwal, I'll close the issue here and we can continue the conversation in the Gitter chat, alright?
