### ISSUE TITLE
Unable to run zalenium

### ISSUE THREAD

**Issue by darkklin** [zalando/zalenium#410]
Hi 
So I run the first comment 
`docker pull elgalu/selenium`
and then the second one 
` docker pull dosel/zalenium`

and after it tried  to run the third comment 

But I get an error

![screenshot_25](https://user-images.githubusercontent.com/25209561/35188241-bdad6472-fe3a-11e7-9799-38b9f018c4de.png)

what can i do ?

**Comment by diemol** [comment]
Hi @darkklin,

The backslashes (\) don't really work in Windows, I just noticed that we have the wrong command in the docs. I'll update it.

Please try this one, with `^`, and let us know how it went.

```
    docker run --rm -ti --name zalenium -p 4444:4444 ^
      -v /var/run/docker.sock:/var/run/docker.sock ^
      -v /c/Users/your_user_name/temp/videos:/home/seluser/videos ^
      --privileged dosel/zalenium start
```

**Comment by darkklin** [comment]
Nope, the same result 
screen shot 
![screenshot_26](https://user-images.githubusercontent.com/25209561/35197747-f459f8e8-feec-11e7-8fc5-2b371b43530c.png)

**Comment by darkklin** [comment]
doesn't work :( 
screen shot 
![screenshot_27](https://user-images.githubusercontent.com/25209561/35197766-3b35279c-feed-11e7-800d-1e2c58c53dfe.png)

**Comment by diemol** [comment]
Seems that in PowerShell you need to use backticks (`) instead of (^)

Can you please try with backticks?

```
    docker run --rm -ti --name zalenium -p 4444:4444 `
      -v /var/run/docker.sock:/var/run/docker.sock `
      -v /c/Users/your_user_name/temp/videos:/home/seluser/videos `
      --privileged dosel/zalenium start
```

or having the command in a single line

```
    docker run --rm -ti --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock       -v /c/Users/your_user_name/temp/videos:/home/seluser/videos --privileged dosel/zalenium start
```

**Comment by darkklin** [comment]
Thanks, Now the comment  want to work 
but i got another error 
`C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: error while creating moun
ath '/host_mnt/c/Users/your_user_name/temp/videos': mkdir /host_mnt/c/Users/your_user_name: permission denied.`
![screenshot_29](https://user-images.githubusercontent.com/25209561/35198122-9cdabff2-fef2-11e7-984f-2bf6456ac1d8.png)

seems like it's something wrong with my docker 
Do you have an idea?

**Comment by diemol** [comment]
I think this path `/host_mnt/c/Users/your_user_name/temp/videos` needs to exist in your machine, and also the docker daemon needs to have access to it.

**Comment by diemol** [comment]
@darkklin I'll close this issue since there was no more activity, but if you are still having more issues, please comment here and we could reopen the issue or you could join out Gitter channel to continue the conversation.

https://gitter.im/zalando/zalenium

**Comment by seeramzan** [comment]
Dear @diemol  I am also getting same error, on Window dockers. could you please help me to solve it.


```
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Mount denied:
The source path "C:/Users/muahmad/temp/videos"
doesn't exist and is not known to Docker.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```

**Comment by seeramzan** [comment]
It works with below command

` docker run --rm -ti --name zalenium -p 4444:4444    -v /var/run/docker.sock:/var/run/docker.sock    -v /tmp/videos:/home/seluser/videos  --privileged dosel/zalenium start`

**Comment by launganik** [comment]
backticks (`) worked for me. Thanks a lot!

**Comment by test-q** [comment]
I also face same issue - docker: Error response from daemon: mkdir c:\Users\your_user_name: Access is denied
