### ISSUE TITLE
Cannot run tests on firefox

### ISSUE THREAD

**Issue by zhex900** [zalando/zalenium#415]
docker run --rm -ti --name zalenium -p 4444:4444 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/videos:/home/seluser/videos \
    --privileged dosel/zalenium start

This is what did to start zalenium
I am using codeception to run the tests. Chrome runs fine. I can see the recorded video. But when I change the browser to firefox, this error is given.
In WebDriverException.php line 114:

    Session [(null externalkey)] not available and is not among the last 1000 terminated sessions.
    Active sessions are[ext. key 3cf741d4-04a1-41c5-b9ec-d81b19b7b05e]

**Comment by diemol** [comment]
Hi @zhex900,

I think there is an issue with the Codeception bindings when using Firefox (also with the Facebook ones and Serenity), I got the same error with those ones. 

To confirm, I just tried with the Java and JavaScript bindings, and it worked. Would it be possible for you to create an issue in the Codeception repo?

**Comment by diemol** [comment]
@zhex900, yeah, this also happen in other images, check 
https://github.com/SeleniumHQ/docker-selenium/issues/651

**Comment by zhex900** [comment]
@diemol, thank you for your reply. How do I change the binding to Java and JavaScript? Do I need to rebuild the docker image?

**Comment by diemol** [comment]
Oh no, the bindings are the "language packages" you use to interact with Selenium WebDriver. In your case you are using the bindings provided by Codeception (PHP), so maybe asking in their repo about the issue can be more helpful.

**Comment by zhex900** [comment]
I have reported it to Codeception. Let's see what they say. 

https://github.com/Codeception/Codeception/issues/4780

**Comment by diemol** [comment]
Thanks! I just subscribed to the issue so I can track it as well.

**Comment by zhex900** [comment]
@diemol look at the [reply](https://github.com/facebook/php-webdriver/issues/523) from facebook/php-webdriver. I will try it out.

**Comment by diemol** [comment]
@zhex900 check this issue to see how to do it :)
https://github.com/zalando/zalenium/issues/394

**Comment by zhex900** [comment]
````
docker run --rm -ti --name zalenium -p 4444:4444 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/videos:/home/seluser/videos -e SELENIUM_HUB_PARAMS="-enablePassThrough false" \
    --privileged dosel/zalenium start
````

`enablePassThrough` is only set false in the hub. Does it need to be set false in the nodes too?

I still have same error `Session [(null externalkey)] not available and is not among the last 1000 terminated sessions.
Active sessions are[ext. key 3cf741d4-04a1-41c5-b9ec-d81b19b7b05e]`

**Comment by diemol** [comment]
Yes, I think it is needed for the nodes as well.

**Comment by zhex900** [comment]
`docker run --rm -ti --name zalenium -p 4444:4444 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/videos:/home/seluser/videos \
-e SELENIUM_NODE_PARAMS="-enablePassThrough false" \
-e SELENIUM_HUB_PARAMS="-enablePassThrough false" \
    --privileged dosel/zalenium start`

`enablePassThrough` in nodes are still true.

**Comment by diemol** [comment]
Yes, that seems to be a bug in the grid itself, even if you pass false the nodes show as true. But inside it the behaviour should be correct.

**Comment by zhex900** [comment]
Worked ! Thank you!

**Comment by diemol** [comment]
Great! Don't forget to star the project to support us :) ⭐️

**Comment by snehakokre** [comment]
Hi @zhex900  @diemol ,
I'm getting the same error while running my test on firefox browser on remote hub.I'm not using docker rather connecting it directly. Issue is with "Firefox" browser ,for chrome its working fine. below is my acceptancesuite.yml-
extensions:
        enabled:
        - Codeception\Extension\RunProcess:
            1: java -jar C:\selenium-server-standalone-3.8.1.jar -enablePassThrough false
            sleep: 15 # wait 5 seconds for processes to boot
    modules:
        enabled:
            - WebDriver:           
                url: 
                window_size: maximize
                host: 
                port: 4444
                browser: firefox
                capabilities:
                    chromeOptions: # additional chrome options
                    binary: "C:/geckodriver"
                    acceptInsecureCerts: true

Any help would be appreciated .

**Comment by snehakokre** [comment]
Hi @zhex900  @diemol ,

I'm getting the same error while running test for remote hub on "firefox" browser .The chrome browser however is working fine.I'm not using docker for remote connection .Below is my acceptancesuite.yml-
extensions:
        enabled:
        - Codeception\Extension\RunProcess:
            1: java -jar C:\selenium-server-standalone-3.8.1.jar -enablePassThrough false
            sleep: 15 # wait 5 seconds for processes to boot
    modules:
        enabled:
            - WebDriver:           
                url: 
                window_size: maximize
                host: 
                port: 4444
                browser: firefox
                capabilities:
                    chromeOptions: # additional chrome options
                    binary: "C:/geckodriver"
                    acceptInsecureCerts: true

error im gettng - 
 [Facebook\WebDriver\Exception\UnknownServerException] Session [(null externalkey)] not available and is not among the last 1000 terminated sessions.

Any quick help will be appreciated.Thanks..
