### ISSUE TITLE
Unable to get firefox working

### ISSUE THREAD

**Issue by garytaylor** [zalando/zalenium#416]
This is a generic question that may well lead me on to providing you with more information from test sessions etc.. so sorry it is a bit light at the moment !!

I have been using zalenium for a few months now mainly testing with chrome and I love it.  The videos are very useful.

But, I went to switch to firefox and I am really struggling to get it working.  I am using capybara with ruby and have tried that many different things with differing results (some producing exceptions from zalenium itself) - I thought i would ask the question - has anyone got it working with firefox and if so, can some form of 'standard config' be provided so I can try it ?  If not, I can run some tests and provide the errors etc.. and hopefully work through the issues

Thanks

Gary

**Comment by diemol** [comment]
Hi @garytaylor,

Thanks for the kind words!

Well, about Firefox, it has had several changes in the last months, and personally I have seen that switching the tests from Chrome to Firefox doesn't work right away. 

In general, what I've had to do is to adjust a lot the explicit waits so the locators actually find the elements correctly. Maybe there are more things to adjust in your case?

What type of exceptions are you getting?

**Comment by diemol** [comment]
I'll close this issue since there is no more activity related to it. Please feel free to reopen in case more info is provided.
