### ISSUE TITLE
Can't run with latest version of docker 

### ISSUE THREAD

**Issue by gtaylor50** [zalando/zalenium#418]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  latest
Docker Version:  17.10.0-ce,
If using docker-compose, version:  1.18.0
OS:  OSX Sierra
Docker Command to start Zalenium:  

Hey Guys, 

When running my docker compose file I get this error: 

ERROR: for zalenium  Cannot start service zalenium: Mounts denied: 
The path /usr/bin/docker
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.

I tried to do what it said but it wouldn't let me. 

When I roll back my docker version then it works fine again

**Comment by diemol** [comment]
Hi @gtaylor50,

That's weird, which version are you exactly running? I am using the following one on macOS High Sierra

![image](https://user-images.githubusercontent.com/5992658/35447951-3f571bc6-02b9-11e8-900d-2c49c5a73fd5.png)

which is the most recent one, and I haven't had any issues. How does your `docker run...` command look like?

**Comment by gtaylor50** [comment]
i use a docker compose file to build it

**Comment by diemol** [comment]
I see, could you please post the compose file? Thanks.

**Comment by gtaylor50** [comment]
# Usage:
#   docker-compose up --force-recreate
version: '2.1'

services:
  #--------------#
  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 4444:4444
    command: >
      start --desiredContainers 4
            --maxDockerSeleniumContainers 6
            --screenWidth 800 --screenHeight 600
            --timeZone "Europe/Dublin"
            --videoRecordingEnabled false
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
    extra_hosts:
            - "local.work.com:192.168.65.1"
    environment:
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET

**Comment by diemol** [comment]
Ah ok, please remove `/usr/bin/docker:/usr/bin/docker` from the docker-compose file.
This one only works on Linux environments, where the docker binary is mapped.

Let me know if it helped.

**Comment by diemol** [comment]
I'll close this issue since there hasn't been more activity. Feel free to reopen if there is more information available.

**Comment by harshachandnani06** [comment]
Hey @diemol..
Thanks.. It helped
