### ISSUE TITLE
Feature Request: Update Live Preview without refreshing page

### ISSUE THREAD

**Issue by mitchellmaler** [zalando/zalenium#423]
Hello, 

I have been showing some users the live preview page so they can watch their tests being ran. The one question I get is why do I have to refresh to show new containers and why don't the old ones just go away. 

I was wondering if the page could be setup in a way that the deleted containers are just removed and the new created containers are added to the preview page without a full page refresh. This way the VNC connections don't have to be constantly recreated to existing containers just to see new ones and have the old ones removed.

**Comment by diemol** [comment]
HI @mitchellmaler.

That's actually a good idea, I agree that a full page refresh is kind of annoying. 

The thing is that my frontend skills are not that great, so we would need to spend sometime checking how to do that in a nice way. Currently it is just plain html and I guess it should use some JS framework that checks on the background every X seconds for new containers.

Maybe your frontend skills are better than mine? :) Would you like to give it a shot?
We are thinking of redoing the dashboard as well, so perhaps we should use the same JS framework  in both. But we have not thought about those details yet.

I'll keep the issue open, I think it'd be a nice improvement.

**Comment by dspasojevic** [comment]
@pearj would this be addressed by your proposed changes?

**Comment by pearj** [comment]
Yep, my idea of using cometd and an angular.io UI to keep the live UI up to date in near real-time will address this enhancement request.

**Comment by diemol** [comment]
Closing, as it is consolidated in #645
If development starts, we'll reopen the issue.
