### ISSUE TITLE
Concurrent sessions not working

### ISSUE THREAD

**Issue by LKay** [zalando/zalenium#424]
Zalenium Image Version(s):  
3.8.1i
Docker Version:  
17.12.0-ce
If using docker-compose, version:  
1.18.0
OS: 
OSX High Mountain
Docker Command to start Zalenium:  

Running through `docker-compose`:

```yml
  zalenium:
    image: dosel/zalenium
    container_name: "zalenium"
    hostname: "zalenium"
    tty: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/local/bin/docker:/usr/bin/docker"
      - "$PWD/test/video:/home/seluser/videos"
      - "$PWD/test/images:/home/seluser/images"
    ports:
      - 4444:4444
    command: >
      start --screenWidth 1280
            --screenHeight 720
            --videoRecordingEnabled true
            --timeZone "Asia/Tokyo"
            --keepOnlyFailedTests false
            --debugEnabled true
            --maxTestSessions 5
            --desiredContainers 5
            --startTunnel $CLOUD_ENABLED
            --browserStackEnabled $CLOUD_ENABLED
    environment:
      - BROWSERSTACK_USERNAME
      - BROWSERSTACK_ACCESS_KEY
```

## Expected Behavior -

Run test on multiple sessions at the same time.

## Actual Behavior -

I'm trying to run tests throu [WebdriverIO](http://webdriver.io/) runner, which seems to be a quite common setup. But Zalenium works only if a single session is set to be run. The configuration setting in runner to set executing multiple concurrent is `maxInstances`. Zelenium work only if this setting is equal to `1` which means it will only execut one test at the time. That kills the purpose of parallel tests and makes whole test run extremely long. 

When I set `maxInstances` to some value greater than `1`, in this case `maxInstances: 2`, Zelenium just hangs on session init and becomes unresponsive. This is what I see in the logs:

```
[08:43:11]  COMMAND	POST 	 "/wd/hub/session"
[08:43:11]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"firefox","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.10.1","name":"webdriverio"}}}
[08:43:11]  COMMAND	POST 	 "/wd/hub/session"
[08:43:11]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"chrome","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.10.1","name":"webdriverio"}}}
```

**Comment by diemol** [comment]
Hi @LKay,

Well, I cannot image why it is not working right away for you. I know people that are running tests in parallel with Zalenium, but using TestNG or other test runners.

I have never executed tests in parallel with WebDriverIO, let me check their site and see how to do it and perhaps I can reproduce the issue.

**Comment by diemol** [comment]
HI again,

I tried with this small test suite https://github.com/diemol/docker-selenium-issues/tree/master/zalenium-issue-421

and things seem to work out normally, I placed there three tests, two browsers, and 6 `maxInstances`. So I get 6 tests in parallel.

If you are running on OSX, you don't need to mount `/usr/local/bin/docker:/usr/bin/docker` since this works only for Linux.

Can you please double check on your end?

**Comment by LKay** [comment]
@diemol Thanks for checking this out. Actually I'm mounting docker executable as I'm running the test on my Jeknins which runs on linux machine on AWS. On local machine I have my whole testing environment dockerized so everything is running inside docker linux containers. I extended memory allocated to 8GB, but sessions disconnects or menotioned problems appear frequently. 

Anyway thanks, for looking into the issue more deeply! I'm going to try with few diffrent configurations on my side.

**Comment by diemol** [comment]
It could also depend on the available resources... Depending on the page being tested, each node could use up to 2GB of RAM, and if one wants to have 5 parallel or more, then it gets a bit tricky when there are not so many available resources.

Did you have any luck?

**Comment by diemol** [comment]
I'll close this issue due to inactivity, if there is something else we can help with, please let us know and reopen the issue.
