### ISSUE TITLE
parallel tests: WebDriverException Connection refused and Error forwarding the request happening with greater frequency

### ISSUE THREAD

**Issue by borisivan** [zalando/zalenium#426]
Zalenium Image Version(s):  latest -- pull is automated before every suite launch.
Docker Version:  17.04.0-ce and 17.12.0-ce
OS: SLES 12 and Ubuntu 16.04

I run tests in parallel -- there is 1 master zalenium container that spins up 6 grid containers, with th chromeContainers 6 option.

This works fine in general, and has been very reliable for the last month or two.

Over the past week, I'll see 2-3 tests fail (across ~140 total in the suite), with various webDriverException errors regarding connection refused, error forwarding the request, and something like an "INVALID_SESSION" error, without changing things here.

I don't really know where to begin.

Let me ask this -- is there some kind of delay needed before starting a test, when the previous test has just finished?

This seems to happen mid-suite when things are busy. Let's say 6 chromeContainers are each running a test, recording video, etc. Let's say container number 3 is the first to finish its test. The last step of that test is to close the browser. Then, the next test starts, and very quickly attempts to instantiate a new remoteWebDriver, and that request gets sent to the 'master' Zalenium container, acting as the selenium hub. What happens if the child grid container is still wrapping up re: copying the video file, or any other kind of cleanup? Or is there any other kind of race condition that can lead to this occurring? I'm often seeing 'connection refused' in the exception.

On a related note, if there are 6 chromeContainers, all running a test.... what happens if a 7th request comes in? Does it queue? Not sure what the expected behavior is.

This is becoming painful enough that we may need to stop using -- we have people that need to triage each of these failures to ensure it isn't a real regression.

Sometimes we don't see any problem, and when we do see a problem, it's always a different test. It looks to be some kind of a race condition, and it seems to have got worse over the last week or so, where I hadn't seen this occur other than once or twice over the past month or two.

**Comment by stefankahn** [comment]
Hi, I've had a similar issue that is caused by the cleanup cycle. Can you check this ticket https://github.com/zalando/zalenium/issues/335

**Comment by borisivan** [comment]
Hi @stefankahn -- it might be related, but not sure. Are your zalenium child containers spawned dynamically and destroyed dynamically, i.e. the default zalenium mode of operation?

When I start Zalenium at the beginning of the suite, I start it with 6 'permanent' child grid containers. My testNG suite should never have more than 6 tests running in parallel, and zalenium should have 6 containers always there, and it shouldn't close->relaunch any of those containers -- they should stay persistent until the suite is complete. Then I shut down zalenium until the next time I launch the suite.

So as far as 'c;leanup' is concerned, I wasn't sure if you were referring to child grid containers that were on their way down and in the process of getting destroyed after each test... or if you were talking about the way I use it, in which I tell Zalenium to start those 6 child containers and leave them running forever, where in that case, the 'cleanup' might only refer to stopping and exporting the video file after each time I close the browser. (which could be a processing problem anyway, which is what I was probing at).

**Comment by stefankahn** [comment]
Hi. I suspect it is the same issue i face. The nodes do some cleanup after the test has completed, this is used to remove logs and video files.  The side effect of this is your runner (TestNG) will be notified that the test has completed and will send another test, however the node is not ready to start a new test (Highlighted in detail in my issue).  There are 2 side effects that i have encountered.
1. The tests queue up waiting for an available node and time out. This returns various selenium errors.
2. A new node does not spawn to take tests from the queue (Up to the max limit you have set) as the Zalenium proxy currently treats a node in cleanup as test ready (In my opinion it is not ready as a new test cannot start until cleanup has been done)

I found 2 temporary solutions, Launch your Zalenium containers with a max test sessions above what each node will need and tear it all down after execution or run in sequence.

**Comment by borisivan** [comment]
Hi @stefankahn -- thanks. Might effectively be the same issue.

Regarding 'notified that the test has completed' -- just want to make sure I'm not missing something. My understanding is that the only thing along those lines that exists is simply the act of closing the browser re: the webDriver.close/quit. Not sure what the master zalenium node might do to delay sending that return value that it has completed closing the browser, but that's the only interaction between the test environment and zalenium. And the test I'm running might still be going on, if there are other actions my test takes after closing the browser. The timing of when my test environment controls when to start it's next test is under my control, though when I get around to sending my next RemoteWebDriver instantiation, Zalenium will then be in control of deciding when it will respond to me (or have problems re: connection refused / cannot forward / etc).

My previous utilization of Zalenium until I read through your bug report was to start zalenium and specify 6 chrome containers, and I didn't specify a maxContainer value at all, though I specified maxTestSessions to a very high number, which would force Zalenium to not close any of those containers after any number of tests. I configured testNG to not run more than 6 tests in parallel -- I never had any additional containers get spawned, those 6 created at startup were the permanent containers to run the suite. I then closed everything at end of suite -- rinse & repeat.

This worked in general with a very rare 'connection refused / error forwarding / invalid session' type of error. But around a week ago, it's happening to 2-3 tests (out of ~140) once every 2-3 suite runs. As far as it being related to a child container not being ready due to video cleanup or some other cleanup-from-the-last-test issue... it sounds like it could be.

After reading your issue, I've added the parameters to specify maxDockerSeleniumContainers and maxTestSessions, with a value 1 greater than the chromeContainers I'm specifying. Am I correct in saying the intent there is to act as a workaround for this issue, so that if the problem were to occur, it's effectively worked around because Zalenium will spin up that extra container (even though we wouldn't have needed it, if the existing container wasn't having it's slow cleanup problem)?

**Comment by borisivan** [comment]
Some questions that would help me understand this better:

* Does Zalenium have logs dedicated to this condition, or is it unaware that this happens?

* Did the parent zalenium container think that the child grid node was ready, yet the grid node wasn't?

* Did the parent zalenium container know that the grid node wasn't ready, and therefore responded with the connection refused himself?

* What is the expected behavior from Zalenium when a new request comes in, and there isn't a container available, and Zalenium is at max containers? i.e. does it find a way to queue that remote web driver instantiation request, or does it immediately respond with a connection refused?

**Comment by borisivan** [comment]
Apologies in advance for the stream of consciousness.

One thing that would be VERY useful, that could also help us throttle..

If there were some kind of an API (REST, etc) in which we could ask Zalenium how many containers were available and ready -- that might be useful as a workaround, even though the normal use case is that this is not needed or used. I suppose it would require that any bugs be fixed that relate to any disagreement between Zalenium master and grid child thinking they are ready..

**Comment by borisivan** [comment]
Seeing mid-test. The error below was seen 1 second after some successful webDriver operations in the middle of a test. So this probably can't be related to grid node cleanup:

org.openqa.selenium.WebDriverException: cannot forward the request 172.17.0.3:40002 failed to respond
Command duration or timeout: 0 milliseconds

**Comment by diemol** [comment]
Hi @borisivan, @stefankahn,

Let me try to answer the questions first, sorry if I forget any, it was quite a read :)

All comes from the implementation months ago of `maxTestSessions`, in order to reuse containers and save time in the whole test suite.

>What happens if the child grid container is still wrapping up re: copying the video file, or any other kind of cleanup? Or is there any other kind of race condition that can lead to this occurring? I'm often seeing 'connection refused' in the exception.

When the test says `driver.quit()`, the browser closes and the cleanup starts. Copying video, cleaning logs and so on. While this happens, the node is marked that it is cleaning and it will be ready soon (given that `maxTestSessions` hasn't been reached). It is important to note that the node is not ready to be used while it is cleaning and no tests are sent to it.

>On a related note, if there are 6 chromeContainers, all running a test.... what happens if a 7th request comes in? Does it queue? Not sure what the expected behavior is.

It depends. If all containers are running a test (busy), then it would start one more container if it is possible (if `maxDockerSeleniumContainers` has not been reached). If not, then the request is queued. 

> Does Zalenium have logs dedicated to this condition, or is it unaware that this happens?

The exception you posted looks like a Selenium Grid exception, so not raised by Zalenium. That would mean that Zalenium is not aware of it.

> Did the parent zalenium container think that the child grid node was ready, yet the grid node wasn't?

Not really, that is controlled by the logic described above. It will not send tests to nodes that are not ready, we are basically reusing methods already existing in a vanilla Grid.

> Did the parent zalenium container know that the grid node wasn't ready, and therefore responded with the connection refused himself?

No. If Zalenium knew that, we could control it, but that is the interaction of the hub and the nodes. Zalenium main logic is implemented in a special node and we didn't change the hub behaviour.

> What is the expected behavior from Zalenium when a new request comes in, and there isn't a container available, and Zalenium is at max containers? i.e. does it find a way to queue that remote web driver instantiation request, or does it immediately respond with a connection refused?

Hopefully this was answered in the previous questions.

*** 

Now, our intention is always to improve Zalenium. That is why we have a template for issues, even though your comments are descriptive, they are hard to match with a setup since we have no information about your current docker version, how Zalenium is started and with which parameters, some logs and some exceptions. It helps to understand also how the tests are launched, and what resources in RAM and CPU you have as well.

We would like to reproduce the issue and of course find a way to solve it. Whenever you can, please post this information and any other that you find relevant.

**Comment by stefankahn** [comment]
@diemol Thank you for answering all the questions from @borisivan :)

@borisivan I reading how you have setup Zalenium i think it may be the same timing issue with the node being being in cleanup, But @diemol would be able to confirm it when he can replicate your issue.

Happy to help out if i can.

**Comment by borisivan** [comment]
I just hit it again mid test.

the browser was established, test was running great for 15-20 seconds, webdriver acting normally.

less than 1 second after successfully responding, it failed, but I was able to notice this in the master zalenium container log:

00:10:17.806 ERROR - cannot forward the request 172.17.0.8:40004 failed to respond
org.apache.http.NoHttpResponseException: 172.17.0.8:40004 failed to respond
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at org.openqa.grid.internal.TestSession.sendRequestToNode(TestSession.java:462)
        at org.openqa.grid.internal.TestSession.forward(TestSession.java:243)

**Comment by diemol** [comment]
@borisivan 

I will see if something can be concluded from that stacktrace. But in general this is not really helpful, it would be great if you can provide more info (the one I asked for above), otherwise it is very hard for us to figure out where the problem is and how to solve it.

**Comment by borisivan** [comment]
@diemol one observation I had today -- the problem seems to go away when I enable debug logging on Zalenium. That suggests to me that it could be a race condition that has a lower chance of getting hit when the master Zalenium container is a little slower due to debug. If I remove the debug logging, I can hit it again.

Was hoping to enable debugging to see more about the problem. :) But can't seem to make it happen w/ debug enabled. I'll likely leave debug enabled. I have automated copying the zalenium log after every execution of the suite, so hopefully if I hit the problem, we'll find something...

Grepping for errors, I saw something interesting a couple of times. Out of ~ 10 suite runs with debug enabled, saw this on 2 of 10, below. None of the executions hit the main issue this defect is about, but still, thought this might be of interest:

The timeframe below is mid-suite.

Error opening file /home/seluser/videos/vid_chrome_or_firefox_40004.mp4: Invalid IsoMedia File
--40004LOG 22:25:20:717999985 MP4Box got errors meaning the mp4 video file is corrupted, trying again...
Error opening file /home/seluser/videos/vid_chrome_or_firefox_40004.mp4: Invalid IsoMedia File
--40004LOG 22:25:21:746126623 MP4Box got errors meaning the mp4 video file is corrupted, trying again...
Error opening file /home/seluser/videos/vid_chrome_or_firefox_40004.mp4: Invalid IsoMedia File
--40004LOG 22:25:22:764824715 MP4Box got errors meaning the mp4 video file is corrupted, trying again...
Error opening file /home/seluser/videos/vid_chrome_or_firefox_40004.mp4: Invalid IsoMedia File
--40004LOG 22:25:23:780139635 MP4Box got errors meaning the mp4 video file is corrupted, trying again...
Error opening file /home/seluser/videos/vid_chrome_or_firefox_40004.mp4: Invalid IsoMedia File
--40004LOG 22:25:24:795754010 MP4Box got errors meaning the mp4 video file is corrupted, trying again...
Error opening file /home/seluser/videos/vid_chrome_or_firefox_40004.mp4: Invalid IsoMedia File
--40004LOG 22:25:25:812146203 MP4Box got errors meaning the mp4 video file is corrupted, trying again...
Error opening file /home/seluser/videos/vid_chrome_or_firefox_40004.mp4: Invalid IsoMedia File
--40004LOG 22:25:26:828925234 MP4Box got errors meaning the mp4 video file is corrupted, trying again...
Error opening file /home/seluser/videos/vid_chrome_or_firefox_40004.mp4: Invalid IsoMedia File
--40004LOG 22:25:27:845884944 MP4Box got errors meaning the mp4 video file is corrupted, trying again...

**Comment by borisivan** [comment]
@diemol, @elgalu, please forgive the frequent updates -- this is just so important (happening daily) that I need to do what I can, re: observations. I've noticed the following when looking at this all day yesterday.

When this occurs mid suite, the first problem is a connection refused on a webDriver session instantiation:

org.openqa.selenium.WebDriverException: java.net.ConnectException: Connection refused (Connection refused)
Command duration or timeout: 0 milliseconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:325)

Looking at the debug logs of Zalenium, I see that the browser was launched, but that's about it:

23:54:59.646 INFO - http://172.17.0.7:40005 [bash, -c, start-video]
23:54:59.653 DEBUG - http://172.17.0.7:40005 lastCommand: POST - /session/a5c256ba77c7837009d44d647cdb8f81/window/current/maximize executing...
23:54:59.783 DEBUG - http://172.17.0.7:40005 lastCommand: POST - /session/a5c256ba77c7837009d44d647cdb8f81/window/current/maximize executed.
23:54:59.787 DEBUG - http://172.17.0.7:40005 lastCommand: POST - /session/a5c256ba77c7837009d44d647cdb8f81/url executing...

... but I **don't** see the next typical message that I would have expected (example below from the test that ran before in the same container):

23:54:04.038 DEBUG - http://172.17.0.7:40005 lastCommand: POST - /session/3af292bac7b544f258041f3fc7e0aa10/url executed.

... the message above never comes. Instead, there is _nothing_ until around 90 seconds later:

23:56:30.273 INFO - http://172.17.0.7:40005 Shutting down node due to test inactivity
23:56:30.285 INFO - http://172.17.0.7:40005 [bash, -c, notify 'Zalenium', 'TEST TIMED OUT', --icon=/home/seluser/images/timeout.png]

The video IS obtained. If I look at the video, I see that chrome launched, and then just sat there, not loading the URL. If I recall correctly, I saw once that it was a blank screen, with "data,;" (or something like that) at the URL bar. This last time, it had the initial URL of the page I'm trying to load, but still has a blank grey screen -- no content. At the 90 second mark (exactly) in the video, I get the cookie popup from Zalenium re: "TEST TIMED OUT".

It's as if chrome hangs or can't proceed. This is in the midst of 5 other containers moving along happily also launching new browsers that visit the same initial URL. The tests are all pretty quick -- ~ 20 seconds to a minute, hitting the same initial URL.

There seems to be a consistent pattern of collateral damage in which zalenium does try and instantiate another test on that container after the one above fails. That one **always** ends up failing with Zalenium saying it can't forward to that container re: connection refused, but slightly after it was already doing so.

OldTestName = the one that suffered re: above, re: the "blank" browser that eventually times out after 90 seconds:

NewTestName = the new one that seems to suffer the collateral damage afterwards (the next test that Zalenium sends to that container):

Logs from the tail end of the first test failing, and then showing the collateral damage on the next test:

23:56:44.269 INFO - http://172.17.0.7:40005 Video file copied to: /home/seluser/videos/zalenium_Feb21-17-40-43-OldTestName_chrome_LINUX_2018022123564423                                                      2.mp4
23:56:44.434 INFO - http://172.17.0.7:40005 [bash, -c, transfer-logs.sh]
23:56:44.538 DEBUG - http://172.17.0.7:40005
23:56:44.722 INFO - http://172.17.0.7:40005 Logs copied to: /home/seluser/videos/logs/zalenium_Feb21-17-40-43-OldTestName_chrome_LINUX_20180221235644232
23:56:44.731 INFO - http://172.17.0.7:40005 [bash, -c, cleanup-container.sh]
23:56:44.876 DEBUG - http://172.17.0.7:40005
23:56:44.891 DEBUG - http://172.17.0.7:40005 lastCommand: POST - /session/a5c256ba77c7837009d44d647cdb8f81/url executed.
23:56:44.960 DEBUG - Available nodes: [http://172.17.0.7:40005, http://172.17.0.4:40000, http://172.17.0.2:30000, http://172.17.0.3:40002, http://172.17.0.6:40003, http://172.17.0.8:4                                                      0004, http://172.17.0.5:40001]
23:56:44.961 DEBUG - Trying to create a new session on node http://172.17.0.7:40005
23:56:44.962 DEBUG - http://172.17.0.7:40005 Creating session for: {acceptSslCerts=true, goog:chromeOptions={args=[], extensions=[]}, se:CONFIG_UUID=466e6c9c-3f81-44df-b069-6e311aeca7                                                      44, zal:screenResolution=1920x1080, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@34e34a5e, browserName=chrome, zal:name=Feb21-17-40-43-NewTestName, group=Feb21-17-40-43}
23:56:44.972 DEBUG - http://172.17.0.7:40005 lastCommand: POST - /session executing...
23:56:45.838 DEBUG - http://172.17.0.7:40005 lastCommand: POST - /session executed.
23:56:45.849 INFO - http://172.17.0.7:40005 [bash, -c, start-video]
23:56:45.866 DEBUG - http://172.17.0.7:40005 lastCommand: POST - /session/344e21227626c6b79813f87c31f917bf/window/current/maximize executing...
23:56:46.006 DEBUG - http://172.17.0.7:40005 lastCommand: POST - /session/344e21227626c6b79813f87c31f917bf/window/current/maximize executed.
23:56:46.009 DEBUG - http://172.17.0.7:40005 lastCommand: POST - /session/344e21227626c6b79813f87c31f917bf/url executing...
23:56:46.395 DEBUG - http://172.17.0.7:40005 lastCommand: POST - /session/344e21227626c6b79813f87c31f917bf/url executed.
23:56:46.400 DEBUG - http://172.17.0.7:40005 lastCommand: POST - /session/344e21227626c6b79813f87c31f917bf/timeouts executing...
23:56:46.411 DEBUG - http://172.17.0.7:40005 lastCommand: POST - /session/344e21227626c6b79813f87c31f917bf/timeouts executed.
23:56:46.415 DEBUG - http://172.17.0.7:40005 lastCommand: POST - /session/344e21227626c6b79813f87c31f917bf/elements executing...
23:56:46.472 DEBUG - http://172.17.0.7:40005 lastCommand: POST - /session/344e21227626c6b79813f87c31f917bf/elements executed.
23:56:46.977 DEBUG - http://172.17.0.7:40005 lastCommand: POST - /session/344e21227626c6b79813f87c31f917bf/elements executing...
23:56:46.983 ERROR - cannot forward the request Connect to 172.17.0.7:40005 [/172.17.0.7] failed: Connection refused (Connection refused)
org.apache.http.conn.HttpHostConnectException: Connect to 172.17.0.7:40005 [/172.17.0.7] failed: Connection refused (Connection refused)
23:56:46.994 INFO - http://172.17.0.7:40005 AFTER_SESSION command received. Cleaning up node for reuse, used 17 of max 150
23:56:47.005 INFO - http://172.17.0.7:40005 [bash, -c, notify 'Zalenium', 'TEST COMPLETED', --icon=/home/seluser/images/completed.png]
23:56:47.024 DEBUG - http://172.17.0.7:40005 lastCommand: POST - /session/344e21227626c6b79813f87c31f917bf/cookie executing...
23:56:47.025 DEBUG - http://172.17.0.7:40005 Checking for cookies...{"cookie":{"path":"/","name":"zaleniumMessage","httpOnly":false,"secure":false,"hCode":-693786604,"value":"TestNewTestName has failed","class":"org.openqa.selenium.Cookie"}}
23:56:47.111 INFO - http://172.17.0.7:40005 [bash, -c, notify 'Zalenium', 'Test NewTestName has failed', --icon=/home/seluser/images/message.png]
23:56:47.219 DEBUG - http://172.17.0.7:40005
23:56:47.228 INFO - http://172.17.0.7:40005 [bash, -c, stop-video]
23:56:47.321 DEBUG - http://172.17.0.7:40005
23:56:47.322 ERROR - cannot forward the request Connect to 172.17.0.7:40005 [/172.17.0.7] failed: Connection refused (Connection refused)
org.apache.http.conn.HttpHostConnectException: Connect to 172.17.0.7:40005 [/172.17.0.7] failed: Connection refused (Connection refused)
23:56:47.353 DEBUG - Available nodes: [http://172.17.0.4:40000, http://172.17.0.2:30000, http://172.17.0.3:40002, http://172.17.0.6:40003, http://172.17.0.8:40004, http://172.17.0.5:4                                                      0001, http://172.17.0.7:40005]
23:56:48.861 DEBUG - Available nodes: [http://172.17.0.2:30000, http://172.17.0.3:40002, http://172.17.0.6:40003, http://172.17.0.8:40004, http://172.17.0.5:40001, http://172.17.0.7:4                                                      0005, http://172.17.0.4:40000]
23:56:48.864 DEBUG - http://172.17.0.7:40005 No more sessions allowed
23:56:49.950 DEBUG - http://172.17.0.7:40005 video-rec: ERROR (not running)
23:56:50.107 INFO - http://172.17.0.7:40005 Video file copied to: /home/seluser/videos/zalenium_Feb21-17-40-43-NewTestName_chrome_LINUX_20180221235650107.mp4
23:56:50.858 INFO - http://172.17.0.7:40005 Marking the node as down because the test has been idle for more than 90 seconds.
23:56:50.859 WARN - Cleaning up stale test sessions on the unregistered node http://172.17.0.7:40005
23:56:50.858 WARN - http://172.17.0.7:40005 java.lang.IllegalStateException: Container cc8adb50e13da826c72963fa6a018ddb23a30dabd1017f231d28b96b832ad436 is not running.

While getting to the bottom of the first thing that goes wrong is obviously the most important, I wonder if it's a valuable data point that when Zalenium attempts to clean up the node after the test that timed out, it seems to move forward with the next test, only to also to be rejected re: "connection refused" by that node container. But it had actually brought up the browser. And while I don't get the video for that test (see end of log snippet above...), the log messages from my test show that it brought up the main URL of the initial page, and had identified an object on the screen (textbox for credentials), before getting:

cannot forward the request Connect to 172.17.0.7:40005 [/172.17.0.7] failed: Connection refused (Connection refused)
Command duration or timeout: 0 milliseconds

While I don't have any answers, I do find it interesting that I've seen this pattern multiple times now, and when I do, the first thing that goes wrong is always a browser that seems to hang on initial launch and not finish loading the main URL, with chrome either stuck at "data,;", or the actual URL in the bar, but in both cases, an empty browser screen. And that container is still healthy enough to record 90 seconds of video with that empty browser, including the zalenium cookie at the 90 second mark, so I know the video isn't 'stuck' either.

I see multiple references in various bug reports / forums that seem to match this footprint for selenium-grid (some with comments from you) re: the DBUS environment variable and also an interesting one re: not enough /dev/random resources available on the node / haveged / etc.... 

It seems like this really jumped up a while ago when most of the commits seem to be around Kubernetes support. I wonder if non Kubernetes support was negatively affected.

Does any of the sequence of events / log messages provided above help? I'm running with debug enabled and it seems to happen less, but did happen a few times late yesterday, which is what the logs above are from. Node containers don't seem to have debug enabled. I've looked at them with the docker logs command and there is nothing of interest. Is there debug that can be enabled there, and I could automate copying those before they are destroyed, if that would be helpful?

To see if the persistent containers were a relevant factor, I changed the mode of operation to be the 'default' mode in which a container is torn down after every test, ran in to the same problem, (don't remember if I also saw the collateral damage, but the same initial problem). I changed it back (6 consistent containers) as that doesn't seem to be the issue.

**Comment by diemol** [comment]
No worries, all additional information is good. Right now we are not able to act on this immediately since we have other stuff to do at work. But we should have more bandwidth around mid-end of March (probably earlier).

**Comment by diemol** [comment]
I think I just reproduced the issue by accident, I will try to double check and see if I find the root cause.

**Comment by borisivan** [comment]
FWIW, I've spent quite a bit of time on this over the past week. I believe that some or most of the examples I encountered earlier were a threadsafe problem re: webDriver usage re: running the tests in parallel. I've moved all webDriver creation and access to a threadlocal strategy, and frequency has diminished by ~ 75%.

Regarding the remainder that I've still been seeing, I believe there might be a threadsafe problem in Zalenium somewhere around the code re: when the webDriver is instantiated, i.e. you allow an entry to be processed from the queue -- specifically, when there are multiple entries being accepted off the queue at approximately the same time.

Specifically, when I switched to threadlocal, I didn't synchronize webDriver creation, because I did not want to serialize that process. When left in parallel (but referenced uniquely via threadlocal), I still see an occasional problem when 2 or more webDrivers are being instantiated at almost the same time, for a container that was just cleaned up (I don't destroy the containers).

When I synchronize that process, so that I won't even attempt to _create_ a new webDriver object until after the other one I requested has been fully instantiated, I haven't seen the problem over the past 2 days, which is making me feel pretty confident that it made the difference. But I think that's something I'd like to see if we can prove in Zalenium and fix, in that I would like to create (not just use, but create) multiple webDriver objects in parallel. _Using_ them in parallel seems fine, but _creating_ them in parallel seems like there is still a potential problem in Zalenium. Does this match with what you might have found?

**Comment by diemol** [comment]
Wow, thanks @borisivan!
You just helped us to find a really old bug!! Your analysis was vital to find the cause of this error you were seeing. That was the pattern indeed, a timeout and then the error.

This bug exists, perhaps, since the early stages of Zalenium. The thing is that it is more prone to happen when running several threads and reusing containers.

In short, the timeout happens, and since we don't know what is the main cause for that timeout (it could be an error in the node or an error in the test), then we decide to shudown the node. The problem is that while the node is shutting down, it receives a test request and accepts it because it has not reached the max amount of tests.

I just changed that and that issue should be solved. What is remaining to check is why the browser freezes when the session is starting and causes the timeout. I would prefer to fix what I mentioned and release it, and then keep monitoring.

I am going to run some more tests locally, and then release this in 1-2 days.

Thanks again!

**Comment by borisivan** [comment]
Hi @diemol (and @stefankahn) -- that's great, will let you know what difference in behavior I see after running it for a few days after you release.

When you have time at some point, would love to know how we might be able to debug the browser startup problem on the node, as that (as you mention) seems like it's the start of this sequence of events. While I forget what I saw re: Firefox, I do know that with Chrome, I see the browser launch but just with "data;," in the URL, with a empty document symbol -- no swirling animation as if it's even making an attempt to load the page. If you have any guidance re: getting debug logs from the node that might yield some clues, I'm all ears.

Thanks again! Will let you know what I see after I pick up your next image.

**Comment by gpapadakis** [comment]
We also found this issue. We are currently use a ThreadPool of size 10 to parallelize our tests and a lot of tests are getting the exception described in this thread. Also found that if i increase the chrome/firefox containers(more than 10 in number) i am always getting at most 10 nodes with 1 chrome instance available? How can i have one node and multiple chrome/firefox instances supported in a single container? Or if i want to run let say 5 Chrome sessions in parallel i need to have 5 different chrome containers?

**Comment by diemol** [comment]
@gpapadakis we are going to release this fix soon, so the exception should not be present (unless the root cause is different in your scenario).

To answer your question, to run 5 Chrome sessions in parallel, 5 containers are needed. We only run on test session per node to simplify everything. Otherwise capturing video would be extremely hard since many browsers are using the same window.

**Comment by gpapadakis** [comment]
Thanks for the quick response and why if i add --chromeContainers 20 it will only start 10 containers? Is this the upper limit?

**Comment by diemol** [comment]
Please use `--desiredContainers` instead, `--chromeContainers`  will be removed soon.

Now, if I request 20 containers, but `--maxDockerSeleniumContainers` is set to 10 (default value), only 10 will be created.

**Comment by diemol** [comment]
This was just released, please pull the new images
https://github.com/zalando/zalenium/releases/tag/3.10.0b

**Comment by gpapadakis** [comment]
Thanks @diemol for the fix!

**Comment by diemol** [comment]
I hope things work in your environments, we tried to test with several threads and we didn't see it. So hopefully it also works on your side. 

If not, don't doubt to report it again, thanks!

**Comment by andresilva5** [comment]
I have 20 jenkins jobs running one at a time, with 18 tests each, in threads of 2.
Sometimes the test fails with "java.net.ConnectException: Connection refused (Connection refused)".

My configuration is :
docker run --rm -d -ti --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos -v /upload:/tmp/node/home/seluser/upload_files -v /downloads:/tmp/node/home/seluser/Downloads --privileged dosel/zalenium start --desiredContainers 0 --videoRecordingEnabled false
