### ISSUE TITLE
Protractor Port Config

### ISSUE THREAD

**Issue by geek876** [zalando/zalenium#437]
Hi,
We running Zalenium within K8s which works as expected (the starting of containers etc).
We use gitlab-ci (also using kubernetes-runner) builds and protractor
Previously, we were using browser-stack but now as most of our tests are Chrome, we want to use Zalenium.
Within Protractor config, our baseurl is set to http://localhost:3000 (https://github.com/angular/protractor/blob/master/lib/config.ts)
The tests do get executed via Zalenium on a K8S docker node, however all tests fail. When we see the recording, we see that the browser is trying to open http://localhost:3000 but it says 'This site can't be reached'. I suspect, there is some port that needs to open between the CI build container (the container that runs tests/protractor) and the Zelinum HUB ? 
The exact configuration works without issues on browser stack and there, if we see recordings, we do actually see the site loading up on http://localhost:3000

**Comment by diemol** [comment]
Hi @geek876,

This is usually only a matter of configuration. When running a test and the browser is inside a container, if you say http://localhost:3000, then `localhost` will be inside the container, and not where your app is actually running.

You could check the docs: https://zalando.github.io/zalenium/#docker, the section called "Accessing the host". Which basically means that the browser needs to access the url where your app is running.

In the case of BrowserStack, it works because you are probably opening a tunnel from the machine where your app is running, and that's why it can access it.

Let us know how it goes, I'll keep this issue open for a few days in case you have feedback for us.

**Comment by geek876** [comment]
Hi @diemol. Thanks for your reply and I did check the "Accessing the host" section. I think my use-case is slightly different. For me, the browser (Zalenium provided) as well as my app (SUT) both are inside the container (K8S). The SUT container is spawned by Gitlab CI (Kubernetes Executor https://docs.gitlab.com/runner/executors/kubernetes.html) and as far as I can see, GitLab doesn't allow any configs to exposing any ports on the POD/Container that it spawns. I can perhaps create a K8S service called 'someservice' and set it to select the CI Container Labels (Gitlab CI does allow setting pod labels via keyword pod_labels) and then set protractor baseurl to be 'http://someservice:3000' but still I won't hit port 3000 on the SUT/CI container as that port is not exposed. Any idea how I get around that ?

**Comment by diemol** [comment]
I think that is the most straightforward way, to actually use a service to access your SUT from the containers. 

About the port part, I don't know, I haven't use GitLab so I am not sure how it should work.
But I think there must be a way to expose a service to be consumed during testing, it is not a strange use case.

**Comment by diemol** [comment]
Hi @geek876,

How did it go? Could you deploy the service with an url that was reachable to the containers?

**Comment by geek876** [comment]
Hi @diemol 
I have raised this with GitLab https://gitlab.com/gitlab-org/gitlab-ce/issues/43206 and see if there is any traction. If not, and if it becomes a priority for us, we will proceed the usual way (i.e. not use GitlLab runner). Will keep you posted. Thanks for checking in.

**Comment by diemol** [comment]
Hi @geek876,

OK, I see, I hope it gets traction and you can use only the GitLab runner.

I think I will close this issue then since there is not an action item for us, but if you see than something could be done on our side, please feel free to comment and reopen the issue.

**Comment by iMbaundso** [comment]
Hi @geek876:

We had a quiet similiar case and solved it like this:

1) Deploying zalenium to the cluster and creating and service for it. Having done this you can simply point your tests to eg. Zalenium:4444/wd/hub within your cluster and kubernetes service discovery is doing the rest. If you need to access it from outside you would have to create an Ingress for it.

2) The happy part. If you need to start up your web app using docker in docker:
```
Testjob:
  image: docker
  stage: e2e
  tags: 
    - kubernetes
  script:
    - docker run .... -p 12345:12345
  variables:
    DOCKER_HOST: "tcp://localhost:2375"
    DOCKER_DRIVER: overlay2
  services: 
    - docker:dind
```
Using this your docker run commands will spin up your dind containers on pod level making them available for other pods on IP:PORT. If you are starting your app as service it will spin up on pod level anyways.

3) Even more happy: As you've seen you cannot simply point to localhost as this is just working within pods. So how to tell zalenium what url to point on. We are using a quiet dirty option here:
export TARGETPOD="$(ip route get 8.8.8.8 | awk '{print $NF; exit}')"; 
npm test
In your test do something like browser.get("http://" + env.AUTOTEST_TARGETSERVER + "YOUR_PORT")
