### ISSUE TITLE
For awareness - Docker network setting enable_icc causes zalenium to fail silently

### ISSUE THREAD

**Issue by dgracehmh** [zalando/zalenium#440]
I spent a bit of time getting to the bottom of why zalenium would not work on my setup. I enabled debug logs etc but they did not help. There is a docker network setting 
```"com.docker.network.bridge.enable_icc": "true",```
This setting allows inter container connectivity. If it is set to false then zalenium will fail.
You can see the docs for it here - https://docs.docker.com/engine/reference/commandline/network_create/#bridge-driver-options

I wanted to log this for visibility in case others have same issue.

I can update documentation for this if you think it is necessary or maybe dig around the code to try catch the issue and log it. If you think this is the way to go could you point me in the right direction in the code and I can have a go?

Zalenium Image Version(s):  
3.8.1i
Docker Version:  
17.12.0-ce, build c97c6d6
If using docker-compose, version:  
na
OS: 
Mac OS High Sierra - 10.13.1
Docker Command to start Zalenium:  
```docker run --rm -d --name zalenium -p 4444:4444 -p 5555:5555 -v $(which docker):/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp/node/home/seluser/Downloads -v /tmp:/home/seluser/Downloads --label zalenium_main --privileged dosel/zalenium start --desiredContainers 4 --maxDockerSeleniumContainers 4 --maxTestSessions 4 --videoRecordingEnabled false```
If using Kubernetes, specify your environment, and if relevant your manifests:

**Comment by diemol** [comment]
Hi @dgracehmh,

Thanks for this information. We are adding a troubleshooting section to the docs soon, so I'll keep this issue open and then we can document it there.

As a side note, I think it just doesn't work with that setting like that (or quite some work is needed to make it work). There was this [issue](https://github.com/SeleniumHQ/docker-selenium/issues/20) in the official docker-selenium repo about the same thing, and in the end we didn't change the setting.
