### ISSUE TITLE
Is there a way to change the WAIT_TIMEOUT for the spawned pod nodes?

### ISSUE THREAD

**Issue by Deklin** [zalando/zalenium#442]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
3.9.1a
Docker Version:  
1.12.6
If using docker-compose, version:  

OS: 
Centos 7.4
Docker Command to start Zalenium:  

If using Kubernetes, specify your environment, and if relevant your manifests:  
standardized yaml based on your github examples
## Expected Behavior -
Ideally timeout would be centrally managed, we are not sure if this is even our issue but we see a WAIT_TIMEOUT env var on the generated nodes but are unable to set that value as far as we can tell.

## Actual Behavior -
Some of our tests are timing out and failing, we are not sure if its the spawned node default timeout of 120s and would like to change it via a env var override but unsure how to on spawned nodes.

**Comment by diemol** [comment]
Hi @Deklin,

Just to understand better, do some of your tests timeout because there are no commands sent to Selenium for more than 90 seconds (that's the default value, controlled in Zalenium). If so, you can add a capability called `idleTime` with the max amount of seconds that the session can be idle before it is shutdown.

https://zalando.github.io/zalenium/#usage -> "Idle Timeout"

**Comment by Deklin** [comment]
@diemol i'll be honest i'm not even sure this is our problem.
Basically sometimes our session gets disconnected, or can't even connect. This may be a selenium issue more than zalenium, but I am not sure.

here is another thread i'm on

https://github.com/SeleniumHQ/selenium/issues/1261

**Comment by diemol** [comment]
This might be just a matter of tuning the deployment. Perhaps you can join the chat where we have other users who are also deploying in k8s and they can share their experience (based on that we have identified things to improve).

We are moving from Gitter to Slack, please go to https://seleniumhq.herokuapp.com, join and then check the #zalenium channel there.

**Comment by diemol** [comment]
I'll close this issue since it doesn't seem related to Zalenium, but we'll follow up with the other one you have opened.
