### ISSUE TITLE
Spawned nodes seem to disappear after they are used.

### ISSUE THREAD

**Issue by Deklin** [zalando/zalenium#443]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
3.9.1a
Docker Version:  
1.12.6
If using docker-compose, version:  

OS: 
Centos 7.4
Docker Command to start Zalenium:  

If using Kubernetes, specify your environment, and if relevant your manifests:  
Standard yaml from your github repo mostly unmodified
## Expected Behavior -
After a session is complete, ideally the pods would stay active and not be destroyed. We are not sure if this is a problem or by design.

## Actual Behavior -
We have the default nodes to start with set to 2, after a test runs, it seems to kill the node. We'd like to keep a minimum number of nodes always running to avoid startup time costs.

**Comment by Deklin** [comment]
Here is what we see after a test has completed, just really want to know if this is expected.

![image](https://user-images.githubusercontent.com/3372511/36293294-3a70f256-12a6-11e8-9e6b-a47b1fd8095f.png)

**Comment by Deklin** [comment]
The failure we see i reported here: https://github.com/seleniumhq/selenium/issues/1261

**Comment by diemol** [comment]
Hi @Deklin,

That is the default behaviour of Zalenium, one test - one node. After the test completes, the container is shutdown. This can be overwritten, in case you want to run more than one test per container, see https://zalando.github.io/zalenium/#docker -> "Run more than one test per node".

Are you running into some errors in your tests due to this?

**Comment by Deklin** [comment]
@diemol Thank you this answered my question, I have opened a separate issue to address the issues we are seeing in our failing tests.

https://github.com/zalando/zalenium/issues/447
