### ISSUE TITLE
How to change browserTimeout or SEL_BROWSER_TIMEOUT_SECS on the spawned nodes

### ISSUE THREAD

**Issue by Deklin** [zalando/zalenium#447]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
3.9.1a
Docker Version:  
1.12.6
If using docker-compose, version:  

OS: 
Centos 7.4
Docker Command to start Zalenium:  

If using Kubernetes, specify your environment, and if relevant your manifests:  

## Expected Behavior -
Ability to change SEL_BROWSER_TIMEOUT_SECS and other env vars on the kubernetes generated worker nodes for zalenium grid.

## Actual Behavior -
We need to change the browsertimeout value to deal with a random test failure. In selenium grid we can change this but we can't seem to change it with zalenium. If I look at the container startup for zalenium I can see an env var of SEL_BROWSER_TIMEOUT_SECS set to 12000 but there seems to be no way to influence this via the hub container settings. Our only option seems to be creating a modified container to override this env var which seems wrong

**Comment by diemol** [comment]
Hi @Deklin,

Were you successful with this and also debugging the failing tests? (As for what you mentioned in the Slack channel).

Please let us know in case something else is needed or perhaps we can close the issue.

**Comment by Deklin** [comment]
@diemol will report back, me and my family are all down w/ the flu right now so the only thing i've looked at lately is a pillow.

**Comment by diemol** [comment]
No worries @Deklin, get well soon!

**Comment by Deklin** [comment]
@diemol unfortunately that passed the values down but caused the container to crash loop because the parameter would have been specified twice.

I'm still exploring options here

**Comment by diemol** [comment]
A fix was merged to master for this, it'll be included in the next release.

**Comment by meyerbro** [comment]
Hey, how this variable is set now? I can't find it... The selenium docker containers are being created with SEL_BROWSER_TIMEOUT_SECS=16000 but I can't change this anymore in Zalenium...
