### ISSUE TITLE
Unable to access file downloaded during test execution in chrome browser

### ISSUE THREAD

**Issue by amalsgit** [zalando/zalenium#448]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  

Docker Version:  
17.09.1-ce
OS: 
Windows 10
Docker Command to start Zalenium:  
  docker run --rm -ti --name zalenium -p 4444:4444 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /C/Users/ajayara/Desktop/AutomationOutput/zalenium:/home/seluser/videos \
    --privileged dosel/zalenium start

During the creation of web driver session, I am updating Chrome's default download path to my host-specific system path. The same path is reflected in the Chrome browser settings inside the Zalenium container. However, once the file gets downloaded as part of the automated test, it is not present in the target directory in the host machine.

## Expected Behavior -
The downloaded file is present in the specified directory in host machine
## Actual Behavior -
File is not present

Can you please guide me on how to view this file inside the file system of the container and then copy it onto the host machine so that I can verify the downloaded contents. Thanks in advance.

**Comment by diemol** [comment]
Hi @amalsgit,

I'll close this issue since we are both handling in the Slack chat already.
