### ISSUE TITLE
VNC artifacts

### ISSUE THREAD

**Issue by arielschiavoni** [zalando/zalenium#45]
Hi,

I have been experiencing some issues when I try to see the tests running in http://mydomain:4444/grid/admin/live. The VNC live preview is not rendered correctly and shows some artifacts as you can see in the attached GIF.

![vnc_artifacts](https://cloud.githubusercontent.com/assets/1364564/21588422/c96b8d8e-d0e6-11e6-83da-b18365f82ac2.gif)

It is only happening on Linux. I tested it in my local machine (macOS) and I was not able to reproduce it.

I suspect it has something to do with mounting `/dev/shm` from the host. I had the same problem when using `elgalu/selenium` and then mounting `/dev/shm`. However it works fine if I use `--shm-size` flag instead.

**Comment by diemol** [comment]
Hi @arielschiavoni , 

What do you mean when you say "some artefacts"? Can you describe the scenario a bit please?

Side question, are you using Selenium 3? Is it working fine?

**Comment by diemol** [comment]
Hi @arielschiavoni 

We released yesterday a new version, where we made a small change in the way the container is created. Switching from the `/dev/shm` sharing to the `--shm-size` flag usage.

Please give it a try and let us know how it looks now.

**Comment by diemol** [comment]
@arielschiavoni 

I'll close this issue since it has been quite inactive for while.

Please feel free to reopen and to give feedback if something comes up.

Thanks!
