### ISSUE TITLE
Cascading zalenium messages

### ISSUE THREAD

**Issue by vikaskedia** [zalando/zalenium#450]
I am using zalenium messages by adding a cookie and it works beautifully.

Is it possible to remove the first zalenium message before displaying the 2nd zalenium message?

![image](https://user-images.githubusercontent.com/6703876/36641831-1e685bac-19eb-11e8-9f08-967dd15f153d.png)

In the above screenshot I would like to remove: 

"Starting test: SC Munki is loading properly"

before displaying

"Starting test: Checking title"

**Comment by diemol** [comment]
Hi @vikaskedia,

Yes, this could be done, and it is not really complicated. I'll just leave the issue open for a while in case someone has a different opinion (since no one has requested this before).

**Comment by diemol** [comment]
Hi @vikaskedia,

This was just merged to master, it will be released in 1-2 days.

**Comment by diemol** [comment]
Hi, this was just released https://github.com/zalando/zalenium/releases/tag/3.10.0c
