### ISSUE TITLE
can i get build status -> success or failed from command line?

### ISSUE THREAD

**Issue by vikaskedia** [zalando/zalenium#451]
Thank you for the wonderful project.

After the tests finish running I need to get the build status from the command line.

Is that possible?

I need the build status so if the test passes I can push code to the upstream server.

I am using protractor for the testing. I see that there is a log file selenium-multinode-stderr.log

And it has entries for the value of "zaleniumTestPassed"

I can probably grep for the value of "zaleniumTestPassed".

I am wondering if there is a simpler/cleaner way?

![image](https://user-images.githubusercontent.com/6703876/36646210-92235b94-1a29-11e8-8669-29e6eda91fa1.png)

**Comment by diemol** [comment]
Hi @vikaskedia,

That status comes from the testing framework, since in it you are able to send the cookie to set the status shown in the dashboard. 

Therefore, the best place to grab it would be the test framework itself.

**Comment by diemol** [comment]
and thanks for the kind words!

**Comment by diemol** [comment]
@vikaskedia in https://github.com/zalando/zalenium/releases/tag/3.10.0a it was just added an endpoint where you can query all the test information in a json format.

This endpoint is under development but it may give you what you need. 

I'll close this issue since this info should be available in the test framework, but now is also available in the endpoint.

**Comment by Pratikck12** [comment]
Currently on zalenium dashboard shows the test cases status as completed even if its failed. How to show PASS/FAIL status on zalenium dashboard for test cases?

**Comment by Pratikck12** [comment]
How to set a logs for test scripts on Zalenium? How we are using the log4j for logging same I want on Zalenium.
