### ISSUE TITLE
Browserstack stops working

### ISSUE THREAD

**Issue by peerster** [zalando/zalenium#452]
Zalenium Image Version(s):  
3.9.1a
Zalenium is running in Openshift origin 3.7

## Expected Behavior -
Browestack continues to work

## Actual Behavior -
We're using browserstack, and it works quite well.
However, from time to time, we get the following:
```
09:56:10.457 INFO - BrowserStack Releasing slot and terminating session due to inactivity.
09:56:10.962 ERROR - java.io.FileNotFoundException: https://www.browserstack.com/automate/sessions/.json
java.io.FileNotFoundException: https://www.browserstack.com/automate/sessions/.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at de.zalando.ep.zalenium.util.CommonProxyUtilities.readJSONFromUrl(CommonProxyUtilities.java:43)
	at de.zalando.ep.zalenium.proxy.BrowserStackRemoteProxy.getTestInformation(BrowserStackRemoteProxy.java:86)
	at de.zalando.ep.zalenium.proxy.CloudTestingRemoteProxy.lambda$addTestToDashboard$2(CloudTestingRemoteProxy.java:236)
	at java.lang.Thread.run(Thread.java:748)
```
And when this happens the error keeps reoccurring and the only way to recover is to deploy again (i.e reboot the pod).

Haven't really debugged this, but I'm not sure why this is happening, and how to reproduce it.
Any advice on where to start?

This is the logs from when starting the pod, showing that the integration with Browserstack is setup propery:
```
2018-02-26 09:58:09.380:INFO:osjs.Server:main: Started @706ms
09:58:09.380 INFO - Selenium Server is up and running on port 30002
09:58:09.380 INFO - Selenium Grid node is up and ready to register to the hub
09:58:09.392 INFO - Registering the node to the hub: http://localhost:4444/grid/register
09:58:09.978 INFO - [BS] Getting account max. concurrency from https://www.browserstack.com/automate/plan.json
09:58:09.989 INFO - Registered a node http://hub-cloud.browserstack.com:80
09:58:09.995 INFO - Updating the node configuration from the hub
09:58:10.010 INFO - The node is registered to the hub and ready to use
......Browser Stack node started!
Starting BrowserStackLocal...
Waiting for BrowserStack tunnel to start...
grep: /home/seluser/logs/browserstack-stdout.log: No such file or directory
.............BrowserStack tunnel started! (wait-browserstack.sh)
TestingBot not enabled...
Zalenium is now ready!
*************************************** Data Processing Agreement ***************************************
By using this software you agree that the following non-PII (non personally identifiable information)
data will be collected, processed and used by Zalando SE for the purpose of improving our test
infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
of the IP address are collected.
See the complete license at https://github.com/zalando/zalenium/blob/master/LICENSE.md
```

**Comment by peerster** [comment]
Hm actually it seems that it can recover from this error. Debugging this is going to be even harder than I thought 😄

**Comment by peerster** [comment]
We're running into this quite often. Any suggestion on what it could be?

**Comment by peerster** [comment]
Also, when it stops working, the grid is unaware of this...

So tests that are trying to be dispatched to browserstack gets:
```
{ value: { message: '[browserstack.local] is set to true but local testing through BrowserStack is not connected.' },
```
Is there any "mechanism" for trying to setup the tunnel if it goes down?

**Comment by peerster** [comment]
Here is some additional debug info from within the zalenium pod:
```
extrauser@zalenium-19-8klf6:/home/seluser$ cat logs/browserstack-stdout.log
BrowserStackLocal v7.0

Setting output as verbose
You can now access your local server(s) in our remote browser.


Connecting to BrowserStack using WebSocket protocol...
Platform supports WebSocket connections.


Connecting to BrowserStack using WebSocket protocol...
Platform supports WebSocket connections.


Connecting to BrowserStack using WebSocket protocol...
Platform supports WebSocket connections.


Connecting to BrowserStack using WebSocket protocol...
Platform supports WebSocket connections.

Press Ctrl-C to exit
```
```
extrauser@zalenium-19-8klf6:/home/seluser$ ps -ef |grep Browser
extraus+    175      1  0 11:37 ?        00:00:04 java -Djava.util.logging.config.file=logging_info.properties -jar /home/seluser/selenium-server-standalone-3.9.1.jar -role node -hub http://localhost:4444/grid/register -registerCycle 0 -proxy de.zalando.ep.zalenium.proxy.BrowserStackRemoteProxy -nodePolling 90000 -port 30002
extraus+    247    243  0 11:37 ?        00:00:00 BrowserStackLocal <our key removed> -skipCheck -v -forcelocal -localIdentifier zalenium
extraus+    261    247  0 11:37 ?        00:00:01 /usr/local/bin/BrowserStackLocal <our key removed> -skipCheck -v -forcelocal -localIdentifier zalenium
extraus+    291    261  0 11:37 ?        00:00:01 /usr/local/bin/BrowserStackLocal <our key removed> -skipCheck -v -forcelocal -localIdentifier zalenium-browserstack-fork-0
extraus+    296    261  0 11:37 ?        00:00:01 /usr/local/bin/BrowserStackLocal <our key removed> -skipCheck -v -forcelocal -localIdentifier zalenium-browserstack-fork-1
extraus+    301    261  0 11:37 ?        00:00:00 /usr/local/bin/BrowserStackLocal <our key removed> -skipCheck -v -forcelocal -localIdentifier zalenium-browserstack-fork-2
extraus+   8967   8411  0 13:04 ?        00:00:00 grep Browser
```

So from that perspective the tunnel seems to be up and everyhings OK... but in realtiy it's not :)

**Comment by diemol** [comment]
Hi @peerster,

It kind of looks like we have two issues. 

One is that somehow Zalenium tries to fetch the test information from BrowserStack and after retrying, it fails with that file not found. We need to add some control there for that case.

The second one, looks like the tunnel crashes? Is it like that?

**Comment by peerster** [comment]
I agree, there are two issues, but I don't know if they're related?
I mean fetching `https://www.browserstack.com/automate/sessions/.json` should not have anything to do with the tunnel right?

Maybe there are more options to the `BrowserstackLocal` (or what's it called) binary that can log more information, because of now I couldn't see anything related to the tunnel not working, but as you stated, the tunnel has most likely crasched (but the processes where running as shown previously).

Since I can't reproduce the tunnel crashing I will have to try to debug it next time it happens.

**Comment by peerster** [comment]
I think our issue is that the tunnel is started somewhere else, causing this to happen with the tunnel started by Zalenium:

```
$ cat logs/browserstack-stdout.log
BrowserStackLocal v7.0

Setting output as verbose
You can now access your local server(s) in our remote browser.


Connecting to BrowserStack using WebSocket protocol...
Platform supports WebSocket connections.


Connecting to BrowserStack using WebSocket protocol...
Platform supports WebSocket connections.


Connecting to BrowserStack using WebSocket protocol...
Platform supports WebSocket connections.


Connecting to BrowserStack using WebSocket protocol...
Platform supports WebSocket connections.

Press Ctrl-C to exit



Multiple binaries spawned with same configuration. Closing older one.
```

So that's basically the reason for the tunnel to stop working.

**Comment by peerster** [comment]
We have solved the tunnel issue by using a separate container for it instead. This way if the tunnel for some reason dies openshift will restart the container, which is exactly what we want.

Regarding the error of fetching the json session:
https://github.com/zalando/zalenium/blob/a3b06b2782763b08534c789ac148bdc29d3e0322/src/main/java/de/zalando/ep/zalenium/proxy/BrowserStackRemoteProxy.java#L85
`seleniumSessionId` is empty for some reason. Probably due to an earlier problem?

@diemol I guess we could close this issue, and I will open a new one when I have more details

**Comment by diemol** [comment]
Thanks for all the feedback @peerster, so it just seemed a matter of keeping the tunnel alive. 
What is strange for me is how the seleniumSessionId appears empty... 

Anyway, I will close the issue and if something comes up, please reopen or start a new one.

**Comment by LKay** [comment]
I have the same problem. BrowserStack tunnel is opened but Zalenium fails to run any tests and returns:`ERROR: [browserstack.local] is set to true but local testing through BrowserStack is not connected.`

I noticed the same messages, when session Id is empty and some fetches with errors: `java.io.FileNotFoundException: https://www.browserstack.com/automate/sessions/.json`

Has this been solved somehow?
