### ISSUE TITLE
Privileged mode off

### ISSUE THREAD

**Issue by gpapadakis** [zalando/zalenium#455]
Hi all,

we are using a vm that we can not have started zalenium in privileged mode as userns host is not supported from spotify. Can we have this configurable? https://github.com/zalando/zalenium/blob/e861ed5874ba505753dc5bc65bc371f7f5b2df37/src/main/java/de/zalando/ep/zalenium/container/DockerContainerClient.java#L223

**Comment by diemol** [comment]
Hi @gpapadakis,

I think you are right, I thought we were grabbing that from the startup parameters. We'll look into that.

Thanks for reporting it. 

PS: What do you mean by "zalenium in privileged mode as userns host is not supported from spotify"?

**Comment by gpapadakis** [comment]
Running the container with privileged mode then messes up the ownership of certain files like sudo so it is complicated to make work. So if we switch off the privileged mode and get them from environment it would be great,

**Comment by hdimitriou** [comment]
> PS: What do you mean by "zalenium in privileged mode as userns host is not supported from spotify"?
So the issues we are facing are multiple.
We are using user namespaces so we need '--userns=host' to apply '--privileged' in zalenium container, however this messes up /usr/bin/sudo and other files permissions and requires handling to work. 

Then zalenium tries to start containers with '--privileged' without having the option to set it and without having the option to use '--userns=host'. What gpapadakis says is that 'com.spotify.docker.client.messages.HostConfig;' that you use, does not have userns as an available option, so you can't add that and the only option is to disable '--privileged'.

**Comment by diemol** [comment]
Yes, that is correct, we suggest to run Zalenium as privileged when possible. Of course this should be configurable, and somehow we missed that when creating the elgalu/selenium containers.

We just made a change to fix that, and we should release it in 1-2 days.

**Comment by diemol** [comment]
Hi, this was just released, please pull the most recent images
https://github.com/zalando/zalenium/releases/tag/3.10.0c

I'll close this issue but if you find any problems, don't doubt to comment and reopen please.
