### ISSUE TITLE
Session terminated due to ORPHAN

### ISSUE THREAD

**Issue by gpapadakis** [zalando/zalenium#469]
Zalenium Image Version(s):  3.10.0b
OS: Ubuntu Linux
Docker Command to start Zalenium:  docker run -d --rm --name zalenium -p 4444:4444 -v /var/run/docker-ci.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged --userns=host docker-registry:41238/ci/zalenium:3.10.0b --desiredContainers 20 --maxDockerSeleniumContainers 20

We are running up to 10 concurrent tests and the issue observed is that some tests were broken in execution due to the exception below:
```
org.openqa.selenium.WebDriverException: 
05:13:05 Session [fed77ca0108e64c9013fbe4754a53acc] was terminated due to ORPHAN
05:13:05 Command duration or timeout: 0 milliseconds
05:13:05 Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
05:13:05 System info: host: 'qa22.atypon.com', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.0-4-amd64', java.version: '1.8.0_112'
05:13:05 Driver info: org.openqa.selenium.remote.RemoteWebDriver
05:13:05 Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.36.540471 (9c759b81a907e7..., userDataDir: /tmp/.org.chromium.Chromium...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 65.0.3325.146, webStorageEnabled: true, webdriver.remote.sessionid: fed77ca0108e64c9013fbe4754a...}
05:13:05 Session ID: fed77ca0108e64c9013fbe4754a53acc
05:13:05 Caused by: org.openqa.grid.common.exception.GridException: Session [fed77ca0108e64c9013fbe4754a53acc] was terminated due to ORPHAN
```

**Comment by gpapadakis** [comment]
It may occur the case that we spawn a session that is idle for a couple of minutes (1-2) and then do actions to the session. So can we configure timeout for idle sessions?

**Comment by gpapadakis** [comment]
In official Selenium Docker nodes were created with the above jvm options: SE_OPTS="-timeout=86400 -browserTimeout=86400" that may is the case for this issue. Is there a way to configure them in Zalenium @diemol ?? Thanks for assist

**Comment by diemol** [comment]
Hi @gpapadakis,

That looks like a timeout, Zalenium ends inactive sessions when they reach 90 seconds (default value). This can be configured via a capability, see https://zalando.github.io/zalenium/#usage > Idle Timeout.

Then you can set it for, e.g., 300 seconds and it should work fine.

**Comment by gpapadakis** [comment]
Thanks for this i will test it ASAP

Στις 8 Μαρ 2018 10:35, ο χρήστης "Diego Molina" <notifications@github.com>
έγραψε:

**Comment by diemol** [comment]
Hi @gpapadakis, I'll close this issue due inactivity, if you have any issues with this, please reopen and let us know how we can help.

**Comment by jsellers180** [comment]
> Hi @gpapadakis,
> 
> That looks like a timeout, Zalenium ends inactive sessions when they reach 90 seconds (default value). This can be configured via a capability, see https://zalando.github.io/zalenium/#usage > Idle Timeout.
> 
> Then you can set it for, e.g., 300 seconds and it should work fine.

Does this flag still exist? I'm missing it on the documentation

**Comment by diemol** [comment]
Yes, it does.

**Comment by diemol** [comment]
Just check for "idle timeout" in the docs.

**Comment by vasdesai** [comment]
@diemol 

I am using Idle Timeout in my desired capabilities but still getting same error.
I have given 600 Sec as Idle timeout

**Comment by Narenqa** [comment]
Issue still happens "unknown error: Session [6827a391379c90bb242ba77e955eaf25] was terminated due to ORPHAN"
This is my Openshift zalenium kubernetes configuration can some one suggest me:

env:
            - name: SEND_ANONYMOUS_USAGE_INFO
              value: 'false'
            - name: LOG_LEVEL
              value: DEBUG
            - name: JAVA_OPTS
              value: '-Xms2048m -Xmx2048m'
            - name: ZALENIUM_KUBERNETES_CPU_REQUEST
              value: 250m
            - name: ZALENIUM_KUBERNETES_CPU_LIMIT
              value: 500m
            - name: ZALENIUM_KUBERNETES_MEMORY_REQUEST
              value: 500Mi
            - name: ZALENIUM_KUBERNETES_MEMORY_LIMIT
              value: 1Gi
            - name: OVERRIDE_WAIT_TIME
              value: 5m
            - name: TZ
              value: Asia/Dubai
            - name: ZALENIUM_TZ
              value: Asia/Dubai
            - name: ZALENIUM_CONTAINER_NAME
              value: node
            - name: DEFAULT_ZALENIUM_CONTAINER_NAME
              value: node
            - name: SE_OPTS
              value: '-browserTimeout 9000 -timeout 9000'
            - name: NEW_SESSION_WAIT_TIMEOUT
              value: '600000'
            - name: SEL_BROWSER_TIMEOUT_SECS
              value: '160000'
            - name: idleTimeout
              value: '9000'
          image: 'docker-registry.default.svc:5000/tools-selenium/zalenium:latest'
