### ISSUE TITLE
Session [(null externalkey)]

### ISSUE THREAD

**Issue by xdavidoff** [zalando/zalenium#470]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  latest
Docker Version:  17.12.1-ce
docker-compose, version:  1.19.0
OS: 
VirtualBox with last ubuntu
Docker Command to start Zalenium:  
        command: >
            start --desiredContainers 2
                  --maxDockerSeleniumContainers 8
                  --screenWidth 800 --screenHeight 600
                  --timeZone "Europe/Berlin"
                  --videoRecordingEnabled true
                  --sauceLabsEnabled false
                  --browserStackEnabled false
                  --testingBotEnabled false
                  --startTunnel false
        environment:
          - HOST_UID
          - HOST_GID
          - SAUCE_USERNAME
          - SAUCE_ACCESS_KEY
          - BROWSER_STACK_USER
          - BROWSER_STACK_KEY
          - TESTINGBOT_KEY
          - TESTINGBOT_SECRET
          **- SE_OPTS=-enablePassThrough false** (i try with or without this argument)

## Actual Behavior -
_This is my acceptance test_
`<?php
// @group Login
$I = new SeleniumTester($scenario);
$I->wantTo('Nalogovat do Adminu');
$I->amOnPage('/prihlaseni/');
$I->fillField('login', 'neco');
$I->fillField('password', 'neco');
$I->click('_submit');
$I->seeCurrentURLEquals('/core/prihlaseni/autentizace');
`
_This is my yml setup_
`actor: SeleniumTester
modules:
    enabled:
      - WebDriver:
          url: http://webserver
          browser: chrome
          host: zalenium
          port: 4444
      - \Helper\Selenium`

If i start test with browser **firefox**
Have this error
 Session [(null externalkey)] not available and is not among the last 1000 terminated sessions.  
  Active sessions are[ext. key 478b9497-e06e-4078-ad7a-632a2274a8b1]

**Comment by diemol** [comment]
Hi @xdavidoff,

That is an issue with the PHP bindings, check https://github.com/zalando/zalenium/issues/415

The thing is that it is not possible to set that flag anymore, it was removed in Selenium 3.9.1 (I think), because people were just using `enablePassThrough` and not reporting bugs to Firefox.

So, yes... Things need to be solved in the PHP bindings. This is a current issue with any type of Selenium Grid using the latest versions.

**Comment by diemol** [comment]
I'll close this issue due to lack of inactivity and since the issue comes from the PHP bindings, if we can do something to help, please let us know.
