### ISSUE TITLE
Record on demand

### ISSUE THREAD

**Issue by gpapadakis** [zalando/zalenium#471]
Zalenium Image Version(s): 3.10.0b

An enhancement that would be great for us is to start /stop video recording on demand just like in elgalu selenium with docker commands: docker exec grid start-video/stop-video. The case for us is that we wants to limit the amount of records to the failed scenarios or start recording after a remote session is initialized on demand. Is this doable @diemol?

**Comment by diemol** [comment]
Zalenium starts recording when the session starts, and stops when the session is deleted or the test times out. 

If what you want to achieve is to only keep the videos of failed tests, then check the docs where you can configure that (`--keepOnlyFailedTests`, plus reporting the test status).

**Comment by gpapadakis** [comment]
In our case the session that will start it may contain a lot of tests how you can keep only the failed one that is in the same recorded file?

**Comment by diemol** [comment]
Ah ok, in that case then it is not possible. In general the idea is to run one test per session. But seems that your use case is different. Sadly it sees that it would not work exactly the way you want it to, then having those seconds at the beginning of the video.

**Comment by diemol** [comment]
Hi @gpapadakis, I'll close this issue due inactivity, if you have any issues with this, please reopen and let us know how we can help.
