### ISSUE TITLE
Show test name in live preview

### ISSUE THREAD

**Issue by ryudice** [zalando/zalenium#48]
Would it be possible to show the currently executing test name in the live preview instead of "DockerSeleniumRemoteProxy"?

![image](https://cloud.githubusercontent.com/assets/125211/21626793/ef2ee19a-d1d8-11e6-95d6-847615583b99.png)

**Comment by diemol** [comment]
This is a good idea! 
Let us check it, and see when we can find some time to find a way to implement it.

We are open to any suggestions of course :blush:

**Comment by diemol** [comment]
Hi @ryudice,

We recently released a new version with this feature implemente, please see usage [here](https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#live-preview) 

Would be cool if we can get some feedback.

**Comment by ryudice** [comment]
Working good, sorry for the late feedback, was away for some time. Thanks a lot for your help.

**Comment by diemol** [comment]
Cool, thanks for the feedback! 
Maybe you can also check #49?

**Comment by radulucian** [comment]
Even if it's 1 year late, awesome work guys, much appreciated!

**Comment by diemol** [comment]
Thanks for the kind words @radulucian!
