### ISSUE TITLE
Test name in dashboard

### ISSUE THREAD

**Issue by asuvorkov** [zalando/zalenium#480]
## Expected Behavior -
Enable to set a test name in dashboard for better navigation in the list of videos

## Actual Behavior -
Random test names in dashboard
![asdfadfg](https://user-images.githubusercontent.com/28843523/37347947-405b4784-26d3-11e8-8e95-a26c1363d026.PNG)

**Comment by diemol** [comment]
Hi @asuvorkov,

Yes, that is possible, you just need to pass the test name in the desired capabilities. From the docs, usage section (https://zalando.github.io/zalenium/#usage), code example in Java:

```java
    DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
    desiredCapabilities.setCapability(CapabilityType.BROWSER_NAME, BrowserType.FIREFOX);
    desiredCapabilities.setCapability(CapabilityType.PLATFORM_NAME, Platform.LINUX);
    desiredCapabilities.setCapability("name", "myTestName");
```
 

Give it a try and let us know how it went.

**Comment by asuvorkov** [comment]
Hi @diemol,

it doesn't work for me. My test class has folowing structure

```
@RunWith(SerenityRunner.class)
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class LoginLogoutTest {

    @Managed
    WebDriver driver;

    @Steps LoginSteps loginSteps;
    @Steps LogoutSteps logoutSteps;

    @Test
    public void userLogsIn() {
        DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
        desiredCapabilities.setCapability("name", "userLogsIn");

        loginSteps.inputsUserName(USERNAME);
        loginSteps.inputsPassword(USER_PASSWORD);
        loginSteps.clicksOnLoginButton();
    }

    @Test
    public void userLogsInAndLogsOut() {
        loginSteps.inputsUserName(USERNAME);
        loginSteps.inputsPassword(USER_PASSWORD);
        loginSteps.clicksOnLoginButton();
        logoutSteps.logsOutFromPage();
    }
}
```

**Comment by iMbaundso** [comment]
Hi @asuvorkov,

I'm not that familiar with Serenity but I guess setting the desired capabilities inside the test as you do it here will have no effect - you would need to use a custom driver to do this.

http://thucydides.info/docs/serenity-staging/#_advanced_webdriver_integration

Btw. Zalenium logs pretty well all incoming requests including their capabilities.

**Comment by diemol** [comment]
Exactly, thanks @iMbaundso, you just wrote what I had in mind.

@asuvorkov please check the link above to create a custom driver in Serenity, so you can send the test name through the capabilities.

I'll keep this issue open for a while in case something else needs to be discussed.

**Comment by diemol** [comment]
Closing as there was no more activity in the issue.

**Comment by asuvorkov** [comment]
Hi @diemol,

I'm runnig a bunch of tests and would give for every test an unique name. Currently I can give a name via
  
`DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
desiredCapabilities.setCapability(CapabilityType.BROWSER_NAME, BrowserType.FIREFOX);
desiredCapabilities.setCapability(CapabilityType.PLATFORM_NAME, Platform.LINUX);
desiredCapabilities.setCapability("name", "myTestName");`.

But it sets the same name for every test. I would like to give a different name for every test.
 Is it possible to give a different name for every test I'm running as a bunch of tests?

![image](https://user-images.githubusercontent.com/28843523/38568471-05de8900-3ce9-11e8-8614-8abdf96bdd5d.png)

**Comment by Pratikck12** [comment]
Hi, Same problem is there for me. Same test name is setting up to all test cases from desiredCapabilities.setCapability("name", "justName");. How we can set it unique name to test cases?

**Comment by diemol** [comment]
@asuvorkov @Pratikck12 of course, just set a different name per test, it is all on the client side, Zalenium just displays whatever is sent in the "name" capability for each test.

**Comment by asuvorkov** [comment]
@Pratikck12 @diemol 

I have solved my problem with this class

```
import net.thucydides.core.fixtureservices.FixtureService;
import org.openqa.selenium.remote.DesiredCapabilities;

public class ZaleniumFixtureService implements FixtureService {
    private static volatile String currentTestName;

    public static void setCurrentTestName(String currentTestName) {
        ZaleniumFixtureService.currentTestName = currentTestName;
    }

    @Override
    public void setup() {
        //nothing to do here
    }

    @Override
    public void shutdown() {
        //nothing to do here
    }

    @Override
    public void addCapabilitiesTo(DesiredCapabilities desiredCapabilities) {
        if (currentTestName != null) {
            desiredCapabilities.setCapability("name", currentTestName);
        }
    }
}
```

For every test will be set automatically unique name. For me works well.

**Comment by Pratikck12** [comment]
Actually, I want the names which I have given to classes(Like, loginTest, signUpTest etc.). Suppose, I have a test suite contains 10 test scripts(Classes) and if I run a suite or individual test classes then whatever names I have given to the classes that should display on Zalenium dashboard.

**Comment by Pratikck12** [comment]
Another thing is that currently on zalenium dashboard shows the test cases status as completed even if its failed. How to show PASS/FAIL status on zalenium dashboard for test cases?

**Comment by saftron** [comment]
> @Pratikck12 @diemol
> 
> I have solved my problem with this class
> 
> ```
> import net.thucydides.core.fixtureservices.FixtureService;
> import org.openqa.selenium.remote.DesiredCapabilities;
> 
> public class ZaleniumFixtureService implements FixtureService {
>     private static volatile String currentTestName;
> 
>     public static void setCurrentTestName(String currentTestName) {
>         ZaleniumFixtureService.currentTestName = currentTestName;
>     }
> 
>     @Override
>     public void setup() {
>         //nothing to do here
>     }
> 
>     @Override
>     public void shutdown() {
>         //nothing to do here
>     }
> 
>     @Override
>     public void addCapabilitiesTo(DesiredCapabilities desiredCapabilities) {
>         if (currentTestName != null) {
>             desiredCapabilities.setCapability("name", currentTestName);
>         }
>     }
> }
> ```
> For every test will be set automatically unique name. For me works well.

Shall I implement this class for Cucumber BDD (Java) as well ?

**Comment by akshattambe** [comment]
> @asuvorkov @Pratikck12 of course, just set a different name per test, it is all on the client side, Zalenium just displays whatever is sent in the "name" capability for each test.

Hi, I am using Cucumber for my Test automation and I feel the Scenario names are the one that should be appearing on the dashboard. How can I do it? Can you please suggest.

**Comment by xparpx** [comment]
Hello,

I'm using java script with webdriverIO and Zalenium.
Do you know where I should set test "name" for each test.
I'm trying do this inside before method:
`describe('Login functionality test suite', () => {
    before('setup', () => {
        browser.capabilities.name = 'LOGIN TEST - SUCCESS';`

![image](https://user-images.githubusercontent.com/11421732/53586688-9d27e180-3b80-11e9-9ac6-c5ab6a2e40f6.png)

Thanks!

**Comment by nareshnayini** [comment]
> Hello,
> 
> I'm using java script with webdriverIO and Zalenium.
> Do you know where I should set test "name" for each test.
> I'm trying do this inside before method:
> `describe('Login functionality test suite', () => { before('setup', () => { browser.capabilities.name = 'LOGIN TEST - SUCCESS';`
> 
> ![image](https://user-images.githubusercontent.com/11421732/53586688-9d27e180-3b80-11e9-9ac6-c5ab6a2e40f6.png)
> 
> Thanks!

@xparpx Hey, I have the same problem. Did you find any solution for this ?

**Comment by xparpx** [comment]
> > Hello,
> > I'm using java script with webdriverIO and Zalenium.
> > Do you know where I should set test "name" for each test.
> > I'm trying do this inside before method:
> > `describe('Login functionality test suite', () => { before('setup', () => { browser.capabilities.name = 'LOGIN TEST - SUCCESS';`
> > ![image](https://user-images.githubusercontent.com/11421732/53586688-9d27e180-3b80-11e9-9ac6-c5ab6a2e40f6.png)
> > Thanks!
> 
> @xparpx Hey, I have the same problem. Did you find any solution for this ?

Yes!! :)

You should do this in your wdio.conf.js on beforeSession function:

`beforeSession: function beforeSession(config, capabilities, specs) {
    capabilities['zal:name'] = 'My test name';
}`

In my case, I use a regex to replace the file name to use as the name of my test:

`beforeSession: function beforeSession(config, capabilities, specs) {
    capabilities['zal:name'] = specs.toString().replace(/.*\/test\/specs\//gi, '');
}`

**Comment by enedelina** [comment]
Hi guys, 
I'm using java, junit and Zalenium. Can you help me to set test name for each test case to be visible in Zalenium dashboard. I saw the solutions that has been provided by @asuvorkov , but desn't work for me. I'm trying the below code indide TestBase class.  


    @Rule
    public TestName testName = new TestName() {

        private String name;
        @Override
        protected void starting(Description description) {

            this.name = description.getMethodName();
            DesiredCapabilities capabilities =  DesiredCapabilities.chrome();
            capabilities.setCapability("name", name);

        }

    };



@Pratikck12 Did you solve it?

**Comment by srikanthvallapuri** [comment]
am stil not able to get teh test name in teh dashboard, doesn anyone has sample wdio.conf.js for adding test name
