### ISSUE TITLE
Zalenium High-Availability/Cluster Kubernetes Mode

### ISSUE THREAD

**Issue by pearj** [zalando/zalenium#484]
In response to #441 and also some discussions on the slack channel.  I've been thinking about how to make zalenium operate correctly in high-availability mode.  By that, I mean that you can run multiple replicas of zalenium pods and that they will share the pool of selenium pods, and even try to rehydrate test sessions into a different zalenium pod in the event of a zalenium pod going down.

These are my thoughts so far.

## Registration

Change the way that the registration process works.  Currently, registration works like this: Zalenium creates a selenium pod with an environment variable that tells it to register at the zalenium IP address.  This means the selenium pod can only ever be connected to one zalenium pod at a time.

I propose to switch the selenium pod mode from "node" (which means register with a grid), to "hub" (which means it won't register itself with any zalenium pod). 

I will also add a readiness health check so that we know when the selenium pod is ready to use.  Maybe something like `curl -s http://localhost:24444/wd/hub/status | jq .value.ready | grep true`, although the health check might need to wait until the chrome and firefox servers have registered.

Then I'll have the KubernetesClient running a watch on all the selenium pods, as soon as the health check passes, each zalenium pod will automatically register the selenium pod.

## Choosing an available Selenium Pod

One obvious problem with sharing selenium pods between multiple zalenium pods is that they might compete for the same selenium pod.  To handle this, we'd need a locking mechanism to ensure that only one selenium pod is used for a test session at one time.  Fortunately, kubernetes can handle this for us very easily.  Basically, when we want to use a selenium pod we'd first try to claim it by adding an annotation/label to the pod with the hostname of the zalenium pod.  If that request succeeds then that means there was no resource contention, if it fails with an optimistic lock error then that pod has been used by another zalenium pod, so it should try a different selenium pod or start another one.

For detail on this search for "read-then-write" in this kubernetes api doc:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#resource-operations

## Resuming a test on a different Zalenium Pod

It should be possible to resume a test session on a different zalenium pod if we store enough of the test session details on the pod itself, ie the external session key, and any other relevant things, desired capabilities maybe?

Basically, when a request comes in for an existing session and there is no record of that session in the current zalenium node, it could query the kubernetes API for that external session key, and then recreate the necessary Java objects, and then the test should, in theory, continue on as normal.

Of course, if zalenium is terminated mid-request, then the client will probably fail and the test will be lost, but if zalenium has a graceful shutdown, it may transition to another zalenium pod without the client noticing. 

Rehydrating test sessions could be done in this method: `de.zalando.ep.zalenium.registry.ZaleniumRegistry.getSession(ExternalSessionKey)`

## Cleaning up dead test session and other background processes

There are a number of scheduled threads, that clean up dead sessions and other things, these would have to be modified to be cluster aware, but I don't imagine it'd be especially difficult.

**Comment by peerster** [comment]
This all sounds awesome to me 👍 . I'm happy to help with testing and supporting this change in any way I can

**Comment by peerster** [comment]
Maybe another issue further down the road, but how would the live page work when having more than one replica? Also the dashboard is another question.

**Comment by pearj** [comment]
@peerster The dashboard would still work because all replicas would register all the proxies, due to registration happening by a kubernetes watch instead of the selenium nodes actively registering with the zalenium grid. 

Alternatively, if making each zalenium register another zalenium’s selenium’s pods doesn’t seem like a good idea. The dashboard could simply be backed by a kubernetes watch instead of the registry. That would be another way to show all selenium pods regardless of who “owns” them.

**Comment by diemol** [comment]
Moving this one to #654, to have a cleaner list of issues and have a central point for people to look at.
