### ISSUE TITLE
Group live previews

### ISSUE THREAD

**Issue by ryudice** [zalando/zalenium#49]
Hi,
I have a use case in which more than one developer is using the same Zalenium instance to run the tests from his computer, thus it is difficult to tell which live preview belongs to the tests they are running.

Would it be possible to group the live preview containers by a customer parameter sent in the driver capabilities? Something like machine name, so that they can easily tell which current executing tests belong to them.

**Comment by diemol** [comment]
We were thinking about something similar because an internal team has that scenario.

After finishing the current feature we are doing, we will check this.

**Comment by LappleApple** [comment]
Hi @ryudice -- would you like to help on this issue by contributing?

**Comment by diemol** [comment]
Hi @ryudice,

We recently released a new version with this feature implemente, please see usage [here](https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#live-preview) 

Would be cool if we can get some feedback.

**Comment by ryudice** [comment]
Hi @diemol,
I will test it in the next few days, I was away.

Thanks a lot for it.

**Comment by diemol** [comment]
I'll close this issue due to inactivity, please feel free to reopen or comment if something does not work as expected.
