### ISSUE TITLE
Can't choose chrome's language 

### ISSUE THREAD

**Issue by mblanloeil** [zalando/zalenium#494]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
"dosel/zalenium:latest"
If using docker-compose, version:  

OS: 

Docker Command to start Zalenium:  

version: '2'

services:
  
  zalenium:
          image: "dosel/zalenium:latest"
          container_name: zalenium
          hostname: zalenium
          tty: true
          volumes:
            - /tmp/videos:/home/seluser/videos
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
          ports:
            - 4444:4444
          extra_hosts:
                - "myapp.mydomain.fr:172.25.0.10"
          command: >
            start --desiredContainers 2
                  --maxDockerSeleniumContainers 8
                  --screenWidth 1680 --screenHeight 1050
                  --timeZone "Europe/Paris"
                  --videoRecordingEnabled true
                  --sauceLabsEnabled false
                  --browserStackEnabled false
                  --testingBotEnabled false
                  --startTunnel false
          environment:
            - HOST_UID
            - HOST_GID
            - SAUCE_USERNAME
            - SAUCE_ACCESS_KEY
            - BROWSER_STACK_USER
            - BROWSER_STACK_KEY
            - TESTINGBOT_KEY
            - TESTINGBOT_SECRET
            - LANG=fr_FR.UTF-8
            - LANGUAGE=fr_FR.UTF-8
            - LC_ALL=fr_FR.UTF-8
          networks:
              mynet:
                ipv4_address: 172.25.0.15

I set :
chromeOptions.addArguments("lang=fr_FR");
capability.setCapability(ChromeOptions.CAPABILITY, chromeOptions);
before invoke webdrvier : 
new RemoteWebDriver(new URL(this.hubUrl), capability); 

My browser is always in english and not take arguement "lang=fr" 

Thank's for you help and sorry for by bad english :)

**Comment by diemol** [comment]
Hi @mblanloeil,

Don't worry, your English is great! :)

About choosing the language in Chrome, let us check. Chrome in the latest releases have made some changes and maybe this also did. 

Perhaps @elgalu can have a look as well?

**Comment by luisxiaomai** [comment]
I also need help on how to specify chrome language in browser level or container level because of the test target maybe not in English version.

**Comment by diemol** [comment]
Hi @mblanloeil,

Sorry for the delay, Easter break :)

I tried to set the language through the locale "fr_FR" and it worked for me, here is the code and the screenshots:

```java
    public void simpleGridTest() throws MalformedURLException, InterruptedException {
        URL gridUrl = new URL("http://localhost:4444/wd/hub");

        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.addArguments("start-maximized");
        chromeOptions.addArguments("lang=fr_FR");
        DesiredCapabilities desiredCapabilities = new DesiredCapabilities(chromeOptions);

        WebDriver webDriver = new RemoteWebDriver(gridUrl, desiredCapabilities);

        webDriver.get("https://www.github.com");

        // Sleep to go and see that the browser is in the desired language
        Thread.sleep(45000);

        Assert.assertEquals(webDriver.getTitle(), "The world's leading software development platform · GitHub",
                "Title was not the expected one.");

        webDriver.quit();
    }
``` 

![image](https://user-images.githubusercontent.com/5992658/38177095-5047c974-35fb-11e8-8b38-b86843181877.png)
![image](https://user-images.githubusercontent.com/5992658/38177105-76915dd4-35fb-11e8-9afb-c0192e159d96.png)

Could you please check again?

**Comment by mblanloeil** [comment]
Hi, 
Thanks for your answer, I tried your code but it's didn't compile with my version of selenium (3.4.0) . 
I upgrade selenium to 3.4.11 and it's work, the browser's language si french !  so the bug it's due to the selenium's version and not zalenium. 

You can close this ticket, thank's a lot for your investigation and your time !

**Comment by diemol** [comment]
Glad to know it works!
