### ISSUE TITLE
zalenium : save videos for only failed sessions/test case ?

### ISSUE THREAD

**Issue by alnhk** [zalando/zalenium#496]
Hi.,

Is there any option to only keep the videos for failed sessions/failed test case execution. Keeping all videos for all sessions consumes too much space., however to save the effort on looking up, can only video for failed test case be kept ?

Thnx

**Comment by matthew-horrocks** [comment]
You probably want to use --keepOnlyFailedTests

It's documented in the "More Configuration Parameters" section at https://zalando.github.io/zalenium/

**Comment by alnhk** [comment]
OK - if i set "--keepOnlyFailedTests true" will only keep recorded video of failed test case/sessions right ?

Please confirm

**Comment by diemol** [comment]
Hi @alnhk

Yes, that is the purpose of that flag. But keep in mind that you need to tell Zalenium if the test passed or failed by sending a cookie (check the "Marking the test as passed or failed" section in the docs).
