### ISSUE TITLE
Zalenium: maximize browser ?

### ISSUE THREAD

**Issue by alnhk** [zalando/zalenium#500]
Zalenium version 3.8.1a

Is there any add on capabilties to maximize the browser (both firefox and chrome) ? We tried using existing selenium code to maximize, yet it's not. Please advice.

**Comment by diemol** [comment]
Hi @alnhk,

Could you please share the code you were using to do that?

**Comment by alnhk** [comment]
@diemol :  this is below piece of code when trying to maximize chrome browser thru zaleneium : 

ChromeOptions options = new ChromeOptions();
options.addArguments("--start-maximized");

**Comment by diemol** [comment]
Sorry for the late reply, it just seems that in the latest ChromeDriver release, it was changed to `start-maximized` (without the `--`).

```java
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.addArguments("start-maximized");
```
