### ISSUE TITLE
Zalenium: windows based ?

### ISSUE THREAD

**Issue by alnhk** [zalando/zalenium#503]
Just like in saucelabs, we notice that there used to be windows based which it is able to spin up on every new session submit and cleans up on every session termination/graceful close.

Is there option for zalenium to support windows based browser ?

**Comment by diemol** [comment]
Hi @alnhk,

No, this is not possible right now because Microsoft has not provided a container with that capability, please see this related issue: https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/214

Closing as there is no action for us now.
