### ISSUE TITLE
container /dev/dm-*  elgalu/selenium base size 25G ?

### ISSUE THREAD

**Issue by alnhk** [zalando/zalenium#505]
Hi.,

After we start zalenium docker which in turns boot up  containers using image name -  elgalu/selenium. Question - how can we increase the default storage size of container - 25G to 50G ?  I tried adding  --storage-opt size=50G , it only increased storage size of zalenium container , however container of elgalu/selenium did not adjust to 50G, still 25G.

Please advice how do we increase ?

**Comment by diemol** [comment]
Hi @alnhk,

No, this was not supported but it just got added. It will be released soon and you'll be able to use it.
