### ISSUE TITLE
Unable to download zalenium image

### ISSUE THREAD

**Issue by kisskool057** [zalando/zalenium#520]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  

Docker Version:  

If using docker-compose, version:  

OS: 

Docker Command to start Zalenium:  

If using Kubernetes, specify your environment, and if relevant your manifests:  

## Expected Behavior -
Download images
## Actual Behavior -
Error response from daemon: Get https://registry-1.docker.io/v2/dosel/zalenium/manifests/latest: unauthorized: incorrect username or password

I'm not able to download the images..Can you please help ?

**Comment by diemol** [comment]
Hi @kisskool057,

That is strange, the images are public. After searching in Google it seems that it is a error on your docker client. Many people suggest that after doing `docker logout` the problem went away. Please give it a try.

**Comment by kisskool057** [comment]
Hi Diemol,
It works fine now after a docker logout/login
thanks a lot !

**Comment by diemol** [comment]
Great!

**Comment by aks0033** [comment]
**Docker Version**: 18.03.1-ce-win65 (17513)
I am also stuck with the same response
I've tried login->pull/logout->pull/again login->pull
![image](https://user-images.githubusercontent.com/22841068/43078939-75aa4e56-8ea9-11e8-8d64-bb9cd8c68ae4.png)

**Comment by pearj** [comment]
Try the above solution and try logging into docker hub.
