### ISSUE TITLE
helm chart deploy not working

### ISSUE THREAD

**Issue by dbwest** [zalando/zalenium#522]
After deploying the helm chart the hub is stable for a short while and then after sending tests to it I get a status of CrashLoopBackOff

**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  

Docker Version:  

If using docker-compose, version:  

OS: 

Docker Command to start Zalenium:  

If using Kubernetes, specify your environment, and if relevant your manifests:

**Comment by diemol** [comment]
Hi @dbwest,

To avoid assuming things, could you please share the commands you used, and the chart you used? (in case you modified something)

**Comment by peerster** [comment]
We're using openshift and not native kuberenetes, but we manage to get our deployment to work without admin of the cluster. We removed one of the permissions in the role that required it and it didn't seemed to be in use anyway

**Comment by diemol** [comment]
Hi @dbwest,

Sorry for replying so late. Did you manage to get it working?
In addition, the latest release has relevant changes where the logic proxies are created changed, and in this should improve things in k8s also, please give it a try.

**Comment by diemol** [comment]
I'll close this issue since we can track progress in #525
