### ISSUE TITLE
We are using Cross Browser Testing - 3rd Party could provider for browsers

### ISSUE THREAD

**Issue by DeChrish** [zalando/zalenium#524]
How to do use it with Zalenium?

**Comment by diemol** [comment]
Hi @DeChrish,

So far we have only integrated Sauce Labs, BrowserStack and TestingBot. I checked Cross Browser Testing, and in theory it should not be that hard to integrate it. 

Right now we don't have so much bandwidth to work on that, and you are the first to ask for it :) Would you like to contribute to Zalenium and add that integration? I could point you to the code bits that would need to be modified and added.

**Comment by DeChrish** [comment]
@diemol Sure i can work on it.

**Comment by diemol** [comment]
Hi @DeChrish,

Sorry for the delay.

You could check how the SauceLabs proxy is created here: https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/proxy/SauceLabsRemoteProxy.java

The integrated cloud providers follow the same pattern, so in theory is is just a matter of adjusting the urls and how the APIs work for Cross Browser Testing.

Thank you very much for showing interest to help!

**Comment by chasecook412** [comment]
@DeChrish I'm an engineer here at CrossBrowserTesting, and I work quite a bit on our automation platform. If there's anything I can do to help contribute to the integration, or any questions you have in regard to our service, let me know. I'd be happy to help.

**Comment by diemol** [comment]
Hi @chasecook412,

Thanks for writing, if you guys are interested to add CrossBrowserTesting as an integration, it is quite simple, in general, the steps would be:

* Follow the same pattern that was used to implement the SauceLabs/BrowserStack/TestingBot classes
* Add the proper bash files to start and stop the tunnel
* Edit the zalenium.sh file to add the checks for the proxy when it starts
* Add the logo so it shows up in the dashboard
* Share with us an API key so it can be used in Travis for continuous testing

The PR doesn't need to be perfect, for example TestingBot sent us a PR to add them as an integration, they did 90% and we just polished it a bit to make it work fine.

Btw: I will close this issue to consolidate all the feature requests. But if some work gets started, we'll reopen the issue.

**Comment by diemol** [comment]
Closing, as it is consolidated in #645
If development starts, we'll reopen the issue.
