### ISSUE TITLE
Need to configure contextPath

### ISSUE THREAD

**Issue by dbwest** [zalando/zalenium#525]
I am in the process of ironing out a helm release of Zalenium to my k8s cluster at work.

It works fine as a NodePort app, but I really need an Ingress for all the convenience that provides. I can't have the URLs I use changing on my and don't really care about having to specify a changing NodePort either.

My cluster admin has told me that part of setting up any particular WebApp with an Ingress on the cluster involves configuring the app.

If this were Grails he used the example of
server:
    contextPath: '/my-path'

How do I do this for Zalenium? (after looking into this it looked like I wanted to configure Jetty using an xml similar to the following:
```
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="contextPath">/zalenium</Set>
</Configure>
```
via https://www.eclipse.org/jetty/documentation/9.3.x/configuring-contexts.html#embedding-web-inf-jetty-web.xml-file
)

My ingress is something like this (I have scrubbed some sensitive company info):

```
{
  "kind": "Ingress",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "zalenium-ing",
    "namespace": "10002-my-app-dev",
    "selfLink": "/apis/extensions/v1beta1/namespaces/10002-my-app-dev/ingresses/zalenium-ing",
    "uid": "asdfgasdg-3daf-11e8-b42f-00215e24b200",
    "resourceVersion": "14462194",
    "generation": 4,
    "creationTimestamp": "2018-04-11T17:42:05Z",
    "annotations": {
      "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"extensions/v1beta1\",\"kind\":\"Ingress\",\"metadata\":{\"annotations\":{\"kubernetes.io/ingress.class\":\"nginx\",\"nginx.ingress.kubernetes.io/rewrite-target\":\"/zalenium\"},\"name\":\"zalenium-ing\",\"namespace\":\"10002-my-app-dev\"},\"spec\":{\"rules\":[{\"host\":\"kubepoc.my_company.com\",\"http\":{\"paths\":[{\"backend\":{\"serviceName\":\"zalenium-grid\",\"servicePort\":4444},\"path\":\"/zalenium/\"}]}}],\"tls\":[{\"hosts\":[\"kubepoc.my_company.com\"],\"secretName\":\"kubepoc-fooby-tls\"}]}}\n",
      "kubernetes.io/ingress.class": "nginx",
      "nginx.ingress.kubernetes.io/rewrite-target": "/zalenium"
    }
  },
  "spec": {
    "tls": [
      {
        "hosts": [
          "kubepoc.my_company.com"
        ],
        "secretName": "kubepoc-ingerss-tls"
      }
    ],
    "rules": [
      {
        "host": "kubepoc.my_company.com",
        "http": {
          "paths": [
            {
              "path": "/zalenium/",
              "backend": {
                "serviceName": "zalenium",
                "servicePort": 4444
              }
            }
          ]
        }
      }
    ]
  },
  "status": {
    "loadBalancer": {
      "ingress": [
        {}
      ]
    }
  }
}
```

**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
3
Docker Version:  
17.09.1-ce, build 19e2cf6
OS: 
Centos7 Nodes for Kubernetes
If using Kubernetes, specify your environment, and if relevant your manifests:  
7 nodes 
~552 GB Ram
~ 32 Cores

## Expected Behavior -
Should See this page
![image](https://user-images.githubusercontent.com/1122691/38756875-f38ebeb2-3f38-11e8-888e-6deb3a605f51.png)

## Actual Behavior -
I see this instead when using the ingress and need to configure the contextPath (per the cluster admin)
![image](https://user-images.githubusercontent.com/1122691/38756946-34d194a8-3f39-11e8-94fc-ce04d030ce0a.png)

**Comment by diemol** [comment]
Hi @dbwest,

Why don't you join https://seleniumhq.herokuapp.com and then the channel #zalenium, where other k8s users can advice you better? I am a bit short of time this week and perhaps you can get a faster answer there.

**Comment by diemol** [comment]
HIi @dbwest,

Are you still having the same issue?

**Comment by pearj** [comment]
@dbwest changing the jetty context is not straightforward because we’re not using a web.xml and the way the selenium guys have embedded jetty means that it doesn’t look for a web.xml. I presume that there would be another programmatic way to achieve it.  But, I think your best bet would be to do some url rewriting inside the nginx . But you might run into edge

**Comment by dbwest** [comment]
I'm still having the same problem. Getting together with the infrastructure guy today. I'll make sure I'm on the slack channel as well and give updates as we go along.

By the way I changed the deploy to do LoadBalancer instead of NodePort. The infrastructure guy will have me change that I'm sure, but it has actually been working to some extent with LoadBalancer set, which is not the default in the helm chart.

**Comment by diemol** [comment]
Closing after the chat in the #zalenium channel at https://seleniumhq.herokuapp.com/

Feel free to open a new issue in case something else pops up.

**Comment by UlaganathanNamachivayam** [comment]
Couldn't find the solution for this issue here and slack as well. Can some one help.

When we add contextpath on k8s ingress its unable to reach {{contextpath}}/dashboard/# as defined in nginx.conf and its throwing 404 error.

**Comment by jibinbabu** [comment]
I have exaclty same issue. When I use ingress context path, there is no hyperlink for "console" as expected. Anyone was able to solve it?
