### ISSUE TITLE
Download video using URL

### ISSUE THREAD

**Issue by ryudice** [zalando/zalenium#528]
Hi,
Is there a way at the moment to download a video from the dashboard using just the URL?

**Comment by peerster** [comment]
You can find out the URL by using "inspect" (chrome), but I guess your looking into have to get it programmatically?

**Comment by ryudice** [comment]
Hi, yes, I mean programmatically.

**Comment by peerster** [comment]
There is no easy way to do this programmatically right now AFAIK.

@diemol I know that you been working on the /dashboard/information page, maybe it can include the URL to the video in it?

**Comment by diemol** [comment]
Hi @ryudice @peerster 

Yes, I am working on it, but the path needs to be changed then, this needs some tweaking still. Also to see if the nginx configuration needs change as well.

**Comment by ryudice** [comment]
Hi, I created #562 which is likely simpler to implement and would fullfil a similar usecase as this.

Extending the webdriver to be able to retrieve the video URL would be ideal but seems very complex to achieve, and also would require users to use a custom webdriver.

I think the project would benefit greatly from having some kind of REST API that you could integrate against. I'm not sure if it fits in your vision of the overall project though.

**Comment by diemol** [comment]
Well, sadly I have not had the time to work more on the information endpoint and we haven't got any PR to improve it.

Nevertheless, I just realised that there is already a way to do this. The information endpoint is located at: http://localhost:4444/dashboard/information, and you'll see a JSON like this:
```
[
{
"seleniumSessionId": "https://www.github.com/ - chrome",
"testName": "https://www.github.com/ - chrome",
"proxyName": "Zalenium",
"browser": "chrome",
"browserVersion": "67.0.3396.62",
"platform": "LINUX",
"fileName": "zalenium_https___www_github_com____chrome_chrome_LINUX_20180602231922371_SUCCESS.mp4",
"fileExtension": ".mp4",
"videoFolderPath": "/home/seluser/videos",
"logsFolderPath": "/home/seluser/videos/logs/zalenium_https___www_github_com____chrome_chrome_LINUX_20180602231922371_SUCCESS",
"testNameNoExtension": "zalenium_https___www_github_com____chrome_chrome_LINUX_20180602231922371_SUCCESS",
"screenDimension": "1920x1080",
"timeZone": "Europe/Berlin",
"build": "",
"testStatus": "TIMEOUT",
"videoRecorded": true
},
{
"seleniumSessionId": "https://www.github.com/ - chrome",
"testName": "https://www.github.com/ - chrome",
"proxyName": "Zalenium",
"browser": "chrome",
"browserVersion": "67.0.3396.62",
"platform": "LINUX",
"fileName": "zalenium_https___www_github_com____chrome_chrome_LINUX_20180602231925484_SUCCESS.mp4",
"fileExtension": ".mp4",
"videoFolderPath": "/home/seluser/videos",
"logsFolderPath": "/home/seluser/videos/logs/zalenium_https___www_github_com____chrome_chrome_LINUX_20180602231925484_SUCCESS",
"testNameNoExtension": "zalenium_https___www_github_com____chrome_chrome_LINUX_20180602231925484_SUCCESS",
"screenDimension": "1920x1080",
"timeZone": "Europe/Berlin",
"build": "",
"testStatus": "TIMEOUT",
"videoRecorded": true
},
{
"seleniumSessionId": "https://www.seleniumconf.com/ - firefox",
"testName": "https://www.seleniumconf.com/ - firefox",
"proxyName": "Zalenium",
"browser": "firefox",
"browserVersion": "60.0.1",
"platform": "LINUX",
"fileName": "zalenium_https___www_seleniumconf_com____firefox_firefox_LINUX_20180602231927607_SUCCESS.mp4",
"fileExtension": ".mp4",
"videoFolderPath": "/home/seluser/videos",
"logsFolderPath": "/home/seluser/videos/logs/zalenium_https___www_seleniumconf_com____firefox_firefox_LINUX_20180602231927607_SUCCESS",
"testNameNoExtension": "zalenium_https___www_seleniumconf_com____firefox_firefox_LINUX_20180602231927607_SUCCESS",
"screenDimension": "1920x1080",
"timeZone": "Europe/Berlin",
"build": "",
"testStatus": "TIMEOUT",
"videoRecorded": true
},
{
"seleniumSessionId": "https://www.seleniumconf.com/ - firefox",
"testName": "https://www.seleniumconf.com/ - firefox",
"proxyName": "Zalenium",
"browser": "firefox",
"browserVersion": "60.0.1",
"platform": "LINUX",
"fileName": "zalenium_https___www_seleniumconf_com____firefox_firefox_LINUX_20180602231927666_SUCCESS.mp4",
"fileExtension": ".mp4",
"videoFolderPath": "/home/seluser/videos",
"logsFolderPath": "/home/seluser/videos/logs/zalenium_https___www_seleniumconf_com____firefox_firefox_LINUX_20180602231927666_SUCCESS",
"testNameNoExtension": "zalenium_https___www_seleniumconf_com____firefox_firefox_LINUX_20180602231927666_SUCCESS",
"screenDimension": "1920x1080",
"timeZone": "Europe/Berlin",
"build": "",
"testStatus": "TIMEOUT",
"videoRecorded": true
}
]
```

From where you can extract the `fileName`.

After that, If I wanted to download the file `zalenium_https___www_github_com____chrome_chrome_LINUX_20180602231922371_SUCCESS.mp4`, I would just need to append it to the dashboard url, and it would look like this:

http://localhost:4444/dashboard/zalenium_https___www_github_com____chrome_chrome_LINUX_20180602231922371_SUCCESS.mp4

So, with a wget or something similar, the video can be downloaded.

I wish there was a nicer way, or to have the url right away in the endpoint, or a most sophisticated endpoint. But with what we have, it is possible to download the video in a programatic way.

I will close the issue since the initial request is being fulfilled.

**Comment by MarianoSalerno** [comment]
@diemol I would like to have an endpoint for the video and another for the logs (while I'm at it I could implement another one that returns all the data that the information endpoint returns but for only one test, or whichever ones you think would be useful to have), could you tell me what changes are needed? If it isn't that hard I'll try to make a PR. 

Besides that I'm not sure which field of the test would serve as an id, how do you think we should specify which test we want?

**Comment by diemol** [comment]
@MarianoSalerno sorry for the late reply, as I mentioned in the previous comment, there is a rough endpoint for the dashboard information, and new endpoint or "subendpoint" of the dashboard could be created following the same principle for videos/logs/etc...

Would be great if a PR comes to improve that.

The id is the seleniumSessionId or the whole file name that is generated when the video file is created.

**Comment by b3ster** [comment]
If someone wants to download the logs/video after each run there is an easy way to do so.
At least if you have integrated zalenium in Jenkins, if you reset the dashboard after each run you can download videos and logs after each Jenkins Job - to access this without any issues, access the files via volume or mount the path to the host.
Docker option: -v /opt/videos:/home/seluser/videos 
This will provide you access to all files, just pickup every new log/video after each run and cleanup, as our zalenium GRID just exists for the time of execution, this works quite will for us :)
