### ISSUE TITLE
http://localhost:4444/dashboard no longer shows dashboard

### ISSUE THREAD

**Issue by FilipB** [zalando/zalenium#530]
Zalenium Image Version(s):  
3.11.0d

## Actual Behavior -
According to documentation http://<host>:4444/dashboard should show the dashboard but it does not. After following commit https://github.com/zalando/zalenium/commit/7669609c371ea6711bbab8d46b66596ae1e5e77b#diff-68c73b5a79443e53542b651429897b70 it's necessary to use a slash http://<host>:4444/dashboard/ to show dashboard.

**Comment by peerster** [comment]
Yeah, kind of duplicate of #353

**Comment by pearj** [comment]
This is fixed by #533

**Comment by diemol** [comment]
Thanks to @pearj, this has been fixed in https://github.com/zalando/zalenium/releases/tag/3.11.0e
