### ISSUE TITLE
Unicode issue �] . While executing selenium test cases in Zalenium containers, I am getting a unicode exception

### ISSUE THREAD

**Issue by Muraligowtham** [zalando/zalenium#545]
Dear Team,
I started the zalenium container using following command.

 docker run --rm --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start --desiredContainers 5 --timeZone EST 
I am executing the test cases in latest docker zalenium version inside a centos machine.

While executing the cases, I am getting an unicode generated in place of ' in the element.getText() selenium methods, So is there a way to change the locale for these containers?

Kindly help me with this

Thanks

**Comment by diemol** [comment]
Hi @Muraligowtham,

Could you please share the test that you are executing to get such exception? The docker-selenium image has a lot of fonts installed to support different languages. It could also be that one font is missing.

We need more details to reproduce the issue and help you.
