### ISSUE TITLE
JavascriptExecutor hangs on BrowserStack when script contains particular character sequence

### ISSUE THREAD

**Issue by anikulin** [zalando/zalenium#546]
Zalenium Image Version(s):  3.11.0
Docker Version:  17.09.1-ce
OS: CentOS Linux 7
Docker Command to start Zalenium:  

```
export BROWSER_STACK_USER=...
export BROWSER_STACK_KEY=...

docker run --rm -d --name zalenium -p 8888:4444 \
      -e BROWSER_STACK_USER -e BROWSER_STACK_KEY \
      -v /tmp/videos:/home/seluser/videos \
      -v /var/run/docker.sock:/var/run/docker.sock \
      --privileged dosel/zalenium start --browserStackEnabled true --startTunnel true --debugEnabled true 
```

Running the following test:
```
public class ScriptTest {
    @Test
    public void zaleniumTest() throws Exception {
        DesiredCapabilities caps = DesiredCapabilities.chrome();
        caps.setVersion("65");
        WebDriver d = new RemoteWebDriver(new URL("http://192.168.1.1:8888/wd/hub"), caps);

        String page = "https://google.com";
        d.get(page);

        String script = "(function() {}());";

        ((JavascriptExecutor) d).executeScript(script);
        
        d.quit();
    }
}
```

## Expected Behavior -
Javascript code should be executed on the page opened in the Chrome on BrowserStack.

## Actual Behavior -
1. Session is forwarded to BS
2. Page is opened in browser
3. Then the executeScript() method hangs indefinitely - no "Run JavaScript" command is being sent to BrowserStack, so it looks like something hangs inside Zalenium.
4. After 90 seconds, BrowserStack terminates the session with "IDLE TIMEOUT" error
5. Test still hangs.

Haven't found anything related in the Zalenium logs.

## Notes
Works fine in local Zalenium chrome node.
Works fine when RemoteWebDriver is requested directly from BrowserStack.
The same issue is reproduced with IE11 on BrowserStack

*Starts to working* fine on BS when the following change is made
```
String script = "(function(){}());"; //removed space
```

**Comment by diemol** [comment]
I'll close this issue since we didn't get more feedback from the OP.
