### ISSUE TITLE
Latest Zalenium failed to start after 2 minutes

### ISSUE THREAD

**Issue by ViLPy** [zalando/zalenium#553]
Zalenium Image Version(s): latest
Docker Version:  18.04.0-ce, 18.05.0-ce-rc1
OS: Ubuntu 18.04
Docker Command to start Zalenium:  
`curl -sSL https://raw.githubusercontent.com/dosel/t/i/p | bash -s start`

## Expected Behavior -
Zalenium started without errors

## Actual Behavior -
```
Checking dependencies... Done Checking dependencies.
latest: Pulling from dosel/zalenium
Digest: sha256:1d9ead62b9993d41b4201b813d0ee9539518eeebcd776bf5a9d4aace463ec069
Status: Image is up to date for dosel/zalenium:latest
latest: Pulling from elgalu/selenium
Digest: sha256:a3de6b760df96e9fb5f46a4f9462cb89773d964c252eff8e95f9d3d94c9b2f29
Status: Image is up to date for elgalu/selenium:latest
Starting Zalenium in docker...
WARN: Sauce Labs will not be enabled because the var $SAUCE_USERNAME is NOT present
WARN: BrowserStack will not be enabled because the var $BROWSER_STACK_USER is NOT present
WARN: Testing Bot will not be enabled because the var $TESTINGBOT_SECRET is NOT present
b4a080043821c37bdc9442f3f98efffd67f6589e31d92fe358df469ffd11cf95
..............................................................
Zalenium failed to start after 2 minutes, failing...
```

Also tested on MacOS Hight Sierra with Docker 18.03.1-ce and same command works fine there, so it looks like that only Linux is broken

**Comment by diemol** [comment]
Hi @ViLPy,

Since the last release, we forgot to adjust the one line script. I just did and it should work again. Please retry.

**Comment by ViLPy** [comment]
Hi @diemol 

Works fine now, thanks a lot!
