### ISSUE TITLE
How to execute the zalenium in multiple machine pointing to the same hub? is there a way?

### ISSUE THREAD

**Issue by Muraligowtham** [zalando/zalenium#554]
Team,
In my scenario, I have two virtual machines, in 1st linux machine, if I start 5 nodes, is it possible to start 5 more nodes in second machine that points to the hub in machine 1 ?

**Comment by pearj** [comment]
You have to be using Kubernetes. It’s the only supported way to scale across more than 1 machine at present. 

I’d recommend OpenShift, but there are lots of Kubernetes flavours out there. 

If you want to use a cloud provider, there are managed kubernetes instances out there so you don’t need to manage your own kubernetes cluster.

**Comment by pearj** [comment]
No response yet. So I presume this is enough information to get you started. Closing.
