### ISSUE TITLE
Organize videos in folders

### ISSUE THREAD

**Issue by ryudice** [zalando/zalenium#562]
It would really help if you could store videos in a folder based on certain variable, this could be the version of the application against which the tests were ran, or you CI build number.

The main usecase of this is just to make videos more accessible to non-tech people. I'm working on uploading the videos to amazon S3 using some scripting and then linking the videos in our reports and this would make much simpler.

Thanks.

**Comment by pearj** [comment]
@ryudice this is already implemented. If you set a test name via a capability then zalenium uses that test name when it creates a folder. I use this concept in Jenkins so I can automatically copy the file after the test completes.

**Comment by diemol** [comment]
Hi @ryudice,

In addition to that, you can pass a capability with a `build` name, and if so, it will be used to create the video name, check the [template](https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/dashboard/TestInformation.java#L13).

With that, it would be quite simple to filter the files you need.

**Comment by pearj** [comment]
The details of how it works is in the doco: https://opensource.zalando.com/zalenium/ click usage and then scroll down for “Test Configuration Options”
