### ISSUE TITLE
Browser proxy issue - Requesting User credentials.

### ISSUE THREAD

**Issue by shiva4983** [zalando/zalenium#564]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
3.11
Docker Version:  
18.03

OS: 
Windows 7
Docker Command to start Zalenium:  
docker run --rm -ti --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /c/Users/tmp/videos:/home/seluser/videos -e "zalenium_http_proxy=http://<username>:<password>@corp_proxy.net:<portno>" -e "zalenium_https_proxy=https://<username>:<password>@corp_proxy.net:<portno>" -e "zalenium_no_proxy= 10.0.0.0/8, *.local, 192.168.99.*, localhost, 127.0.0.1" --privileged dosel/zalenium start 
If using Kubernetes, specify your environment, and if relevant your manifests:  

## Expected Behavior -
Application run in the browser with the proxy username and password provided alone with the proxy url.

## Actual Behavior -
Chrome and Firefox is throwing proxy credentials with popup
![error](https://user-images.githubusercontent.com/5982324/39826604-43805ad0-5383-11e8-85ce-98ba396700c0.png)

**Comment by pearj** [comment]
What are you trying to do exactly? Are you trying to use your corporate proxy for selenium tests? If so, you shouldn’t be setting it on the zalenium container but rather inside as a desired capability inside your selenium tests. Zalenium has no special proxy handling. Just whatever selenium provides.

**Comment by shiva4983** [comment]
Thanks Pearj. That answers my question. I will try it out through selenium test.

**Comment by diemol** [comment]
Hi @shiva4983,

What @pearj mentions is exactly the way to go. When one needs to use a proxy for the test, it should be set in the browser's options when all the capabilities are being created.

I'll close this issue since it is not related to Zalenium.
