### ISSUE TITLE
Append testStatus to end of video fileName

### ISSUE THREAD

**Issue by kendalsickels-wf** [zalando/zalenium#565]
We’re using Zalenium to run our tests and it’s been awesome! However, as our test cases have grown it’s become difficult to parse the large list of video artifacts to find the failure video we might be interested in.  Further complicating the issue is we have targeted retries on test failures so you end up with two video artifacts that are named very similarly.

I recognize that we could just save the failed videos but occasionally it’s nice to go back and watch a passing test (verify a new test is doing what you think or perhaps it’s not immediately apparent why the test is failing for your changes and not someone elses).  

Thoughts on appending the testStatus to the end of the fileName?  This will allow me to organize the video artifacts into separate directories at the completion of the test run.

**Comment by pearj** [comment]
Sounds doable, we’re pretty busy at the moment, but feel free to implement this and send us a PR :)

**Comment by pearj** [comment]
The dashboard knows which videos failed, so right now you could parse the HTML to figure out which videos have failed. It’s not amazing, but it should work.

**Comment by pearj** [comment]
It's pretty easy to build.  If you're building on a docker host, you can simply run `mvn clean package -DskipTests=true -Pbuild-docker-image`. And that should build a docker image for zalenium.

**Comment by kendalsickels-wf** [comment]
I was able to verify this does append the testStatus to the end of the video file using the above build command and shoving the image into our test platform. Below is an tidbit from the logs:

```
36mzalenium-functional-tests_zalenium   |[0m 20:11:39.001 [Terminate Test Session int id: [79cedc5a-8e70-44d5-8826-18b9273b3031] ext id: [daceca3e8e8367a71a7a66fb65c424e6] container: [d9773f256dd3ddc3b6c5eb7a05d7fe662b8de671f4c6fa6674a7742ca83a993c]] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - d9773f256dd3ddc3b6c5eb7a05d7fe662b8de671f4c6fa6674a7742ca83a993c Video file copied to: /home/seluser/videos/zalenium_Doc:_export_test.dart_-_create_document_and_export_:_linuxChrome_chrome_LINUX_20180510201138496_FAILED.mp4
```

**Comment by diemol** [comment]
👍 just checked the code, and looks good! thanks @kendalsickels-wf!

**Comment by kendalsickels-wf** [comment]
https://github.com/zalando/zalenium/pull/569 PR has been opened 👍

**Comment by diemol** [comment]
Relased https://github.com/zalando/zalenium/releases/tag/3.11.0h
Thanks for contributing @kendalsickels-wf!
