### ISSUE TITLE
Service runs out of ports after running for a while

### ISSUE THREAD

**Issue by apechersky** [zalando/zalenium#57]
I've noticed that after running a service for 2-3 days in our high-traffic test environment the service would run of free ports and would be in "zombie" state - it appears alive but no new session can be started.

I traced it to the following area of the code - once the port is allocated it is never released back: 

```
private int findFreePortInRange(int lowerBoundary, int upperBoundary) throws IllegalStateException {
        for (int portNumber = lowerBoundary; portNumber <= upperBoundary; portNumber++) {
               ...
                if (freePort != -1) {
                    allocatedPorts.add(freePort);
                    return freePort;
                }
            }
        }
        throw new IllegalStateException("Could not find a free TCP/IP port to use for docker-selenium");
    }
```
Is this known issue?

The simplest graceful solution would be to use something like CircularFifoQueue<> (Apache Commons Collections 4) instead of ArrayList to hold ports, the most thorough solution is to clean up ports on session end/container cleanup.

**Comment by diemol** [comment]
Hi @apechersky,

No, this is not a know issue but it makes complete sense when you describe your scenario. We didn't think of running Zalenium for several days. Here, we start it before the tests and stop it afterwards, but we have also noticed that people are starting to use it in the same way you do (perhaps with less traffic).

Do you feel like submitting a PR? Or else we can take a look in ~2 weeks.

**Comment by diemol** [comment]
I started to check this since we need to release a bug fix.

I like the idea of the `CircularFifoQueue`, but I don't want to add a new dependency only for this reason. The best solution, as you suggest, is to remove the port from that list during the teardown, but this creates a dependency between the classes.

I will try to find a solution that works without to much hassle, any other ideas are welcome.

**Comment by diemol** [comment]
Hi @apechersky,

We just released Fixed [3.0.1e](https://github.com/zalando/zalenium/releases/tag/3.0.1e) and [2.53.1p](https://github.com/zalando/zalenium/releases/tag/2.53.1p), which should fix the issue.

It was implemented in a simple way and ideally this should cover your scenario.

Please give it a try and let us know.

**Comment by apechersky** [comment]
Thanks a lot! Looks great, trying it out now...

**Comment by diemol** [comment]
I'll close this issue due to inactivity, please feel free to reopen or comment if something does not work as expected.
