### ISSUE TITLE
Adding test name in Robot tests produces jibberish rather than the one provided on capabilities

### ISSUE THREAD

**Issue by sree98** [zalando/zalenium#578]
Zalenium Image Version(s):  
Zalenium Latest
Selenium Latest

Docker Version:  18.03.1-ce,

If using docker-compose, version:  N/A

OS: Ubuntu 16.04

Docker Command to start Zalenium:  Oneliner with timezone as America/New_York and maxDockerSeleniumContainers to 6

If using Kubernetes, specify your environment, and if relevant your manifests:  N/A

## Expected Behavior -
Adding DesieredCapabilties to add test name on Robot Tests using chromeoptions by adding a chrome option and making it a capabiltiy should get the test name to be the one given.
## Actual Behavior -
I am trying to run tests using the Robot Framework on Zalenium. But on the Dashboard the test names are just jibberish. I did see on the usage that you can add DesieredCapabilties using the Java code but since Robot is a keyword driven framework and is based off python I am not able to use that snippet. I did try doing many answers i found stackoverflow and other places and found one answer that looks promissing. Tried that and its still showing jibberish.

Code to open up chrome on Zalenium
```
${chrome options} =	Evaluate	sys.modules['selenium.webdriver'].ChromeOptions()	sys, selenium.webdriver
Call Method	${chromeoptions}	add_argument	"name":'${SUITE_NAME}'
${options}=	Call Method	${chrome_options}	to_capabilities
Create Webdriver	Remote	command_executor=http://localhost:4444/wd/hub	desired_capabilities=${options}
Go To	${url}		
Set Window Size	1920	1080	
```

**Comment by sree98** [comment]
After a lot of googling and trying a bunch of combinations of things it looks like i have found the answer.
You have to first export google options and then get the capabilities and then add the different capabilities you want to that dictionary and use that to open the browser.
**Sample:**
```
[Arguments]    ${url}
${chrome options} =    Evaluate    sys.modules['selenium.webdriver'].ChromeOptions()    sys, selenium.webdriver
${options}=    Call Method    ${chrome options}    to_capabilities
Set To Dictionary    ${options}    name    test
Create Webdriver    Remote    command_executor=http://localhost:4444/wd/hub    desired_capabilities=${options}
Go To    ${url}
```
Sorry for posting this question as an issue.

**Comment by diemol** [comment]
Hi @sree98,

Yes, exactly, that is the issue. I have never used Robot framework, but what I could see is the same, the `name` was being passed as an argument to Chrome instead of being passed as a capability.

Glad you figured it out!

Closing this issue.
