### ISSUE TITLE
Dashboard cant be view when using diff port instead of 4444

### ISSUE THREAD

**Issue by ezwanharun** [zalando/zalenium#581]
Zalenium dashboards cant be view when I started with different port number (eg 4445) instead of 4444 as I try to start multiple container with diff port number. Does the zalenium is only hardcoded to 1 port (4444) and cant be configurable?

## Expected Behavior -
Dashboard able to be view and can see the live functionality

## Actual Behavior -
Dashboard cant be access.

**Comment by peerster** [comment]
@ezwanharun It can indeed. We use for instance port 80 to access all zaleniun endpoints (dashboard, live view etc).

It comes down to how you start and run zalenium. 
That's why the issue template contains stuff like what docker version and if you're using openshift etc. It's hard to help you without that information

**Comment by diemol** [comment]
Hi @ezwanharun,

@peerster is right, many people use a different port for it and so far it works well. Please post more relevant info so we can find a way to help.

**Comment by ezwanharun** [comment]
OS: debian 9.3
docker version : Docker version 17.09.1-ce
Zalenium image version : Think latest since I didnt see it specify any version. 

Start Command :  
sudo docker run --rm -di --name ${bamboo.zaleniumName} -p ${bamboo.zaleniumPort}:${bamboo.zaleniumPort} -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start --maxDockerSeleniumContainers ${bamboo.maxDockerSeleniumContainers} --desiredContainers ${bamboo.desiredContainers} --timeZone "Asia/Singapore" --videoRecordingEnabled ${bamboo.videoRecordingEnabled}


Stop Command : 
 sudo docker stop $(sudo docker ps | grep ${bamboo.zaleniumName} | awk '{print $1}')

**Comment by pearj** [comment]
You have a bug in your start command:

Replace `${bamboo.zaleniumPort}:${bamboo.zaleniumPort}` with `${bamboo.zaleniumPort}:4444`

**Comment by ezwanharun** [comment]
got it..thanks

**Comment by pearj** [comment]
Sounds like this problem is fixed then. Closing. You can reopen if it isn’t resolved.
