### ISSUE TITLE
Zalenium 3.12.0a with elgalu/selenium:3.12.0-p0 

### ISSUE THREAD

**Issue by Deklin** [zalando/zalenium#584]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  

Docker Version:  

If using docker-compose, version:  
1.13.1
OS: 
Centos 7.4
Docker Command to start Zalenium:  

If using Kubernetes, specify your environment, and if relevant your manifests:  
pull images as described

If I switch to zalenium 3.11.0h and elgalu selenium 3.11.0-p15 it works fine.

## Expected Behavior -
The readiness probe on the spawned containers for elgalu/selenium should pass readiness checks.

## Actual Behavior -
Using 3.11.0h and 3.11.0-p15 work fine, just changing the tag to use the latest 3.12.* as described the spawned nodes all fail readiness probes.

**Comment by diemol** [comment]
Hi @Deklin,

What probe were you using?

**Comment by Deklin** [comment]
I didnt add a probe, its being auto added when the nodes are spawned. 3.11 does it too but the probe works properly with 3.11, but fails with 3.12

**Comment by GeorgFleig** [comment]
The probe in question is automatically created by the zalenium pod:
```
        "readinessProbe": {
          "exec": {
            "command": [
              "/bin/sh",
              "-c",
              "curl -s http://localhost:40000/wd/hub/status | jq .value.ready | grep true"
            ]
          }
```
Since selenium:3.12.0-p0 the service being probed does not bind to localhost but to the pod's IP address. Therefore the probe fails.

**Comment by pearj** [comment]
Thanks for the heads up @GeorgFleig, I tried it locally and you're right, it doesn't bind to localhost anymore. I've updated the probe in #589.  We should be able to get a new version out soon.
I guess Selenium 3.12 changed something, as I had a look at the docker selenium start script and it hasn't changed in 8 months.
