### ISSUE TITLE
Running Zalenium as a GitLab service

### ISSUE THREAD

**Issue by degerlac** [zalando/zalenium#585]
I am trying to use Zalenium as a Gitlab service. Essentially I need to start it without the docker.sock volume binding is this possible? Gitlab service documentation, https://docs.gitlab.com/ee/ci/docker/using_docker_images.html Is there a way to set environment variables for volume nappings?

Configuration
Zalenium Image Version(s):  3.11.0h
Docker Version:  
Version 18.03.0-ce-mac60
If using docker-compose, version:  
N/A
OS: 
OSX Sierra

Docker Command to start Zalenium:  
docker run -d --name service-zalenium dosel/zalenium:3.11.0h

## Expected Behavior -
Starts and runs

## Actual Behavior -
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by diemol** [comment]
Hi @degerlac,

Not really, Zalenium needs it to actually create the nodes on demand.  Without it, Zalenium cannot work properly in a docker environment. 

Someone else tried to do the same, and then went the Kubernetes path, but I am not sure if they were able to do it in the end. https://github.com/zalando/zalenium/issues/437

I'll leave this issue open for a while in case you have more comments.

**Comment by iMbaundso** [comment]
Hi all. 

I think in general you should not try to create an 1:1 relation between zalenium and your tests. Zalenium should act standalone executing multiple jobs. Where are your Gitlab jobs running on (Kubernetes, docker-machine, single hosts...)?

**Comment by diemol** [comment]
@iMbaundso it kind of depends, some people create a Zalenium instance in Jenkins before starting their tests and shut it down afterwards. As always, scenarios are different.

In this case, I agree since Zalenium cannot run as a GitLab service, then doing something like what you suggest makes sense.

I'll close this issue since there is no action item for us.

**Comment by degerlac** [comment]
Thanks for the feedback.
