### ISSUE TITLE
Different resolutions for each instance.

### ISSUE THREAD

**Issue by oscarbuho888** [zalando/zalenium#586]
How to run 4 instances of chrome with different resolution each. For example:

Chrome1 - 1200 x 600
Chrome2 - 800 x 600

**Comment by diemol** [comment]
Hi @oscarbuho888,

The most simple way would be to start Zalenium with `--desiredContainers 0` and `--maxTestSessions` to a high number that works for you. After that you just start the tests and pass the `screenResolution` capability to what you wish.

**Comment by oscarbuho888** [comment]
Hi @diemol,

Thanks for your help, I actually found a way to execute it with my protractor tests. Here I leave the protractor.conf. js of my tests.

`multiCapabilities: [
        {
            'name': 'Pruebas e2e Ghost en 1200 x 600',
            'browserName': 'chrome',
            chromeOptions: {args: [ "--disable-gpu", "--window-size=1200x600" ]},
            screenResolution: '1200x600'
        },

        {
            'name': 'Pruebas e2e Ghost en 800 x 600',
            'browserName': 'chrome',
            chromeOptions: {args: [ "--disable-gpu", "--window-size=800x600" ]},
            screenResolution: '800x600'
        },
      ],`
