### ISSUE TITLE
Support for IE

### ISSUE THREAD

**Issue by sai-tirunagiri** [zalando/zalenium#587]
Hi,

This sounds to be more on the enhancement side.

Are we thinking of adding internet explorer node.? is this possible.?

Thanks,
Sai

**Comment by diemol** [comment]
Hi @sai-tirunagiri,

Right now it is not possible, maybe in the future Microsoft will provide an image for that.

Check:

https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/214
https://github.com/zalando/zalenium/issues/503
https://windowsserver.uservoice.com/forums/304624-containers/suggestions/17506354-provide-an-internet-explorer-docker-container-ena
https://github.com/SeleniumHQ/docker-selenium/issues/610

**Comment by Svitskyi** [comment]
https://github.com/aerokube/windows-images

**Comment by Svitskyi** [comment]
Now it is seems to be possible

**Comment by pearj** [comment]
Bundling a full windows virtual machine inside a docker container is cheating a bit, and most likely wouldn't run in all situations, ie I'm sure kubernetes doesn't allow virtualisation out of the box.  It would be much better if there was a native windows docker container instead.  But that doesn't look like it exists yet
