### ISSUE TITLE
Disconnect Timeout error coming for the docker containers in the Zalenium Live Preview

### ISSUE THREAD

**Issue by sayom88** [zalando/zalenium#588]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  

Docker Version:  

If using docker-compose, version:  

OS: Linux

Docker Command to start Zalenium:  
docker run --rm -ti --name zalenium -p 4444:4444 -p 5555:5555 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/videos:/home/seluser/videos \
    --privileged dosel/zalenium start --maxTestSessions 2 --desiredContainers 2 \
    --videoRecordingEnabled false

If using Kubernetes, specify your environment, and if relevant your manifests:  

## Actual Behavior -
After some time intervals, I am getting a Disconnect Timeout error coming for the docker containers in the Zalenium Live Preview screen. How can I get rid of this?
![1ef11bebed26a95c](https://user-images.githubusercontent.com/16284729/40421354-4f1b43de-5e94-11e8-9250-03bd79446eef.jpg)

**Comment by diemol** [comment]
Hi @sayom88,

This is the normal behaviour. In your case, after two tests were executed, the containers are thrown away and new ones are being created. What you see in the live preview is the process where the old ones are disconnecting and if you refresh the page, new ones should pop up.

I'll leave this issue open for a while in case there are more comments,

**Comment by sayom88** [comment]
hi @diemol ,
Thanks for your comments. Now my question is while I am starting Zalenium, is there any way via which I can tell that the nodes/containers which are being created will remain active for a stipulated time duration? I want a node to be created will remain active for a certain timeperiod. Can I do that please?

**Comment by diemol** [comment]
Not really, they are up until the `--maxTestSessions` is reached. If you need them up for a while, just try to use a high number of `--maxTestSessions` and find one that works for you.

I'll close this issue since there is no action item for us.

**Comment by sayom88** [comment]
Thanks for the updates. Yes you can close it now.
