### ISSUE TITLE
Change live preview background image

### ISSUE THREAD

**Issue by sai-tirunagiri** [zalando/zalenium#591]
Hi,

Could someone please help me with some instructions on like, how to change the background image on the noVNC screens (live preview).

Thank you.

**Comment by diemol** [comment]
Hi @sai-tirunagiri,

Which image do you mean exactly?

**Comment by sai-tirunagiri** [comment]
![image](https://user-images.githubusercontent.com/12015596/40447821-6ee9daf6-5ef1-11e8-8357-17a13ec08d5f.png)

The zalenium logo.

**Comment by diemol** [comment]
But why do you want to remove our beautiful logo? 😢 

Well, this is open source and anyone can change it of course... You need to build your own docker-selenium image and replace the Zalenium wallpaper so it gets used in the entry.sh -> https://github.com/elgalu/docker-selenium/blob/master/bin/entry.sh

Afterwards, specify the image you have created when running Zalenium via the `--seleniumImageName` flag. That should be it.

**Comment by sai-tirunagiri** [comment]
@diemol , :) It's beautiful logo indeed.! But, wanted to perform some experiments on this.

I will go ahead and try this. Thank you very much.!

**Comment by diemol** [comment]
Sounds good, post a picture of your experiments :)
And star the projects to support us!
