### ISSUE TITLE
Node container terminate and restart continuously

### ISSUE THREAD

**Issue by shiva4983** [zalando/zalenium#594]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
3.12.0
Docker Version:  
17.09.1-ce

OS: 
Linux
Docker Command to start Zalenium:  
C:\Users\svelusw>docker run --rm -ti --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /c/Users/svelusw/tmp/videos:/home/seluser/videos -e "zalenium_http_proxy=Proxy" -e "zalenium_https_proxy=Proxy" -e "zalenium_no_proxy=localhost, 127.0.0.1" --privileged dosel/zalenium start --screenWidth 1440 --screenHeight 810 --timeZone "America/Montreal" --desiredContainers 3 --maxTestSessions 4 --sendAnonymousUsageInfo false
If using Kubernetes, specify your environment, and if relevant your manifests:  

## Expected Behavior -
Node container shouldn't restart before the test ends
## Actual Behavior -
Node container restarts continuously. 
16:30:34.884 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container zalenium_stefv5 started after 13439.
16:30:35.752 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container zalenium_nisU0G started after 17618.
16:30:36.220 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container zalenium_rlPKdt started after 21481.
16:30:36.252 [Thread-10] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.17.0.4:40001
16:30:36.258 [Thread-12] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.17.0.3:40000
16:30:36.264 [Thread-11] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.17.0.5:40002
16:30:36.271 [Thread-12] INFO  d.z.e.z.proxy.AutoStartProxySet - Registered a container ce51f3d8092f9b94b4c7e6d2c8d31ab3962d18cf4c1fd2dd8a3f838cd112615f http://172.17.0.3:40000.
16:30:36.286 [Thread-10] INFO  d.z.e.z.proxy.AutoStartProxySet - Registered a container 5c01ac1b157478b8db2df77efdf5baade8749c6b3fd604d073e4e5d62c150b1d http://172.17.0.4:40001.
16:30:36.287 [Thread-11] INFO  d.z.e.z.proxy.AutoStartProxySet - Registered a container e16144b54f5c0112b4fc8f7bb17bc6a1d4d8452150ef7c5452f23b302fd3cabc http://172.17.0.5:40002.
16:32:36.194 [AutoStartProxyPoolPoller] INFO  d.z.e.z.c.DockerContainerClient - Container ContainerCreationStatus [isCreated=true, containerName=zalenium_stefv5, containerId=e16144b54f5c0112b4fc8f7bb17bc6a1d4d8452150ef7c5452f23b302fd3cabc, nodePort=40002] not found - it is terminated.
16:32:36.198 [AutoStartProxyPoolPoller] INFO  d.z.e.z.c.DockerContainerClient - Container ContainerCreationStatus [isCreated=true, containerName=zalenium_nisU0G, containerId=5c01ac1b157478b8db2df77efdf5baade8749c6b3fd604d073e4e5d62c150b1d, nodePort=40001] not found - it is terminated.
16:32:36.200 [AutoStartProxyPoolPoller] INFO  d.z.e.z.c.DockerContainerClient - Container ContainerCreationStatus [isCreated=true, containerName=zalenium_rlPKdt, containerId=ce51f3d8092f9b94b4c7e6d2c8d31ab3962d18cf4c1fd2dd8a3f838cd112615f, nodePort=40000] not found - it is terminated.
16:32:36.201 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container ContainerCreationStatus [isCreated=true, containerName=zalenium_stefv5, containerId=e16144b54f5c0112b4fc8f7bb17bc6a1d4d8452150ef7c5452f23b302fd3cabc, nodePort=40002] is terminated. Removing from tracked set.
16:32:36.208 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - e16144b54f5c0112b4fc8f7bb17bc6a1d4d8452150ef7c5452f23b302fd3cabc Marking node down.
16:32:36.208 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container ContainerCreationStatus [isCreated=true, containerName=zalenium_nisU0G, containerId=5c01ac1b157478b8db2df77efdf5baade8749c6b3fd604d073e4e5d62c150b1d, nodePort=40001] is terminated. Removing from tracked set.
16:32:36.209 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - 5c01ac1b157478b8db2df77efdf5baade8749c6b3fd604d073e4e5d62c150b1d Marking node down.
16:32:36.209 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container ContainerCreationStatus [isCreated=true, containerName=zalenium_rlPKdt, containerId=ce51f3d8092f9b94b4c7e6d2c8d31ab3962d18cf4c1fd2dd8a3f838cd112615f, nodePort=40000] is terminated. Removing from tracked set.
16:32:36.210 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - ce51f3d8092f9b94b4c7e6d2c8d31ab3962d18cf4c1fd2dd8a3f838cd112615f Marking node down.
16:32:37.211 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Autostarting container, because 0 is less than min 3

Please see the attached TXT for complete log
[log.txt](https://github.com/zalando/zalenium/files/2037017/log.txt)

**Comment by shiva4983** [comment]
an Update, it is happening only when I pass the proxy value. I think the issue is with elgalu/selenium.

**Comment by diemol** [comment]
Hi @shiva4983,

That is clearly the issue, when using `"zalenium_http_proxy=Proxy"`, then the created containers will look for a proxy called "Proxy" and it probably won't find it. You need to pass something like `"zalenium_http_proxy=http://myproxy.example.com:8080"`, basically the full proxy url.

**Comment by shiva4983** [comment]
Hi @diemol , thanks for the quick reply. May be I have confused you by putting "Proxy" but what I meant by Proxy is my full proxy address ex: "http://ProxyUsername:ProxyPassword@ProxyIP:Port". Even though I am facing the issue.

**Comment by diemol** [comment]
I am not sure, that should work right away. Perhaps the password has some characters that need to be escaped or something like that? (I got that from googling 5 minutes, not sure if that is the case).

I see that you are also raising the issue in `elgalu/selenium`, but either here or there, what I suggest is that you try first and debug with a simple image if setting the proxy works, since it is quite probable that there is a string missing or some detail that needs adjustment.

Since there is no issue with Zalenium, but more a config with the proxy that needs to be handled, I will close this issue. If you need help, join us in https://seleniumhq.herokuapp.com/, there is a channel called #zalenium where more users are present and they could also answer these type of questions.

**Comment by shiva4983** [comment]
Sure @diemol I will post join you guys in Slack.

**Comment by Balajiiguru** [comment]
@shiva4983 @diemol: Am facing the same issue is any solution for this issue,on using proxy always the container terminates in middle of execution(around 2 minutes) with the below error.

INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - Marking node down.
15:02:09 21:02:09.708 [http://172.17.0.5:40002] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - Marking node down.[http://172.17.0.5:40004] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - Marking node down.


and 2 new container get registered and hence my execution get interrupted.

**Comment by evgenyfedorenko** [comment]
hey Balajiiguru did you resolve your issue? I am getting the same one.

**Comment by bhupender-agarwal** [comment]
Hi @diemol,

Although this issue has been closed, I would like to comment that the aforementioned issue still exists which is making it impossible to execute the tests on the zalenium grid with proxy settings on. I have tried all the methods discussed in various comments, such as use of an IP address of proxy server, using a custom image with proxy settings passed to elgalu/selenium using Dockerfile, etc., but none of the solutions worked. Please look into this issue as we want to use Zalenium for setting up a selenium-grid in our private cloud.

Thanks,
Bhupender Agarwal
