### ISSUE TITLE
Test name in dashboard is same for all scenarios

### ISSUE THREAD

**Issue by rmullaguri2308** [zalando/zalenium#598]
Zalenium Image Version(s):  

Docker Version:  

If using docker-compose, version:  

OS: 

Docker Command to start Zalenium:  

If using Kubernetes, specify your environment, and if relevant your manifests:  

I am using cucumber-spring in java 
## Expected Behavior -
I am expecting to see my scenario names on dash board.
Right now it displays the same test name instead I need scenario name dynamically so i can run it in parallel with a unique name
## Actual Behavior -
As we need to set Test name as part of Desired Capabilities so test name is same for all scenarios as we don't create the driver for each scenario

**Comment by diemol** [comment]
Hi @rmullaguri2308,

As you mentioned, the test name is set via capabilities and this is connected to the WebDriver session, therefore the name will be that always in the dashboard. 

Alternatives for that:
* Give us a hand on #490 so videos can be recorded on demand, in this case per scenario.
* Reference the scenarios in the video, see how to do it here: https://opensource.zalando.com/zalenium/#usage.

Thanks for trying Zalenium, if you have any more doubts, please join us at https://seleniumhq.herokuapp.com/ (channel #zalenium), where we can also work out different type of questions.
