### ISSUE TITLE
Changing Selenium Log level

### ISSUE THREAD

**Issue by javacoldbrew** [zalando/zalenium#607]
<img width="708" alt="zaleniumseleniumloglevel" src="https://user-images.githubusercontent.com/25971275/40923408-ca0a0d44-67e2-11e8-8aac-b44c1686758b.PNG">

How would I be able to change the Selenium Log level on the Dashboard page?

I am using WebdriverIO and I am able to change the log level in `wdio.conf.js`

```
exports.config = {
...
   // Level of logging verbosity: silent | verbose | command | data | result | error

   logLevel: 'command',
...
}
```

But this only changes the log level in the terminal.

**Comment by javacoldbrew** [comment]
@diemol Thank you for informing me. Are there plans for a feature like this to be added?

**Comment by diemol** [comment]
I don't think so, it does not seem to add so much value to the end result I would say.

Nevertheless, we are always open to PRs :)

I will close this issue since there is no task for us.
