### ISSUE TITLE
cpu & memory request + limits

### ISSUE THREAD

**Issue by bramvdklinkenberg** [zalando/zalenium#610]
In the values.yaml hub.cpuRequest, hub.cpuLimit and hun.memRequest are defined twice.
These values are for the browser pods right?

And the hub.resources.limits are for the intial zalenium pod right?

Is there a reason why the browser pod cpu and memory values are mentioned twice in the values.yaml?

**Comment by pearj** [comment]
Ahh you mean https://github.com/zalando/zalenium/blob/master/docs/k8s/helm/local/zalenium/values.yaml#L59-L60 and  https://github.com/zalando/zalenium/blob/master/docs/k8s/helm/local/zalenium/values.yaml#L71-L72
It looks like a mistake to me, I presume that last entry takes priority. Feel free to submit a PR to correct it!
