### ISSUE TITLE
Feature Request : Read SAUCE_LABS_URL from environment variable 

### ISSUE THREAD

**Issue by clyton** [zalando/zalenium#615]
Hello,

In my company we use sauce labs to execute our tests. We are unable to use zalenium's SauceLabsRemoteProxy class to connect to our sauce servers because SAUCE_LABS_URL field is hard coded. 

https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/proxy/SauceLabsRemoteProxy.java

In my company we have different servers urls in the format : 'server_name.cloud.company_name:80' 

Can you please add the capability to read this field using getEnv() method just like you read the SAUCE_LABS_USER_NAME

**Comment by micheletest** [comment]
This would be great to do for Browserstack also, the URL that my company is supposed to use is slightly different than the BROWSER_STACK_URL in zalenium.

**Comment by pearj** [comment]
@clyton feel free to submit a PR for this, as from what you say it sounds pretty straightforward.

**Comment by clyton** [comment]
@pearj I have forked your code and done the changes. But can't seem to figure how to build and test my code. Can you guide me on this?

**Comment by clyton** [comment]
Since this feature has been added in merge #642 I am closing this issue.

**Comment by diemol** [comment]
Thanks for your contribution @clyton! This has been just released.
