### ISSUE TITLE
PhantomJS or Chrome headless

### ISSUE THREAD

**Issue by madhavajay** [zalando/zalenium#62]
Any chance of having either PhantomJS or Chrome headless as an option seeing as Xvfb uses a lot CPU and Memory. I cant get to 100 Chrome instances on 16 cores but I can with PhantomJS.

I built a working version of PhantomJS 2.1.1 with a custom ghostdriver which connects from a Docker container and allows a return connection.

https://github.com/madhavajay/selenium-node-phantomjs

**Comment by elgalu** [comment]
Hi @madhavajay thanks for bringing this up.

I'm not sure how a Selenium server is needed if the tests can run in PhantomJS already, why not just running the tests in phantom directly without docker or anything additional?

**Comment by diemol** [comment]
Hi guys,

I'll close this issue due to inactivity, feel free to reopen and start the discussion when new ideas come!

**Comment by ylavoie** [comment]
Having PhantomJS would be a great idea. Zalenium acts as a bridge for others, why impose a specific setup when this the desired browser? I, for one, am interested to check if my projects run well on many and would welcome the integration.

**Comment by diemol** [comment]
I agree with what you say @ylavoie, imposing things doesn't work at all. That is why we have tried to integrate as many things as we can, but also taking into account if the integration adds value.

On the Phantom JS topic, the current state is that the only [maintainer stepped down](https://www.infoq.com/news/2017/04/Phantomjs-future-uncertain). So it doesn't sound like it bring a lot of value to add something that won't be maintained, and also taking into account that we try to provide video features, Phantom JS doesn't fit that well there.

**Comment by madhavajay** [comment]
Sorry for not replying sooner, the reason why its important to use the Selenium Grid is to allow for easy parallel scheduling from a variety of testing frameworks. However I agree now that PhantomJS's future is in limbo its probably best to leave it. However there it seems there is already progress running Chrome Headless with selenium which I mentioned at the start of the ticket.

https://github.com/SeleniumHQ/docker-selenium/issues/429#issuecomment-304531622

The difference being that Chrome headless is using less ram which is always a win.

**Comment by diemol** [comment]
Yeah, I think we just need to wait until the headless part improves, because it is not possible to do a "sendKeys" without XVFB so far.

**Comment by ylavoie** [comment]
My comment about PhantomJS came from the fact that it is still in the official Selenium hub & nodes setup and, although its future is far from being bright, it is nevertheless still a good solution to test our code against.

**Comment by diemol** [comment]
@ylavoie you are right, but based on the last comments from https://github.com/SeleniumHQ/docker-selenium/issues/429, I think something could work in the near future.

**Comment by ylavoie** [comment]
@diemol What is discussed there is to find a way to have Chrome run headless, which is a **very** good idea. What I am demanding is that, even if PhantomJS future may be shaky, to say the least, we support it while it is in the official Selenium images.
