### ISSUE TITLE
Hand baked IE slaves support

### ISSUE THREAD

**Issue by aalbul** [zalando/zalenium#626]
Hi, is it possible to add few hand-baked windows slaves to hub? Will it even work? I mean, if this is just a selenium hub with some modifications for scalability, it should not be a problem?

I understand that maybe it is not really working well with overall idea of Zalenium, but i have a requirements to do testing on IE and unfortunately cloud solutions as a fallback are not an option because of security restrictions.
So i'm trying to get the best of two worlds: get minimal IE support + the whole set of cool auto-scalability/live view/video recording stuff on Chrome/Firefox builds.

**Comment by diemol** [comment]
Hi @aalbul,

Zalenium is a standard Selenium Grid with extended features, therefore you could register a Windows node as you would do it to a regular hub.

Please give it a try and let us know how it went. If any issue pops up, don't doubt to create a new issue.

**Comment by diemol** [comment]
Exactly, that is the expected behaviour. There is nothing implemented for the functionality you mention.

**Comment by espguitarist33** [comment]
Ah, I see! Thanks for the quick reply!

So, just confirming, there is currently no way to retain the recording features while testing on, say, an IE node? (I’m not sure if the Sauce Labs services get recorded, but we’re hoping to not need them).

**Comment by diemol** [comment]
Right, there is nothing implemented about that for IE nodes added manually. If you use a cloud provider like Sauce Labs then the videos will get recorded, downloaded and added to the dashboard.
