### ISSUE TITLE
Unique docker container name generation from release 3.11.0e

### ISSUE THREAD

**Issue by jbengit** [zalando/zalenium#627]
Zalenium Image Version(s):  

## Expected Behavior -
Hi,
During our Automation process, we need to change the DNS server per test / running container / browser. To be able to do this, we retrieved the selenium port of the specific test in run-time, and then guessed the running docker container associated with the test. 
From the 3.11.0e release, the container name is now randomly generated. Is there possible to retrieve it anyway (HTTP request, web-driver, etc) in run-time or to go back to the previous behavior?

**Comment by pearj** [comment]
If you set a test name via capabilities, then you could scrape the container name from the live preview page: `/grid/admin/live`

See Test Configuration Options in the the usage section of the doco: https://opensource.zalando.com/zalenium/#usage
