### ISSUE TITLE
WebDriverException webdriver.gecko.driver

### ISSUE THREAD

**Issue by aschiavon91** [zalando/zalenium#63]
# Meta -

OS: Ubuntu 16.04 64bits
Selenium Version: 3.0.1
Browser: Firefox version 47.0.1

# Expected Behavior -

Get Firefox remote webdriver

# Actual Behavior -

Raises exception: "WebDriverException: Message: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/jgraham/wires. The latest version can be downloaded from https://github.com/jgraham/wires"

## My method to return a remote webdriver

```
def getWebDriver(self):
        SeleniumServer = 'http://localhost:4444/wd/hub'
        profilePath = "/mnt/firefox-profiles/" + str(self.login)
        if not os.path.exists(profilePath):
                os.makedirs(profilePath)
                ffProfile = webdriver.FirefoxProfile(profile_directory=profilePath)
        else:
                ffProfile = webdriver.FirefoxProfile(profile_directory=profilePath)
                ffCapabilities = webdriver.DesiredCapabilities.FIREFOX
                try:
                        driver = webdriver.Remote(command_executor=SeleniumServer, desired_capabilities=ffCapabilities, browser_profile=ffProfile)
                except Exception as e:
                        print "Error starting browser: " + str(e)
                else:
                        driver.set_page_load_timeout(120)
                        return driver
```

I have pasted the return error here: http://pastebin.com/CjSZPAnk

**Comment by aschiavon91** [comment]
I was able to avoid the problem using selenium version 2 "-e USE_SELENIUM: 2" and setting DesiredCapabilities['marionette'] to False.

```
def getWebDriver(self):
        SeleniumServer = 'http://localhost:4444/wd/hub'
        profilePath = "/mnt/firefox-profiles/" + str(self.login)
        if not os.path.exists(profilePath):
                os.makedirs(profilePath)
                ffProfile = webdriver.FirefoxProfile(profile_directory=profilePath)
        else:
                ffProfile = webdriver.FirefoxProfile(profile_directory=profilePath)
                ffCapabilities = webdriver.DesiredCapabilities.FIREFOX
                ffCapabilities['marionette'] = False
                try:
                        driver = webdriver.Remote(command_executor=SeleniumServer, desired_capabilities=ffCapabilities, browser_profile=ffProfile)
                except Exception as e:
                        print "Error starting browser: " + str(e)
                else:
                        driver.set_page_load_timeout(120)
                        return driver
```

**Comment by diemol** [comment]
Hi @aschiavon91,

We were here talking about that a moment ago. I think what was happening is that you were using the bindings for Selenium 3 with the `latest` Zalenium image.

The thing is that `latest` right now points to the most recent Zalenium release for Selenium 2. There is an image for Selenium 3, which is tagged with `3.0.1f` right now. You could try to use that one.

Until Google Analytics tells us that Selenium 3 is more used than Selenium 2, we will leave `latest` pointing to the most recent release with Selenium 2.

The one line installer can help you to start Zalenium with Selenium 3 without you having to worry about the latest tag for the image. Check it here https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#install-and-start-with-latest-selenium-3

**Comment by diemol** [comment]
If it works with Selenium 3, please let us know, so we can close the issue. Thanks!

**Comment by aschiavon91** [comment]
Its worked man! Thank you!

**Comment by diemol** [comment]
Cool, I'll close the issue then.
