### ISSUE TITLE
Zalanium not creating nodes more than 2

### ISSUE THREAD

**Issue by seeramzan** [zalando/zalenium#633]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
<3.7.0>
Docker Version:  
<18.03.1>
If using docker-compose, version:  
N/A
OS: 
< Windows 10>
Docker Command to start Zalenium:  
docker run --rm -ti --name zalenium -p 4444:4444 \ -v /var/run/docker.sock:/var/run/docker.sock \ -v /tmp/videos:/home/seluser/videos \ --privileged dosel/zalenium start 

If using Kubernetes, specify your environment, and if relevant your manifests:  

## Expected Behavior -
Based on no of threads, nodes should be created.

## Actual Behavior -

My program is creating 04 threads, but zalanium is creating 02 nodes one time and once test finished then creating remaining 02 tests nodes.

Jul 01, 2018 3:32:44 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Jul 01, 2018 3:32:44 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
verifyLogin executed with test data : tomsmith Thread# 15
verifyLogin1 executed with test data : row2 Thread# 17
verifyLogin1 Execution Successfull with test data : row2 Thread# 17
		[FAIL]  Login failed
verifyLogin Execution Successfull with test data : tomsmith Thread# 15
		[PASS]  Login Passed
Jul 01, 2018 3:32:59 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
verifyLogin1 executed with test data : row3 Thread# 16
verifyLogin1 Execution Successfull with test data : row3 Thread# 16
		[FAIL]  Login failed

_________ End Test  _________

**Comment by pearj** [comment]
You should probably read https://opensource.zalando.com/zalenium/ as you haven't specified any of the variables relating to how many containers zalenium is allowed to use.

If you need more help try joining https://seleniumhq.herokuapp.com/ and the #zalenium channel
