### ISSUE TITLE
Feature - Node mount folder

### ISSUE THREAD

**Issue by aschiavon91** [zalando/zalenium#64]
Hi,

I need to mount a folder from host or zalenium container(hub) in all selenium containers (nodes), can you add this?

Exemple:
```
docker run --rm -ti --name zalenium -d -p 4444:4444 -p 5555:5555 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos dosel/zalenium start --mount /mnt:/mnt
```

**Comment by diemol** [comment]
Hi,

By coincidence other guys were asking for something similar, they need to use special Chrome profiles and something needs to be mounted so they can use them across the containers.

In theory, it should not be hard, let us check this the next couple of days and see if we can do it fast.  But we should add this option definitively.

**Comment by diemol** [comment]
Hi,

We released yesterday and we included this feature. I still need to update the readme to describe it, but to make it short, there is now a folder mapped between the Zalenium containers and all the other docker-selenium containers. 

The folder is called `/tmp/mounted`. So you could just mount from your host with 
`-v /my/host/folder:/tmp/mounted` when starting Zalenium.

Please let us know if it works as expected.

**Comment by diemol** [comment]
Hi again,

Please check https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#with-a-multi-purpose-folder-mounted for more information.

**Comment by aschiavon91** [comment]
Hi @diemol, sorry by the late.

I have tested this new update, and i have a good and a bad news.
The good news is, the /tmp/mounted folder works pretty nice in all containers, thx to all zalando team, its helps me too much <3.
The bad news is, i tryed to mount another folder to /tmp/mounted by the option -v (-v /some/folder:/tmp/mounted), apparently its always mounts /tmp/mounted in host to /tmp/mounted in dockers.
U have some ideia of what is going on?

**Comment by diemol** [comment]
No worries!

Can you show me the command you tried? If you used the one line installer/starter, we are mapping by default `/tmp/mounted`.
We tested it with some basic cases, perhaps we missed something.

**Comment by aschiavon91** [comment]
That's the command that i currently using to starting up zalenium
´´´
docker run --rm -ti --name zalenium -d -p 4444:4444 -p 5555:5555 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos -v /mnt:/tmp/mounted -e USE_SELENIUM=3 dosel/zalenium:3.0.1g start --maxDockerSeleniumContainers 10 --timeZone "America/Sao_Paulo" --screenWidth 1920 --screenHeight 1080
´´´

**Comment by diemol** [comment]
OK, I think that now I get it.

The folder in the host can have any name, in your command it is: `/mnt`
But inside all containers, the mapped volumes are all `/tmp/mounted`

So, if you are looking for a file in your test, you should look for it in `/tmp/mounted`. I hope that it works like that for you.

We could try to find a way to make it configurable, but for now we are spending our efforts in a new feature.

**Comment by diemol** [comment]
@aschiavon91 was my comment helpful? Please let me know if the solution works for your case.

**Comment by aschiavon91** [comment]
Hey @diemol.

Yeah man its very helpful! The solution is working pretty nice.
Thx man.

**Comment by diemol** [comment]
Cool! Thanks for the feedback.
