### ISSUE TITLE
How to use kuberentes for Zalenium, any documentation? how to connect both?

### ISSUE THREAD

**Issue by sunipa11** [zalando/zalenium#640]
Hi,

How to connect kuberentes with Zalenium?

I able to create kuberentes pods and able to run selenium scripts using kuberentes selenium grid URL but it is not configured using zalenium so I am not able to see video and can't expect that it will auto scale on it's own, can somebody please help us here and guide me?

Regards

**Comment by diemol** [comment]
Hi @sunipa11,

If your issue is not covered by the documentation found here: https://opensource.zalando.com/zalenium/#kubernetes

It is not clear what you describe there, so I think it is better if you join us at https://seleniumhq.herokuapp.com/ and find us in the #zalenium channel.
