### ISSUE TITLE
Dump logs kept in the memory to the local file during the Runtime

### ISSUE THREAD

**Issue by baflQA** [zalando/zalenium#644]
Zalenium Image Version(s):  
3.12.0e
Env: K8S on AWS, deployed with the helm chart from the Zalenium repository.

## Expected Behavior -
Zalenium saves the logs displayed in the Dashboard to the local file so that they are not stored in the memory during the runtime.

## Actual Behavior -
While running a long suite of tests, a lot of RAM is being consumed by the Hub pod. The picture below shows the amount of RAM consumed by the pod with the video recording turned off:
![zrzut ekranu 2018-07-06 o 13 21 55](https://user-images.githubusercontent.com/27357499/42376574-e34248b6-811f-11e8-84a3-b0a1f4a43c04.png)

The significant drop in the consumption was observed after using the cleanup functionality in the dashboard. 

Actual behaviour is, quoting @diemol 
> the array is kept in memory and dump to a file when Zalenium shuts down

**Comment by pearj** [comment]
I’m pretty sure the actual logs themselves aren’t kept in memory, but rather the list of test sessions and related file names, ie logs and videos.

**Comment by diemol** [comment]
Right, to be more precise, the logs are not in memory, but the information shown in the dashboard, which could add up after running a lot of tests. 

We should dump this to disk when it grows too much and then just append new entries.
