### ISSUE TITLE
Server returned HTTP response code: 429 for URL: https://saucelabs.com

### ISSUE THREAD

**Issue by ximbal** [zalando/zalenium#649]
Zalenium Image Version(s):  
`3.0.12c `
Docker Version:  
`Docker version 18.03.1-ce, build 9ee9f40`

OS: 
` 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Hardware:
`32 GB RAM, 8 processors`

Docker Command to start Zalenium:  

`docker run --rm -ti --name elastic-selenium-grid -p 4444:4444 -e SAUCE_USERNAME -e SAUCE_ACCESS_KEY -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start --screenWidth 1280 --screenHeight 1024 --timeZone "America/Toronto" --desiredContainers 20 --videoRecordingEnabled false --maxDockerSeleniumContainers 25 --maxTestSessions 10`

## Expected Behavior -

Fall Back to SauceLabs when we the grid does not have the requested capability.

## Actual Behavior -

Calls to SauceLabs are reaching it's allowed limit to call the API. Response Code 429 `is too many attempts to hit the SauceLabs API`

```
20:02:26.425 [qtp1829217853-15] INFO  d.z.e.z.util.CommonProxyUtilities - Trying download once again from https://saucelabs.com/rest/v1/users/<EDITED>
....SauceLabsRemoteProxy failed to start after 40 seconds, failing...

[qtp1829217853-15] ERROR d.z.e.z.util.CommonProxyUtilities - java.io.IOException: Server returned HTTP response code: 429 for URL: https://saucelabs.com/rest/v1/users/<EDITED>
java.io.IOException: Server returned HTTP response code: 429 for URL: https://saucelabs.com/rest/v1/users/<EDITED>
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
```
Any ideas on how to prevent this?

This is also causing the Dashboard and Live views to become unresponsive

**Comment by diemol** [comment]
Hi @ximbal,

It just looks that a lot of tests are using SauceLabs. If that is what is intended, perhaps it is a better idea to use SauceLabs directly?

If the API is limiting the API calls there is not really something we could do, perhaps contact their support and see what can be done?

I am sorry, but there is not something we could do to improve the situation since it is more related to the SauceLabs API.

I'll close this issue, but just let us know if there is anything else we can do to help.

**Comment by ximbal** [comment]
I do agree with your comment, however, the issue that I am trying to bring to the table is the fact that this killed the entire Zalenium instance, rendering unusable and forcing us to restart it completely, wouldn't it be wise to add some sort of mechanism to prevent this use case from disrupting zalenium service?

**Comment by wnickmoore** [comment]
Following up on 

> This is also causing the Dashboard and Live views to become unresponsive

Does Zalenium have the capability to rate-limit it's requests to the SauceLabs API, or to configure a maximum attempts before it will stop attempting to access the API?

The use case here would be to prevent Zalenium from trying to access the SauceLabs API too frequently; especially since we now know that SauceLabs has some specific limits.

**Comment by diemol** [comment]
All the requests are done with the userName/accessKey passed as env vars, it is kind of weird that more than 3.500 requests are done in an hour, does that make sense in your case?

Anyway, technically it is possible to check the current API usage and decide to make the request again, or to implement some sort of retry mechanism based on that. Would you like to help us with a PR?

This is where we interact with the SauceLabs API 
https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/proxy/SauceLabsRemoteProxy.java#L97

Here is the method downloading videos and logs
https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/proxy/CloudTestingRemoteProxy.java#L269

and here is the detailed implementation of the download
https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/util/CommonProxyUtilities.java#L86

I am reopening the issue for discussion, and based on that we can add it to #654 or not.

**Comment by diemol** [comment]
Added to #654, we would be very happy if you guys can give us a hand.

Closing for the moment and when someone picks it up, we'll reopen.
