### ISSUE TITLE
Add option to mount a volume in the Node in order to use chrome-profiles

### ISSUE THREAD

**Issue by diogopublio** [zalando/zalenium#65]
As of now, we are able to mount a directory in the hub docker, but not in the node docker. We need to be able to set this in order work with chrome-profiles.

**Comment by diemol** [comment]
We are working on this now, I will mark this issue as duplicated and put more details in #64.

@diogopublio, please watch #64 so you can follow it. 

I'll close this one now.

**Comment by diemol** [comment]
@diogopublio, we released something to solve #64 
Whenever you can, please check it and give us some feedback at #64 
Thanks!

**Comment by diogopublio** [comment]
That worked like a charm! Thanks!
