### ISSUE TITLE
Build names show always false on dashboard

### ISSUE THREAD

**Issue by tempuser14** [zalando/zalenium#653]
Zalenium Image Version(s): 3.12.0f, latest
Docker Version: 17.12.1-ce, build 7390fc6
OS: Ubuntu 16.04.4 LTS

Docker Command to start Zalenium:
`docker run -tid --restart unless-stopped --name zalenium -p 80:4444 -p 5555:5555  -v /var/run/docker.sock:/var/run/docker.sock -v /home/vlx/seluser/Downloads:/tmp/node/home/seluser/Downloads  -v /tmp/videos:/home/seluser/videos  --privileged dosel/zalenium start --sendAnonymousUsageInfo false`

In Zalenium dashboard we do not see the build names anymore. I think it started after our image pull a month ago (~with the tag 3.12.0d)
![grafik](https://user-images.githubusercontent.com/31033828/42632116-74190742-85dc-11e8-991e-bdf05d2a6a54.png)

**Comment by pearj** [comment]
Can you paste the code you use to set the build name?

**Comment by tempuser14** [comment]
The build name ist set statically as a maven parameter:
`mvn clean verify -Prc -Dcontext=chrome -Dinjected.tags="browser:chrome" -Dwebdriver.remote.driver=chrome -Dwebdriver.remote.url="http://zalenium.domain/wd/hub" -Dserenity.driver.capabilities="build:project-rc;name:chromeTest"`

**Comment by tempuser14** [comment]
I am closing this issue because this is [a problem in the Serenity framework](https://github.com/serenity-bdd/serenity-core/issues/1306)  and not in Zalenium.
