### ISSUE TITLE
Containers which are created succesfully but later fail remain in startedContainers Map forever

### ISSUE THREAD

**Issue by FilipB** [zalando/zalenium#670]
Zalenium Image Version(s):  
3.13.0a
Docker Version:  
1.13.1
OS: 
RHEL 7.5
If using Kubernetes, specify your environment, and if relevant your manifests:  
OCP  v3.9.30 
## Expected Behavior -
Containers which were created successfully but were not started (ready) due to some error should be removed from startedContainers Map after some timeout.

## Actual Behavior -
When container is successfully created it's added to startedContainers https://github.com/zalando/zalenium/blob/50caa4e056b7197bad5bb5c171cb1649114ebf1b/src/main/java/de/zalando/ep/zalenium/proxy/AutoStartProxySet.java#L385

When the container fails to start successfully following will never be true: https://github.com/zalando/zalenium/blob/50caa4e056b7197bad5bb5c171cb1649114ebf1b/src/main/java/de/zalando/ep/zalenium/proxy/AutoStartProxySet.java#L323

The container will stay in startedContainers map forever and following warning will be thrown periodically:
https://github.com/zalando/zalenium/blob/50caa4e056b7197bad5bb5c171cb1649114ebf1b/src/main/java/de/zalando/ep/zalenium/proxy/AutoStartProxySet.java#L331

After some time startedContainers map will be blocked by those containers and no new containers will be created:
https://github.com/zalando/zalenium/blob/50caa4e056b7197bad5bb5c171cb1649114ebf1b/src/main/java/de/zalando/ep/zalenium/proxy/AutoStartProxySet.java#L226

**Comment by diemol** [comment]
Hi @FilipB,

Sorry for the late reply. I think you are right, there might be a case where a container stays in a "starting" state and then it will be never removed from the `startedContainers` map. I just added a change that takes care of that. 
We are in the process of adding other improvements, so this will land with those ones in the next week. 

Thank you for taking the time to report this.
