### ISSUE TITLE
Start to zalenium's selenium hub image with resources that cpuLimit and memoryLimit

### ISSUE THREAD

**Issue by furkandogan** [zalando/zalenium#676]
"sudo docker run --rm -ti --name zalenium -d -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v "$workpath/$testnumber"/zalenium:/home/seluser/videos --privileged 192.168.10.88:8123/zalenium start --desiredContainers 4 --maxDockerSeleniumContainers 5 --maxTestSessions 4 --screenWidth 1920 --screenHeight 1080 --timeZone "Europe/Istanbul" --videoRecordingEnabled true --keepOnlyFailedTests false --seleniumImageName 192.168.10.88:8123/elgalu-selenium"

I usually run the docker image with this script. But ı want to give cpu and memory limit to selelnium image. Is this possible?

For example;
I want to start with below script
sudo docker run --rm -ti --name zalenium -d -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v "$workpath/$testnumber"/zalenium:/home/seluser/videos --privileged 192.168.10.88:8123/zalenium start --desiredContainers 4 --maxDockerSeleniumContainers 5 --maxTestSessions 4 --screenWidth 1920 --screenHeight 1080 --timeZone "Europe/Istanbul" --videoRecordingEnabled true --keepOnlyFailedTests false --seleniumImageName 192.168.10.88:8123/elgalu-selenium --cpuLimit 1000m --memLimit 1000mi

**Comment by diemol** [comment]
Hi @furkandogan 
Right now it is not possible but it sounds like a good idea, would you like to send us a PR implementing the feature?

**Comment by furkandogan** [comment]
Okey I will try to develop this PR and than i will send you.

**Comment by furkandogan** [comment]
hi @diemol I develop that issue. How can ı push my branch. I can't push because of permission.

**Comment by diemol** [comment]
@furkandogan you need to fork the repository and then send a PR, thanks!
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by furkandogan** [comment]
I have question @diemol . Can you answer? How can ı deploy code in docker that is in src/main

**Comment by furkandogan** [comment]
docker build -t zalenium . script is enough

**Comment by diemol** [comment]
You can also do `mvn clean package -Pbuild-docker-image -DskipTests=true`

**Comment by furkandogan** [comment]
Hi @diemol ı run your script "mvn clean package -Pbuild-docker-image -DskipTests=true".
But I get this exception "Execution default of goal org.codehaus.mojo:aspectj-maven-plugin:1.11:compile failed: Plugin org.codehaus.mojo:aspectj-maven-plugin:1.11 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:9.0.1 at specified path /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/../lib/tools.jar ". Is that plugin use specific java version?

**Comment by diemol** [comment]
I am not sure, but we build Zalenium with Java 8, so please use that to build it.

**Comment by furkandogan** [comment]
Thanks @pearj. I create pull request @diemol thanks for your helps.

**Comment by diemol** [comment]
Closed via https://github.com/zalando/zalenium/commit/1a584812bfcfb74a762424e1aa2e3849b18efaf3

Thanks @furkandogan
