### ISSUE TITLE
Zalenium on AWS Dashboard Videos/logs not Available

### ISSUE THREAD

**Issue by saibtech** [zalando/zalenium#677]
Created a AWS EC2 instance installed docker on to it .Added Required Security Group to it .

After the Pulling image from the docker hub 
 # Pull docker-selenium
    docker pull elgalu/selenium
    
    # Pull Zalenium
    docker pull dosel/zalenium

Ran the following command
docker run --rm -ti --name zalenium -p 4444:4444 \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v /tmp/videos:/home/seluser/videos \
     -v /usr/bin/docker:/usr/bin/docker \
      --privileged dosel/zalenium start --videoRecordingEnabled true

Tests ran fine with no issues 

Expected behaviour
http://{EC2HostPName}:4444/dashboard/ should display the videos and logs

Actual Behaviour
Waiting for the dashboard to be ready...
It will load automatically after the first videos are ready.

Debug:
There is no files in the /tmp/videos folder of the EC2 instance machine 
but the selenium grid logs shows the following text
22:41:00.569 [Terminate Test Session int id: [6ca715d7-1c4f-41f9-a89d-881ce49c0824] ext id: [f09c601d31ae9c451919c3c5e916b43f] container: [3a51ec236d52aa80544d27f50dc3012d729c6d70742896989e60b698bf72d106]] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - 3a51ec236d52aa80544d27f50dc3012d729c6d70742896989e60b698bf72d106 Video file copied to: /home/seluser/videos/zalenium_SampleTest_chrome_LINUX_20180727224100141_COMPLETED.mp4

**Comment by diemol** [comment]
Hi @saibtech,

Could you please provide the full logs of Zalenium?

**Comment by saibtech** [comment]
im not seeing the above the logs this is the logs in get 

18:30:29.486 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockeredSeleniumStarter - Created container [zalenium_MXTyIX] with dimensions [(1920, 1080)] and tz [sun.util.calendar.ZoneInfo[id="Europe/Berlin",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=143,lastRule=java.util.SimpleTimeZone[id=Europe/Berlin,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]].
18:30:29.490 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Created ContainerCreationStatus [isCreated=true, containerName=zalenium_MXTyIX, containerId=bb3ec7e022e30f8341e20870716905e58dcab6c62e34169462e464edd4454033, nodePort=40000].
18:30:31.188 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockeredSeleniumStarter - Created container [zalenium_GZNUSW] with dimensions [(1920, 1080)] and tz [sun.util.calendar.ZoneInfo[id="Europe/Berlin",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=143,lastRule=java.util.SimpleTimeZone[id=Europe/Berlin,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]].
18:30:31.189 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Created ContainerCreationStatus [isCreated=true, containerName=zalenium_GZNUSW, containerId=aecf2f627c2bd27d62a3fd9070f8d892784d7fdebb9e68d9072329593623f593, nodePort=40001].
18:30:59.186 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container zalenium_MXTyIX started after 29696.
18:31:03.885 [Thread-10] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.17.0.3:40000
18:31:03.903 [Thread-10] INFO  d.z.e.z.proxy.AutoStartProxySet - Registered a container bb3ec7e022e30f8341e20870716905e58dcab6c62e34169462e464edd4454033 http://172.17.0.3:40000.
18:31:03.921 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container zalenium_GZNUSW started after 32732.
18:31:06.555 [Thread-11] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.17.0.4:40001
18:31:06.556 [Thread-11] INFO  d.z.e.z.proxy.AutoStartProxySet - Registered a container aecf2f627c2bd27d62a3fd9070f8d892784d7fdebb9e68d9072329593623f593 http://172.17.0.4:40001

**Comment by saibtech** [comment]
I

**Comment by saibtech** [comment]
Oops Accidently closed

**Comment by diemol** [comment]
That is the log when Zalenium starts, but I don't see any tests being executed, did you run any tests?

**Comment by saibtech** [comment]
Yes I did ran. I dont know some how its not showing any logs . I fi ran locally its working fine .Have you tried in the aws ec2 server?

**Comment by saibtech** [comment]
Im using Nightwatch My configuration is as follows 
selenium: {
		start_process: false,
		server_path: "node_modules/selenium-server-standalone-jar/jar/selenium-server-standalone-3.4.0.jar",
		log_path: "./reports",
		host: "${Ec2ServerIpAddress}",
		port: 4444,
		cli_args: {
			"webdriver.chrome.driver": "./node_modules/chromedriver/lib/chromedriver/chromedriver.exe",
			"webdriver.gecko.driver": "./node_modules/geckodriver/geckodriver.exe",
			"webdriver.ie.driver": "./node_modules/iedriver/lib/iedriver/IEDriverServer.exe"
		}
	}

**Comment by saibtech** [comment]
Sorry its working now  i need include these settings too
test_settings: {
		default: {
			selenium_port: 4444,
			selenium_host: "${ec2server}",
			silent: true,
