### ISSUE TITLE
Desired Capabilities are deprecated what to do?

### ISSUE THREAD

**Issue by johnqa** [zalando/zalenium#682]
Hi,

If the Desired Capabilities are deprecated in selenium, what would be the correct manner in which we can set the more advanced test configuration options?

Thank you,
John

**Comment by diemol** [comment]
Hi @johnqa, what do you mean exactly? Is this more a Selenium question?

**Comment by johnqa** [comment]
Hi, 

You are probably right, this was more of a selenium question. 
The thing is that I use C# and the method to add a new capability complains when I add the capabilities needed by Zalenium that they are unrecognized chrome options.
System.InvalidOperationException: System.InvalidOperationException: unknown error: cannot parse capability: goog:chromeOptions
from unknown error: unrecognized chrome option: idleTimeout
 (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.14393 x86_64).

And regarding capabilities being deprecated I see that DesiredCapabilities.SetCapability(string capability, object capabilityValue) is marked as deprecated, the message saying that it has been deprecated in favour of browser-specifiv Options classes.

If you think this doesn't concern Zalenium, please close the ticket.

Thank you.
![image2018-8-8 10_39_52](https://user-images.githubusercontent.com/4747139/43826602-39d2d6f6-9ae7-11e8-9d27-c6ad374c2e91.png)

**Comment by diemol** [comment]
Can you post here the C# code for the used capabilities please?

**Comment by johnqa** [comment]
The code I played with looks like this:
```
case "chrome":
 var chromeOptions = new ChromeOptions();
 chromeOptions.AddArgument("--ignore-certificate-errors");
 chromeOptions.AddArgument("--allow-running-insecure-content");
 chromeOptions.AddArgument("--disable-extensions");
 chromeOptions.AddArgument("--start-maximized");

chromeOptions.AddAdditionalCapability("name", "TEST NAME"); //this gives an error when running the test

 DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
 desiredCapabilities.SetCapability("idleTimeout", 150);

 desiredCapabilities.SetCapability(ChromeOptions.Capability, chromeOptions);

 result = new RemoteWebDriver(new Uri(Settings.Browser.SeleniumHubAddress), desiredCapabilities);
 //result = new RemoteWebDriver(new Uri(Settings.Browser.SeleniumHubAddress), chromeOptions);

break;
```

**Comment by johnqa** [comment]
For some reason if I do 
 ```
DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
 desiredCapabilities.SetCapability("zal:idleTimeout", 150);
 desiredCapabilities.SetCapability(ChromeOptions.Capability, chromeOptions);
 result = new RemoteWebDriver(new Uri(Settings.Browser.SeleniumHubAddress), desiredCapabilities);

```

**Comment by diemol** [comment]
OK, glad it worked.

**Comment by Ananda1521** [comment]
Hi
I am facing the same problem while launching my selenium script in the Zalenium grid configuration.
@johnqa  Would you please help me on this or send me the code part where you have configured the desired capabilities.

**Comment by data-scientist94** [comment]
Hi all
I am facing an issue regarding cross browser testing using selenium grid with xunit framework. Here is my code to launch multiple instance of browser  on node machine which is working fine but i need different kind of browser to be launched. Please suggest any kind of help regarding this issue using Desired Capabilities without specifying the browser name to launch the browser.                                                                                                
             dynamic option;
            switch(seleniumConfig.GetValueOrDefault("browser"))
            {
                case "firefox":
                    option = new FirefoxOptions();
                    break;
                case "chrome":
                    option = new ChromeOptions();
                    break;
                case "opera":
                    option = new OperaOptions();
                    break;
                case "safari":
                    option = new SafariOptions();
                    break;
                case "IE":
                    option = new InternetExplorerOptions();
                    break;
                case "ie":
                    option = new InternetExplorerOptions();
                    break;
                case "internetExplorer":
                    option = new InternetExplorerOptions();
                    break;
                case "edge":
                    option = new InternetExplorerOptions();
                    break;
                default:
                    option = null;
                    break;
            }

            String seleniuHubAddress = seleniumConfig.GetValueOrDefault("seleniumserverhost");
            Uri selServerHost = null;

            try
            {
                selServerHost = new Uri(seleniuHubAddress);
            }
            catch (Exception e)
            {
                Console.WriteLine("Following error occured due to the reason: " + e);
            }
            return new RemoteWebDriver(selServerHost, option.ToCapabilities());
