### ISSUE TITLE
Local Host Configuration Error

### ISSUE THREAD

**Issue by RafaelCoura** [zalando/zalenium#685]
How do I for the Selenium containers, upload with the Host settings of the local machine where it is being started.

**Comment by diemol** [comment]
Hi @RafaelCoura,

What do you mean? To upload files in a Selenium test?

**Comment by RafaelCoura** [comment]
That's it.

I need to run an automation, in selenium, that needs to configure a host to get access to the screen.

I would like to know how do I get Zalenium, use my host configurations, location for the containers.

**Comment by diemol** [comment]
It is still not clear to me, and this looks more like a question than an issue or a bug. Could you please join us to the #zalenium channel at https://seleniumhq.herokuapp.com/?

Over there we can chat and there is more people who can actively help.


I'll close the issue and we can continue in Slack.
