### ISSUE TITLE
unknown error: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by jtamGCC** [zalando/zalenium#686]
Zalenium Image Version(s):  
- latest:  is that 3.13.0b? Not sure how to get version except it shows latest on docker image list

Docker Version:  
17.09.0-ce

OS: 
Windows 10

Docker Command to start Zalenium:  
docker run --rm -ti --name zalenium -p 4444:4444 `
-e ZALENIUM_EXTRA_JVM_PARAMS="-Dwebdriver.http.factory=apache" `
-v /var/run/docker.sock:/var/run/docker.sock `
-v /c/Users/Testuser1/temp/videos:/home/seluser/videos `
--privileged dosel/zalenium start `
--timeZone "America/New_York" `
--maxDockerSeleniumContainers 4 `
--desiredContainers 2 `
--videoRecordingEnabled false

## Expected Behavior -
I am running zalenium on windows10 with zalenium started using above command. I have 4 tests that I run.  All 4 tests should pass

## Actual Behavior -
One of the test (random) always seems to fail with error:

unknown error: DevToolsActivePort file doesn't exist (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.9.93-linuxkit-aufs x86_64) (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 61.68 seconds Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:19.891Z' System info: host: 'f31da9d7ec0f', ip: '172.17.0.5', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.93-linuxkit-aufs', java.version: '1.8.0_171' Driver info: driver.version: unknown

System.InvalidOperationException: unknown error: DevToolsActivePort file doesn't exist   (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.9.93-linuxkit-aufs x86_64) (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 61.68 seconds Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:19.891Z' System info: host: 'f31da9d7ec0f', ip: '172.17.0.5', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.93-linuxkit-aufs', java.version: '1.8.0_171' Driver info: driver.version: unknown

I start my chromedriver in my C# code by using:

string defaultTimeOutSeconds = "240";
ChromeOptions options = new ChromeOptions();
options.AddArgument("--ignore-certificate-errors");
options.AddArgument("--start-maximized"); // open Browser in maximized mode
options.AddArgument("--test-type");  // --enable-automation
options.AddArgument("--disable-gpu");   // applicable to windows os only
options.AddArguments("chrome.switches", "--disable-extensions");
options.AddArgument("disable-infobars"); // disabling infobars
options.AddUserProfilePreference("credentials_enable_service", false);
options.AddUserProfilePreference("profile.password_manager_enabled", false);
options.AddArgument("--no-sandbox");    // Bypass OS security model
options.AddArgument("--disable-dev-shm-usage"); // overcome limited resource problems

DesiredCapabilities capabilities = options.ToCapabilities() as DesiredCapabilities;          
capabilities.SetCapability("name", scenarioTitle); // adds testname for running with zalenium 
capabilities.SetCapability("idleTime", Convert.ToDouble(defaultTimeOutSeconds)+30); // sets zalenium timeout to 30 secs greater than driver timeout

RemoteWebDriver driver = new RemoteWebDriver(url, capabilities, TimeSpan.FromSeconds(Convert.ToDouble(defaultTimeOutSeconds)));

The error seems to be happening on the new RemoteWebDriver line.  Is this a resource problem? I am running on Windows 10 Pro with 16 GB memory.  If I set --maxDockerSeleniumContainers to 2, all tests pass.

**Comment by diemol** [comment]
I haven't seen that error before, have you checked this? https://stackoverflow.com/questions/50642308/org-openqa-selenium-webdriverexception-unknown-error-devtoolsactiveport-file-d

**Comment by jtamGCC** [comment]
I have tried everything in the stackflow link.  I still cannot consistently get all tests to pass when trying to use 4 containers.  Setting containers to 2 seems to work although that is very limited.  It also runs very slow.   Any other solutions would be helpful. Thanks.

**Comment by diemol** [comment]
Are you running exclusively Zalenium on that machine? Depending on what resources are available it is also how the containers will perform. For example, video recording is very CPU intense, and starting the browsers is also an expensive operation. That could explain the issue since it works well with 2 containers. Is there a way that you can measure CPU and RAM during the execution?

**Comment by jtamGCC** [comment]
The machine is exclusively for running selenium tests with zalenium.  I do not have video recording enable.  Unless I turn on video recording, there seems to be plenty of CPU and  Memory available according to Windows Task Manager.

**Comment by diemol** [comment]
As per this [comment](https://github.com/zalando/zalenium/issues/694#issuecomment-412861556), I think you are not running Zalenium right now, so we can revisit this issue when you find the resources for it.

Closing for now. Thanks.
