### ISSUE TITLE
zalenium on specific network

### ISSUE THREAD

**Issue by ghayo** [zalando/zalenium#689]
Hi,
The containers wont registered them to the hub when specify --network.
there is a way to do it?

Thanks a lot Guy
 
Zalenium Image Version(s):  latest
Docker Version:  18.03.1-ce
OS: Ubuntu16.04
Docker Command to start Zalenium:  

docker run --name zalenium --network ghayo_net --rm -ti -p 4444:4444 -p 5555:5555 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/hom e/seluser/videos dosel/zalenium start
## Expected Behavior -
everything should works
## Actual Behavior -
when I am running the command with --network the zalenium create the containers successfully but wont registered them to the hub

logs: 
Docker version 17.09.1-ce, build 19e2cf6
-- LOG 10:34:30:080727168 Ensuring docker works...
-- LOG 10:34:30:149349580 Ensuring no stale Zalenium related containers are still around...
-- LOG 10:34:30:176706031 Ensuring docker-selenium is available...
haveged: haveged starting up
Copying files for Dashboard...
Starting Nginx reverse proxy...
Starting Selenium Hub...
....10:34:31.122 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium build info: version: '3.13.0', revision: 'unknown'
10:34:31.129 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
.10:34:31.505 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Starting poller.
10:34:31.505 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Autostarting container, because 0 is less than min 2
..10:34:31.978 [main] INFO  d.z.ep.zalenium.aspect.HubAspect - Registering custom Zalenium servlets
.10:34:32.120 [main] INFO  org.openqa.grid.web.Hub - Selenium Grid hub is up and running
10:34:32.120 [main] INFO  org.openqa.grid.web.Hub - Nodes should register to http://172.18.0.17:4445/grid/register/
10:34:32.120 [main] INFO  org.openqa.grid.web.Hub - Clients should connect to http://172.18.0.17:4445/wd/hub
Selenium Hub started!
Sauce Labs not enabled...
Browser Stack not enabled...
TestingBot not enabled...
Zalenium is now ready!
*************************************** Data Processing Agreement ***************************************
By using this software you agree that the following non-PII (non personally identifiable information)
data will be collected, processed and used by Zalando SE for the purpose of improving our test
infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
of the IP address are collected.

See the complete license at https://github.com/zalando/zalenium/blob/master/LICENSE.md
*************************************** Data Processing Agreement ***************************************
haveged: haveged: RNDADDENTROPY failed!
10:34:33.753 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockeredSeleniumStarter - Created container [zalenium_tOh1aB] with dimensions [(1920, 1080)] and tz [sun.util.calendar.ZoneInfo[id="Europe/Berlin",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=143,lastRule=java.util.SimpleTimeZone[id=Europe/Berlin,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]].
10:34:33.754 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Created ContainerCreationStatus [isCreated=true, containerName=zalenium_tOh1aB, containerId=930fe0f01a891b7f9628197ba70512382ebb46a823ee28fb03b2920ff8915293, nodePort=40000].
10:34:34.840 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockeredSeleniumStarter - Created container [zalenium_Hs1Oen] with dimensions [(1920, 1080)] and tz [sun.util.calendar.ZoneInfo[id="Europe/Berlin",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=143,lastRule=java.util.SimpleTimeZone[id=Europe/Berlin,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]].
10:34:34.841 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Created ContainerCreationStatus [isCreated=true, containerName=zalenium_Hs1Oen, containerId=b9cae7ebe463149e582fa5ce614b18795bad40484bcc8106ef1cf059eeef4f63, nodePort=40001].
10:34:38.250 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container zalenium_tOh1aB started after 4496.
10:34:39.301 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container zalenium_Hs1Oen started after 4460.

**Comment by diemol** [comment]
Hi @ghayo,

I tried the following commands and it worked fine (also Ubuntu 16.04):

``` 
root@ubuntu:/home/ubuntu# docker network create ghayo_net
cb5aee22916daa1ff8bbe205061a8d57f801a29316ea7d90b8165501f9e277c8


root@ubuntu:/home/ubuntu# docker run --rm -ti --name zalenium --network ghayo_net -p 4444:4444       -v /var/run/docker.sock:/var/run/docker.sock       -v /tmp/videos:/home/seluser/videos       --privileged dosel/zalenium start
Docker version 17.09.1-ce, build 19e2cf6
-- LOG 19:48:41:436221413 Ensuring docker works...
-- LOG 19:48:41:461393428 Ensuring no stale Zalenium related containers are still around...
-- LOG 19:48:41:473618829 Ensuring docker-selenium is available...
haveged: haveged starting up
Copying files for Dashboard...
Starting Nginx reverse proxy...
Starting Selenium Hub...
...19:48:41.975 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium build info: version: '3.14.0', revision: 'unknown'
19:48:41.978 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
.19:48:42.209 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Starting poller.
19:48:42.209 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Autostarting container, because 0 is less than min 2
.19:48:42.575 [main] INFO  d.z.ep.zalenium.aspect.HubAspect - Registering custom Zalenium servlets
.19:48:42.650 [main] INFO  org.openqa.grid.web.Hub - Selenium Grid hub is up and running
19:48:42.651 [main] INFO  org.openqa.grid.web.Hub - Nodes should register to http://172.19.0.2:4445/grid/register/
19:48:42.651 [main] INFO  org.openqa.grid.web.Hub - Clients should connect to http://172.19.0.2:4445/wd/hub
Selenium Hub started!
Sauce Labs not enabled...
Browser Stack not enabled...
TestingBot not enabled...
Zalenium is now ready!
*************************************** Data Processing Agreement ***************************************
By using this software you agree that the following non-PII (non personally identifiable information)
data will be collected, processed and used by Zalando SE for the purpose of improving our test
infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
of the IP address are collected.

See the complete license at https://github.com/zalando/zalenium/blob/master/LICENSE.md
*************************************** Data Processing Agreement ***************************************
19:48:43.273 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockeredSeleniumStarter - Created container [zalenium_yImAzB] with dimensions [(1920, 1080)] and tz [sun.util.calendar.ZoneInfo[id="Europe/Berlin",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=143,lastRule=java.util.SimpleTimeZone[id=Europe/Berlin,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]].
19:48:43.273 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Created ContainerCreationStatus [isCreated=true, containerName=zalenium_yImAzB, containerId=55f68207c8a39a2d9dfc86b5030a4ac3e30b6f3dec556eb082dee3da646d15a8, nodePort=40000].
19:48:43.600 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockeredSeleniumStarter - Created container [zalenium_2Mefjx] with dimensions [(1920, 1080)] and tz [sun.util.calendar.ZoneInfo[id="Europe/Berlin",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=143,lastRule=java.util.SimpleTimeZone[id=Europe/Berlin,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]].
19:48:43.600 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Created ContainerCreationStatus [isCreated=true, containerName=zalenium_2Mefjx, containerId=b5e7cfd4e4e283fbd6a8fe10ebeead46971e709fc57bd01355a57a50c729d773, nodePort=40001].
19:48:46.279 [Thread-10] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.19.0.3:40000
19:48:46.288 [Thread-10] INFO  d.z.e.z.proxy.AutoStartProxySet - Registered a container 55f68207c8a39a2d9dfc86b5030a4ac3e30b6f3dec556eb082dee3da646d15a8 http://172.19.0.3:40000.
19:48:46.646 [Thread-11] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.19.0.4:40001
19:48:46.646 [Thread-11] INFO  d.z.e.z.proxy.AutoStartProxySet - Registered a container b5e7cfd4e4e283fbd6a8fe10ebeead46971e709fc57bd01355a57a50c729d773 http://172.19.0.4:40001.
19:48:46.757 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container zalenium_2Mefjx started after 3157.
19:48:46.772 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container zalenium_yImAzB started after 3499.

```

Please check your network configuration as many people use similar setups or "network=host" and this is normally working, otherwise we would have many issues reported about it.

**Comment by garfieldjty** [comment]
I tried to attach it to docker overlay network and it is not working.

To create an overlay network:
`docker network create --driver=overlay --attachable test-net`

And then run the zalenium:
`docker run --rm -ti --name zalenium --network test-net -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start`

The nodes are not registered to the hub.

**Comment by ghayo** [comment]
Hi,
it is still not working for me.
I am using overlay network and that is not working.

if in your command when you create the network with –driver overlay it will not registered the nodes

Can you please check it?

Thanks a lot Guy
