### ISSUE TITLE
Driver object to return the proxy port of the corresponding instance

### ISSUE THREAD

**Issue by diogopublio** [zalando/zalenium#69]
Is there a way for the Driver object to return the proxy port of the corresponding instance.

I am running many instances concurrent, and I would like to keep track for instance, the current instance I am debugging, which zalenium window is this process attached to ?
for example:
localhost:40101 or 40132 or anyother ?

**Comment by diemol** [comment]
I am not sure... I could check in the java bindings for Selenium to see if there is something like that.

What are you trying to achieve? Just to know where your test is running? If so, check these features from the live preview: https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#live-preview
Basically:
* With the name of your test, you can see where it is running.
* Or with a group name you can filter which nodes are shown in the live preview.

**Comment by diogopublio** [comment]
That will do, that's great. Thanks.
