### ISSUE TITLE
Tests stuck at "Shutting down node due to proxy being stuck | stale during a test."

### ISSUE THREAD

**Issue by jtamGCC** [zalando/zalenium#694]
Zalenium Image Version(s):
latest:  3.13.0
Docker Version:
18.06.0-ce
OS:
Windows 10
Docker Command to start Zalenium:
docker run --rm -ti --name zalenium -p 4444:4444 `
-v /var/run/docker.sock:/var/run/docker.sock `
-v /c/Users/Testauto1/temp/videos:/home/seluser/videos `
--privileged dosel/zalenium start `
--timeZone "America/New_York" `
--maxDockerSeleniumContainers 2 `
--desiredContainers 2 `
--videoRecordingEnabled false `
--firefoxContainers 0 `
--chromeContainers 2 `
--keepOnlyFailedTests true

## Expected Behavior -
Run 35 tests using 2 threads, tests should execute 2 at a time on 2 containers.

## Actual Behavior -
On test 32 of 35 completed, the tests get stuck showing 91% and 70 seconds left.  

On the windows powershell window that started up the docker run command, it shows:
13:15:38.519 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - [00e87eaa03d7694d06136f0b507708d0cb5d6d7de7a3dee40fb209fdac31653a] has been idle [164502] which is more than [90000]
13:15:38.582 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - [00e87eaa03d7694d06136f0b507708d0cb5d6d7de7a3dee40fb209fdac31653a] is stale.
13:15:38.582 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - 00e87eaa03d7694d06136f0b507708d0cb5d6d7de7a3dee40fb209fdac31653a Shutting down node due to proxy being stuck | stale during a test.
13:16:18.468 [pool-3-thread-1] INFO  d.z.e.z.c.DockerContainerClient - http://172.17.0.3:40000 [bash, -c, notify 'Zalenium', 'TEST TIMED OUT', --icon=/home/seluser/images/timeout.png]
13:16:32.021 [pool-3-thread-2] INFO  d.z.e.z.c.DockerContainerClient - http://172.17.0.4:40001 [bash, -c, notify 'Zalenium', 'TEST TIMED OUT', --icon=/home/seluser/images/timeout.png]
13:24:54.607 [pool-3-thread-1] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - 2081179276d0e9ef79c89459d3889c83b74ec51c436692ef452e049e954f4e1c stop-video: Video recording is disabled
13:25:00.686 [pool-3-thread-2] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - 00e87eaa03d7694d06136f0b507708d0cb5d6d7de7a3dee40fb209fdac31653a stop-video: Video recording is disabled
13:26:44.361 [pool-3-thread-1] INFO  d.z.e.z.c.DockerContainerClient - http://172.17.0.3:40000 [bash, -c, transfer-logs.sh]
13:27:45.788 [pool-3-thread-2] INFO  d.z.e.z.c.DockerContainerClient - http://172.17.0.4:40001 [bash, -c, transfer-logs.sh]

**Comment by diemol** [comment]
Hi @jtamGCC,

>Shutting down node due to proxy being stuck | stale during a test

That means that the node did not receive any Selenium commands for more than 90 seconds, are you sure your tests are not getting stuck?

**Comment by jtamGCC** [comment]
It seems I am having resource issues when running Zalenium.  The tests will run on the machines without running through docker and zalenium however when I try it with  zalenium, it never finishes.  I have to set it to 1 container in order for tests to complete.  I will revisit Zalenium when I have a machine with more resources.

**Comment by diemol** [comment]
OK, thanks for the feedback, closing this then.
