### ISSUE TITLE
Error: render error in "zalenium/templates/role-binding.yaml": template: zalenium/templates/role-binding.yaml:14:20: executing "zalenium/templates/role-binding.yaml" at <{{template "fullname...>: template "fullname" not defined

### ISSUE THREAD

**Issue by CatCassie** [zalando/zalenium#696]
Hello,

I tried a helm install with cluster role binding and I got this error:
Error: render error in "zalenium/templates/role-binding.yaml": template: zalenium/templates/role-binding.yaml:14:20: executing "zalenium/templates/role-binding.yaml" at <{{template "fullname...>: template "fullname" not defined
After some investigation, I think the issue is at line 14 of the role-binding.yaml file: 
name: {{ template "fullname" }}
this should use "zalenium.fullname" instead of "fullname" according to your _helper.tpl file.

**Comment by diemol** [comment]
Hi @CatCassie,

Thanks for pointing that out, would you like to send a PR to correct it?
