### ISSUE TITLE
Remove the need for manual docker pull of the selenium image

### ISSUE THREAD

**Issue by wmitsuda** [zalando/zalenium#702]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
3.14.0a
Docker Version:  
18.03.1-ce
OS: 
Amazon Linux ECS optimized AMI
Docker Command to start Zalenium:  
N/A

## Expected Behavior -
Actually, this is a feature request: it would be good to remove the need for the manual docker pull of the selenium image, why doesn't the zalenium itself can pull the image?

## Actual Behavior -
I'm using zalenium with ECS and it is now working fine, I can automate all the execution. The only remaining issue is that because zalenium doesn't pull the selenium image, I had to configure a "workaround" in each machine of my computing pool, making all the machines run a "docker pull" on startup to ensure all of them have the image pulled.

I had to configure it in all the machines because I've deployed an ECS service, so the zalenium container can be run in any of the machines.

**Comment by diemol** [comment]
Hi @wmitsuda

A while ago we added a flag "PULL_SELENIUM_IMAGE" but we forgot to document it, if you set it to true when starting Zalenium, it will pull the image. It wasn't tested in all envs, but perhaps it works in your scenario. 

If it works, would you help us to document it? Thanks!

**Comment by wmitsuda** [comment]
Hi, it works perfectly! I tested locally and also in ECS.

A simple example to run it locally:

`docker run --rm --name zalenium -p 4444:4444 -e PULL_SELENIUM_IMAGE=true -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium:3.14.0a start`

**Comment by diemol** [comment]
Cool, glad it works.
