### ISSUE TITLE
Is there a way I can pass the Configuration Parameters from my test ?

### ISSUE THREAD

**Issue by sachintalapudi** [zalando/zalenium#706]
Example:

For Enabling Sauce Labs, I have to manually run the below commands on Docker:

{
    export SAUCE_USERNAME=<your Sauce Labs username>
    export SAUCE_ACCESS_KEY=<your Sauce Labs access key>
    export SAUCE_LABS_URL=<your Sauce Labs url:port number>
    docker run --rm -ti --name zalenium -p 4444:4444 \
      -e SAUCE_USERNAME -e SAUCE_ACCESS_KEY -e SAUCE_LABS_URL\
      -v /tmp/videos:/home/seluser/videos \
      -v /var/run/docker.sock:/var/run/docker.sock \
      --privileged dosel/zalenium start --sauceLabsEnabled true
}

Instead, is there a way I can do this on as needed basis from my tests or test solution ? So, the idea is, I am trying to see if there is a way to control all Configuration Parameters from my tests or test solution.

Example:

For Disable Video Recording, I can pass the values from desiredCapabilities like so:

DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
desiredCapabilities.setCapability("recordVideo", false);

Thanks in advance.

**Comment by diemol** [comment]
Hi @sachintalapudi,

No, right now the only way to pass the env vars for Sauce Labs is the way you mention it. 

If you have any more questions, please join us on the #zalenium channel at https://seleniumhq.herokuapp.com/
