### ISSUE TITLE
Request to provide access local media inside a container (virtual web camera)

### ISSUE THREAD

**Issue by abannur** [zalando/zalenium#709]
Team , I need to access the local media (virtual web camera) inside zalenium container.
During my test run I need to transfer video and audio and validate the same.
Could you please let me know weather we can virtual web cam installed inside a container or it needs to implemented newly.

**Comment by abannur** [comment]
The container is run inside a VM so it has no access to any physical webcam.
We want to spin up multiple zalenium container for our test with virtual can access.
Can you please tell me how I can go about achieving  above two requirements

Thank you

**Comment by diemol** [comment]
@abannur to be honest, I don't really know how this can be achieved, but I suspect this needs to be implemented from scratch, perhaps reusing some existing components.

I suggest you go to different chats and post what you want to achieve and maybe different people can suggest different approaches.

Recommended chats about testing and related:
https://software-testers.herokuapp.com/
https://www.ministryoftesting.com/slack_invite
https://seleniumhq.herokuapp.com/
