### ISSUE TITLE
Selenium logs not loaded yet...

### ISSUE THREAD

**Issue by furkandogan** [zalando/zalenium#712]
Usually I run this script for my testing. But it can't load selenium logs. Can you help me?

"sudo docker run --rm -ti --name zalenium -d -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v "$workpath/$testnumber"/zalenium:/home/seluser/videos --privileged zalenium:latest start --desiredContainers 20 --maxDockerSeleniumContainers 20 --maxTestSessions 20 --screenWidth 1920 --screenHeight 1080 --timeZone "Europe/Istanbul" --videoRecordingEnabled true --keepOnlyFailedTests false --seleniumImageName elgalu-selenium"

**Comment by diemol** [comment]
@furkandogan for questions please join our channel #zalenium in https://seleniumhq.herokuapp.com/

More people are there and we can answer this type of questions faster and in a simple way.
