### ISSUE TITLE
Zalenium Integration with Sikuli

### ISSUE THREAD

**Issue by nkvangip** [zalando/zalenium#715]
Sikuli is an awesome open source project that can be used to automate the desktop applications.  Currently there is an open source project in git hub that integrated selenium server with sikuli. 

https://github.com/sterodium/selenium-grid-extensions

Will be great if Zalenium can integrate this extension as it will be a one shop stop for both web and desktop automation testing.

**Comment by diemol** [comment]
Hi @nkvangip,

That might be a good idea, yes. Nevertheless, we don't have any experience with Sikuli, nor bandwidth to look into that. Additionally, Zalenium is already doing many things, and adding one more level of complexity would make the project really hard to maintain and develop further.

If someone has interest in this, I suggest a new project is created and the Zalenium images can be reused for it... In the end, it is open source and anyone can extend it.
