### ISSUE TITLE
Download Dialog appears if mapping to volume /tmp/node/home/seluser/Downloads

### ISSUE THREAD

**Issue by KernowCode** [zalando/zalenium#716]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
zalenium-3.14.0b

Docker Version:  
18.06.1-ce-win73 (19507)

OS: 
Windows 10

Docker Command to start Zalenium:  
docker run --rm -ti --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos -v /downloads:/tmp/node/home/seluser/Downloads --privileged dosel/zalenium start

## Expected Behavior -
Download dialog should not be present when downloading from target page

## Actual Behavior -
Download dialog is present and not automatically downloaded to downloads folder,

This is happening if you add the '-v /downloads:/tmp/node/home/seluser/Downloads'. If this option is removed then it downloads normally without the download dialog.

**Comment by KernowCode** [comment]
This change to the docker run command seems to help
docker run --rm -ti --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos -v "/c/code/CPM Automation2/Docker-SeleniumGrid2/downloads:/tmp/node/home/seluser/Downloads" --privileged dosel/zalenium start

**Comment by diemol** [comment]
Hi @KernowCode,

In most of the cases, the prompt for download will pop up when Chrome does not have write permissions on that directory, which in the case is `/downloads`. I guess that Docker cannot write there, and that is why it works when you changed it to `-v "/c/code/CPM Automation2/Docker-SeleniumGrid2/downloads`.

Closing this as it is not a Zalenium issue.
