### ISSUE TITLE
zalenium on overlay network not working

### ISSUE THREAD

**Issue by ghayo** [zalando/zalenium#723]
Hi,
The containers wont registered them to the hub when specify **overlay** --network.
there is a way to do it?

Thanks a lot Guy

Zalenium Image Version(s): latest
Docker Version: 18.03.1-ce
OS: Ubuntu16.04
Docker Command to start Zalenium:

docker run --name zalenium --network ghayo_net --rm -ti -p 4444:4444 -p 5555:5555 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/hom e/seluser/videos dosel/zalenium start

Zalenium Image Version(s):  
latest
Docker Version:  
18.03

OS: 
Ubuntu (linux)
Docker Command to start Zalenium:  

## Expected Behavior -
everything should works.
## Actual Behavior -
when I am running the command with --network --driver overlay the zalenium create the containers successfully but wont registered them to the hub

logs:
Docker version 17.09.1-ce, build 19e2cf6
-- LOG 10:34:30:080727168 Ensuring docker works...
-- LOG 10:34:30:149349580 Ensuring no stale Zalenium related containers are still around...
-- LOG 10:34:30:176706031 Ensuring docker-selenium is available...
haveged: haveged starting up
Copying files for Dashboard...
Starting Nginx reverse proxy...
Starting Selenium Hub...
....10:34:31.122 [main] INFO o.o.grid.selenium.GridLauncherV3 - Selenium build info: version: '3.13.0', revision: 'unknown'
10:34:31.129 [main] INFO o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
.10:34:31.505 [AutoStartProxyPoolPoller] INFO d.z.e.z.proxy.AutoStartProxySet - Starting poller.
10:34:31.505 [AutoStartProxyPoolPoller] INFO d.z.e.z.proxy.AutoStartProxySet - Autostarting container, because 0 is less than min 2
..10:34:31.978 [main] INFO d.z.ep.zalenium.aspect.HubAspect - Registering custom Zalenium servlets
.10:34:32.120 [main] INFO org.openqa.grid.web.Hub - Selenium Grid hub is up and running
10:34:32.120 [main] INFO org.openqa.grid.web.Hub - Nodes should register to http://172.18.0.17:4445/grid/register/
10:34:32.120 [main] INFO org.openqa.grid.web.Hub - Clients should connect to http://172.18.0.17:4445/wd/hub
Selenium Hub started!
Sauce Labs not enabled...
Browser Stack not enabled...
TestingBot not enabled...
Zalenium is now ready!
*************************************** Data Processing Agreement ***************************************
By using this software you agree that the following non-PII (non personally identifiable information)
data will be collected, processed and used by Zalando SE for the purpose of improving our test
infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
of the IP address are collected.

See the complete license at https://github.com/zalando/zalenium/blob/master/LICENSE.md
*************************************** Data Processing Agreement ***************************************
haveged: haveged: RNDADDENTROPY failed!
10:34:33.753 [AutoStartProxyPoolPoller] INFO d.z.e.z.p.DockeredSeleniumStarter - Created container [zalenium_tOh1aB] with dimensions [(1920, 1080)] and tz [sun.util.calendar.ZoneInfo[id="Europe/Berlin",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=143,lastRule=java.util.SimpleTimeZone[id=Europe/Berlin,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]].
10:34:33.754 [AutoStartProxyPoolPoller] INFO d.z.e.z.proxy.AutoStartProxySet - Created ContainerCreationStatus [isCreated=true, containerName=zalenium_tOh1aB, containerId=930fe0f01a891b7f9628197ba70512382ebb46a823ee28fb03b2920ff8915293, nodePort=40000].
10:34:34.840 [AutoStartProxyPoolPoller] INFO d.z.e.z.p.DockeredSeleniumStarter - Created container [zalenium_Hs1Oen] with dimensions [(1920, 1080)] and tz [sun.util.calendar.ZoneInfo[id="Europe/Berlin",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=143,lastRule=java.util.SimpleTimeZone[id=Europe/Berlin,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]].
10:34:34.841 [AutoStartProxyPoolPoller] INFO d.z.e.z.proxy.AutoStartProxySet - Created ContainerCreationStatus [isCreated=true, containerName=zalenium_Hs1Oen, containerId=b9cae7ebe463149e582fa5ce614b18795bad40484bcc8106ef1cf059eeef4f63, nodePort=40001].
10:34:38.250 [AutoStartProxyPoolPoller] INFO d.z.e.z.proxy.AutoStartProxySet - Container zalenium_tOh1aB started after 4496.
10:34:39.301 [AutoStartProxyPoolPoller] INFO d.z.e.z.proxy.AutoStartProxySet - Container zalenium_Hs1Oen started after 4460.

**Comment by diemol** [comment]
Hi @ghayo,

It won't work because:
>Taken from https://docs.docker.com/network/overlay/ -> the overlay network driver creates a distributed network among multiple Docker daemon hosts. 

When using Zalenium with docker, it only works on a single docker daemon. Using something like network overlay or docker swarm is not supported. (Not supported because it is not implemented, however, if you want to, feel free to send us a PR with a great implementation :) ).

If you are looking to run Zalenium in several hosts, you should try it with Kubernetes, the how to is available in the docs -> https://opensource.zalando.com/zalenium/#kubernetes
