### ISSUE TITLE
VNC viewer for nodes aren't displyed in the browser

### ISSUE THREAD

**Issue by nsalin** [zalando/zalenium#732]
Hi guys, I'm trying to run some tests on my local machine through Zalenium, but the VNC views for nodes aren't displayed in the browser. The tests run successfully and the the videos can be found locally but I cannot see the VNC views, I tried with the latest Firefox and Chrome browsers.

Zalenium Image Version(s):  
3.14.0c
Docker Version:  
18.06.1-ce
OS: 
macOS: High Sierra, 10.13.6
Docker Command to start Zalenium:  
docker run --rm -ti --name zalenium -p 4444:4444     -v /var/run/docker.sock:/var/run/docker.sock     -v /tmp/videos:/home/seluser/videos     --privileged dosel/zalenium start
## Expected Behavior -
The VNC views for nodes should be available in the browser
## Actual Behavior -
VNC views for nodes aren't displyed
<img width="1414" alt="screen shot 2018-09-28 at 17 11 06" src="https://user-images.githubusercontent.com/8618602/46214170-2d000000-c343-11e8-8d9d-7517b7d6eefc.png">

**Comment by diemol** [comment]
Hi @nsalin,

Did you try http://localhost:4444/grid/admin/live?
Check more details at https://opensource.zalando.com/zalenium/

If you were trying this URL and it still didn't work, feel free to reopen the issue and provide detailed steps to reproduce it.
