### ISSUE TITLE
Not able to start chrome in headless mode 

### ISSUE THREAD

**Issue by diogopublio** [zalando/zalenium#734]
I tried multiple ways starting chrome headless like Watir (ruby gem for selenium) informs in their documentation, however it does not seems to work (http://watir.com/guides/chrome/)

I have latest version of chromedriver,chrome,zalenium,selenium and watir (ruby gem for selenium)

<img width="642" alt="captura de tela 2018-09-29 as 17 00 49" src="https://user-images.githubusercontent.com/1724596/46250075-a7935300-c409-11e8-84ab-bcd605e5ebda.png">

**Comment by pearj** [comment]
If you want some help you’re going to need to add zalenium logs and some code snippets of what you actually tried. 

Have you read the documentation at https://opensource.zalando.com/zalenium/?

Zalenium is just a selenium grid after all. 

This doesn’t sound like a Zalenium problem but that you don’t know how Watir works with Selenium Grid

**Comment by diemol** [comment]
Closing as we didn't get an answer, please feel free to reopen when more complete information is provided.

**Comment by jithinkmatthew** [comment]
I am running protractor tests in Zalenium. In the [config](https://github.com/angular/protractor/blob/5.4.1/example/conf.js) file, used [headless mode](http://www.protractortest.org/#/browser-setup#using-headless-chrome) configuration. 

While running test against firefox browser, it is working as expected. But for chrome, it is opening a new chrome browser.

**Comment by diemol** [comment]
@jithinkmatthew I just checked the links you mention, I did not find anything that shows how headless is being used.

Please show us how exactly the capabilities you are using look like, otherwise it is very hard to help.

**Comment by jithinkmatthew** [comment]
I created a sample repository [here](https://github.com/jithinkmatthew/protractor-zalenium). Please check it

**Comment by diemol** [comment]
In the same way you prefix the Firefox option here
https://github.com/jithinkmatthew/protractor-zalenium/blob/master/conf.js#L25

You need to do the same for the Chrome options here
https://github.com/jithinkmatthew/protractor-zalenium/blob/master/conf.js#L13
The prefix is `goog:`

**Comment by diemol** [comment]
What is the version of the Selenium Grid you are using?

**Comment by jithinkmatthew** [comment]
```
$ webdriver-manager version
[16:01:10] I/version - webdriver-manager 12.1.0
```

**Comment by diemol** [comment]
That is an npm package, not Selenium Grid. Anyway, in recent versions of Grid, you need to prefix the Chrome options as well `goog:chromeOptions`.

This is not really related to Zalenium but more a general Selenium question.

**Comment by jithinkmatthew** [comment]
Changed my configuration to 

```
    capabilities: {
      browserName: 'chrome',
    
      'goog:chromeOptions': {
         args: [ "--headless" ]
       }
    },

```

It is working as expected. Thanks

**Comment by SaifuddinR** [comment]
Thanks. This helps. Adding 'goog' to chrome options Works.
