### ISSUE TITLE
Ability to customize Test File Name Template

### ISSUE THREAD

**Issue by gaiquelsf** [zalando/zalenium#737]
We started using Zalenium to run our automated test suites, and it is a great tool.

However we found that it is not possible to get video and log file name from our tests code because it contains a timestamp. Since we store the test result on a database within the logs and the recording video, we need to know what file name will be created.

Thoughts on adding a new capability where "test file name template" can be customized? This will allow to set video and log file names as necessary.

Thank you all about any suggestion here.

Best regards

**Comment by gaiquelsf** [comment]
[#738 PR](https://github.com/zalando/zalenium/pull/738) has been opened

**Comment by diemol** [comment]
Closed via #738, thanks @gaiquelsf!

**Comment by gaiquelsf** [comment]
@diemol I saw on Zalenium home page that break lines didn't work on the .md documentation file, should I add <br/> html break lines?

**Comment by diemol** [comment]
Ah yes, with this template one needs to add `<br>` explicitly for a line break. If you want to you can send a PR for that, thanks!

**Comment by diemol** [comment]
Oh sorry! Seems I screwed up, I will release again :)

**Comment by diemol** [comment]
https://github.com/zalando/zalenium/releases/tag/3.14.0f
