### ISSUE TITLE
Trying to install extension to remote chrome

### ISSUE THREAD

**Issue by chebyte** [zalando/zalenium#739]
Hello there, I'm trying to install a extension to chrome but I cant figure out

I made the following code

````
client = Selenium::WebDriver::Remote::Http::Default.new
caps = Selenium::WebDriver::Remote::Capabilities.chrome("chromeOptions" => {
       "extensions" => [
        Base64.strict_encode64(File.open('path/file.crx', 'rb').read)
      ]
    })

url = "http://localhost:4444/wd/hub"

browser = Watir::Browser.new :remote, {desired_capabilities: caps, http_client: client, url: url}
````

the browser open fine but not load extension

thanks for advance

**Comment by diemol** [comment]
Hi @chebyte,

I've never installed extensions, but the only thing I can see is that `chromeOptions` should have the `goog:` prefix -> `goog:chromeOptions`.

If you try that code, does it work in a non-docker environment?

**Comment by chebyte** [comment]
ey @diemol thanks a lot!, you rocks man!, now is working, was missing this prefix

thanks!
