### ISSUE TITLE
Driver fail if change platform parameter

### ISSUE THREAD

**Issue by diogopublio** [zalando/zalenium#74]
I am running under a linux machine, if I set platform as Linux it works fine:

{'name': 'Docker 239', 'chromeOptions': {'args': [], 'extensions': []}, 'javascriptEnabled': True, 'os_version': '10', 'platform': 'LINUX', 'browserName': 'chrome', 'version': '', 'browser_version': '50.0', 'resolution': '1366x768'}
it opens the webdriver

if I set any other platform I get error like it could not find the session:

Error starting chrome: Message: Error forwarding the new session cannot find : Capabilities [{os=Windows, os_version=10, name=Docker 307, browserName=chrome, javascriptEnabled=true, chromeOptions={args=[], extensions=[]}, browser_version=50.0, version=, resolution=1366x768, platform=WINDOWS}]

Error starting chrome: Message: Error forwarding the new session cannot find : Capabilities [{os=Windows, os_version=10, name=Docker 323, browserName=chrome, javascriptEnabled=true, chromeOptions={args=[], extensions=[]}, browser_version=50.0, version=, resolution=1366x768, platform=MAC}]

Has anyone faced the same issue ?

**Comment by diemol** [comment]
Hi @diogopublio, 

Zalenium per se does not support anything different than Chrome-Firefox/Linux.

If you want to use any other browser/platform combination, you would need to plug any of the integrated cloud testing services we support (BrowserStack, Sauce Labs or TestingBot). With this, you can combine Zalenium and other platforms for a full browser/platform coverage.

Check https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#starting-zalenium

**Please note that we are not related commercially to any of those providers at all. We just implemented those integrations since we use them internally (except TestingBot, which was integrated thanks to a PR sent by them).**

**Comment by diogopublio** [comment]
hey @diemol 

Thanks for the quick reply! I understand your point. 2 follow up questions:

1. maybe loading a chrome extension that does this change can work. does this makes sense to you ?

2. In Usage Examples under docs you show a example line that seems like you could set the platform:

`desiredCapabilities.setCapability(CapabilityType.PLATFORM, Platform.LINUX);`

so this setting is overriden when zalenium actually start the docker instance ?

**Comment by diemol** [comment]
Hi @diogopublio,

Sorry for not replying before... 

> maybe loading a chrome extension that does this change can work. does this makes sense to you ?

Do you mean installing a Chrome extension that emulates Internet Explorer or something like that? If so, I don't know if this is suitable for serious testing. I would try it locally first.

> In Usage Examples under docs you show a example line that seems like you could set the platform:

That is Java code that shows the normal way of setting the platform for a test capability, Zalenium does not overwrite the platform. It just uses it to decide if the test can be executed in docker-selenium or not.

**Comment by diemol** [comment]
@diogopublio, if you have more questions, please feel free to open a new issue or you can also try Gitter.

I'll close this issue due to inactivity.

**Comment by diogopublio** [comment]
@diemol just updating, I could not change that using the platform parameter (ex. platform=MAC)
I think this is not possible.

**Comment by diemol** [comment]
@diogopublio 
If you use platform=MAC, it won't run in Zalenium of course, you will need something that provides the MAC capabilities, that is why I suggested using a cloud provider for this part.
