### ISSUE TITLE
Kubernetes and Openshift standardization

### ISSUE THREAD

**Issue by arnaud-deprez** [zalando/zalenium#750]
Hi,

Currently there are 2-3 ways to deploy `zalenium` on Openshift that I'm aware of: 

1. Apply the kubernetes dir https://github.com/zalando/zalenium/tree/master/kubernetes as documented [here](https://opensource.zalando.com/zalenium/#kubernetes)
1. Process and then apply the template https://github.com/zalando/zalenium/blob/master/docs/k8s/zalenium-template.yaml
1. Install with helm https://github.com/zalando/zalenium/tree/master/docs/k8s/helm

It would be nice if we can manage a helm template which is compatible with all Kubernetes vanilla and get rid of the others.

To be compatible with all Kubernetes vanilla, it means considering the default policy in Openshift: 

1. A pod cannot run as root. It is started with a random user id part of the root user group (0).
1. A pod cannot run with privilege.

From what I know, it should be possible to follow these 2 guidelines in `zalenium`.

Also for users that do not want `tiller` which is coming with `helm v2`, we can document the alternative of 

```
helm template --set foo=bar docs/k8s/helm/local/zalenium | kubectl apply -n <target_namespace> -f -
``` 

which is the equivalent of 

```
oc process -p foo=bar -f docs/k8s/zalenium-template.yaml | oc apply -n <target_namespace> -f -
```

I tried the current helm template in openshift and it is not working because of the init container https://github.com/zalando/zalenium/blob/master/docs/k8s/helm/local/zalenium/templates/deployment.yaml#L24-L29 (which is not defined in the openshift template).

I'm not sure why this is necessary especially because it comes from a PersitentVolume so it should have the appropriate rights already.

I think this would simplify life of users like that tries to find way to install `zalenium` in kubernetes.

What do you think ?

And then why not eventually publish this helm chart to the [official repo](https://github.com/helm/charts/) ?

**Comment by diemol** [comment]
Hi @arnaud-deprez,

There are also templates to deploy to OpenShift. The containers are already working in those non-root environments.

To avoid long answers... Yes, if you feel like this would be an improvement, go for it and help us unify the way it can be deployed. The documentation would also need a change. All that improves Zalenium is welcomed.

How do you want to proceed? Should I leave this issue open and you comment everytime you advance in the PR? Or should I close it and you open a PR where we discuss details over there.

Thanks for the initiative and let us know!

**Comment by arnaud-deprez** [comment]
I can start something and propose a PR here but it will not be before 2 weeks because I'm in hollidays.  So if you can wait, fine ! :)

**Comment by diemol** [comment]
Sounds good. There is no hurry at all, so please send us a PR whenever you can :)

**Comment by arnaud-deprez** [comment]
Ok :).
But can you please keep this opened so it is like a reminder to me and I can link my PR to it. 
Cheers

**Comment by diemol** [comment]
Reopened

**Comment by arnaud-deprez** [comment]
WIP: https://github.com/arnaud-deprez/zalenium/tree/feature/k8s-vanilla-standardization

**Comment by pearj** [comment]
The `initContainers` came about as part of #631, I thought `initContainers` were a reasonable compromise as opposed to adding it directly to `scripts/entry.sh`.

How did you go about fixing initContainers? Or did you not solve that yet?

Also, it looks like you reformatted a lot of the yaml files which makes it hard to see what you changed, can you try to match the existing indentation?

**Comment by arnaud-deprez** [comment]
Hi @pearj,

I didn't reformat a lot but I've put a labels in a template function and it seems that for some files, it consider that the whole file has changed. 
I will check that, thanks.

For the initContainer, it is very strange because it is only present in the helm chart but not in the `Openshift template` nor in `GKE` nor in https://github.com/zalando/zalenium/blob/master/kubernetes/zaleniumDeployment.yaml for instance.
I've tested `Openshift template` and it was working perfectly fine.

IMO, the deployment should remain compliant with `Openshift security guidance` and so running `sudo` command at runtime is not recommended and is even prohibited by default in `Openshift`.
So normally, the necessary permissions should be properly configured in the docker image and not in the container at runtime.

Also, if someone knows what is the usage of the `mounted` volume here https://github.com/zalando/zalenium/blob/master/docs/k8s/helm/local/zalenium/templates/deployment.yaml#L151-L152 or https://github.com/zalando/zalenium/blob/master/kubernetes/zaleniumDeployment.yaml#L56-L57, can he enlighten me ? Because this volume does not exist in other deployments such as `Openshift template` nor `GKE`.

**Comment by pearj** [comment]
`/tmp/mounted` is a magic directory that gets remounted on all the pods. It’s useful if you want to be able to make files available for uploading for instance on a pod. Or maybe you want to override a file on all pods, maybe the ca certs for example. 

I’m fairly certain that feature is documented.

**Comment by arnaud-deprez** [comment]
Thank you for the input, I've never used it but I'm sure it must documented as well :-).
I'm quite busy for now, I'll try to get back on it next week, hopefully.
