### ISSUE TITLE
Zalenium falls over with 503 Service Unavailable soon after running tests

### ISSUE THREAD

**Issue by cbll** [zalando/zalenium#759]
Zalenium Image Version(s):  
3.14.0f

## Expected Behavior -

We are constraining a test suite by amount of workers in a .NET project which is parameterized through a Jenkins build that then runs on Zalenium.

It has been beefed up quite a bit with resources and doesn't hit the limits at all. We'd expect it to scale to ~50 nodes without issues. We currently use Selenium-grid with a constant of 70 nodes with the same resource allocation and it doesn't have any issues. 

## Actual Behavior -

If we scale the amount of workers(hence, nodes for Zalenium), it will fail quite fast - throwing `503 Service Unavailable`. 

Before the inevitable crash of the hub itself, we notice a few error messages from the nodes:

`Failed to pull image "elgalu/selenium:latest": rpc error: code = Unknown desc = Error response from daemon: unauthorized: authentication required`

`Failed to pull image "elgalu/selenium:latest": rpc error: code = Unknown desc = Error response from daemon: received unexpected HTTP status: 503 Service Unavailable`

What's strange is that a lot of pods before this manages to pull the image just fine. It happens seemingly randomly, but simultaniously with the Zalenium hub becoming unstable(accessing `/grid/admin/live` will also throw a 503).

What we've tried:

Changing `elgalu/selenium:latest` to `elgalu/selenium:3.14.0-p14`. This appeared to speed up performance quite a bit - I am not Kubernetes expert at all, but I'd guess the `latest` tag would make a request to Docker-hub for each new pod creation to pull down the image, whereas a specific version - as here - caches it locally in the cluster instead. I'm not sure if this is correct.

If not, could the following hard-coded setting for the pod creation be a potential issue? https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/container/kubernetes/KubernetesContainerClient.java#L560

Regardless, we still face the issue of the service falling over quite fast. Resources are monitored; network IO doesn't look suspecious, and it has plenty of memory + CPU pools to take from, and doesn't hit anywhere near the limits.

Any idea what this could be? I'm not entirely sure it's related to Zalenium, more likely to our cluster setup, but any pointers towards a solution would greatly be appreciated.

**Comment by cbll** [comment]
We've noticed the nodes fail the readiness state since they are only getting 5 seconds delay + 1 second timeout window. 

Is there a way to parameterize these values, or overwrite them? 

https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/container/kubernetes/KubernetesContainerClient.java#L574

**Comment by cbll** [comment]
See [PR #764 ](https://github.com/zalando/zalenium/pull/764)

**Comment by cbll** [comment]
Update: We suspect the issue might not be with Zalenium itself, but rather some Docker/k8s internals on our cluster - specifically versioning of each and compatibility. We'll try to upgrade and see if it helps. Will update after :-)

**Comment by diemol** [comment]
I will close this for now, in case anything else is needed, feel free to comment or open a new issue.
