### ISSUE TITLE
Files in /home/seluser/videos belonging to root

### ISSUE THREAD

**Issue by schnatterer** [zalando/zalenium#760]
I'm trying to run zalenium during a Jenkins build, in order to archive the test videos for failing builds.
My problem is that I can't delete zalenium's video folder (that was mounted into the container) on subsequent builds, because it contains files belonging to `root`, wheras my jenkins is run with its own non-root user.

Zalenium Image Version(s):  
3.14.0g

Docker Version:  18.03.0-ce

If using docker-compose, version:  -

OS: Ubuntu 16.04.4 LTS

Docker Command to start Zalenium:  
```bash
docker run -d -e HOST_UID=1002 -e HOST_GID=1003 -v /var/run/docker.sock:/var/run/docker.sock -v /home/jenkins/workspace/.../zalenium:/home/seluser/videos  dosel/zalenium:3.14.0f start
```
I had a look into `scripts/entry.sh` but am quite confused by all the UID/GIDs and sudoing 😕
Tried adding `USE_KUBERNETES=true ` without luck.
From a security perspective I would also love to add `-u 1002:1003` but can't do this because of the sudoing.

If using Kubernetes, specify your environment, and if relevant your manifests:  -

## Expected Behavior 

All files in the video folder (`/home/seluser/videos` in the zalenium container)  belong the the UID/GID passed by the env vars.

## Actual Behavior

```bash
ls -la /home/jenkins/workspace/.../zalenium

drwxr-xr-x  2 root    root    4096 Nov  5 13:39 css/
-rwxr--r--  1 root    root     959 Nov  5 13:39 index.html*
drwxr-xr-x  2 root    root    4096 Nov  5 13:39 js/
```

**Comment by schnatterer** [comment]
In case this should be relvant for someone else: I worked around this by using the reset option provided by zalenium's dashboard (HTTP GET on `dashboard/cleanup?action=doReset`).
The solutions with Jenkins is also open source, have a look at [loudogu/spring-petclinic](https://github.com/cloudogu/spring-petclinic/blob/d11fdd8add2d3e5d9657d775156bceece07f0685/Jenkinsfile#L46).

The downside of this workaround is that the files listed above in the "Actual Behavior" section are not cleared by the reset. So once you run the job, Jenkins will never be able to delete the workspace, because those file are owned by root. You would have to access the workspace folder on the agent via SSH and delete the files with sudo rights, if you would ever like to get rid of the job or workspace...

**Comment by blaw2422** [comment]
@schnatterer , if using the kubernetes helm chart, you can see where they are using an `initContainer` to chown the dir.  not sure why its not setup like that by the `Dockerfile`

**Comment by pearj** [comment]
@blaw2422 I'm not super keen to include chowning in the `Dockerfile` cmd script on every start because it doesn't affect everybody, it seems to be up to the implementation of the kubernetes cluster.  For example, I never experienced this issue in OpenShift.  I suppose in theory the script could detect if sudo is available and `chown` if the permissions are wrong.  But I think it's a kubernetes cluster configuration issue as it hasn't been widely reported.  Unless people worked around it another way, or it only affects new versions of kubernetes?
It's discussed at length in #631 

But I'm happy to be wrong, if most people are affected, then it probably does belong in the start script.

**Comment by pearj** [comment]
@blaw2422 specifically look at https://github.com/zalando/zalenium/issues/631#issuecomment-403458625 that could be a solution to not using `initContainers`

**Comment by schnatterer** [comment]
@blaw2422 thanks for getting back to me. I don't think that the owner of the dir is related to my issue. I think that some processes running as root writes files in it *after* the container starts.

I wonder why and if I can avoid it or at least make the files belong to a non root user or allow "the world" to delete them.

**Comment by diemol** [comment]
@schnatterer it makes sense, I think I also bumped into this issue a while ago and didn't take the time to fix it, that's why we use `sudo` sometimes when running the tests in Travis.

We will have a look and try to provide something that works out of the box.

**Comment by schnatterer** [comment]
Thanks a lot @diemol!
I can confirm 3.141.59f now stores video as non-root, as UID/GID `1000`.

For my use case running on Jenkins, I'd like to change the UID/GID the files are stored with, as the Jenkins user necessarily have UID/GID 1000.

However, when I run the zalenium container with `-u 1001:1001 -e HOST_GID=1001 -e HOST_UID=1001`
(using an image that uses `groupadd -f` [here](https://github.com/zalando/zalenium/blob/5f9f22b3c9f79e46e4795b633dc065ce3cc00e38/scripts/entry.sh#L38)) the files belong to `root` again.

Is there something else I can do? Does this belong to this issue or is it another issue?

**Comment by diemol** [comment]
@schnatterer could you please the full `docker run` command you are using? Somehow I cannot reproduce.

**Comment by schnatterer** [comment]
@diemol thanks for getting back to me.

Somehow I now cannot reproduce the files belonging to `root` / UID 0. 😕
However, I the following leads to files always belonging to UID 1000, no matter which UID I run it with. This still causes problems in my Jenkins CI use case, because I can't delete the files in the next job execution, when jenkins does not happen to be running as UID 1000.

```bash
rm -rf /tmp/videos && mkdir /tmp/videos
docker run -d --name zalenium-patched -u 1042:1042 -e HOST_GID=1042 -e HOST_UID=1042 \         
  -v /var/run/docker.sock:/var/run/docker.sock  -v /tmp/videos:/home/seluser/videos \
  --privileged \                                 
  dosel/zalenium:3.141.59f  start

# Run a selenium test 

ls -ln /tmp/videos | grep mp4
# Result:
# -rw-r--r-- 1 1000 1000 1672561 Jan 14 17:50 zalenium_a614c7a9_49b6_478d_a820_d634cd7e627f_chrome_LINUX_20190114175017873_COMPLETED.mp4
```
In case it matters, here's my (a bit hacky TBH) workaround for running as UID/GID 1001.
Result is the same: mp4 belongs to UID 1000.

```bash
# Avoid error "groupadd: GID '1001' already exists"
docker run -d --name zalenium-base -v /var/run/docker.sock:/var/run/docker.sock dosel/zalenium:3.141.59f start
curl https://raw.githubusercontent.com/zalando/zalenium/9712cb20db6bcce52bcd45427786478780c764b7/scripts/entry.sh > /tmp/entry.sh
vi /tmp/entry.sh
# Replace sudo groupadd --gid ${CURRENT_GID} selgroup
# By: sudo groupadd -f --gid ${CURRENT_GID} selgroup
chmod +x /tmp/entry.sh
docker cp /tmp/entry.sh zalenium-base:/usr/bin/entry.sh
docker commit zalenium-base patched-zalenium

rm -rf /tmp/videos && mkdir /tmp/videos
docker run -d --name zalenium-patched -u 1001:1001 -e HOST_GID=1001 -e HOST_UID=1001 \         
  -v /var/run/docker.sock:/var/run/docker.sock  -v /tmp/videos:/home/seluser/videos \
  --privileged \                                 
  patched-zalenium start

# Run a selenium test 

ls -ln /tmp/videos | grep mp4
```

**Comment by diemol** [comment]
Thanks for the descriptive comment, now I get it :)

So, if you change the `entry.sh`, by:
```
# Replace sudo groupadd --gid ${CURRENT_GID} selgroup
# By: sudo groupadd -f --gid ${CURRENT_GID} selgroup
```
then it works?

If so, I don't see why we could not add that to the script. Would you like to send us a PR for that?

**Comment by diemol** [comment]
Ok, after reading again, _now I think_ I get it...
So even with the workaround, it does not work, the files end up with UID/GID 1000. I'll have a look again.

**Comment by schnatterer** [comment]
I actually spent some time formulating my answer to make it not confusing, but obviously failed 😛 

I Should have left the UID 1001 out of it, because it's not directly related to the acutal issue here. 
Still, if the `-f` solution is alright with you I will open a PR ASAIC in order to resolve the ` "groupadd: GID '1001' already exists"` error when running with GID 1001.

You're correct, the actual issue for #760 is that no matter which UID/GID (I tried 1001 and 1042) I start the container with, it will always result in the mp4s belongin to UID 1000.
Hope you can reproduce.

**Comment by schnatterer** [comment]
Hey @diemol,
I can confirm that `zalenium:3.141.59g` provides what I need for making the [cloudogu/zalenium-build-lib](https://github.com/cloudogu/zalenium-build-lib) for Jenkins [store videos as the Jenkins user](https://github.com/cloudogu/zalenium-build-lib/commit/30923630ced3089ae0861bef25b60903429841aa#diff-d99059fc890d0593be1fb01b977d65a4R23). :champagne:

Thanks so much for your efforts.

**Comment by diemol** [comment]
Cool, glad it worked!
