### ISSUE TITLE
I'm not able to replace selenium env vars

### ISSUE THREAD

**Issue by meyerbro** [zalando/zalenium#761]
I added the env var SEL_BROWSER_TIMEOUT_SECS to my Zalenium Grid, it went to the Zalenium Docker Container but not to any Selenium containers...

They are still having this:
SEL_BROWSER_TIMEOUT_SECS=16000

This is also an old request:
https://github.com/zalando/zalenium/issues/447

This was added on that time but the code was removed after that...

How can this be achieved now?

Thanks

**Comment by meyerbro** [comment]
If I use the SELENIUM_NODE_PARAMS env var, it makes all new selenium containers to crash as there's a duplicated "browserTimeout" parameter... The code doesn't try to replace the parameter but just add it in the end...

**Comment by diemol** [comment]
Hi @meyerbro,

Sorry we missed your previous comment, we usually don't check closed issues unless the OP reopens them.

Going back to the question, why do you need to change the browserTimeout? (By the way, browserTimeout has been broken in Grid since a few releases ago, it was just fixed in the latest 3.141.0 release).

**Comment by meyerbro** [comment]
Hi @diemol, I could set by hand in a selenium container and yes, it didn't help me.

My issue now is to setup a proxy with correct no_proxy rules.

I followed this https://github.com/zalando/zalenium/issues/679#issuecomment-433008829 without luck, it seems that no matter what the container breaks if the no_proxy is different than "*" (which is the same as not having proxy). In any other case I get a "parse error: Invalid numeric literal at line 1, column 10" in the xterm-stderr.log and then after 1 min or more the container get destroyed...

I tried using our proxy and then I tried with my own squid proxy, as recommended by you, the proxy doesn't get any request from the container.

It seems there's something broken...

Can you help? We can move this second issue to another place if you prefer. Thanks!!

**Comment by meyerbro** [comment]
Sorry, my fault, was check the wrong logs, I'm having these logs on the squid proxy:
```1541504751.537      0 172.17.0.1 TCP_DENIED/403 3972 GET http://172.17.0.4:40000/wd/hub/status - HIER_NONE/- text/html
1541504751.649      0 172.17.0.1 TCP_DENIED/403 3972 GET http://172.17.0.4:40000/wd/hub/status - HIER_NONE/- text/html
1541504751.762      0 172.17.0.1 TCP_DENIED/403 3972 GET http://172.17.0.4:40000/wd/hub/status - HIER_NONE/- text/html
1541504751.874      0 172.17.0.1 TCP_DENIED/403 3972 GET http://172.17.0.4:40000/wd/hub/status - HIER_NONE/- text/html
1541504751.988      0 172.17.0.1 TCP_DENIED/403 3972 GET http://172.17.0.4:40000/wd/hub/status - HIER_NONE/- text/html```

**Comment by meyerbro** [comment]
Even starting my container like this docker run --rm -ti --name zalenium -p 30444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos -e "zalenium_http_proxy=http://MY_PROXY:3128" -e "zalenium_https_proxy=http://MY_PROXY:3128" -e "zalenium_no_proxy='localhost,127.0.0.1,MY_PROXY,172.17.0.5,172.17.0.4'" --privileged dosel/zalenium start

**Comment by diemol** [comment]
Closing based on https://github.com/zalando/zalenium/issues/679#issuecomment-436287826

**Comment by diemol** [comment]
You can also ask questions in the #zalenium channel at [Slack](https://seleniumhq.herokuapp.com) where the community can help you as well.

**Comment by meyerbro** [comment]
Thanks @diemol !
