### ISSUE TITLE
The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.

### ISSUE THREAD

**Issue by vasikarla** [zalando/zalenium#766]
using Kubernetes (out of the box):  

## Expected Behavior -
Move to Should work As-Is

## Actual Behavior -
POST /session/fa406ead-a30c-468f-909a-3808917f5b08/moveto did not match a known command
running firefox
Error: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.
    at moveTo("0969f73a-51f9-4a3a-b0a0-94570e80f180", 10, 10) - moveToObject.js:55:22

**Comment by diemol** [comment]
Hi @vasikarla,

This is an issue in your client bindings, which are sending a command not supported by W3C to Firefox, you can see all these issues as a reference:
https://github.com/SeleniumHQ/docker-selenium/issues/771
https://github.com/mozilla/geckodriver/issues/958
https://github.com/SeleniumHQ/selenium/issues/4564

Please have a look at your client bindings and try to update them to their latest version. If the issue persists, please report it to the issue tracker of the language bindings you are using.
