### ISSUE TITLE
Does zalenium support multiple workers for testing?

### ISSUE THREAD

**Issue by therippa** [zalando/zalenium#77]
Sorry, more of a question that a bug report.

I see that you can specify the number of containers to run, but when I enable multiple test_workers on my selenium config, zalenium just seems to hang.   Is that a known issue?

Thanks!

**Comment by therippa** [comment]
nevermind, posting about it here fixed the issue for me

**Comment by diemol** [comment]
Cool you were able to fix it!
I didn't really understand the question though 😃
