### ISSUE TITLE
Tests failing with session timed out error

### ISSUE THREAD

**Issue by QAPK** [zalando/zalenium#774]
**Zalenium Image Version(s):**  
latest
**Docker Version:**  
Docker version 18.03.1-ce, build 9ee9f40
If using docker-compose, version:  N/A
**OS:** 
Windows server 2016
**Docker Command to start Zalenium:**  
docker run --rm -ti --name zalenium -p 4444:4444  -v /var/run/docker.sock:/var/run/docker.sock  -v /c/Zalenium/videos:/home/seluser/videos -v /c/SelGridDocuments:/tmp/node/home/seluser/docs --privileged dosel/zalenium start --timeZone "Europe/London" --keepOnlyFailedTests true

If using Kubernetes, specify your environment, and if relevant your manifests:  N/A

**## Actual Behavior -**
 I am running concurrent selenium tests with chrome driver. Interested in Zalenium auto scaling capabilities. So, I have started my execution by setting thread count in Specflow run profile to 10. . First few mins, tests are running fine. But then I am getting below error and all remaining tests are failing. 
I have executed them on our default grid environment and they are executed fine.
Any suggestions?

OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://test-seleniumgrid:4444/wd/hub/session timed out after 60 seconds. ---> System.Net.WebException: The operation has timed out at System.Net.HttpWebRequest.GetResponse() at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo) --- End of inner exception stack trace --- at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo) at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute) at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities) at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities) at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities) at 

**## Expected Behavior -**
Tests should continue to execute without encountering above error.

**Comment by pearj** [comment]
Are you doing video recording? How much memory does the virtual machine have? How much CPU? Running 10 concurrent tests on a single virtual machine with video recording is most likely not possible unless your vm is quite large. You will need to use kubernetes if you want scale. Video recording is very taxing on the CPU and consume 1.5 CPU cores before a test has even started executing. Multiply that by 10 and unless you have 8 CPU cores spare than timeouts are probably expected. 

If you want more help then come onto the slack channel.

**Comment by QAPK** [comment]
Thanks for the suggestion. My VM has 8 cores and 16GB RAM. Will try without video recording.
