### ISSUE TITLE
Caused by: org.openqa.selenium.WebDriverException: cannot forward the request Failed to connect to /172.18.0.4:40000

### ISSUE THREAD

**Issue by barahate90** [zalando/zalenium#775]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
3.11.0h
[zaleniumlog](https://gist.github.com/c38845015ceda42a44110f76971c5c0c.git)

Docker Version:  
Docker version 17.12.1-ce, build 7390fc6

If using docker-compose, version:  
docker-compose version 1.18.0, build 8dd22a9

OS: 
RHEL7.6

Docker Command to start Zalenium:  
docker-compose up -d

## Expected Behavior -
When test started browser should open the URL and complete the test and close the browser.
## Actual Behavior -
Test gets started browser get open and then in the middle it gets stuck and I get an error **"Caused by: org.openqa.selenium.WebDriverException: cannot forward the request Failed to connect to /172.18.0.4:40000**
"

Things I tired from the previous issue.
1)[Issue 679](https://github.com/zalando/zalenium/issues/679) I have checked the proxy is not blocking my nodes request.

2) Tried this for unexpected end of stream issue  ZALENIUM_EXTRA_JVM_PARAMS="-Dwebdriver.http.factory=apache

3)I observed test get allocated to one of the containers and  suddenly in middle of execution it get's stuck

`15:24:03.523 [qtp1148255190-20] INFO  o.o.g.w.s.handler.RequestHandler - Got a request to create a new session: Capabilities {browserName: chrome, browserstack.local: true, cssSelectorsEnabled: true, javascriptEnabled: true, takesScreenshot: true}
15:24:03.524 [qtp1148255190-20] INFO  d.z.e.z.m.DockerSeleniumCapabilityMatcher - Validating {browserName=chrome, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true} in node with capabilities {seleniumProtocol=WebDriver, acceptSslCerts=true, screen-resolution=1920x1080, tz=Europe/Berlin, browserName=chrome, maxInstances=1, screenResolution=1920x1080, resolution=1920x1080, version=70.0.3538.102, platform=LINUX}
15:24:03.527 [qtp1148255190-20] INFO  d.z.e.z.registry.ZaleniumRegistry - Adding sessionRequest for {browserName=chrome, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true}
15:24:03.528 [Matcher thread] INFO  d.z.e.z.m.DockerSeleniumCapabilityMatcher - Validating {browserName=chrome, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true} in node with capabilities {seleniumProtocol=WebDriver, zal:tz=Europe/Berlin, acceptSslCerts=true, zal:screenResolution=1920x1080, zal:screen-resolution=1920x1080, browserName=chrome, zal:resolution=1920x1080, maxInstances=1, version=70.0.3538.102, platform=LINUX}
15:24:03.528 [Matcher thread] INFO  d.z.e.z.m.DockerSeleniumCapabilityMatcher - Validating {browserName=chrome, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true} in node with capabilities {seleniumProtocol=WebDriver, acceptSslCerts=true, screen-resolution=1920x1080, tz=Europe/Berlin, browserName=chrome, maxInstances=1, screenResolution=1920x1080, resolution=1920x1080, version=70.0.3538.102, platform=LINUX}
15:24:03.529 [Matcher thread] INFO  d.z.e.z.m.DockerSeleniumCapabilityMatcher - Validating {browserName=chrome, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true} in node with capabilities {seleniumProtocol=WebDriver, zal:tz=Europe/Berlin, acceptSslCerts=true, zal:screenResolution=1920x1080, zal:screen-resolution=1920x1080, browserName=chrome, zal:resolution=1920x1080, maxInstances=1, version=70.0.3538.102, platform=LINUX}
15:24:03.529 [Matcher thread] INFO  d.z.e.z.m.DockerSeleniumCapabilityMatcher - Validating {browserName=chrome, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true} in node with capabilities {seleniumProtocol=WebDriver, zal:tz=Europe/Berlin, acceptSslCerts=true, zal:screenResolution=1920x1080, zal:screen-resolution=1920x1080, browserName=chrome, zal:resolution=1920x1080, maxInstances=1, version=70.0.3538.102, platform=LINUX}
15:24:03.529 [Matcher thread] INFO  d.z.e.z.m.DockerSeleniumCapabilityMatcher - Validating {browserName=chrome, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true} in node with capabilities {seleniumProtocol=WebDriver, zal:tz=Europe/Berlin, acceptSslCerts=true, zal:screenResolution=1920x1080, zal:screen-resolution=1920x1080, browserName=chrome, zal:resolution=1920x1080, maxInstances=1, version=70.0.3538.102, platform=LINUX}
15:24:03.530 [Matcher thread] INFO  org.openqa.grid.internal.TestSlot - Trying to create a new session on test slot {seleniumProtocol=WebDriver, zal:tz=Europe/Berlin, acceptSslCerts=true, zal:screenResolution=1920x1080, zal:screen-resolution=1920x1080, browserName=chrome, zal:resolution=1920x1080, maxInstances=1, version=70.0.3538.102, platform=LINUX}
15:24:03.533 [Matcher thread] INFO  d.z.e.z.registry.ZaleniumRegistry - Test session with internal key e0d22a86-8664-4a18-bd06-f9350fbcf889 assigned to remote (5b0e95c611701e67324670788c1c61dee9652e92317ef2db1c6a5983001c8084) after 0 seconds (122 ms).
15:24:03.555 [qtp1148255190-18] INFO  o.o.g.w.s.handler.RequestHandler - Got a request to create a new session: Capabilities {browserName: firefox, browserstack.local: true, cssSelectorsEnabled: true, javascriptEnabled: true, takesScreenshot: true}
15:24:03.555 [qtp1148255190-18] INFO  d.z.e.z.m.DockerSeleniumCapabilityMatcher - Validating {browserName=firefox, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true} in node with capabilities {seleniumProtocol=WebDriver, zal:tz=Europe/Berlin, acceptSslCerts=true, zal:screenResolution=1920x1080, zal:screen-resolution=1920x1080, browserName=chrome, zal:resolution=1920x1080, maxInstances=1, version=70.0.3538.102, platform=LINUX}
15:24:03.555 [qtp1148255190-18] INFO  d.z.e.z.m.DockerSeleniumCapabilityMatcher - Validating {browserName=firefox, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true} in node with capabilities {seleniumProtocol=WebDriver, acceptSslCerts=true, screen-resolution=1920x1080, tz=Europe/Berlin, browserName=firefox, maxInstances=1, screenResolution=1920x1080, resolution=1920x1080, version=60.0.2, platform=LINUX}
15:24:03.555 [qtp1148255190-18] INFO  d.z.e.z.registry.ZaleniumRegistry - Adding sessionRequest for {browserName=firefox, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true}
15:24:03.556 [Matcher thread] INFO  d.z.e.z.m.DockerSeleniumCapabilityMatcher - Validating {browserName=firefox, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true} in node with capabilities {seleniumProtocol=WebDriver, zal:tz=Europe/Berlin, acceptSslCerts=true, zal:screenResolution=1920x1080, zal:screen-resolution=1920x1080, browserName=chrome, zal:resolution=1920x1080, maxInstances=1, version=70.0.3538.102, platform=LINUX}
15:24:03.556 [Matcher thread] INFO  d.z.e.z.m.DockerSeleniumCapabilityMatcher - Validating {browserName=firefox, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true} in node with capabilities {seleniumProtocol=WebDriver, acceptSslCerts=true, screen-resolution=1920x1080, tz=Europe/Berlin, browserName=firefox, maxInstances=1, screenResolution=1920x1080, resolution=1920x1080, version=60.0.2, platform=LINUX}
15:24:03.556 [Matcher thread] INFO  d.z.e.z.m.DockerSeleniumCapabilityMatcher - Validating {browserName=firefox, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true} in node with capabilities {seleniumProtocol=WebDriver, zal:tz=Europe/Berlin, acceptSslCerts=true, zal:screenResolution=1920x1080, zal:screen-resolution=1920x1080, browserName=chrome, zal:resolution=1920x1080, maxInstances=1, version=70.0.3538.102, platform=LINUX}
15:24:03.556 [Matcher thread] INFO  d.z.e.z.m.DockerSeleniumCapabilityMatcher - Validating {browserName=firefox, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true} in node with capabilities {seleniumProtocol=WebDriver, zal:tz=Europe/Berlin, acceptSslCerts=true, zal:screenResolution=1920x1080, zal:screen-resolution=1920x1080, browserName=firefox, zal:resolution=1920x1080, maxInstances=1, version=60.0.2, platform=LINUX}
15:24:03.556 [Matcher thread] INFO  d.z.e.z.m.DockerSeleniumCapabilityMatcher - Validating {browserName=firefox, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true} in node with capabilities {seleniumProtocol=WebDriver, zal:tz=Europe/Berlin, acceptSslCerts=true, zal:screenResolution=1920x1080, zal:screen-resolution=1920x1080, browserName=chrome, zal:resolution=1920x1080, maxInstances=1, version=70.0.3538.102, platform=LINUX}
15:24:03.556 [Matcher thread] INFO  d.z.e.z.m.DockerSeleniumCapabilityMatcher - Validating {browserName=firefox, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true} in node with capabilities {seleniumProtocol=WebDriver, zal:tz=Europe/Berlin, acceptSslCerts=true, zal:screenResolution=1920x1080, zal:screen-resolution=1920x1080, browserName=firefox, zal:resolution=1920x1080, maxInstances=1, version=60.0.2, platform=LINUX}
15:24:03.556 [Matcher thread] INFO  d.z.e.z.m.DockerSeleniumCapabilityMatcher - Validating {browserName=firefox, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true} in node with capabilities {seleniumProtocol=WebDriver, zal:tz=Europe/Berlin, acceptSslCerts=true, zal:screenResolution=1920x1080, zal:screen-resolution=1920x1080, browserName=chrome, zal:resolution=1920x1080, maxInstances=1, version=70.0.3538.102, platform=LINUX}
15:24:03.556 [Matcher thread] INFO  d.z.e.z.m.DockerSeleniumCapabilityMatcher - Validating {browserName=firefox, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true} in node with capabilities {seleniumProtocol=WebDriver, zal:tz=Europe/Berlin, acceptSslCerts=true, zal:screenResolution=1920x1080, zal:screen-resolution=1920x1080, browserName=firefox, zal:resolution=1920x1080, maxInstances=1, version=60.0.2, platform=LINUX}
15:24:03.557 [Matcher thread] INFO  d.z.e.z.m.DockerSeleniumCapabilityMatcher - Validating {browserName=firefox, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true} in node with capabilities {seleniumProtocol=WebDriver, zal:tz=Europe/Berlin, acceptSslCerts=true, zal:screenResolution=1920x1080, zal:screen-resolution=1920x1080, browserName=chrome, zal:resolution=1920x1080, maxInstances=1, version=70.0.3538.102, platform=LINUX}
15:24:03.557 [Matcher thread] INFO  d.z.e.z.m.DockerSeleniumCapabilityMatcher - Validating {browserName=firefox, takesScreenshot=true, browserstack.local=true, javascriptEnabled=true, cssSelectorsEnabled=true} in node with capabilities {seleniumProtocol=WebDriver, zal:tz=Europe/Berlin, acceptSslCerts=true, zal:screenResolution=1920x1080, zal:screen-resolution=1920x1080, browserName=firefox, zal:resolution=1920x1080, maxInstances=1, version=60.0.2, platform=LINUX}
15:24:03.557 [Matcher thread] INFO  org.openqa.grid.internal.TestSlot - Trying to create a new session on test slot {seleniumProtocol=WebDriver, zal:tz=Europe/Berlin, acceptSslCerts=true, zal:screenResolution=1920x1080, zal:screen-resolution=1920x1080, browserName=firefox, zal:resolution=1920x1080, maxInstances=1, version=60.0.2, platform=LINUX}
15:24:03.557 [Matcher thread] INFO  d.z.e.z.registry.ZaleniumRegistry - Test session with internal key e176b4e9-dbe5-4f66-a6ea-ce0ecc72648b assigned to remote (baa30939fa5cfdead579fae6024d0d3a4d09b2f287d6ee4053a76b1eddec6306) after 0 seconds (5 ms).
15:24:04.401 [Forwarding e0d22a86-8664-4a18-bd06-f9350fbcf889 (int. key, remote not contacted yet.) to http://172.17.0.4:40000/wd/hub at 3:24:03 PM] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - Test session started with internal key e0d22a86-8664-4a18-bd06-f9350fbcf889 and external key d09812e7-e21e-41d8-8bef-268552e08376 assigned to remote 5b0e95c611701e67324670788c1c61dee9652e92317ef2db1c6a5983001c8084.
15:24:04.464 [Forwarding e0d22a86-8664-4a18-bd06-f9350fbcf889 (int. key, remote not contacted yet.) to http://172.17.0.4:40000/wd/hub at 3:24:03 PM] INFO  d.z.e.z.c.DockerContainerClient - http://172.17.0.4:40000 [bash, -c, start-video]
15:24:05.768 [Forwarding e176b4e9-dbe5-4f66-a6ea-ce0ecc72648b **(int. key, remote not contacted yet.)** to http://172.17.0.5:40000/wd/hub at 3:24:03 PM] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - Test session started with internal key e176b4e9-dbe5-4f66-a6ea-ce0ecc72648b and external key 4e6a7866-14b5-4a70-b75f-94a5d78c11ed assigned to remote baa30939fa5cfdead579fae6024d0d3a4d09b2f287d6ee4053a76b1eddec6306.
15:24:05.798 [Forwarding e176b4e9-dbe5-4f66-a6ea-ce0ecc72648b (int. key, remote not contacted yet.) to http://172.17.0.5:40000/wd/hub at 3:24:03 PM] INFO  d.z.e.z.c.DockerContainerClient - http://172.17.0.5:40000 [bash, -c, start-video]
15:25:34.962 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - [5b0e95c611701e67324670788c1c61dee9652e92317ef2db1c6a5983001c8084] has been idle [90250] which is more than [90000]
15:25:34.963 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - [5b0e95c611701e67324670788c1c61dee9652e92317ef2db1c6a5983001c8084] is stale.
15:25:34.963 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - 5b0e95c611701e67324670788c1c61dee9652e92317ef2db1c6a5983001c8084 Shutting down node due to proxy being stuck | stale during a test.
15:25:34.976 [pool-3-thread-1] INFO  d.z.e.z.c.DockerContainerClient - http://172.17.0.4:40000 [bash, -c, notify 'Zalenium', 'TEST TIMED OUT', --icon=/home/seluser/images/timeout.png]
15:25:35.232 [pool-3-thread-1] INFO  d.z.e.z.c.DockerContainerClient - http://172.17.0.4:40000 [bash, -c, stop-video]
15:25:35.984 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - [baa30939fa5cfdead579fae6024d0d3a4d09b2f287d6ee4053a76b1eddec6306] has been idle [90015] which is more than [90000]
15:25:35.985 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - [baa30939fa5cfdead579fae6024d0d3a4d09b2f287d6ee4053a76b1eddec6306] is stale.
15:25:35.985 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - baa30939fa5cfdead579fae6024d0d3a4d09b2f287d6ee4053a76b1eddec6306 Shutting down node due to proxy being stuck | stale during a test.
15:25:35.990 [pool-3-thread-2] INFO  d.z.e.z.c.DockerContainerClient - http://172.17.0.5:40000 [bash, -c, notify 'Zalenium', 'TEST TIMED OUT', --icon=/home/seluser/images/timeout.png]
15:25:36.266 [pool-3-thread-2] INFO  d.z.e.z.c.DockerContainerClient - http://172.17.0.5:40000 [bash, -c, stop-video]
15:26:01.463 [qtp1148255190-20] ERROR o.o.g.w.s.handler.RequestHandler - **cannot forward the request Connect to 172.17.0.4:40000 [/172.17.0.4] failed: Connection refused (Connection refused)
org.apache.http.conn.HttpHostConnectException: Connect to 172.17.0.4:40000 [/172.17.0.4] failed: Connection refused (Connection refused)**
`

Nothing worked for me .

Can you please check my log and see if anything inappropriate?

**Comment by barahate90** [comment]
@pearj  

> What is the contents of your docker compose file?
--- 
services: 
  zalenium: 
    command:
        start --desiredContainers 2
              --maxDockerSeleniumContainers 8 --maxTestSessions 3
              --screenWidth 800 --screenHeight 600
              --timeZone "Europe/Berlin"
              --videoRecordingEnabled true
              --sauceLabsEnabled false
              --browserStackEnabled false
              --testingBotEnabled false
              --startTunnel false --sendAnonymousUsageInfo false
              --keepOnlyFailedTests false
    environment: 
      - DEBUG=1
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
    hostname: zalenium
    image: dosel/zalenium:3.11.0h
    ports:
      - "4443:4444"
    tty: true
    entrypoint: /usr/bin/entry.sh
    volumes: 
      - "/tmp/videos:/home/seluser/videos"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
version: "3"
>  What makes you think it’s not a proxy problem?

- Before posting the issue I tried to check whether zalenium is running behind any organization proxy and that was not the case for me.

- After posting the issue I observed few URL's are getting blocked at firewall layer which in turn making test idle for some time and as the browser is idle for more than 90sec I can see containers are getting deleted/autorestarted and hence the error.

> Does it fail every single time?

-  Yes, It's getting failed in one particular environment which is running behind the firewall.
- same test is running fine with another sandbox without firewall.

I will check the issue after whitelisting the URLs and update this thread.

**Comment by pearj** [comment]
Ok, it sounds environmental then if you’re saying it works on another environment without a firewall. Closing

If you think there is an actual zalenium issue then it could be reopened.
