### ISSUE TITLE
How to change newSessionWaitTimeout in hub config

### ISSUE THREAD

**Issue by QAPK** [zalando/zalenium#776]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

**Zalenium Image Version(s):**  
Latest
**Docker Version:**  
Docker version 18.03.1-ce, build 9ee9f40

**OS:** 
Windows server 2016
Docker Command to start Zalenium:  
docker run --rm -ti --name zalenium -p 4444:4444  -v /var/run/docker.sock:/var/run/docker.sock  -v /c/Zalenium/videos:/home/seluser/videos -v /c/SeleniumGridDocuments:/tmp/node/home/seluser/docs --privileged dosel/zalenium start --timeZone "Europe/London" --keepOnlyFailedTests true

**## Expected Behavior -**
Once I run Zalenium, hub config (http://localhost:4444/grid/api/hub) showing newSessionWaitTimeout as 600000. How to override this. I want to wait indefinitely. Please help.

**Comment by pearj** [comment]
Why would you want to wait longer than 10 minutes? If you can’t start a session for 10 minutes it’s probably not going to start at all. 

Assuming your doing the same level of concurrency as #774 then you’ve simply overcommitted your resources. 

Come on slack to discuss.

**Comment by DeChrish** [comment]
I would like to discuss on this topic.

**Comment by DeChrish** [comment]
Currently, we are using SauceLabs for cross-browser testing, and we have limited VM's. We need to wait for a minimum of 30 minutes for a new session.
