### ISSUE TITLE
Intermittent 502 Bad Gateway during test run

### ISSUE THREAD

**Issue by jordanm-mel** [zalando/zalenium#777]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
3.141.59c

Docker Version:  
18.05.0-ce

If using docker-compose, version:  
version 1.21.2, build a133471

OS: 
Ubuntu 16.04.4 LTS

Docker Command to start Zalenium:  
docker-compose up --force-recreate -d

Docker Compose file:
```
# Usage:
#   docker-compose up --force-recreate -d
# Modified from https://opensource.zalando.com/zalenium/

version: '2.1'

services:
  #--------------#
  zalenium:
    image: "dosel/zalenium"
    restart: always
    hostname: zalenium
    tty: true
    volumes:
      - ./videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 4444:4444
    command: >
      start --desiredContainers 10
            --maxDockerSeleniumContainers 12
            --screenWidth 1366 --screenHeight 768
            --timeZone "Australia/Melbourne"
            --videoRecordingEnabled false
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
    environment:
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
      - ZALENIUM_EXTRA_JVM_PARAMS=-Dwebdriver.http.factory=apache
    networks:
      zgridnet:

  mock:
    image: elgalu/google_adwords_mock
    restart: always
    depends_on:
      - zalenium
    ports:
      - 8080:8080
    tty: true
    environment:
      - MOCK_SERVER_PORT=8080
    networks:
      zgridnet:

  updater:
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: watchtower cops-zgrid_zalenium_1 cops-zgrid_updater_1

networks:
  zgridnet:
    driver: bridge
```

## Expected Behavior -
Zalenium should be able to return the requested element or attribute, without potentially returning a 502.

## Actual Behavior -
During seemingly unrelated calls (Finding an element by ID, accessing the Displayed attribute, executing Javascript) there is a chance that a 502 Bad Gateway will be returned instead, causing NUnit to rethrow the exception.
```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

I have monitored the resource usage and performance of my zalenium box while running these tests. CPU never hits 100% usage and memory usage sits comfortably at around 70%.

**Comment by jordanm-mel** [comment]
Hey @diemol,

We're running our hub on 20 vCPUs with 8GB RAM, and we currently run 10 tests in parallel, could you please advise if this is appropriate specification, or if we need to increase our resourcing?

After lowering our containers to 5 (with 5 tests in parallel) we noticed quite a dramatic decrease in the number of 502 errors being thrown. Do you know if this is a known issue, or if we should be increasing our vCPUs to account for the load?

**Comment by diemol** [comment]
@jordanm-mel that is interesting, normally people have lots of RAM and just a few CPUs... Anyway, normally a container needs 1 CPU and 1 GB of RAM. If you are recording video, add 1 CPU more. These are standard values and can vary depending on the app you are testing... If if it is a light app that does not use too much RAM or does not execute a lot of JavaScript in the background, perhaps you'll do fine with a bit less.

Please try with these recommendations and let us know how it goes.
