### ISSUE TITLE
Session/Container Timeout conflicts with cluster-autoscaler

### ISSUE THREAD

**Issue by dcherman** [zalando/zalenium#779]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  

3.141.59b

If using Kubernetes, specify your environment, and if relevant your manifests:

K8s on AWS w/ `cluster-autoscaler` and spot instances

## Expected Behavior

When used in conjunction with `cluster-autoscaler`, Zalenium should be configurable to wait for upcoming nodes being created by `cluster-autoscaler` to be available before marking a Pod as failed since it often takes 3+ minutes for a node to be available.

## Actual Behavior -

Zalenium marks the Pod as failed after 30 seconds with it still in the pending state, then attempts to spin up a new pod to fulfill the request.  This results in us hitting the maximum number of containers that we allow pretty regularly despite only having a small numbers of requests since the node where the pod can be scheduled is often not available for 3 minutes or so.

Can we consider allowing this to be configurable, or figuring out some other way of determining whether or not a pod should be considered failed?

https://github.com/zalando/zalenium/blob/57a94fac5b41d8f292d26bff75626f7ae9369017/src/main/java/de/zalando/ep/zalenium/proxy/SessionRequestFilter.java#L25-L30

https://github.com/zalando/zalenium/blob/de1241dca465550dab2cca37b57439b2ca0daf44/src/main/java/de/zalando/ep/zalenium/proxy/AutoStartProxySet.java#L113-L121

https://github.com/zalando/zalenium/blob/de1241dca465550dab2cca37b57439b2ca0daf44/src/main/java/de/zalando/ep/zalenium/proxy/AutoStartProxySet.java#L241-L243

**Comment by diemol** [comment]
Hi @dcherman,

Thanks for pointing this out, these hardcoded values have worked in many scenarios. But you are right, they should be configurable. We have added these [env vars](https://github.com/zalando/zalenium/blob/master/scripts/zalenium.sh#L29-L31), and they will be available in the next release. Ideally by the end of the upcoming week.

**Comment by dcherman** [comment]
Sweet, thanks @diemol!
