### ISSUE TITLE
Stopped containers not removed from Rancher environment 

### ISSUE THREAD

**Issue by sercegovic** [zalando/zalenium#780]
Hi, I saw similar issues reported and solved, but I'm still not able to solve this one, so I hope you can help.
After "'TEST COMPLETED'", node is marked as down and container is stopped, but it's not removed from Rancher environment. This cause a lot of stopped containers that are polluting my environment and takes some amount of memory.  

Zalenium Image Version(s):  
3.141.59c
Docker Version:  
17.12.1-ce, build 7390fc6

## Expected Behavior -
After "'TEST COMPLETED'", node is marked as down and container is stopped and removed.
## Actual Behavior -
After "'TEST COMPLETED'", node is marked as down and container is stopped, but it's not removed from Rancher environment.

INFO  d.z.e.z.c.DockerContainerClient - http://127.0.0.1:40005 [bash, -c, notify 'Zalenium', 'TEST COMPLETED', --icon=/home/seluser/images/completed.png]
21/11/2018 01:34:1401:34:14.501 [pool-3-thread-4] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - c3a4e5988707b85dedbec6def4eba433acdf1eb50a21bc799059ad67f994332d stop-video: Video recording is disabled
21/11/2018 01:34:1401:34:14.505 [pool-3-thread-4] INFO  d.z.e.z.c.DockerContainerClient - http://127.0.0.1:40005 [bash, -c, transfer-logs.sh]
21/11/2018 01:34:1401:34:14.676 [pool-3-thread-4] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - c3a4e5988707b85dedbec6def4eba433acdf1eb50a21bc799059ad67f994332d Logs copied to: /home/seluser/videos/logs/zalenium_a7ce3388_fe63_438e_a388_7a4d6c402d9b_chrome_LINUX_20181121012140701_COMPLETED
21/11/2018 01:34:1401:34:14.684 [pool-3-thread-4] INFO  d.z.e.z.c.DockerContainerClient - http://127.0.0.1:40005 [bash, -c, cleanup-container.sh]
21/11/2018 01:34:1701:34:17.661 [pool-3-thread-4] INFO  o.o.g.s.proxy.DefaultRemoteProxy - c3a4e5988707b85dedbec6def4eba433acdf1eb50a21bc799059ad67f994332d Marking the node as down because the test has been idle for more than 360 seconds.
21/11/2018 01:34:1701:34:17.661 [pool-3-thread-4] WARN  d.z.e.z.registry.ZaleniumRegistry - Cleaning up stale test sessions on the unregistered node http://127.0.0.1:40005
21/11/2018 01:34:1701:34:17.662 [pool-3-thread-4] INFO  d.z.e.z.proxy.AutoStartProxySet - Stopping removed container [c3a4e5988707b85dedbec6def4eba433acdf1eb50a21bc799059ad67f994332d].

![rancher 2018-11-21 10-06-39](https://user-images.githubusercontent.com/30793623/48830598-3e7aec80-ed75-11e8-9696-2bb050361bdd.png)

**Comment by sercegovic** [comment]
Solved after using driver.quit instead of driver.close in conftest.py addfinalizer

**Comment by diemol** [comment]
HI @sercegovic,

Thanks for troubleshooting this on your own! 🎉  
We haven't had time this week to check the new issues.
