### ISSUE TITLE
How to change newSessionWaitTimeout in hub config

### ISSUE THREAD

**Issue by DeChrish** [zalando/zalenium#784]
@diemol 
Currently, we are using SauceLabs for cross-browser testing, and we have limited VM's. We need to wait for a minimum of 30 minutes for a new session.

P.S: we will eventually increase the VM's but before that, we would like to understand the load before buying VM's

Can we pass this in CLI - 
#zalenium.sh
NEW_SESSION_WAIT_TIMEOUT=${NEW_SESSION_WAIT_TIMEOUT:-600000}

**Comment by diemol** [comment]
Hi @DeChrish,

Actually, you are right, I completely forgot about that. Just pass the value you want in milliseconds through the env var `NEW_SESSION_WAIT_TIMEOUT`.

e.g.
`docker run ... -e NEW_SESSION_WAIT_TIMEOUT=1800000 ... dosel/zalenium start`

**Comment by DeChrish** [comment]
@diemol Thanks.

**Comment by DeChrish** [comment]
@diemol how to use the above option in kubernetes?

https://github.com/zalando/zalenium/blob/master/charts/zalenium/values.yaml
