### ISSUE TITLE
Enable Zalenium to run in a non-root context

### ISSUE THREAD

**Issue by ramapalani** [zalando/zalenium#794]
In my Kubernetes cluster, I have a ngnix ingress (with a public domain name, say hostname.com). I use this ingress for more than one application.  I want to have the same ingress for Zalenium too.  So I tried exposing Zalenium through a non-root context (say hostname.com/zalenium).  But Zalenium assumes that it would be running only in root context and many pages failed to load. 

Zalenium Image Version(s):  
3
Docker Version:  
17.3.2
If using docker-compose, version:  
NA
OS: 
RHEL
Docker Command to start Zalenium:  
NA
If using Kubernetes, specify your environment, and if relevant your manifests:  
Used helm charts in Zalenium repo with these changes
https://github.com/ramapalani/zalenium/commit/330ace0ce2ec7427d5ad4332774ab5a6084da575?w=1

helm install --name zal1 charts/zalenium

## Expected Behavior -
hostname.com/zalenium/dashboard works good.  I expect other UI pages to work the same.
## Actual Behavior -
This page: /zalenium/grid/admin/live
* couldn't find all static content (css, images,javascript...)
* VNC Iframe results in 404 because it tries to load /vnc/*

When I manually opened hostname.com//zalenium/vnc/host/100.97.233.90/port/50000/?nginx=100.97.233.90:50000&view_only=true
The page loaded but couldn't connect to VNC because, websockify was directly pointing to /proxy

It would be great to fix this, let me know how I could help this fixed

**Comment by ramapalani** [comment]
Not working UI pages
![live](https://user-images.githubusercontent.com/7064234/49760059-4b09ab00-fc78-11e8-8f3b-1f83e351c8c8.png)
![vnc](https://user-images.githubusercontent.com/7064234/49760069-52c94f80-fc78-11e8-8e93-b6d7ceec8d62.png)

Working UI page
![dashboard](https://user-images.githubusercontent.com/7064234/49760087-5f4da800-fc78-11e8-8272-e512c0977070.png)

**Comment by diemol** [comment]
Hi @ramapalani,

Yes, the dashboard comes through an nginx config and the other ones are rendered by Jetty. These are the files for the LiveView
https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/servlet/LivePreviewServlet.java
https://github.com/zalando/zalenium/blob/master/src/main/resources/html_templates/live_preview_servlet.html

Maybe you can give us a hand to make this work for your use case as well?

**Comment by ramapalani** [comment]
Sure, I can contribute.  I couldn't get the build working.  Do you have any doc on getting started?

I tried this command and it failed:
mvn clean verify -Pintegration-test -DthreadCountProperty=2 -Dskip.surefire.tests=true -DintegrationToTest=sauceLabs

Step 8/50 : RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 2EA8F35793D8809A   && apt-key update -qqy
 ---> Running in 91da9659b8ad
Executing: /tmp/tmp.6q2Sn7dSpB/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv-keys
2EA8F35793D8809A
gpg: requesting key 93D8809A from hkp server keyserver.ubuntu.com
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver unreachable
gpg: keyserver communications error: public key not found
gpg: keyserver receive failed: public key not found
?: keyserver.ubuntu.com: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Success
The command '/bin/sh -c apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 2EA8F35793D8809A   && apt-key update -qqy' returned a non-zero code: 2
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)


I directly tried to build docker image, and that failed for missing files.

**Comment by ramapalani** [comment]
Could you review PR https://github.com/zalando/zalenium/pull/797 for this issue?

**Comment by arnaud-deprez** [comment]
Hi @ramapalani, 
I guess we should close this now, shoudln't we ?
@diemol ?

**Comment by diemol** [comment]
Right, I thought they were linked :) Thanks

**Comment by ramapalani** [comment]
HI Diego,

I'm not able to get the VNC working with a non-root context yet.  websokify
used in novnc (part of elgalu/selenium) is always pointing to root (/).  I
need help in fixing this.

Regards,
Rama

**Comment by diemol** [comment]
@ramapalani we haven't released yet. We will do another release by the end of this week/beginning of the next one.

**Comment by ramapalani** [comment]
@diemol & @arnaud-deprez Fix for the last part of this issue is in PR https://github.com/zalando/zalenium/pull/811
