### ISSUE TITLE
Unable to customise browser and grid timeouts

### ISSUE THREAD

**Issue by KierranM** [zalando/zalenium#795]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  3

Docker Version:  

If using docker-compose, version:  

OS: Debian

Docker Command to start Zalenium:  

If using Kubernetes, specify your environment, and if relevant your manifests:  
Deployed using the helm chart in this repository.

## Expected Behavior -
I am able to set the same timeout values that I can when using the stable/selenium chart. Specifically browser timeout and grid timeout.

## Actual Behavior -
I am unable to set these values.

This has been brought up a few times (#761 #447) and was seemingly fixed in #523 (though it looks like the file that was changed no longer exists.

It would be useful to be able to customise the browserTimeout and timeout values of the nodes as we have a few tests that require significantly extended timeouts. The docker image for the nodes already supports setting these via [environment variables](https://github.com/elgalu/docker-selenium/blob/master/Dockerfile#L897-L898).

From some cursory looking through this repository I believe the changes required are to add the environment variables to [this hash](https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/proxy/DockeredSeleniumStarter.java#L276-L309), and then add them into the helm chart as values that can be set.  

The environment variables as specified by the container are `SEL_RELEASE_TIMEOUT_SECS` and `SEL_BROWSER_TIMEOUT_SECS`

**Comment by diemol** [comment]
Hi @KierranM,

That is true, maybe in the huge refactoring done many releases ago `SEL_BROWSER_TIMEOUT_SECS` got lost. Would you like to send us a PR adding it again?

About `SEL_BROWSER_TIMEOUT_SECS`, we manage the `timeout` differently, you can set it up per test through the `idleTimeout`. E.g.;

```java
    DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
    desiredCapabilities.setCapability(CapabilityType.BROWSER_NAME, BrowserType.FIREFOX);
    desiredCapabilities.setCapability(CapabilityType.PLATFORM_NAME, Platform.LINUX);
    desiredCapabilities.setCapability("idleTimeout", 150);
```

**Comment by KierranM** [comment]
Happy to open a PR for the browser timeout, I'm about to go on leave for a few weeks, so I'll look at it in the new year if someone doesn't beat me to it.

Is the `idleTimeout` you're specifying in that example correspond to `SEL_BROWSER_TIMEOUT_SECS` or `SEL_RELEASE_TIMEOUT_SECS`. I'm not actually on the team that works with the tests, we've just found ourselves maintaining the selenium grid, so ideally we'd like to avoid forcing the other teams to make changes for all their tests (even though that's clearly the better way).

**Comment by diemol** [comment]
Hi @KierranM, I just added the env var back in the commit linked above, we will merge this soon and release before this weekend.

 About your previous question; `idleTimeout` will correspond to `SEL_RELEASE_TIMEOUT_SECS`.
