### ISSUE TITLE
cannot custom user-agent by remote chrome

### ISSUE THREAD

**Issue by careyyoung** [zalando/zalenium#796]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  zalenium-3.141.59c

Docker Version:   Docker version 1.13.1, build 8633870/1.13.1

If using docker-compose, version:  

OS: Centos7

Docker Command to start Zalenium:  docker run -ti --name zalenium -p 60044:4444 \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v /tmp/videos:/home/seluser/videos \
      --privileged dosel/zalenium start --timeZone "Asia/Shanghai" 

If using Kubernetes, specify your environment, and if relevant your manifests:  

## Expected Behavior -
hi, thank you for read.
i want to change user-agent by chrome driver,
so i code about: 
options = webdriver.ChromeOptions()
options.add_argument('--userAgent='+ua)
options.add_argument('--start-maximized')
desired_capabilities = options.to_capabilities()
desired_capabilities['browserName'] = 'chrome'
desired_capabilities['name'] = driver_name
browser = webdriver.Remote(
            command_executor='http://127.0.0.1:60044/wd/hub',
            desired_capabilities=desired_capabilities,
        )
browser.get(url)
is it wrong code?
but when i check the access log, the user-agent always old, not customized.
## Actual Behavior -
accesslog from httpd log:
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"

**Comment by careyyoung** [comment]
> Hi @careyyoung,
> 
> I am not sure. If you try it with ChromeDriver directly, does it work? If there is an issue, it is probably in the `elgalu/selenium` image, maybe you can help us to debug that.

it's ok with ChromeDriver directly, but have no effect by remote webdriver. 
i test upon selenium/hub&selenium/node-chrome just now.

**Comment by diemol** [comment]
OK @careyyoung, let us know your the results of your test.

**Comment by careyyoung** [comment]
> Please try this, it should work:
> 
> ```python
> capabilities = webdriver.common.desired_capabilities.DesiredCapabilities.CHROME.copy()
> capabilities['javascriptEnabled'] = True
> 
> options = webdriver.ChromeOptions()
> options.add_argument('--user-agent=<YOUR USER AGENT HERE>')
> 
> driver = webdriver.Remote(command_executor='http://<YOUR SELENIUM HUB HERE>:4444/wd/hub',desired_capabilities=capabilities, options=options)
> ```

but webdriver.Remote donot have keyword argument 'options'.

**Comment by diemol** [comment]
Thanks for helping us troubleshoot it @thureos!

@careyyoung please, have a look at the link, and if you have more Selenium related questions, please head to send it to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well. 
For Zalenium specific question we also have a #zalenium channel at [Slack](https://seleniumhq.herokuapp.com).

**Comment by careyyoung** [comment]
> > > Please try this, it should work:
> > > ```python
> > > capabilities = webdriver.common.desired_capabilities.DesiredCapabilities.CHROME.copy()
> > > capabilities['javascriptEnabled'] = True
> > > 
> > > options = webdriver.ChromeOptions()
> > > options.add_argument('--user-agent=<YOUR USER AGENT HERE>')
> > > 
> > > driver = webdriver.Remote(command_executor='http://<YOUR SELENIUM HUB HERE>:4444/wd/hub',desired_capabilities=capabilities, options=options)
> > > ```
> > 
> > 
> > but webdriver.Remote donot have keyword argument 'options'.
> 
> I just used it, and it worked very well
> 
> Check the docs here:
> 
> https://selenium-python.readthedocs.io/api.html#selenium.webdriver.remote.webdriver.WebDriver.__init__

thanks very much, because you infomation,
so i check the doc and the lib installed in my machine, i find the lib is too old. 
after update the selenium to 3.xx, it worked.
thanks again.

**Comment by monkpit** [comment]
I had a similar issue with trying to set the `user-agent` - in my case it turns out that I needed to change my parameter in protractor from `chromeOptions:{args: ['--user-agent=TEST']}` to `'goog:chromeOptions': {args: ['--user-agent=TEST']}`.

Without changing it to `goog: chromeOptions` the args were being ignored by the Selenium instance.

This was with protractor version 5.4.2.
