### ISSUE TITLE
when run docker by host network mode, can not see /grid/admin/live page

### ISSUE THREAD

**Issue by careyyoung** [zalando/zalenium#803]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  zalenium-3.141.59c

Docker Version:   Docker version 1.13.1, build 8633870/1.13.1

If using docker-compose, version:  

OS: Centos7

Docker Command to start Zalenium:  
```
docker run -ti --name zalenium --network host \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v /tmp/videos:/home/seluser/videos \
      --privileged dosel/zalenium start --timeZone "Asia/Shanghai" 
```

If using Kubernetes, specify your environment, and if relevant your manifests:  

## Expected Behavior -
hi, thank you for read.
when i run docker by: docker run -ti --name zalenium --network host ...
then i access: http://127.0.0.1:4445/grid/admin/live
the config is
```
browserTimeout: 16000

debug: false

host: 127.0.0.1

port: 40000

role: node

timeout: 19000

cleanUpCycle: 5000

maxSession: 1

capabilities: Capabilities {acceptSslCerts: true, browserName: chrome, maxInstances: 1, platform: LINUX, platformName: LINUX, resolution: 1920x1080, screen-resolution: 1920x1080, screenResolution: 1920x1080, seleniumProtocol: WebDriver, server:CONFIG_UUID: f011fc9b-2664-4d52-931a-793..., tz: Asia/Shanghai, version: 71.0.3578.80}

capabilities: Capabilities {acceptSslCerts: true, browserName: firefox, maxInstances: 1, platform: LINUX, platformName: LINUX, resolution: 1920x1080, screen-resolution: 1920x1080, screenResolution: 1920x1080, seleniumProtocol: WebDriver, server:CONFIG_UUID: 556e34ed-c7bb-48d6-8ad3-3e5..., tz: Asia/Shanghai, version: 64.0}

downPollingLimit: 2

hub: http://127.0.0.1:4445/grid/register

id: http://127.0.0.1:40000

nodePolling: 101000

nodeStatusCheckTimeout: 5000

proxy: de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy

register: true

registerCycle: 20000

remoteHost: http://127.0.0.1:40000

unregisterIfStillDownAfter: 2500
```

after i click the url: Interact via VNC, it is :
```
http://127.0.0.1:4445/vnc/host/127.0.0.1/port/50000/?nginx=127.0.0.1:50000&view_only=true
```
## Actual Behavior -
but i can not see vnc views, it is a "Whoops! The URL specified routes to this help page." line showed.
![image](https://user-images.githubusercontent.com/9160429/50268322-4c4f8a80-0465-11e9-9337-af76de55b269.png)

**Comment by diemol** [comment]
@careyyoung please try with port 4444, which is the one where nginx is serving.

Also, it is known that the live view does not work 100% of the times when using network `host`.
