### ISSUE TITLE
Basic auth not working when Zalenium deployed using Helm chart

### ISSUE THREAD

**Issue by baflQA** [zalando/zalenium#805]
Zalenium Image Version(s):  
3.141.59e
Docker Version:  
elgalu/selenium:3.141.59-p6
OS: 
AWS Linux

Zalenium is deployed to K8S using given helm chart:

> hub:
>   serviceAnnotations:
>     service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
>     service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "1200"
> 
>   \## The repository and image
>   \## ref: https://hub.docker.com/r/selenium/hub/
>   image: "dosel/zalenium"
> 
>   \## The tag for the image
>   \## ref: https://hub.docker.com/r/selenium/hub/tags/
>   tag: "3.141.59e"
> 
>   \## Specify a imagePullPolicy
>   \## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
>   pullPolicy: "IfNotPresent"
> 
>   \## The port which the hub listens on
>   port: 4444
> 
>   \## Timeout for probe Hub readiness via HTTP request on Hub console
>   readinessTimeout: 30
> 
>   \## Set the JAVA_OPTS environment variable
>   \## If you find your selenium hub is OOMKilled, try adding -XX:+UseSerialGC
>   javaOpts: "-Xmx400m -XX:+UseSerialGC"
> 
>   \## Set the SE_OPTS environment variable
>   \## ref: http://www.seleniumhq.org/docs/07_selenium_grid.jsp#node-configuration
>   \# seOpts:
> 
>   \## Defining a JMX port will open the port on the container, however, it
>   \## requires additional javaOpts, ie
>   \## javaOpts: >
>   \##   -Dcom.sun.management.jmxremote.port=4000
>   \##   -Dcom.sun.management.jmxremote.authenticate=false
>   \##   -Dcom.sun.management.jmxremote.ssl=false
>   \## ref: http://openjdk.java.net/groups/jmx/
>   \# jmxPort: 4000
> 
>   \## Configure resource requests and limits
>   \## ref: http://kubernetes.io/docs/user-guide/compute-resources/
>   resources:
>     limits:
>       cpu: "1"
>       memory: "3814Mi"
>     requests:
>       cpu: "0.5"
>       memory: "500Mi"
> 
>   \## The type of service to create
>   \##   Values: ClusterIP, NodePort, LoadBalancer, or ExternalName
>   \## ref: https://kubernetes.io/docs/user-guide/services/
>   serviceType: "LoadBalancer"
> 
>   \## Control where client requests go, to the same pod or round-robin
>   \##   Values: ClientIP or None
>   \## ref: https://kubernetes.io/docs/user-guide/services/
>   serviceSessionAffinity: "None"
> 
>   \# Zalenium hub uses these values to schedule pods through the k8s apiserver.
>   cpuRequest: 500m
>   memRequest: 500Mi
> 
>   \## Start arguments for Zalenium hub itself
>   \## https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md
>   desiredContainers: 1
>   maxDockerSeleniumContainers: 25
>   sauceLabsEnabled: false
>   browserStackEnabled: false
>   testingBotEnabled: false
>   videoRecordingEnabled: false
>   cpuRequest: 500m
>   memRequest: 500Mi
>   screenWidth: 1440
>   screenHeight: 900
>   timeZone: "Europe/Berlin"
>   seleniumImageName: "elgalu/selenium:3.141.59-p6"
>   maxTestSessions: 1
>   debugEnabled: false
>   sendAnonymousUsageInfo: false
>   keepOnlyFailedTests: true
>   retentionPeriod: 2
>   basicAuth:
>     enabled: true
>     username: "zalenium"
>     password: "password"

## Expected Behavior -
A user has to provide credentials when e.g. opening the Zalenium console page.
## Actual Behavior -
No credentials are required to open the console page.

**Comment by diemol** [comment]
Hi @baflQA,

I just tried by following the instructions in the [docs](https://opensource.zalando.com/zalenium/#kubernetes). more specifically:

_Changed before the value:_
```
  basicAuth:
    enabled: true
```
_in the `values.yaml` file._

and then:

```
    cd zalenium
    kubectl create namespace zalenium
    helm init --client-only
    helm template --name zalenium \
        --set hub.serviceType=NodePort \
        charts/zalenium | kubectl -n zalenium apply -f -
```

and auth was working as expected.

Could you please double check and reopen in case it does not work for you?

**Comment by ryderstorm** [comment]
@diemol - I was running into this as well, and I think I found the problem.

If you just enable `basicAuth`, like this:
```
  basicAuth:
    enabled: true
    username: "zalenium"
    password: "password"
```
and apply the manifest, then Zalenium prompts for authentication when you try to access it via the browser, just as you described.

However, if you enable `basicAuth` and change either the `username` or the `password` to a value that includes spaces, like this:
```
  basicAuth:
    enabled: true
    username: "zalenium user"
    password: "password"
```

or this:
```
  basicAuth:
    enabled: true
    user: "zalenium"
    password: "passwords are so awesome"
```

and apply the manifest, then Zalenium does not prompt for authentication when you try to access it via the browser.

I enabled debugging and checked the hub logs, and found this:
```
$ kubectl logs -f pod/zalenium-5d67bfc5dc-k7t49
Kubernetes service account found.
Copying files for Dashboard...
/home/seluser/zalenium.sh: line 443: [: too many arguments
Starting Nginx reverse proxy...
Starting Selenium Hub...
```

I would bet that this bug could be resolved by simply changing [this line](https://github.com/zalando/zalenium/blob/master/scripts/zalenium.sh#L443) from this:
```
htpasswd -bc /home/seluser/.htpasswd ${GRID_USER} ${GRID_PASSWORD}
```

to this:
```
htpasswd -bc /home/seluser/.htpasswd "${GRID_USER}" "${GRID_PASSWORD}"
```

But you may also want to add some validations to the helm chart around what are valid values for username/password. 

If just changing the line in `zalenium.sh` is sufficient, let me know, and i'll open up a PR to do that.

**Comment by diemol** [comment]
I think that is a good solution, would be nice to have a PR for that, thanks!

**Comment by ryderstorm** [comment]
@diemol - done! https://github.com/zalando/zalenium/pull/976

**Comment by monkpit** [comment]
@diemol I am not able to get basic auth working on Google Cloud kubernetes with the zalenium helm charts. The zalenium pods all get created correctly, but it looks like the loadbalancer thinks the backend service is down with 401/unauthorized errors. Any tips?

I have tried changing the `livenessProbe` and `readinessProbe` from `httpGet` to `tcpSocket` on port 4444 to try and circumvent the auth requirement, but it did not work.

The issue I am seeing is essentially the same issue seen by the OP here: https://stackoverflow.com/questions/42967763/kubernetes-ingress-gce-keeps-returning-502-error/42971328

**Comment by bagatonovic** [comment]
I am having this exact same issue!  Works fine without auth on GKE, but when I add auth the readiness check fails! 

could it be because no header is passed here?

                        // Add a readiness health check so that we can know when the selenium pod is ready to accept requests
                        // so then we can initiate a registration.
                        .withNewReadinessProbe()
                            .withNewExec()
                                .addToCommand(new String[] {"/bin/sh", "-c", "http_proxy=\"\" curl -s http://`hostname -i`:"
                                        + config.getNodePort() + "/wd/hub/status | jq .value.ready | grep true"})
                            .endExec()
