### ISSUE TITLE
[minikubes] How to change newSessionWaitTimeout in hub config 

### ISSUE THREAD

**Issue by DeChrish** [zalando/zalenium#814]
Reference: #784

@pearj  @diemol 
how to use the above option in minikubes?
https://github.com/zalando/zalenium/blob/master/charts/zalenium/values.yaml

Current docker command: 
`docker run --rm -ti --name zalenium -p 4444:4444 -e SAUCE_USERNAME -e SAUCE_ACCESS_KEY -e SAUCE_LABS_URL -v /tmp/videos:/home/seluser/videos -v /var/run/docker.sock:/var/run/docker.sock -e NEW_SESSION_WAIT_TIMEOUT=1800000 --privileged dosel/zalenium start --sauceLabsEnabled true
`

Kubes ref: #671 

How to use New Session Wait Timeout in Kubes,  
https://opensource.zalando.com/zalenium/#usage

NEW_SESSION_WAIT_TIMEOUT | 600000 | Time in ms that a session will be kept in the queue before it timesout while waiting for a node to be available.

Not able to find as option - https://github.com/zalando/zalenium/blob/master/charts/zalenium/templates/_pod-template.yaml

**Comment by arnaud-deprez** [comment]
Correct!

We should be able to set this via environment variables + being able to pass any additional arbitrary environment variables.
I'll add this when I'll have a bit of time today or tomorrow.

Cheers,
