### ISSUE TITLE
Mounting error while Pulling latest from dosel/zalenium

### ISSUE THREAD

**Issue by DeChrish** [zalando/zalenium#815]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
 How to check it?

Docker Version:  
`Docker version 18.09.0, build 4d60db4`

If using docker-compose, version:  
   How to check it?

OS: 
`Red Hat Enterprise Linux Server release 7.5 (Maipo)`

Docker Command to start Zalenium:  

If using Kubernetes, specify your environment, and if relevant your manifests:  

## Actual Behavior -

`
docker: failed to register layer: devmapper: Error mounting '/dev/mapper/docker-253:6-2052-73e0468796610b23038e8f747c14e3bc98f35fde50d0b89f02aad4c9fe413bf9' on '/var/lib/docker/devicemapper/mnt/73e0468796610b23038e8f747c14e3bc98f35fde50d0b89f02aad4c9fe413bf9' (fstype='xfs' options='nouuid'): input/output error
<4>[392831.730479] XFS (dm-12): failed to locate log tail
<4>[392831.730889] XFS (dm-12): log mount/recovery failed: error -5
<4>[392831.732048] XFS (dm-12): log mount failed
`

P.S. 
**This image worked fine == Status: Downloaded newer image for dosel/zalenium:3.141.59d**

**Comment by diemol** [comment]
Hi @DeChrish,

After checking https://stackoverflow.com/questions/44942790/docker-error-failed-to-register-layer-symlink, https://github.com/moby/moby/issues/29354 and several other links after Googling the error, it just looks like it is an issue of the local installation (perhaps free up some space and check the local filesystem). This is not really a Zalenium issue.

**Comment by DeChrish** [comment]
@diemol  any recommended rhel configuration ?

**Comment by diemol** [comment]
Hardware configuration? what do you mean?

**Comment by DeChrish** [comment]
@diemol  RAM/ CPU / HDD

**Comment by diemol** [comment]
Rule of thumb, 1CPU 1GB RAM per container, add 1 CPU if recording video. HDD, depending on how many videos you want to keep and how long your tests are.
Keep in mind that this does not work in all environments, try to run your tests and see how much CPU and RAM in average is used based on your use case.
