### ISSUE TITLE
Error response from daemon: client is newer than server

### ISSUE THREAD

**Issue by cyrillebonnaud** [zalando/zalenium#83]
Hello guys

Having pulled dosel/zalenium and elgalu/selenium, when I run : 
`
docker run --rm -ti --name zalenium -p 4444:4444 -p 5555:5555 -v var/run/docker.sock:/var/run/docker.sock  dosel/zalenium start
`
I get the following error  : 
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.21)

Do you have any idea how to solve this ?

Thanks
cyrille

**Comment by elgalu** [comment]
@cyrillebonnaud give it a try to [the one-liner](https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#install-and-start) as it will check that you have the correct dependencies.

**Comment by diemol** [comment]
What @elgalu says is a good idea.

You could also try:
* Upgrade your docker version or 
* Check what version of docker API 1.21 is and pass it as a parameter, as we mention [here](https://github.com/zalando/zalenium#docker-version)

**Comment by cyrillebonnaud** [comment]
Using the following did the trick : 
`docker run --rm -ti --name zalenium -p 4444:4444 -p 5555:5555 \
  -v $(which docker):/usr/bin/docker \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/videos:/home/seluser/videos \
  dosel/zalenium start `

thanks guys
