### ISSUE TITLE
chromeOptions are not working with Zalenium

### ISSUE THREAD

**Issue by AlinaVasylieva** [zalando/zalenium#830]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**
Hey, a bit new to Zalenium, please let me know if the question is addressed not in the right place.
Using the following chromeOption
`chromeOptions: {
          args: [
           ......
            '--disable-notifications'`

But when run it with Zalenium Grid, this arg is not applied.
Could you please help to figure it out how to do it?

Zalenium Image Version(s):  

Docker Version:  

If using docker-compose, version:  

OS: 

Docker Command to start Zalenium:  

If using Kubernetes, specify your environment, and if relevant your manifests:

**Comment by diemol** [comment]
Hi @AlinaVasylieva,

The thing is that since a several Selenium versions ago, the correct way to declare `chromeOptions` is by prefixing it with `goog`, therefore it will look like `goog:chromeOptions`.

Please try to declare them like that. If it still does not work, feel free to reopen.

**Comment by AlinaVasylieva** [comment]
@diemol thank you so much for your help!
Worked for me!

**Comment by diemol** [comment]
Glad it helped!
