### ISSUE TITLE
[Chart]: replace persistence.enabled by persistence.video.enabled and persistence.data.enabled

### ISSUE THREAD

**Issue by arnaud-deprez** [zalando/zalenium#834]
## Expected Behavior

It should be possible to deploy zalenium on Kubernetes cluster via the helm chart with `PersistentVolume` for either: 
- video
- data (data shared across all selenium grid)
- video and data

## Actual Behavior

Currently when `persistence.enabled = true`, 2 `PersistentVolume` are systematically used for `video` and `data`.

## Proposal

We should replace the option `persistence.enabled` by `persistence.video.enabled` and `persistence.data.enabled` to have more fine grained control.

**Comment by diemol** [comment]
Hi @arnaud-deprez

Sounds good and makes a lot of sense, would be cool to get a PR for that!

**Comment by arnaud-deprez** [comment]
Yeah, 

I'll try to find a moment today or tomorrow :-)
