### ISSUE TITLE
Scoping issue in Zalenium; Same works fine in docker image from seleniumHQ

### ISSUE THREAD

**Issue by DeChrish** [zalando/zalenium#840]
TEST Framework  :  Java + Cucumber + cucumber-jvm-parallel-plugin

Test are executing in Parallel Mode using cucumber-jvm-parallel-plugin

OS: RHEL

Docker Command to start Zalenium:  
docker run --rm -d --name zalenium -p 4444:4444 -e SAUCE_USERNAME=saucelabs.id -e SAUCE_ACCESS_KEY=sauce-key -e SAUCE_LABS_URL=http://ondemand.saucelabs.com:80 -v /tmp/videos:/home/seluser/videos -v /var/run/docker.sock:/var/run/docker.sock -e NEW_SESSION_WAIT_TIMEOUT=1800000 --privileged dosel/zalenium start --sauceLabsEnabled true --sendAnonymousUsageInfo false

## Expected Behavior -
No scoping issue 

## Actual Behavior -

[ERROR] Tests run: 18, Failures: 0, Errors: 18, Skipped: 0, Time elapsed: 0.099 s <<< FAILURE! - in Parallel04IT
[ERROR] Examples:   Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: A scoping block is already in progress

[ERROR] Examples:   Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: A scoping block is already in progress

[ERROR] Examples:   Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: A scoping block is already in progress

[ERROR] Examples:   Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: A scoping block is already in progress

[ERROR] Examples:   Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: A scoping block is already in progress

[ERROR] Examples:   Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: A scoping block is already in progress

[ERROR] Examples:   Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: A scoping block is already in progress

[ERROR] Examples:   Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: A scoping block is already in progress

[ERROR] Examples:   Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: A scoping block is already in progress

[ERROR] Examples:   Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: A scoping block is already in progress

[ERROR] Examples:   Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: A scoping block is already in progress

[ERROR] Examples:   Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: A scoping block is already in progress

[ERROR] Examples:   Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: A scoping block is already in progress

[ERROR] Examples:   Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: A scoping block is already in progress

[ERROR] Examples:   Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: A scoping block is already in progress

[ERROR] Examples:   Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: A scoping block is already in progress

**Comment by diemol** [comment]
@DeChrish but that error comes from the testing framework you are using, what should we do? Why are no Zalenium logs provided? How can we know if this is really a Zalenium issue?

**Comment by DeChrish** [comment]
@diemol i will re-run it again and collect zalenium logs.

**Comment by diemol** [comment]
@DeChrish are those logs related to the test execution?
Can you please start Zalenium and then only run your test? After that please provide those logs. No need to run Zalenium in debug mode.

An alternative is that you provide a self contained test in a GitHub repo that I can clone and run to reproduce the issue.

**Comment by DeChrish** [comment]
@diemol I will share the git-repo. asap

**Comment by DeChrish** [comment]
@diemol looks like cucumber scenario issue. https://github.com/cucumber/cucumber-jvm/issues/1485
