### ISSUE TITLE
E-Mail wrong in coc

### ISSUE THREAD

**Issue by szuecs** [zalando/zalenium#844]
https://github.com/zalando/zalenium/blob/master/CODE_OF_CONDUCT.md
shows Diego as owner, but he has no zalando address anymore.

**Comment by szuecs** [comment]
@diemol I pinged someone internal who should decide this.

**Comment by diemol** [comment]
Thank you.

**Comment by diemol** [comment]
@szuecs @perploug do you know if Zappr was enabled again in all repos? Somehow I cannot merge PRs anymore since the status is not reported. 
The transfer of the repo thing is still in process and I don't have any admin rights anymore, sadly I am blocked now.

**Comment by perploug** [comment]
@diemol - I've turned it off again - this was due to a general update on all zalando repos

**Comment by diemol** [comment]
Thanks @perploug!

**Comment by elgalu** [comment]
Hi all, could we move FWD with transferring this project outside of Zalando? before it dies and left fully unmaintained.

**Comment by diemol** [comment]
Created PR #1109 to replace my old Zalando email with @elgalu's email since he is still working at Zalando and the moving the project outside Zalando got stalled.
