### ISSUE TITLE
Running test inside a docker container to a remote zalenium grid results in ProtocolError: ('Connection aborted.', BadStatusLine("''",))

### ISSUE THREAD

**Issue by rnth** [zalando/zalenium#846]
We have selenium grid already setup remotely.
I am using a docker image to connect to just connect to that grid (in robot script itself) and run it.
That particular test appears in the https://server/grid/console
But after a while i get ProtocolError: ('Connection aborted.', BadStatusLine("''",))

Why is this so ? I am unable to proceed further.

**Comment by diemol** [comment]
This is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
