### ISSUE TITLE
Zalenium containers restart after each test even when maxTestSessions set to 100

### ISSUE THREAD

**Issue by anirudhkumarvyas** [zalando/zalenium#849]
## 🐛 Bug Report
I have set up a Zalenium grid of 60 pods(desiredContainers) on GCP, I am using WebdriverIO framework to run concurrent tests each test of 30 sec. 
When I run the concurrent test (set in WebdriverIO) equal to number of pods, the test executes succesfully. However if I increase the number of test just above number of pods and keeping concurrency still set to 60 I get below error for number of test which are greater than number of pods .
Example : 
Concurrency set : 60
Number of pods : 60
Number of tests : 61 
Errors seen for number of test : 61 - 60 = 1

ERROR: Session [463407653afa56b183eb0394063af7c9] not available and is not among the last 1000 terminated sessions.
Active sessions are[]

## To Reproduce
1. Set up the Zalenium grid as per instructions on https://opensource.zalando.com/zalenium/  [Google Container Engine] 
2. Run the test with 60 concurrency and number of test 61

Zalenium.yaml attached
[zalenium.yaml.txt](https://github.com/zalando/zalenium/files/2800329/zalenium.yaml.txt)

## Expected behavior

Since the maxTestSessions is set to 100 the container should be reused and the containers should not be recreated.

## Environment

OS: linux
Zalenium Image Version(s): 3.141.59g

kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.9-gke.5", GitCommit:"d776b4deeb3655fa4b8f4e8e7e4651d00c5f4a98", GitTreeState:"clean", BuildDate:"2018-11-08T20:33:00Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

gcloud version
Google Cloud SDK 230.0.0
bq 2.0.39
core 2019.01.11
gsutil 4.35
kubectl 2018.09.17

**Comment by diemol** [comment]
@anirudhkumarvyas 
Sorry for the late reply, can you please provide the Zalenium logs?

**Comment by diemol** [comment]
Closing as we didn't get any more information.
