### ISSUE TITLE
Video does not record for real device nodes

### ISSUE THREAD

**Issue by MaheshGooner** [zalando/zalenium#850]
## 🐛 Bug Report

I tried to register a mac machine as a node with the normal procedure and was able to run the tests on my real device. But i cannot see the videos recorded on the dashboard. Although i could see the videos from the tests which are run on docker containers.

## To Reproduce

register a real device as a node and run the tests

## Expected behavior

videos should be recorded

## Test script reproducing this issue (when applicable)
java -jar selenium-server-standalone-xxx.jar -role node  -hub http://localhost:4444/grid/register 

node Config

> 
> browserTimeout: 16000
> 
> debug: false
> 
> host: 10.129.11.108
> 
> port: 2000
> 
> role: node
> 
> timeout: 1800
> 
> cleanUpCycle: 5000
> 
> maxSession: 5
> 
> capabilities: Capabilities {browserName: firefox, marionette: true, maxInstances: 5, platform: MAC, platformName: MAC, seleniumProtocol: WebDriver, server:CONFIG_UUID: 194ff692-efde-4fe1-9c21-d69...}
> 
> capabilities: Capabilities {browserName: chrome, maxInstances: 5, platform: MAC, platformName: MAC, seleniumProtocol: WebDriver, server:CONFIG_UUID: c9954502-84d7-45df-a3a7-5cd...}
> 
> capabilities: Capabilities {browserName: safari, maxInstances: 1, platform: MAC, platformName: MAC, seleniumProtocol: WebDriver, server:CONFIG_UUID: 17b94693-b7b9-4c66-a2bb-3c4..., technologyPreview: false}
> 
> downPollingLimit: 2

hub: http://localhost:4444/grid/register
## Environment

OS:  OS X Mojave
Zalenium Image Version(s):  v. 3.141.59

**Comment by diemol** [comment]
Hi @MaheshGooner,

>Expected behavior
>videos should be recorded 

Those are some high expectations :)

Video is recorded only for the tests running in the docker-selenium containers, Zalenium cannot record video any test running "natively" on the host.
