### ISSUE TITLE
Difficulty running in ECS task

### ISSUE THREAD

**Issue by rselias** [zalando/zalenium#855]
I'm able to run Zalenium on an EC2 instance without issue by SSHing into the instance and manually entering the run command. However, if I try to run it via task, Zalenium starts then quickly stops, and I can't find a descriptive error. Might anyone be able to point me in a direction to start looking for the issue?

Here's the docker log for the Zalenium container:
```Docker version 18.06.1-ce, build e68fc7a
-- LOG 21:09:43:348754425 Ensuring docker works...
"docker inspect" requires at least 1 argument.
See 'docker inspect --help'.

Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]

Return low-level information on Docker objects
-- LOG 21:09:43:477581979 Ensuring docker-selenium is available...
Copying files for Dashboard...
cp: cannot create regular file '/home/seluser/videos/index.html': No such file or directory
Starting Nginx reverse proxy...
Starting Selenium Hub...
.....21:09:44.710 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium server version: 3.141.59, revision: unknown
21:09:44.817 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
..21:09:45.313 [main] INFO  d.z.e.z.c.DockerContainerClient - About to clean up any left over DockerSelenium containers created by Zalenium
...............21:09:48.446 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Starting poller.
21:09:48.450 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - AutoStarting container, because 0 is less than min 2
..21:09:48.918 [main] INFO  d.z.ep.zalenium.aspect.HubAspect - Registering custom Zalenium servlets
21:09:49.029 [main] INFO  org.openqa.grid.web.Hub - Selenium Grid hub is up and running
21:09:49.029 [main] INFO  org.openqa.grid.web.Hub - Nodes should register to http://169.254.172.6:4445/grid/register/
21:09:49.031 [main] INFO  org.openqa.grid.web.Hub - Clients should connect to http://169.254.172.6:4445/wd/hub
Trapped SIGTERM/SIGINT so shutting down Zalenium gracefully...
Stopping Hub...
*************************************** Data Processing Agreement ***************************************
By using this software you agree that the following non-PII (non personally identifiable information)
data will be collected, processed and used by Zalando SE for the purpose of improving our test
infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
of the IP address are collected.

See the complete license at https://github.com/zalando/zalenium/blob/master/LICENSE.md
*************************************** Data Processing Agreement ***************************************
21:09:49.355 [DockerContainerClient shutdown hook] INFO  d.z.e.z.c.DockerContainerClient - About to clean up any left over DockerSelenium containers created by Zalenium
```
And here's the task definition:
```
{
  "ipcMode": null,
  "executionRoleArn": "arn:aws:iam::936193374620:role/zaleniExecutionRole",
  "containerDefinitions": [
    {
      "dnsSearchDomains": null,
      "logConfiguration": {
        "logDriver": "json-file",
        "options": null
      },
      "entryPoint": null,
      "portMappings": [
        {
          "hostPort": 4444,
          "protocol": "tcp",
          "containerPort": 4444
        }
      ],
      "command": [
        "start",
        "--videoRecordingEnabled",
        "false"
      ],
      "linuxParameters": null,
      "cpu": 1024,
      "environment": [],
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [
        {
          "readOnly": null,
          "containerPath": "/var/run/docker.sock",
          "sourceVolume": "docker"
        }
      ],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": null,
      "memoryReservation": 3072,
      "volumesFrom": [],
      "image": "dosel/zalenium:latest",
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "systemControls": null,
      "privileged": true,
      "name": "zalenium"
    },
    {
      "dnsSearchDomains": null,
      "logConfiguration": {
        "logDriver": "json-file",
        "options": null
      },
      "entryPoint": null,
      "portMappings": [],
      "command": null,
      "linuxParameters": null,
      "cpu": 0,
      "environment": [],
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": null,
      "memoryReservation": 128,
      "volumesFrom": [],
      "image": "elgalu/selenium:latest",
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "systemControls": null,
      "privileged": null,
      "name": "selenium"
    }
  ],
  "placementConstraints": [],
  "memory": null,
  "taskRoleArn": "arn:aws:iam::936193374620:role/zaleniExecutionRole",
  "compatibilities": [
    "EC2"
  ],
  "taskDefinitionArn": "arn:aws:ecs:us-east-1:936193374620:task-definition/zalenium:51",
  "family": "zalenium",
  "requiresAttributes": [
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.privileged-container"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.task-eni"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.task-iam-role"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.logging-driver.json-file"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.21"
    }
  ],
  "pidMode": null,
  "requiresCompatibilities": [
    "EC2"
  ],
  "networkMode": "awsvpc",
  "cpu": null,
  "revision": 51,
  "status": "ACTIVE",
  "volumes": [
    {
      "name": "docker",
      "host": {
        "sourcePath": "/var/run/docker.sock"
      },
      "dockerVolumeConfiguration": null
    }
  ]
}
```

**Comment by diemol** [comment]
Hi @rselias,

Please have a look at #463, there is a task definition there that might help you. Other than that, I cannot help so much because I have not used ECS. If you need some help, I"m sure you can ping @MarianoSalerno in #463, he might be able to give you a hand.

**Comment by shailendrajain1208** [comment]
Hi @rselias : Did it work for you. I am struggling with task definition while running on ECS. It would be helpful if you can point me good working tasks definitions .
mentioning @MarianoSalerno as well to get working tasks def..
thanks guys!

**Comment by rselias** [comment]
Unfortunately not. I managed to get the task to work once, but when I tried it again with exactly the same configuration, it failed with the same error as before. I have a hunch there's a bug in there somewhere. Instead of using a task, I ended up writing a shell script using the AWS CLI to start up an EC2 instance and run Zalenium on it.

**Comment by shailendrajain1208** [comment]
@rselias : Thanks for your quick response. So you are using shell scripts in ECS environment or you just moved away from ecs. Can you please give me sample shell script so that i can try in that way if it is under EC2 is running under ECS. thanks for your response!

**Comment by rselias** [comment]
Sure. This is written for an Azure DevOps agent, so it's a bit weird where I had to avoid using $() syntax for substitution. Feel free to use more standard syntax if you're running in a different environment. It's also assuming you've already configured your AWS credentials with the CLI.

```
#Need to generate a new key pair if you don't have the private key
read randHex < <(openssl rand -hex 8)
keyName="key_$randHex"
aws ec2 create-key-pair --key-name $keyName --output text --query 'KeyMaterial' > $keyName.pem
chmod 400 $keyName.pem

#Run the EC2 instance
aws ec2 run-instances \
--image-id 'ami-03c999cbbc54b7a4d' \ #Ubuntu 18 with Docker and AWS SSM installed
--count 1 \
--instance-type xx.whateversize \
--key-name $keyName \
--security-group-ids sg-xxxxxxxxxxxxxxxxx \
--subnet-id subnet-xxxxxxxx \
--iam-instance-profile Name='SSM' \
--output text \
> instanceInfo.txt
read instanceID < <(grep -oP "\s\K(i-[a-z0-9]*)" instanceInfo.txt)
echo $instanceID
read hubIP < <(grep -oP "PRIVATEIPADDRESS.*\K(10\.0\.2\.[0-9]*)" instanceInfo.txt)
echo $hubIP
rm instanceInfo.txt

#Wait for the instance to run and register with the SSM
aws ec2 wait instance-running --filters "Name=instance-id,Values=$instanceID"
timeout 30 bash -c \
"until grep $instanceID <(aws ssm describe-instance-information --output text); \
do sleep 1; \
done"

#Pull Docker images
aws ssm send-command --instance-ids "$instanceID" --document-name "AWS-RunShellScript" \
--comment "Pull Images" --parameters commands=\
["docker pull dosel/zalenium:latest",\
"docker pull elgalu/selenium:latest"]

#Run Zalenium
aws ssm send-command --instance-ids "$instanceID" --document-name "AWS-RunShellScript" \
--comment "Run Zalenium" --parameters commands=\
["docker run --rm -ti -d \
--name zalenium \
-p 4444:4444 \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /tmp/videos:/home/seluser/videos \
--privileged \
dosel/zalenium start \
--videoRecordingEnabled true \
--timeZone \\"yourtimezone\\""]

#Store any variables you'll need later
```
After the test suite has finished:
```
aws ec2 terminate-instances --instance-ids $instanceID
aws ec2 delete-key-pair --key-name $keyName
rm $keyName.pem
```

**Comment by shailendrajain1208** [comment]
@rselias 👍 Thank you so much for detailed information. it would be really helpful while i am a new user to AWS. I will try and get back to you in case i am stuck .
You said task definition worked one time for you. can you please upload that as well if it is different than what you have in this thread since i want to compare what i have created . thanks a lot for your help !

**Comment by shailendrajain1208** [comment]
@rselias : Here is my tasks def which is giving error 
01:31:25 An error occurred (ClientException) when calling the RegisterTaskDefinition operation: Unknown volume 'shm'.

{
  "family": "zalenium-tool-task-defn",
  "volumes": [
    {
      "host": {
        "sourcePath": "/var/run/docker.sock"
      },
      "name": "docker"
    },
    {
      "host": {
        "sourcePath": "/home/seluser/videos"
      },
      "name": "videos"
    }
  ],

  "containerDefinitions": [
    {
      "name": "zalenium",
      "hostname": "zalenium",
      "image": "artifactory.cloud.capitalone.com/entepriseatdd/bluexpressdashboard:zaleniumJan20_v4",
      "memoryReservation": 6144,
      "essential": true,
      "privileged": true,
      "cpu": 1024,
      "mountPoints": [
        {
          "sourceVolume": "shm",
          "containerPath": "/dev/shm",
          "readOnly": false
        },
        {
          "sourceVolume": "docker",
          "containerPath": "/var/run/docker.sock"
        },
        {
          "sourceVolume": "videos",
          "containerPath": "/home/seluser/videos",
          "readOnly": false
        }
      ],
      "portMappings": [
        {
          "containerPort": 4444,
          "hostPort": 8080,
          "protocol": "tcp"
        }
      ],
      "command": [
        "start",
        "--videoRecordingEnabled",
        "false",
        "--seleniumImageName",
        "artifactory.cloud.capitalone.com/entepriseatdd/bluexpresshub:elg-3_141_59p2_c70"
      ]
    }
  ]
}

**Comment by swsunnywadhwa** [comment]
I am also facing slimier issue, Please let me know if anyone is able to run ECS with EC2 by using zalenium image.

**Comment by shailendrajain1208** [comment]
Hi @swsunnywadhwa , Yes I have my ECS cluster running without any issues. Please check #463 for more information. I was having issue with task def but it is fixed now

**Comment by swsunnywadhwa** [comment]
@shailendrajain1208 thanks for the response.

Is it possible to share the task def which you are using. You can remove the confidential information if any in task def.

**Comment by shailendrajain1208** [comment]
@swsunnywadhwa : I have already added in #463 .

**Comment by diemol** [comment]
Would be cool if you could send a PR to add this to the docs.

**Comment by swsunnywadhwa** [comment]
@shailendrajain1208  Thanks for your response. 

This is my task def but its not working.



{
  "ipcMode": null,
  "executionRoleArn": null,
  "containerDefinitions": [
    {
      "dnsSearchDomains": null,
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group": "/ecs/Zel-Task",
          "awslogs-region": "us-west-2",
          "awslogs-stream-prefix": "ecs"
        }
      },
      "entryPoint": null,
      "portMappings": [
        {
          "hostPort": 80,
          "protocol": "tcp",
          "containerPort": 4444
        }
      ],
      "command": null,
      "linuxParameters": null,
      "cpu": 512,
      "environment": [],
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [
        {
          "readOnly": null,
          "containerPath": "/dev/shm",
          "sourceVolume": "shm"
        },
        {
          "readOnly": null,
          "containerPath": "/var/run/docker.sock",
          "sourceVolume": "docker"
        },
        {
          "readOnly": null,
          "containerPath": "/home/seluser/videos",
          "sourceVolume": "videos"
        }
      ],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": null,
      "memoryReservation": null,
      "volumesFrom": [],
      "stopTimeout": null,
      "image": "dosel/zalenium:latest",
      "startTimeout": null,
      "dependsOn": null,
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": {
        "retries": 3,
        "command": [
          "start",
          "--maxTestSessions",
          "2",
          "--desiredContainers",
          "2",
          "--maxDockerSeleniumContainers",
          "3",
          "--seleniumImageName",
          "elgalu/docker-selenium:latest"
        ],
        "timeout": 5,
        "interval": 30,
        "startPeriod": null
      },
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "systemControls": null,
      "privileged": true,
      "name": "Zelenium"
    },
    {
      "dnsSearchDomains": null,
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group": "/ecs/Zel-Task",
          "awslogs-region": "us-west-2",
          "awslogs-stream-prefix": "ecs"
        }
      },
      "entryPoint": null,
      "portMappings": [],
      "command": null,
      "linuxParameters": null,
      "cpu": 512,
      "environment": [],
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [
        {
          "readOnly": null,
          "containerPath": "/dev/shm",
          "sourceVolume": "shm"
        }
      ],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": null,
      "memoryReservation": null,
      "volumesFrom": [],
      "stopTimeout": null,
      "image": "elgalu/docker-selenium:latest",
      "startTimeout": null,
      "dependsOn": null,
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "systemControls": null,
      "privileged": true,
      "name": "Selinium"
    }
  ],
  "placementConstraints": [],
  "memory": "2000",
  "taskRoleArn": "arn:aws:iam::**************:role/ecsTaskExecutionRole",
  "compatibilities": [
    "EC2"
  ],
  "taskDefinitionArn": "arn:aws:ecs:us-west-2:**********:task-definition/Zel-Task:6",
  "family": "Zel-Task",
  "requiresAttributes": [
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.privileged-container"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.task-iam-role"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.container-health-check"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.24"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
    }
  ],
  "pidMode": null,
  "requiresCompatibilities": [
    "EC2"
  ],
  "networkMode": null,
  "cpu": "1500",
  "revision": 6,
  "status": "ACTIVE",
  "proxyConfiguration": null,
  "volumes": [
    {
      "name": "shm",
      "host": {
        "sourcePath": "/dev/shm"
      },
      "dockerVolumeConfiguration": null
    },
    {
      "name": "docker",
      "host": {
        "sourcePath": "/var/run/docker.sock"
      },
      "dockerVolumeConfiguration": null
    },
    {
      "name": "videos",
      "host": {
        "sourcePath": "/tmp/videos"
      },
      "dockerVolumeConfiguration": null
    }
  ]
}

**Comment by swsunnywadhwa** [comment]
@shailendrajain1208  Please confirm if you get a chance to check the above configuration.

**Comment by shailendrajain1208** [comment]
{
"family": "zalenium-tool-task-defn",
"volumes": [
{
"host": {
"sourcePath": "/dev/shm"
},
"name": "shm"
},
{
"host": {
"sourcePath": "/var/run/docker.sock"
},
"name": "docker"
},
{
"host": {
"sourcePath": "/bluxpress"
},
"name": "videos"
}
],
"containerDefinitions": [
{
"name": "selenium-zalenium",
"image": "xxxxxxx",
"memoryReservation": 8144,
"essential": true,
"privileged": true,
"mountPoints": [
{
"sourceVolume": "shm",
"containerPath": "/dev/shm",
"readOnly": false
},
{
"sourceVolume": "docker",
"containerPath": "/var/run/docker.sock"
},
{
"sourceVolume": "videos",
"containerPath": "/home/seluser/videos",
"readOnly": false
}
],
"portMappings": [
{
"containerPort": 4444,
"hostPort": 0,
"protocol": "tcp"
}
],
"environment": [
{
"name": "PULL_SELENIUM_IMAGE",
"value": "false"
}
],
"command": [
"start",
"--screenWidth",
"1980",
"--screenHeight",
"1200",
"--sauceLabsEnabled",
"false",
"--browserStackEnabled",
"false",
"--testingBotEnabled",
"false",
"--startTunnel",
"false",
"--sendAnonymousUsageInfo",
"false",
"--debugEnabled",
"false",
"--videoRecordingEnabled",
"true",
"--timeZone",
"America/New_York",
"--maxTestSessions",
"5",
"--desiredContainers",
"8",
"--maxDockerSeleniumContainers",
"50",
"--retentionPeriod",
"2",
"--seleniumImageName",
"xxxx"
]
},
{
"name": "selenium-custom",
"image": "xxxx",
"memoryReservation": 1024,
"essential": true,
"privileged": true,
"mountPoints": [
{
"sourceVolume": "shm",
"containerPath": "/dev/shm",
"readOnly": false
}
]
}
]
}

**Comment by shailendrajain1208** [comment]
@swsunnywadhwa : Please check this task def and it works fine.  If you use PULL_SELENIUM_IMAGE = true . you can remove section for custom image
{
"name": "selenium-custom",
"image": "xxxx",
"memoryReservation": 1024,
"essential": true,
"privileged": true,
"mountPoints": [
{
"sourceVolume": "shm",
"containerPath": "/dev/shm",
"readOnly": false
}

@swsunnywadhwa : please let me know who it goes now

**Comment by swsunnywadhwa** [comment]
@shailendrajain1208  I am not sure what issue exactly on my ECS culuster,

I am using a T2 large instance with 2 selenium session. In initial stage all the three containers are working and after few seconds Zalenium and 1 Selenium container is getting exited. I am using same task defination but not sure what exactly the issue is. In container logs also i can't see much information.

Could you please join on the Selenium slack where we can have some discussion online. This is an official slack link from Selenium Zalenium. 


![image](https://user-images.githubusercontent.com/48507817/54525991-6d0f7980-499b-11e9-8495-a346b036fcf8.png)

![image](https://user-images.githubusercontent.com/48507817/54526013-7b5d9580-499b-11e9-8c49-51d37222ef6d.png)

**Comment by swsunnywadhwa** [comment]
@shailendrajain1208  Thanks Its working now.

In my configuration env variable were missing.

**Comment by shailendrajain1208** [comment]
@swsunnywadhwa : That is good news man. would you please upload final task definition here. i want to take it reference when creating a document for ECS. 

Do you have any scale up plan as well ?

**Comment by swsunnywadhwa** [comment]
@shailendrajain1208  yes i have plan  to scale this up with EKS or something if we can manage this via ECS.

I am looking for a setup where i can host Zalenium in one instance and Selenium in another instance where Auto scaling can be enabled.

I hope you are also using something like this if not may be we can work to scale this up . I am using below task definition via CF.

    "TaskDefinition": {
      "Type": "AWS::ECS::TaskDefinition",
      "DependsOn": [
        "VPC"
      ],
      "Properties": {
        "Family": "selenium-Service",
        "ContainerDefinitions": [{
          "Name": "selenium-Service",
          "Essential": true,
          "Privileged": true,
          "Image": "************/dosel/zalenium:latest",
          "Memory": 800,
          "Environment": [{
            "Name": "PULL_SELENIUM_IMAGE",
            "Value": "false"
          }],
          "Command": [
            "start",
            "--screenWidth",
            "1980",
            "--screenHeight",
            "1200",
            "--videoRecordingEnabled",
            "true",
            "--timeZone",
            "America/New_York",
            "--maxTestSessions",
            "2",
            "--desiredContainers",
            "2",
            "--maxDockerSeleniumContainers",
            "2",
            "--retentionPeriod",
            "2",
            "--seleniumImageName",
            "**********/elgalu/selenium:latest"
          ],
          "PortMappings": [{
            "HostPort": "80",
            "ContainerPort": "4444",
            "Protocol": "tcp"
          }],

          "MountPoints": [{
            "SourceVolume": "docker",
            "ContainerPath": "/var/run/docker.sock",
            "ReadOnly": false
          }, {
            "SourceVolume": "videos",
            "ContainerPath": "/home/seluser/videos",
            "ReadOnly": false
          }],
          "LogConfiguration": {
            "LogDriver": "awslogs",
            "Options": {
              "awslogs-group": {
                "Ref": "CloudWatchLogsGroup"
              },
              "awslogs-region": {
                "Ref": "AWS::Region"
              }
            }
          }
        }],
        "Volumes": [{
          "Host": {
            "SourcePath": "/var/run/docker.sock"
          },
          "Name": "docker"
        }, {
          "Host": {
            "SourcePath": "/tmp/video"
          },
          "Name": "videos"
        }, {
          "Host": {
            "SourcePath": "/dev/shm"
          },
          "Name": "shm"
        }]
      }
    },
