### ISSUE TITLE
Auto remove pods wrong/aborted tests in k8s

### ISSUE THREAD

**Issue by zpavlig** [zalando/zalenium#856]
Hello.

Installed zalenium version 3.141.59e and selenium-node version 3.141.59-p6-1 in k8s.
I have a lot of idle pods because of some wrong/aborted tests. Only delete manually.

Read docs and find:

> By default, Zalenium allows a test to be idle up to 90 seconds. After that elapsed time, the session will be terminated, the node will be shutdown and the recorded video will be saved (if video recording is enabled). This prevents a test to run indefinitely after something went wrong. If you need to have a longer idle timeout, just set an idleTimeout capability in your test. Example code in Java for the capability (it sets the idleTimeout to 150 seconds):
> 
>     DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
>     desiredCapabilities.setCapability(CapabilityType.BROWSER_NAME, BrowserType.FIREFOX);
>     desiredCapabilities.setCapability(CapabilityType.PLATFORM_NAME, Platform.LINUX);
>     desiredCapabilities.setCapability("idleTimeout", 150);

but not working in my k8s cluster

please help me, thanks.

**Comment by diemol** [comment]
Hi @zpavlig,

I don't mean to be rude, but I'm going to close this issue because we don't have enough information to provide a good answer. Could you please create a new issue and fill out the full template?

**Comment by zpavlig** [comment]
@diemol What information is needed?

**Comment by diemol** [comment]
When you create an issue, there is a template that has placeholders for the information we need to understand the issue better.
