### ISSUE TITLE
Unable to mount volumes inside the chrome-node containers

### ISSUE THREAD

**Issue by prashanth-sams** [zalando/zalenium#859]
## Expected behavior

Should mount local volumes inside the chrome-node containers

## Test script reproducing this issue (when applicable)

```
docker run --rm --name zalenium -p 4444:4444 \
  -e PULL_SELENIUM_IMAGE=true \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/videos:/home/seluser/videos \
  -v $PWD/project/data:/var/tmp \
  --privileged dosel/zalenium start \
  --desiredContainers 8 --screenWidth 1440 --screenHeight 900 \
  --timeZone "Asia/Dubai" --maxDockerSeleniumContainers 8 --maxTestSessions 50 \
  --videoRecordingEnabled false --keepOnlyFailedTests true --sendAnonymousUsageInfo false &
```

By doing so, the volume ` -v $PWD/project/data:/var/tmp` is mounted inside the Hub (dosel) but not on the nodes (elgalu).

![image](https://user-images.githubusercontent.com/2948696/52277823-08f6a000-296f-11e9-9049-b9ce93b5c45c.png)

## Environment

OS: 
Zalenium Image Version(s): latest
Docker version: latest

**Comment by prashanth-sams** [comment]
@diemol any help here

**Comment by diemol** [comment]
@prashanth-sams please check "Mounting volumes/folders across containers" in https://opensource.zalando.com/zalenium/

**Comment by prashanth-sams** [comment]
@diemol I tried `-v $PWD/project/data:/tmp/node/var/tmp` even that didn't help

**Comment by diemol** [comment]
I am not sure you can actually mount things in `/var/tmp/`, you should try a different path.

**Comment by prashanth-sams** [comment]
@diemol is there a way to mount volumes in nodes if we use `curl -sSL https://raw.githubusercontent.com/dosel/t/i/p | bash -s start` command

**Comment by anandhi-credible** [comment]
@diemol As @prashanth-sams asked, is there a way to mount volumes in nodes via `curl` command?
