### ISSUE TITLE
Zalenium with TestNG thread-count

### ISSUE THREAD

**Issue by kshammout** [zalando/zalenium#862]
## 💬 Questions and Help
hello, 
I'm running my tests by using TestNG, what I want to understand how Zalenium will handle the Thread-count that I send, what I notice Zalenium does not affect when I send 1 thread or 10 thread I have the same results, where I'm running my test on TestNG on "tests" level?

**Comment by diemol** [comment]
@kshammout 

Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y) or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
