### ISSUE TITLE
Session problem during testing

### ISSUE THREAD

**Issue by AliagaMusayev** [zalando/zalenium#864]
I am facing with session problem during Testing through Zalenium docker image. We have test cases more than 100 and it takes more than 1 hour for testing of all test cases. But during testing, after 30-40 minutes Zalenium node ends the session and all remaining test cases fail due to this reason. I don't know the reason. Please help me to solve this problem.
Thanks in advance

**Comment by diemol** [comment]
@AliagaMusayev could you please create a new issue with the full template? There is not enough information to help you.

Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y) or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
