### ISSUE TITLE
Test status is always showing as Success on dashboard even after setting Cookie cookie = new Cookie("zaleniumTestPassed", "false");

### ISSUE THREAD

**Issue by akshattambe** [zalando/zalenium#866]
## 🐛 Bug Report

Hi, I have gone through the previous bugs but the resolution in them couldn't help me in getting the right fix for my issue. 

In my case Test status is always showing as Success on dashboard even after setting. This is happening in Chrome and Firefox both. I am using the latest version of both browsers.
```
Cookie cookie = new Cookie("zaleniumTestPassed", "false");
```

Here is the sample code for your reference.
```
@After
    public void afterScenario(Scenario scenario){
        if (scenario.isFailed()) {
            logger.info("Test failed.");
            // Take a screenshot...
            TakesScreenshot scrShot =((TakesScreenshot)getDriverForCurrentThread());
            File SrcFile=scrShot.getScreenshotAs(OutputType.FILE);
            SrcFile.renameTo(new File("src/test/resources/screenshots/"+scenario.getName()));

            //Mark test as Fail
            Cookie cookie = new Cookie("zaleniumTestPassed", "false");
            driverThreadLocal.get().manage().addCookie(cookie);
        }else{
        //Mark test as Pass
        Cookie cookie = new Cookie("zaleniumTestPassed", "true");
        driverThreadLocal.get().manage().addCookie(cookie);
       }
        synchronized (driverThreadLocal){
            new BrowserDownloadDirectory().cleanDownloadDirectory();
            if(driverThreadLocal != null){
                driverThreadLocal.get().quit();
            }
        }
    }
```
Please refer screenhsot -
![image](https://user-images.githubusercontent.com/20226086/52734518-b9931e00-2fc5-11e9-9dce-0208116694b8.png)

## Environment

OS: Ubuntu 16.04
Zalenium Image Version(s): dosel/zalenium:3
Azure Docker version: 3.01
AKS Kubernetes

Please share your thoughts if you see I am missing any configuration at my end. I am new to Zalenium and trying to learn and implement its features. Please let me know if you need more details.

Thanks for your help in advance

**Comment by akshattambe** [comment]
This is totally my mistake. The issue is not reproducing now.

**Comment by akshattambe** [comment]
This is totally my mistake. The issue is not reproducing now. The feature is working in Chrome and Firefox as expected.

**Comment by rhiltbrunner** [comment]
In addition to others with the same problem!

Hi, i had the same problem. I dont know what the problem of akshattambe was, but i know what i did wrong. I set the Cookie behavior to 0:

FirefoxProfile ffp = new FirefoxProfile();
ffp.setPreference("network.cookie.cookieBehavior", 0);

In that case, you can prevent cross-site tracking with cookies and EverCookies.
Then i set the behavior to 1, to allow the cookies and it worked for me so far.

FirefoxProfile ffp = new FirefoxProfile();
ffp.setPreference("network.cookie.cookieBehavior", 1);

**Comment by bhagya74** [comment]
@akshattambe 

Hi, I'm facing the similar issue, but in my case TestStatus is coming as Completed in dashboard for failed scenarios(TestStatus is success for pass scenario). 

Below is the sample code for reference(using Cucumber,Selenium,Junit framework):
@After
    public void afterScenario(Scenario scenario) throws InterruptedException {
        boolean status = scenario.isFailed();
        String flag;
        if(status)
            flag="false";
        else
            flag="true";
        Cookie cookie = new Cookie("zaleniumTestPassed",flag);
        driver.manage().addCookie(cookie);
        driver.quit();
    }

Can you please share your resolution steps to check if that works for me?
Any help is much appreciated!
