### ISSUE TITLE
some times containers are not destroyed after the run

### ISSUE THREAD

**Issue by PramodDutta** [zalando/zalenium#87]
I have been using it to run the protractor test cases, Some times when i run test cases, Zalenium creates 3 containers and run test cases in them. But after test finishes, Those three are remaining in on(not destroyed). and in next run we have 6 out of which 3 are not used and just sitting there.

Do you guys require more information. Let me know. I am facing this issue a lot.

P.S : I have very new to open source community to please bear with me

**Comment by diemol** [comment]
Hi @PramodDutta,

Zalenium will shutdown the container after the test completes or after a period of test inactivity/timeout (default is 90 seconds). 
The test completes when the `webDriver.quit()` command is sent, maybe you are missing this in your test?

**Comment by PramodDutta** [comment]
Thanks for the Reply.

**Comment by diemol** [comment]
Well, this should not me happening since we introduced the feature of terminating the node/container when the test is idle for 90 seconds. This was done for #52 

What image tags are you using? If they are not the latest ones, could you please update?

**Comment by diemol** [comment]
@PramodDutta I'll close this issue due to inactivity. Please feel free to reopen it if you got more information in case something does not work :)
