### ISSUE TITLE
maxTestSessions is ignored 

### ISSUE THREAD

**Issue by nagendra-devireddy** [zalando/zalenium#870]
I have tried setting the max sessions per container to 4 with below **command** (in windows 10)
docker run --rm -ti --name zalenium -p 4444:4444 ^
-v /var/run/docker.sock:/var/run/docker.sock ^
-v /c/Users/test_user/temp/videos:/home/seluser/videos ^
--privileged dosel/zalenium start --maxTestSessions 4

## **here are the logs**
> docker run --rm -ti --name zalenium -p 4444:4444 ^
> More?       -v /var/run/docker.sock:/var/run/docker.sock ^
> More?       -v /c/Users/test_user/temp/videos:/home/seluser/videos ^
> More?       --privileged dosel/zalenium start --maxTestSessions 4
> Docker version 18.09.0, build 4d60db4
> -- LOG 17:37:52:108161400 Ensuring docker works...
> -- LOG 17:37:52:261904000 Ensuring docker-selenium is available...
> haveged: haveged starting up
> Copying files for Dashboard...
> Starting Nginx reverse proxy...
> Starting Selenium Hub...
> .....17:37:55.839 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium server version: 3.141.59, revision: unknown
> .17:37:56.039 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
> ....17:37:56.992 [main] INFO  d.z.e.z.c.DockerContainerClient - About to clean up any left over DockerSelenium containers created by Zalenium
> ........17:37:58.830 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Starting poller.
> ...17:37:59.817 [main] INFO  d.z.ep.zalenium.aspect.HubAspect - Registering custom Zalenium servlets
> .17:38:00.117 [main] INFO  org.openqa.grid.web.Hub - Selenium Grid hub is up and running
> 17:38:00.120 [main] INFO  org.openqa.grid.web.Hub - Nodes should register to http://172.17.0.2:4445/grid/register/
> 17:38:00.120 [main] INFO  org.openqa.grid.web.Hub - Clients should connect to http://172.17.0.2:4445/wd/hub
> Selenium Hub started!
> Sauce Labs not enabled...
> Browser Stack not enabled...
> TestingBot not enabled...
> Zalenium is now ready!
> *************************************** Data Processing Agreement ***************************************
> By using this software you agree that the following non-PII (non personally identifiable information)
> data will be collected, processed and used by Zalando SE for the purpose of improving our test
> infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
> of the IP address are collected.

**Grid Console**
http://localhost:4444/grid/console?config=true&configDebug=true
In the grid console always showing it as 1 for maxSession
![image](https://user-images.githubusercontent.com/5219581/52802809-ac9a2b80-30a6-11e9-9769-bf60ae637c11.png)

I have tried with below command as well in Rancher 1.x
command: >
start --maxTestSessions 5
--timeZone "Asia/Calcutta"

Even we have passed ZALENIUM_MAX_TEST_SESSIONS as environment variable while starting the zalenium server.

After doing all(ignoring console maxSessions :1 message),we went ahead and run the script still captured only 1 test case per video.

**Comment by diemol** [comment]
Hi @nagendra-devireddy,

There is no relation between the `maxTestSessions` parameter in Zalenium and the `maxSession` one in Selenium Grid.
WIth `maxTestSessions` you just set the maximum amount of tests that will run in a node (sequentially), which by default is one. It is not possible to run more than one test concurrently in one node.
