### ISSUE TITLE
Video is not captured on Red Hat 4.8.3-9

### ISSUE THREAD

**Issue by espguitarist33** [zalando/zalenium#872]
## 🐛 Bug Report

When running with default configuration on Red Hat 4.8.3-9 (Linux version 3.10.0-327.28.3.el7.x86_64) host, we are unable to capture video. I can see the logs are all being created, and I can see the test run logged via the dashboard, but the video file throws a 404. I don't see anything that looks like a video file being captured in the videos folder, only the text logs.

## To Reproduce

1. Run the documented command to create an instance in Linux
2. Run a test
3. View the dashboard, note no video available
4. See 404 for request to load video file in browser console

## Expected behavior

The expected behavior would be to see the video after running the test.

## Environment

OS:  Red Hat 4.8.3-9 (Linux version 3.10.0-327.28.3.el7.x86_64)
Zalenium Image Version(s): I pulled latest yesterday
Docker version: 1.13.1

**Comment by diemol** [comment]
@espguitarist33 
Can you please try to use https://github.com/elgalu/docker-selenium directly on that operating system and see if a video gets recorded?

**Comment by espguitarist33** [comment]
Sure!

**Comment by espguitarist33** [comment]
Some things I’m noticing just trying to get it running:

I started with -e VIDEO=true  but /videos is blank

The documentation says to run `docker exec grid /bin-utils/stop-video`, however this script is actually located in /usr/bin. When I do try to run it I end up with `unix:///var/run/sele/supervisor.sock refused connection` and if I try to start-video I get the following:

seluser@87484c43433e:/usr/bin$ start-video
cat: VIDEO_LOG_FILE: No such file or directory
cat: VIDEO_PIDFILE: No such file or directory
cat: VIDEO_FILE_NAME: No such file or directory
cat: VIDEO_PATH: No such file or directory
unix:///var/run/sele/supervisor.sock refused connection
Waiting for ffmpeg video recording to start...
ERROR: Required env var VIDEO_LOG_FILE
ERROR: Failed while waiting for video recording to start!

**Comment by diemol** [comment]
Did you check https://github.com/elgalu/docker-selenium/blob/master/docs/videos.md?
I just followed it step by step and it works.

**Comment by espguitarist33** [comment]
Just tried that and got the following errors:

==> errors <==
/var/log/cont/wait-xvfb-stdout.log:    class:    TrueColor
/var/log/cont/wait-xvfb-stdout.log:    depth:    32 planes
/var/log/cont/wait-xvfb-stdout.log:    available colormap entries:    256 per subfield
/var/log/cont/wait-xvfb-stdout.log:    red, green, blue masks:    0xff0000, 0xff00, 0xff
/var/log/cont/wait-xvfb-stdout.log:    significant bits in color specification:    8 bits
/var/log/cont/wait-xvfb-stdout.log:Done wait-xvfb.sh
/var/log/cont/xterm-stderr.log:grep: /var/log/cont/video-rec-stdout.log: No such file or directory
/var/log/cont/xterm-stderr.log:ERROR: FATAL! supervisorctl status failed in /usr/bin/start-xterm.sh
/var/log/cont/xterm-stdout.log:--LOG 16:23:19:769932804 Won't start noVNC service due to NOVNC env var false
/var/log/cont/xterm-stdout.log:Waiting for Selenium Hub to be ready...
/var/log/cont/xterm-stdout.log:...........0
/var/log/cont/xterm-stdout.log:Done wait-selenium-hub.sh
/var/log/cont/xterm-stdout.log:Waiting for Selenium Node Chrome stable to be ready...
/var/log/cont/xterm-stdout.log:.........true
/var/log/cont/xterm-stdout.log:Done wait-selenium-node-chrome-stable.sh
/var/log/cont/wait-xvfb-stdout.log:    class:    TrueColor
/var/log/cont/wait-xvfb-stdout.log:    depth:    32 planes
/var/log/cont/wait-xvfb-stdout.log:    available colormap entries:    256 per subfield
/var/log/cont/wait-xvfb-stdout.log:    red, green, blue masks:    0xff0000, 0xff00, 0xff
/var/log/cont/wait-xvfb-stdout.log:    significant bits in color specification:    8 bits
/var/log/cont/wait-xvfb-stdout.log:Done wait-xvfb.sh
/var/log/cont/xterm-stderr.log:grep: /var/log/cont/video-rec-stdout.log: No such file or directory
/var/log/cont/xterm-stderr.log:ERROR: FATAL! supervisorctl status failed in /usr/bin/start-xterm.sh
/var/log/cont/xterm-stdout.log:--LOG 16:23:19:769932804 Won't start noVNC service due to NOVNC env var false
/var/log/cont/xterm-stdout.log:Waiting for Selenium Hub to be ready...
/var/log/cont/xterm-stdout.log:...........0
/var/log/cont/xterm-stdout.log:Done wait-selenium-hub.sh
/var/log/cont/xterm-stdout.log:Waiting for Selenium Node Chrome stable to be ready...
/var/log/cont/xterm-stdout.log:.........true
/var/log/cont/xterm-stdout.log:Done wait-selenium-node-chrome-stable.sh
/var/log/cont/xterm-stderr.log:ERROR: FATAL! supervisorctl status failed in /usr/bin/start-xterm.sh
ERROR:
   Your docker-selenium didn't start properly.

**Comment by diemol** [comment]
Then it seems that the docker image does not work in your operating system, perhaps you have some restrictions or settings that don't allow it?
It is hard for us to say since we don't have that environment available.

**Comment by espguitarist33** [comment]
I figured out the issue there.  The host didn’t have supervisor set up, which I thought it would have. Now that I have that set up I was able to get all the way to actually seeing a 1,511 kb .mp4 file.  The video just shows the DockerSelenium logo, however.   It’s at least recording now, which it wasn’t at all before.

**Comment by espguitarist33** [comment]
I gave it a shot on zalenium proper after installing supervisor and it is all working okay now. So for anybody having this issue, easy_install supervisor is the magic ticket!
