### ISSUE TITLE
Driver.quit() does not remove the exited container

### ISSUE THREAD

**Issue by jaasal** [zalando/zalenium#876]
## 🐛 Bug Report

After running a test which opens multiple windows, exited containers are not removed.

This behavior started after updated zalenium and elgalu/selenium on 18th of Feb 2019.

## To Reproduce

Open more than one browser, issue driver.quit(), check from dashboard that one container remains occupied.

## Expected behavior

driver.quit() closes all browsers and releases the container

## Environment

OS: Ubuntu
Zalenium Image Version(s): Do not know how to see this, "latest" from 2 days ago
Docker version: Do not know how to see this, "latest" from 5 days ago (Selenium
Grid Console v. 3.141.59)
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
docker run --rm -d -ti --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos -v /var/lib/jenkins/workspace:/tmp/node/home/seluser/workspace -e SEL_BROWSER_TIMEOUT_SECS=120 --privileged dosel/zalenium start --retentionPeriod 5 --timeZone "Europe/Helsinki" --maxDockerSeleniumContainers 30

**Comment by diemol** [comment]
Hi @jaasal,

Could you please provide a self contained test that reproduces the issue?

**Comment by diemol** [comment]
Closing as we didn't get more info about the issue.
