### ISSUE TITLE
Create selenium-node on a specific node

### ISSUE THREAD

**Issue by zpavlig** [zalando/zalenium#878]
hello

i have for example 5 nodes to k8s cluster, i want selenium-node to be created only first node. is it possible to do this?

zalenium version 3.141.59e
selenium-node version 3.141.59

**Comment by diemol** [comment]
Hi @zpavlig,
This is #662, a feature request, if you want to, you could give us a hand by sending us a PR :)

For now, I'll close this issue and follow up any other requests in #662
