### ISSUE TITLE
Default accessMode for PVCs should be ReadWriteOnce

### ISSUE THREAD

**Issue by MoonMoon1919** [zalando/zalenium#884]
## What
By default the PersistentVolumeClaim's specified in the Helm Chart should use the accessMode `ReadWriteOnce`. 

## Why
With the default provisioner on both AWS, GKE, and DigitalOcean, the provisioned disk types (EBS, Compute Engine Persistent Disks, and DigitalOcean BlockStorage respectively) don't support ReadWriteMany. For ReadWriteMany a user would need to set up a NFS via an available service on their provider or set up NFS as a service sitting on top of several PVs.

## What happens
By default PVCs will fail to provision which leaves the deployment hanging.

## Solution(s)
- Change default accessMode to ReadWriteOnce and describe setting up the nodeSelector in documentation if the user wants to use block storage. While this limits the user to a single node (EBS/CEPS/DOBS all can only be mounted to one node at a time) I have found this to be sufficient for the purposes Zalenium serves for small to medium sized teams running many large test suites 40+ times a day.
- If distributing the workload across nodes is desired by default, include an NFS setup on top of several PVs in the chart. This would include a deployment and a service, then some minor modification to the existing PVC templates to get working.

Thanks for the excellent product!

**Comment by diemol** [comment]
Thanks for the kind words @MoonMoon1919, closed in the above commit.
