### ISSUE TITLE
Does setting "--sendAnonymousUsageInfo false" refrains zalenium from collecting information like stacktrace, Test capabilities

### ISSUE THREAD

**Issue by RameshEmis** [zalando/zalenium#893]
Hi team,

We tried Zalenium in our company and its quit useful. We have a question that if we set "--sendAnonymousUsageInfo false" will it refrain zalenium from collecting information like stacktrace, Test capabilities. Also what kind of information will be collected from stack trace? 

Thanks.

**Comment by diemol** [comment]
Hi @RameshEmis,

Yes, when set to false, nothing is sent to Google Analytics.

**Comment by RameshEmis** [comment]
Thanks for the comment @diemol :)
