### ISSUE TITLE
Zelanium ECS task configuration

### ISSUE THREAD

**Issue by swsunnywadhwa** [zalando/zalenium#894]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium)
- [Slack channel - #zalenium channel](https://seleniumhq.herokuapp.com/)

**Comment by swsunnywadhwa** [comment]
Hi Guys,

I am facing an issue in Zelanium ECS task configuration.

Please let me know if someone is able to manage zelanium with ECS ec2. In my case zelanium container  is not working and its starting new task with unable to start the container.

**Comment by diemol** [comment]
Already replied in https://github.com/zalando/zalenium/issues/855#issuecomment-472577459
