### ISSUE TITLE
Directories containing logs are not removed on the dashboard reset

### ISSUE THREAD

**Issue by baflQA** [zalando/zalenium#901]
Zalenium version: 3.141.59i
Zalenium deployed to the K8S.
Persistent volumes enabled - 80Gb each.
Zalenium is running 24h/7. 
Every 30 mins, there is a curl sent to the Dashboard's Reset endpoint.
After a few days, on one of the Zalenium Hub restarts, the readiness probe starts to fail, and in the logs, I see that Zalenium has stopped somewhere there:
https://github.com/zalando/zalenium/blob/7552f4327881bb5fa00e0117370afffe982ae7c1/scripts/zalenium.sh#L395
The last message in the logs is: "Copying files for Dashboard..."

After some investigation, it turned out, that there are over 60k files and the 2700 directories in the videos partition:
```
videos/buildName/logs$ ls -ltr | head -10
total 10972
drwxr-xr-x 2 1000 1000 6144 Mar 12 21:12 zalenium_ET_crud_chrome_LINUX_20190312221136639_COMPLETED
drwxr-xr-x 2 1000 1000 6144 Mar 12 21:12 zalenium_ET_crud_chrome_LINUX_20190312221051861_COMPLETED
drwxr-xr-x 2 1000 1000 6144 Mar 12 21:13 zalenium_ET_crud_chrome_LINUX_20190312221049256_COMPLETED
drwxr-xr-x 2 1000 1000 6144 Mar 12 21:13 zalenium_ET_crud_chrome_LINUX_20190312221050626_COMPLETED
drwxr-xr-x 2 1000 1000 6144 Mar 12 21:13 zalenium_ET_crud_chrome_LINUX_20190312221102232_COMPLETED
drwxr-xr-x 2 1000 1000 6144 Mar 12 21:13 zalenium_ET_crud_chrome_LINUX_20190312221113999_COMPLETED
...
```
Each directory had givn content:
```videos/corey/logs$ ls -l 
testName_chrome_LINUX_20190318171857408_COMPLETED
total 912
-rw-r--r-- 1 1000 1000    215 Mar 18 16:19 chrome_browser.log
-rw-r--r-- 1 1000 1000 645365 Mar 18 16:19 chrome_driver.log
-rw-r--r-- 1 1000 1000      1 Mar 18 16:19 docker-selenium-status.log
-rw-r--r-- 1 1000 1000    124 Mar 18 16:19 firefox_browser.log
-rw-r--r-- 1 1000 1000  12111 Mar 18 16:19 fluxbox-tryouts-stderr.log
-rw-r--r-- 1 1000 1000      0 Mar 18 16:19 fluxbox-tryouts-stdout.log
-rw-r--r-- 1 1000 1000    209 Mar 18 16:19 novnc-stderr.log
-rw-r--r-- 1 1000 1000    939 Mar 18 16:19 novnc-stdout.log
-rw-r--r-- 1 1000 1000   2215 Mar 18 16:19 selenium-multinode-stderr.log
-rw-r--r-- 1 1000 1000     83 Mar 18 16:19 selenium-multinode-stdout.log
-rw-r--r-- 1 1000 1000   2087 Mar 18 16:19 supervisord.log
-rw-r--r-- 1 1000 1000      0 Mar 18 16:19 vnc-stderr.log
-rw-r--r-- 1 1000 1000     47 Mar 18 16:19 vnc-stdout.log
-rw-r--r-- 1 1000 1000  10566 Mar 18 16:19 vnc-tryouts-stderr.60000.log
-rw-r--r-- 1 1000 1000     11 Mar 18 16:19 vnc-tryouts-stdout.60000.log
-rw-r--r-- 1 1000 1000     69 Mar 18 16:19 wait-xmanager-stdout.log
-rw-r--r-- 1 1000 1000  60276 Mar 18 16:19 wait-xvfb.1.log
-rw-r--r-- 1 1000 1000  60276 Mar 18 16:19 wait-xvfb.2.log
-rw-r--r-- 1 1000 1000  60276 Mar 18 16:19 wait-xvfb-stdout.log
-rw-r--r-- 1 1000 1000      0 Mar 18 16:19 xmanager-stderr.log
-rw-r--r-- 1 1000 1000      0 Mar 18 16:19 xmanager-stdout.log
-rw-r--r-- 1 1000 1000      0 Mar 18 16:19 xterm-stderr.log
-rw-r--r-- 1 1000 1000    768 Mar 18 16:19 xterm-stdout.log
-rw-r--r-- 1 1000 1000     64 Mar 18 16:19 xvfb-tryouts-stderr.log
-rw-r--r-- 1 1000 1000      0 Mar 18 16:19 xvfb-tryouts-stdout.log
```

Each of the tests was created with given capabilities:
```Map<String, String> prefs = ImmutableMap.of(
                "name", envSetup.useEnvironment + ' ' + method.getName(),
                "build", "buildNme")
```
It looks like the logs coming from the named builds are not cleaned up on the reset, and on the pod restart it was timeout due to the huge number of files to copy.

**Comment by baflQA** [comment]
Hi @diemol. Any chance You can take a look there?

**Comment by diemol** [comment]
I have a bit of time this week, first I was testing and merging a few PRs we had, then we will release. After that I can have a look again.

**Comment by diemol** [comment]
@baflQA I tried to reproduce it but I could not. 
Of course, I had a clean installation, with files generated only during this test run. What makes me think... is it possible that you had files (videos/logs) generated before the new dashboard was released and tried to delete them with the new dashboard changed logic?
See https://github.com/zalando/zalenium/releases/tag/3.141.59h

**Comment by baflQA** [comment]
Hi. @diemol pls check the create dates of the dirs and files from the description. it's on the 12 of March. The new dashboard was released on 30th of January.
Did You add the build capability while trying to reproduce?

**Comment by diemol** [comment]
Yes, I did.
I made a video of the attempt to reproduce the issue, here it is:
https://drive.google.com/open?id=1ONSQjdpLICd_AQ2IFplA4iMvzYNiycok

Did I miss something that could help me to reproduce it?

**Comment by schlippi** [comment]
The thing is we do not record videos by default, only when requested. Every run basically just creates a folder without video files but containing log files. Those are then not correctly picked up by cleanup mechanism as it tries to find videos only.
