### ISSUE TITLE
Locally dashboard empty

### ISSUE THREAD

**Issue by SMorozovIT** [zalando/zalenium#902]
## 🐛 Bug Report

Hello, thanks for the product development, however
If you copy the directory in which the video tests, then when you open dashboard empty.
Previously, the file structure was different and it was possible to take the entire directory and dashboard opened correctly.
I used this folder as an artifact and displayed the test results in teamcity. Now it is always empty.
![image](https://user-images.githubusercontent.com/35658281/54740255-d83f9280-4bcb-11e9-87d7-cb8aaf6678fc.png)

## To Reproduce

- docker pull elgalu/selenium
- docker pull dosel/zalenium
- docker run --rm -ti --name zalenium -p 4444:4444 \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v /tmp/videos:/home/seluser/videos \
      --privileged dosel/zalenium start
- Run test
- After end test go to /tmp/videos and open dashboard 

## Expected behavior

The list of tests performed is the same as running like this - http://localhost:4444/dashboard

## Environment

Zalenium Image Version(s): 3.141.59i

**Comment by diemol** [comment]
@SMorozovIT 
Maybe there is something I am missing, I was trying it a moment ago and it works for me. Perhaps you are using `name` or `build` capabilities? If so, could you add a sample test please?

**Comment by diemol** [comment]
@SMorozovIT I just tried to run a couple of tests and setting the capability:
```
chromeCaps.setCapability("build", "Sample Build Name");
```

and things worked out for me fine locally, I'm actuallty attaching a zip file with the working offiline dashboard.

[videos.zip](https://github.com/zalando/zalenium/files/3137579/videos.zip)

Please have a look and let us know, if it is still not working for you, please provide a test so we can reproduce.

**Comment by diemol** [comment]
Closing as the issue got inactive.
