### ISSUE TITLE
kubernetes securtiyContext is not implemented in node spawning (rbac enabled)

### ISSUE THREAD

**Issue by EyalZilberblum** [zalando/zalenium#904]
## 🐛 Bug Report

KubernetesContainerClient not implementing securityContext, which leading to "Error: container has runAsNonRoot and image has non-numeric user (seluser), cannot verify user is non-root
"

## To Reproduce

rbac enabled on kubernates
adding securityContaxt to values.yaml of the helm chart:
 securityContext:
    enabled: true
    fsGroup: 1
    runAsUser: 1001

notice that replicaset is creating a pod using the securityContext we provide,
but the spawned containers does not inherit it from the values.yaml

**Comment by rajesh-kumar** [comment]
Hi, This is really crucial for us. Any updates on this, please?

**Comment by davidcollom** [comment]
I believe this was resolved in #918

**Comment by diemol** [comment]
Thanks @davidcollom! This will be released between tomorrow and Tuesday
