### ISSUE TITLE
Zalenium Memory/ CPU Issue.

### ISSUE THREAD

**Issue by AshwinK1989** [zalando/zalenium#906]
**Zalenium Image Version(s)**: latest
**Kernel Version**
Linux 4.15.0-1034-aws #36-Ubuntu SMP Tue Mar 5 23:17:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Docker Version**
Docker version 18.09.1, build 4c52b90

**Docker Compose**
docker-compose version 1.17.1, build unknown

**OS**
Ubuntu 18.04.1 LTS

**Server Specs**
2 Core vCPU, 8 GB RAM

**Docker Command to start Zalenium**: Executing through docker-compose.yml
Using latest elgalu image.

Following is the file:
```
# Usage:
#   docker-compose up --force-recreate
version: '2.1'

services:
  #--------------#
  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    tty: true
    mem_limit: 600000000
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      #- /usr/local/bin/docker:/usr/local/bin/docker
    ports:
      - 4444:4444
    command: >
      start
      --desiredContainers 1
      --maxTestSessions 3
      --videoRecordingEnabled false
      --sauceLabsEnabled false
      --browserStackEnabled false
      --testingBotEnabled false
      --startTunnel false
    environment:
      - HOST_UID
      - HOST_GID
      - ZALENIUM_SELENIUM_CONTAINER_MEMORY_LIMIT=1073741824
      - ZALENIUM_SELENIUM_CONTAINER_CPU_LIMIT=1073741824
```

**Expected Behvaiour:** 
8 Threads should run selenium tests parallely without error.

**Actual Behaviour:** 
Facing following 2 issues randomly even when I am running 3 threads parallely:
  1. Session was terminated due to FORWARDING_TO_NODE_FAILED (#783)
  2. Cannot forward the request unexpected end of stream on Connection (#742)
  3. We also removed the container's memory/cpu limits but still facing the same issue.

We also refered and tried out the solutions from both the above issues but it did not help.

Can someone please help to optimize both the zalenium application and the server so that we dont face any errors and are able to run it as expected?

**Comment by diemol** [comment]
@AshwinK1989,

The expected behaviour is extremelly optimist with only 2 CPUs and 8GB of RAM. Normally, one container needs 1CPU and 1GB of RAM, if video is used then add one more CPU. After that, start measuring the performance to adjust the number of threads.

See also https://github.com/zalando/zalenium/blob/master/docs/performance.md

**Comment by vinayhegde90** [comment]
@diemol thanks for the response but we've already referred the performance link as part of our debugging in setting CPU / Memory limits. We also `videoRecording` disabled so I believe 1 CPU / container suffice for us.

Meanwhile can you please confirm 2 things?
1. Does setting `mem_limit: 4294967296`, i.e: 4 GB for the main zalenium container throttle it in any way?

2. As per the CPU section [here](https://opensource.zalando.com/zalenium/), does setting `CPU Value 100000000 = 1 cpu` means allotting 1 Core dedicatedly to that container OR is it 1 CPU Cycle. What'd be the best values for a machine with 2/4 Cores?

**Comment by diemol** [comment]
But you are mentioning in the initial post that the server specs are 2 Core vCPU and 8 GB of RAM. With that you could run up to two tests in parallel without video, right?

**Comment by vinayhegde90** [comment]
Yes I did say that since we initially figured it as a server issue so we upscaled it to 4 Cores. We'll soon downscale as we're looking to **optimise** the machine with 2 Cores / 8 GB Ram for running our tests rather than increase hardware every time we run into performance issues.

Can you please guide us further with the aforementioned queries?
> @diemol thanks for suggesting the performance link but we've already referred it as part of our debugging in setting CPU / Memory limits. We also `videoRecording` disabled so I believe 1 CPU / container suffice for us.
> 
> Meanwhile can you please confirm 2 things?
> 
> 1. Does setting `mem_limit: 4294967296`, i.e: 4 GB for the main zalenium container throttle it in any way?
> 2. As per the CPU section [here](https://opensource.zalando.com/zalenium/), does setting `CPU Value 100000000 = 1 cpu` means allotting 1 Core dedicatedly to that container OR is it 1 CPU Cycle. What'd be the best values for a machine with 2/4 Cores?

**Comment by vinayhegde90** [comment]
@diemol can you please help us with the above queries?

**Comment by diemol** [comment]
>Does setting mem_limit: 4294967296, i.e: 4 GB for the main zalenium container throttle it in any way?

What do you mean exactly? That will just limit the amount of memory that the Zalenium container is allowed to use.

>CPU Value 100000000 = 1 cpu

`ZALENIUM_SELENIUM_CONTAINER_CPU_LIMIT` is used to set limits to the containers started from Zalenium. There is no CPU dedicated or alloted, it is just a limit. 


Overall, setting low limits to container does not help too much if the application under test uses lots of memory in the browser, this will just make things slow.

If you only have a 4 vCPU machine, start with 4 tests concurrently and measure CPU and RAM, if the usage is low, then go up one concurrent thread and so on... There is no unique formula for everyone, some apps use less memory and CPU than other ones, and the other way around.

Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.

**Comment by vinayhegde90** [comment]
@diemol thanks for recommending the Slack / StackOverflow channels & clarifying that `mem_limit` & `ZALENIUM_SELENIUM_CONTAINER_CPU_LIMIT` are just parameters to limit amount of memory and number of CPUs respectively.

As you mentioned, we're concurrently running 4 tests on a 4 vCPU machine and herein we've found one parameter useful to enforce CPU/Memory optimisation which is `--maxDockerSeleniumContainers X` which we've currently set to 4 (_we'll be gradually increasing this_)

For anyone with a similar use-case: Without the above parameter, we've observed Zalenium spawns upto 8 containers consuming resources quickly that's controllable as specified above.
