### ISSUE TITLE
 zalenium exited with code 1 error--seleniumImageName 

### ISSUE THREAD

**Issue by Pratish-minted** [zalando/zalenium#914]
@diemol 
## 🐛 Bug Report

when try to bring zalenium docker image using below compose file it doesn't take           
`  --seleniumImageName elgalu/selenium:latest`
 and throws error 
Creating network "auto_default" with the default driver
```
Creating zalenium ... done
Attaching to zalenium
zalenium    | Docker version 18.09.0, build 4d60db4
zalenium    | -- LOG 13:35:22:592917823 Ensuring docker works...
zalenium    | -- LOG 13:35:22:658976853 Ensuring docker-selenium is available...
zalenium    | Seems that docker-selenium's image has not been pulled yet
zalenium    | Please run 'docker pull elgalu/selenium', or use your own compatible image via --seleniumImageName
zalenium exited with code 1
```

Does `--seleniumImageName` work? 

here is docker-compose.

```
# Usage:
#   docker-compose up --force-recreate
version: '2.1'

services:
  #--------------#
  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - 4444:444
    command: >
      start --desiredContainers 8
            --maxDockerSeleniumContainers 10
            --screenWidth 1920 --screenHeight 1200
            --timeZone "America/Los_Angeles"
            --videoRecordingEnabled false
            --seleniumImageName "elgalu/selenium:latest"
            --sauceLabsEnabled false
            --browserStackEnabled true
            --testingBotEnabled false
            --startTunnel true
    environment:
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
```

## To Reproduce

Steps to reproduce the behavior (including the docker command/docker-compose/Kubernetes manifests to start Zalenium):

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: OSX 
Zalenium Image Version(s): LATEST 
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
If using Kubernetes, specify your environment, and if relevant your manifests:

**Comment by diemol** [comment]
@Pratish-minted 
As per the message
`zalenium    | Please run 'docker pull elgalu/selenium', or use your own compatible image via --seleniumImageName`.

Please pull `docker pull elgalu/selenium`, you are trying to use it but you have not pulled it.
