### ISSUE TITLE
No control over the browser version being used on containers for our test. Browser comes with selenium image. For different browser version, need to pull different docker image.

### ISSUE THREAD

**Issue by nisargdave1993** [zalando/zalenium#923]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium)
- [Slack channel - #zalenium channel](https://seleniumhq.herokuapp.com/)

**Comment by nisargdave1993** [comment]
Suppose I want to run my tests on Chrome Browser's 73.0.3683.86 version, then Can we consider an option of specifying the browser version while starting zalenium ? i.e. docker run --rm -ti --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start --timeZone "Asia/Kolkata" --screenWidth 1280 --screenHeight 720 **--chromeVersion "73.0.3683.86"**

**Comment by nisargdave1993** [comment]
It should pull the version runtime in image.

**Comment by diemol** [comment]
@nisargdave1993 this not supported at the moment, would you like to send us a PR with those improvements?

**Comment by nisargdave1993** [comment]
@diemol : I am not sure, what a PR is .. Is it a problem record ? And can you please let me know how to raise the same ?

**Comment by diemol** [comment]
Sorry, I just thought it was clear. 
Here you can read about PRs https://help.github.com/en/articles/about-pull-requests

Which is basically a way to contribute to open source, in this case you are seeing an opportunity to improve this open source project, therefore you could help us by implementing the feature and sending us a pull request (PR).

**Comment by diemol** [comment]
Merged into #654 since this is a feature request, if someone is interested to contribute and development starts we will reopen this issue.
