### ISSUE TITLE
New Zalenium dashboard - No build name

### ISSUE THREAD

**Issue by micheletest** [zalando/zalenium#925]
## 🐛 Bug Report

I am testing an upgrade from zalenium:3.141.59d to zalenium:3.141.59j, so I expected to see the new dashboard. I am setting the build capability, but no longer see the build in the new dashboard. We run alot of builds, and could get to over 5000 tests per day, so use this heavily to filter tests. Thanks for any help here.

The build is being set properly behind the scenes. I do see the video stored by build on the kubernetes grid pod.

## To Reproduce

1. Run a test while setting capability['build'] to something
2. Check the dashboard.

## Expected behavior

I would like to see the build that I set in the dashboard.

## Test script reproducing this issue (when applicable)

None developed yet.

## Environment

OS: Linux 4.4.121-k8s x86_64
Zalenium Image Version(s): zalenium:3.141.59j
Docker version: Docker version 18.06.1-ce, build d72f525745
Docker-Compose version (if applicable): N/A
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
If using Kubernetes, specify your environment, and if relevant your manifests: kubernetes 1.9

## Related capabilities

```20:18:10.361 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome",
  "goog:chromeOptions": {
    "args": [
      "--disable-dev-shm-usage",
      "--no-sandbox",
      "--disable-infobars",
      "--disable-extensions"
    ],
    "extensions": [
    ]
  },
  "tags": [
    "c9727a66c02c4f8c82ea89fb0691f43343730efb",
    "zalenium-upgrade"
  ],
  "zal:build": "80034",
  "zal:idleTimeout": 160,
  "zal:name": "test_segment",
  "zal:resolution": "1440x1440"
}
```

Also attaching a screenshot of the test where the capability is set, but there is no build in the display.

<img width="1674" alt="Screen Shot 2019-04-04 at 4 34 41 PM" src="https://user-images.githubusercontent.com/1161578/55586726-a7954800-56f7-11e9-916e-a9983cc85ad1.png">

**Comment by micheletest** [comment]
I am having a different issue where searching isn't working, but the error in chrome devtools makes make me think it may be related.  I can put in a different issue if it's not.

1. In the new dashboard, search by test name
2. It doesn't work, nothing is filtered

Chrome devtools error:

`dashboard.js:186 Uncaught TypeError: $(...).data(...).toUpperCase is not a function
    at HTMLAnchorElement.<anonymous> (dashboard.js:186)`

dashboard.js is:

```
const currentKeyword = $(this).text().toUpperCase() + $(this).data("browser").toUpperCase() +
                $(this).data("platform").toUpperCase() + $(this).data("test-build").toUpperCase() +
```

**Comment by diemol** [comment]
Hi @micheletest,
I made a video of the attempt to reproduce the issue, here it is:
https://drive.google.com/open?id=1ONSQjdpLICd_AQ2IFplA4iMvzYNiycok

Did I miss something that could help me to reproduce it?

**Comment by micheletest** [comment]
@diemol Thanks for looking at this. Your video was really helpful. I tried a few cases on my side and I think I got it.  If I set the build capability to a string that's just a number `90210` I can reproduce my issue. Can you try that?

If I set the build capability to a string/number combination, like `build_90210`, it works. As a workaround, that's what I'm going to do for now.

To be specific, in my case with python:
`session_capabilities['build'] = 'build_90210'` works
`session_capabilities['build'] = '90210'` does not work.

Thanks again.

**Comment by diemol** [comment]
Thanks for the hint @micheletest, just fixed it and it will be released soon.
