### ISSUE TITLE
Video not containing audio

### ISSUE THREAD

**Issue by M-Younus** [zalando/zalenium#928]
## 🐛 Bug Report

Videos not containing audio.
Is there any flag I have to pass for audio?I already look into 'github issues' and 'stackoverflow' as well and didn't find anything related to getting audio.
Thanks

**Comment by jithinkmatthew** [comment]
@M-Younus, Usually, running test doesn't need audio. Could you please explain, what are you trying to achieve by adding audio?

**Comment by M-Younus** [comment]
@jithinkmatthew  for my usecase I need audio too :(.

**Comment by diemol** [comment]
Zalenium uses VNC, which so far does not support audio, some additional things would need to be done like adding pulseaudio and another layer on top to put video and audio together. So, the short answer is: it is not possible.

**Comment by mohammadsaleh** [comment]
Hi @diemol ,

"elgalu/docker-selenium" you have used support video whit audio recording, why don't you update?

**Comment by diemol** [comment]
Nothing needs to be done in Zalenium @mohammadsaleh, you just need to pull the latest `elgalu/selenium` image.

**Comment by mohammadsaleh** [comment]
Thank you @diemol for fast reply,

I have pulled the latest version but doesn't record with sound. I have mounted '/dev/snd" as devices too but dosn't work. what should I do?

**Comment by diemol** [comment]
I am not sure, maybe an extra variable is needed in the container, what does the documentation of `elgalu/selenium` say?

**Comment by mohammadsaleh** [comment]
here is the closed issue:
https://github.com/elgalu/docker-selenium/pull/372

**Comment by diemol** [comment]
How do you run a test with `elgalu/selenium` and recording sound? Without Zalenium

**Comment by mohammadsaleh** [comment]
Just as this document:

https://github.com/elgalu/docker-selenium/commit/97931576bac30b6c349de06913a09c2834cb214c#diff-6cdba8648313fb83883fc05562f9ac3cR52

I run elgalu/selenium and send a GET request to a video in youtube and then play that.

**Comment by diemol** [comment]
I just checked the code briefly, and Zalenium would need to pass the `AUDIO=true` env var to `elgalu/selenium`. But we are not working on Zalenium anymore, so that change is not going to happen.
Alternatives are:
- You can fork Zalenium and do the change around [here](https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/proxy/DockeredSeleniumStarter.java#L343)
- You build your own `elgalu/selenium` image and have `AUDIO=true` enabled by default.

**Comment by mohammadsaleh** [comment]
Ok, I will try and send you result.

Thanks

**Comment by mohammadsaleh** [comment]
@diemol 
I got error while building 

```
Step 42/54 : ENV ZAL_VER="${project.build.finalName}"     BROWSER_STACK_TUNNEL_OPTS="-skipCheck -v -forcelocal"     BROWSER_STACK_TUNNEL_ID="zalenium"     BROWSER_STACK_TUNNEL="false"     BROWSER_STACK_WAIT_TIMEOUT="2m"     SAUCE_TUNNEL_MAX_RETRY_ATTEMPTS="1"     SAUCE_TUNNEL_READY_FILE="/tmp/sauce-connect-ready"     SAUCE_TUNNEL_ID="zalenium"     SAUCE_TUNNEL_DOCTOR_TEST="false"     SAUCE_WAIT_TIMEOUT="2m"     SAUCE_TUNNEL="false"     TESTINGBOT_TUNNEL_OPTS="--se-port 4447"     TESTINGBOT_TUNNEL="false"     TESTINGBOT_WAIT_TIMEOUT="2m"     TESTINGBOT_TUNNEL_ID="zalenium"     CBT_TUNNEL_ID="zalenium"     CBT_TUNNEL="false"     LT_TUNNEL_ID="zalenium"     LT_TUNNEL="false"     SELENIUM_HUB_PARAMS=""     SELENIUM_NODE_PARAMS=""     SELENIUM_CONTAINER_LABELS=""     SELENIUM_WAIT_FOR_CONTAINER="true"
failed to process "\"${project.build.finalName}\"": missing ':' in substitution
```

this is how I try to build it:

```
git clone https://github.com/zalando/zalenium.git .
docker build -t test/zalenium ./docker/

```
is it true?

**Comment by diemol** [comment]
Please read this section https://opensource.zalando.com/zalenium/#contributing
It has all the instructions to build your own Zalenium

**Comment by mohammadsaleh** [comment]
Hmm ... Thanks

**Comment by mohammadsaleh** [comment]
@diemol 
I have error while trying to build.

`[ERROR] Failed to execute goal org.codehaus.mojo:aspectj-maven-plugin:1.11:compile (default) on project zalenium: Execution default of goal org.codehaus.mojo:aspectj-maven-plugin:1.11:compile failed: Plugin org.codehaus.mojo:aspectj-maven-plugin:1.11 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:10.0.2 at specified path /usr/lib/jvm/java-10-openjdk-amd64/../lib/tools.jar -> [Help 1]`

I am using this command:
`docker run -it --rm --name my-maven-project -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:latest mvn clean package`

**Comment by diemol** [comment]
Sorry, but I don't know where that error comes from, I've never compiled Zalenium with the maven docker image.

**Comment by pearj** [comment]
You’re trying to compile with jdk 10. That isn’t supported, you need to use jdk 8, because of the aspectj plugin.
