### ISSUE TITLE
Add Servlet to clean actives sessions

### ISSUE THREAD

**Issue by jlamaille** [zalando/zalenium#931]
We use zalenium on our computers and in a continuous deployment chain.
On local computers, we want to keep our Selenium nodes on many iterations and especially to be able to stop our tests in debug mode without properly releasing the node.
So, to be sure to leave on a free probe without having to recreate one, I would like to be able to add a session management servlet with a cleanUp action for active sessions.

I have already done this development, I plan to make a pull request soon.

What do you think about that?

**Comment by diemol** [comment]
Hi @jlamaille, we would be happy to receive a PR that does that.

I'll close this one and we can continue the conversation in the future PR, thanks!
