### ISSUE TITLE
Is '--chromeContainers'  parameter available for Kubernetes env as well? if not how can i use them?

### ISSUE THREAD

**Issue by akshattambe** [zalando/zalenium#932]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium)
- [Slack channel - #zalenium channel](https://seleniumhq.herokuapp.com/)

**Comment by diemol** [comment]
The parameter is called `--desiredContainers`.

This is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
