### ISSUE TITLE
links in/to some k8s docs are broken

### ISSUE THREAD

**Issue by pdebruic** [zalando/zalenium#934]
## 🐛 Bug Report
On the homepage and in comments on issues people linked to docs and yaml files that are now gone.

e.g.
on the home page in the Google Container Engine section
https://github.com/zalando/zalenium/blob/master/docs/k8s/gke/plumbing.yaml

in issue #499 the suggestion for the helm template points to 
https://github.com/zalando/zalenium/tree/master/docs/k8s/helm

## To Reproduce

Click the links

## Expected behavior

The links should go to the resources the authors intended

## Environment
Web.......

**Comment by diemol** [comment]
@pdebruic where did you find the links? Maybe you can help us to either remove them or link them to the proper docs?

**Comment by pdebruic** [comment]
As far as I can see in the repo the dierctory with the docs are gone.   

The links on the home page are in the "Google Container Engine" expandable section of the home page as I described and in various issues.  


Someone deleted the k8s directory from the docs directory and now the links to that directory fail.

**Comment by pdebruic** [comment]
I'm not going to do more than this btw

**Comment by diemol** [comment]
There was a refactor of the Kubernetes docs to point all resources to the helm chart, which should be working in all environments. Probably we missed some links, and thankfully you have found those issues. I will remove all that part since people should be using just the helm chart.
Thanks for reporting this.
