### ISSUE TITLE
Zalenium as Hub and with Nodes from different Host

### ISSUE THREAD

**Issue by arunaousula9421** [zalando/zalenium#938]
Hi Guys,

I have been trying to setup Zalenium as hub in one host and then use different host to connect them as nodes to the hub using docker. 

Can I please know if there anyway I can do this,  I have tried running Zalenium on a host with 8 Containers which is very slow so I would like to use different hosts to connect to the hub and run the tests.

Any link or sample example would be helpful

**Comment by diemol** [comment]
@arunaousula9421 right now that is not possible, the only option to do that is with Kubernetes. During the end of this week we will have a look at #907, which could help your case. 
Keep an eye on the repo during the next weeks.

**Comment by arunaousula9421** [comment]
@diemol As you said I am trying things with Kubernetes. Is there any documentation I can refer to setup Zalenium as hub and Node separately?? When I looked into Zalenium website it only mentions details about the things to setup the things on Kubernetes but not about configuring them as Hub and Node

**Comment by diemol** [comment]
There is no concept of placing a hub and nodes separately in Zalenium because Zalenium creates the nodes on demand.
