### ISSUE TITLE
🚀 LambdaTest support

### ISSUE THREAD

**Issue by nextlevelbeard** [zalando/zalenium#947]
## 🚀 Feature Proposal

Add ability to run tests on the [Lambdatest](https://www.lambdatest.com/) third-party service, as done recently with the [CrossBrowserTesting](https://crossbrowsertesting.com/) service  in #898 (#929 #935)

## Motivation

Zalenium should try to support as many third-party services as possible in order to give users a choice. Lambdatest happens to have one of the most accessible plans in terms of pricing.

## Example

The feature would be used as all the other third-party services are used: BrowserStack, SauceLabs, CrossBrowserTesting, TestingBot.

**Comment by diemol** [comment]
@nextlevelbeard absolutely, we would happily add more integrations in case someone is interested to implement them. Keep in mind that CrossBrowserTesting was added because they sent a PR for it, I just helped a bit in the end to have things completed.

Would you like to contact Lamdatest and request the integration?

**Comment by nextlevelbeard** [comment]
From LambdaTest support:

> Currently, our tech team is working on to bring Mobile Web Automation on our platform. Once this feature is deployed on the production, the team would start working on Zalenium. It might take 8-10 weeks for Zalenium to get live on production.

So good news, they'll be actively contributing towards this.

**Comment by diemol** [comment]
That's great news @nextlevelbeard!
I've merged this request into #654, and hopefully they can give us a hand!

**Comment by jjdia** [comment]
Any word on this feature?

**Comment by diemol** [comment]
No clue, maybe @nextlevelbeard knows.

**Comment by nikhil-lambda** [comment]
hi @diemol 

Created a pull request after extensive testing #988. Need your support to merge the pull request. 👍.
@nextlevelbeard  Good news for you.  Zalenium will start supporting LambdaTest shortly.  We are happy to help you.
