### ISSUE TITLE
userdatadir config

### ISSUE THREAD

**Issue by onlonely** [zalando/zalenium#948]
I would like to configure the following:

ChromeOptions options = new ChromeOptions(); 
options.addArguments("user-data-dir=/tmp/userdata");

But the selenium parameter is not customized,

Excuse me, do I think the need to persist user data can be achieved?

**Comment by diemol** [comment]
Hi @onlonely,

Could you explain a bit more? Why do you need a specific profile directory?

**Comment by diemol** [comment]
I'll close this since it is not really clear what it is intended, feel free to join us in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y) where the community can help you as well.
