### ISSUE TITLE
Discussion: labels "version" and "appVersion" in the Helm chart

### ISSUE THREAD

**Issue by axozoid** [zalando/zalenium#951]
Hi guys, just wanted to discuss about `version` and `appVersion` in:
https://github.com/zalando/zalenium/blob/ba05d55cc60e137d3f2c1e05a95dbf1b2aa5a974/charts/zalenium/Chart.yaml#L2-L3

I would suggest keeping them different, to follow [Helm](https://helm.sh/docs/developing_charts/#charts-and-versioning) documentation.

Because updating `version` in the helm chart every time Zalenium got a new release doesn't make much sense - the helm chart (`version`) has not been changed, but the application version it deploys - has been changed (`appVersion`).

What are your thoughts?

**Comment by arnaud-deprez** [comment]
Hi @axozoid,

I would be for it if we would manage the chart and zalenium in a different git repo but in this context, I think it makes more sense to manage this in the same git repo.

My argues are: 

- Having different versions make it harder to find out which chart version is compatible with which zalenium version
- Dealing with one version that should match a git tag is IMO way more convenient than having different versions under the same tag.
- Having to deal with 2 versions makes it harder or impossible to automatically update these files (see #917), so it involves more human action and so potentially more errors.

**Comment by diemol** [comment]
We could create the chart already in the http://github.com/dosel org, and handle everthing there. At some point we will move this repo there as well, but if it simplyfies things, as I said, we could create the repo for the chart there.

Would you like to contribute @axozoid?

**Comment by axozoid** [comment]
Hi @diemol, sure, I'm happy to contribute.

**Comment by diemol** [comment]
I close this and I'll let @elgalu handle the repo creation in case we decide to host the helm chart there.
