### ISSUE TITLE
unknown flag: --maxDockerSeleniumContainers when setup on windows machine

### ISSUE THREAD

**Issue by piyugit** [zalando/zalenium#952]
## To Reproduce

Steps to reproduce the behavior (including the docker command/docker-compose/Kubernetes manifests to start Zalenium):

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Zalenium Image Version(s): 
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
If using Kubernetes, specify your environment, and if relevant your manifests:

**Comment by diemol** [comment]
@piyugit 
Can you please add:

> Steps to reproduce the behavior (including the docker command/docker-compose/Kubernetes manifests to start Zalenium):
