### ISSUE TITLE
Spread tests across multiple zalenium containers

### ISSUE THREAD

**Issue by jandialrajiv** [zalando/zalenium#954]
## 💬 Questions and Help
can you please help me on- how can we configure our tests to run on multiple zalenium containers? I want to run my 300 + tests across 10 containers so that I can get the results as quick as I can. looking forward to hear on what you guys did?

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium)
- [Slack channel - #zalenium channel](https://seleniumhq.herokuapp.com/)

**Comment by jandialrajiv** [comment]
@diemol can you please help!

**Comment by diemol** [comment]
Hi @jandialrajiv 

This is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y) or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
