### ISSUE TITLE
Zalenium one line installer script doesn't work anymore with Homebrew 2.x

### ISSUE THREAD

**Issue by RiZKiT** [zalando/zalenium#955]
## 🐛 Bug Report

The "Zalenium one line installer" script (https://raw.githubusercontent.com/dosel/t/i/p), uses `brew install grep --with-default-names`, this parameter is not supported anymore in Homebrew 2.x, instead you have to modify the PATH variable in `.bashrc`, see also https://github.com/Homebrew/brew/issues/5731.

## To Reproduce

Run one line installer.

## Expected behavior

A better description what to do and do not use --with-default-names anymore.

## Test script reproducing this issue (when applicable)

brew install grep

## Environment

OS: MacOS 10.14.4
Homebrew: 2.1.1

**Comment by antlong** [comment]
The code for the one-liner lives in a different repo: https://github.com/dosel/t/

I made a pull request there to fix this issue: https://github.com/dosel/t/pull/7

I made a pull request here to use the updated url in the readme as-well: https://github.com/zalando/zalenium/pull/1045

In the meantime, you users can run the one-liner with `curl -sSL https://raw.githubusercontent.com/antlong/t/i/p | bash -s start`

**Comment by diemol** [comment]
Fixed via https://github.com/dosel/t/pull/7, thanks @antlong!

**Comment by antlong** [comment]
@diemol just submitted another PR, the fi wasn't closed in the PR i submitted since it had caught up the beginning of another PR i was working on.
