### ISSUE TITLE
ScreenResolution does not change browser screen size

### ISSUE THREAD

**Issue by dmngu9** [zalando/zalenium#966]
## 🐛 Bug Report

I use Nightwatch to run my e2e tests. In desiredCapabilities in Nightwatch test setting I specify 

`
desiredCapabilities: {
    browserName: 'chrome',
    chromeOptions: {
      args: ['--no-sandbox', '--no-proxy-server', '--headless', '--disable-gpu', 'window-size=2560,1200'],
      prefs: {
        credentials_enabled_service: false,
        'profile.password_manager_enabled': false,
      },
    },
    marionette: true,
    screenResolution: '2560x1200',
    webStorageEnabled: true,
    recordVideo: true,
  },
`

But the screen size is not matched the one specified and seem be to lots smaller

**Comment by diemol** [comment]
Because it must be `goog:chromeOptions`, not just `chromeOptions`.
