### ISSUE TITLE
Connect refused when using clean all active sessions

### ISSUE THREAD

**Issue by jlamaille** [zalando/zalenium#970]
## 🐛 Bug Report

I detected an anomaly when using the active session cleaning feature that I recently pushed.
If you start a test class with several tests, when running the second test, you force the cleaning of the active sessions while a thread already cleaning these sessions is running. This generates an error of the Connect Refused type.
java.net.ConnectException: Connection refused (Connection refused)
Command duration or timeout: 0 milliseconds
**I will fix this problem quickly. The fix is already almost finished**

## To Reproduce
Using one of Selenium Grid
- Launch a test class containing several tests
- Between each test, call the cleaning url for active sessions (http://localhost:4444/grid/sessions?action=doCleanupActiveSessions)

## Expected behavior
All tests are passed

## Environment
OS: All
Zalenium Image Version(s): 3.141.59n
Docker version: All

**Comment by diemol** [comment]
Closed via #971, will be released in the next days.
