### ISSUE TITLE
Implement container-scoped securityContext configuration

### ISSUE THREAD

**Issue by martincfo** [zalando/zalenium#973]
Hi, this request is similar to #904; however, in this case we'd like to have the container-scoped securityContext configurable, and passed to the spawned pods.   

This would allow us to set capabilities for the spawned containers (such as NET_ADMIN), which would in turn enable us to run tc/netem to induce impaired networking conditions in the client browser test environment.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#securitycontext-v1-core

Please let me know if you'd like further elaboration.

Thanks,
Martin

**Comment by diemol** [comment]
Hey @davidcollom @arnaud-deprez, do you have any thoughs about this?

**Comment by davidcollom** [comment]
I think its something to investigate implementing, the hub may not always need/want the same level of permissions than that of the nodes, similar to that of the kubernetes service account.

**Comment by arnaud-deprez** [comment]
Hi @diemol,

Sorry for the delay, it is indeed something I can look into.
Will keep you posted :-)
