### ISSUE TITLE
Zalenium nodes die when proxy is set through command line

### ISSUE THREAD

**Issue by MentalDisruptor** [zalando/zalenium#974]
## 🐛 Bug Report

When Zalenium is launched with a proxy passed in to be used by containers, containers die shortly after 2 minutes runtime and are restarted. This is reproducible regardless of which proxy is passed.

## To Reproduce

Steps to reproduce the behavior (including the docker command/docker-compose/Kubernetes manifests to start Zalenium):

Launch Zalenium with 
```
docker run -d --rm -ti --name zalenium -p 4444:4444 \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v /home/dmc/zalenium/videos:/home/seluser/videos \
          -e "zalenium_http_proxy=__YOUR_PROXY__:__YOUR_PROXYPORT__" \
          -e "zalenium_https_proxy=__YOUR_PROXY__:__YOUR_PROXYPORT__" \
          -e "zalenium_no_proxy=172.16/12, 10.0.0.0/8, *.local, 169.168.99.*, localhost, 127.0.0.1" \
          --privileged dosel/zalenium start \
          --desiredContainers 1 \
          --videoRecordingEnabled false
```

In a second terminal, you could do something like
`watch -n 0.2 docker container ls`
to watch container status / uptime.

## Expected behavior

Since $desiredContainers was set to 1, there should be 1 node running constantly, without being restarted after a certain time.

## Test script reproducing this issue (when applicable)

Can be reproduced just by launching above command. Container termination can be observed with provided watch command. Each (re-)launched container will not live longer than 2 minutes.

## Environment

OS: Ubuntu 18.04 amd64
Zalenium Image Version(s): currently updated to latest each nightly restart
Docker version: 18.09.1, build 4c52b90
Docker-Compose version (if applicable): not applicable
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): please see command in Reproduction section.
If using Kubernetes, specify your environment, and if relevant your manifests: n/a

**Comment by diemol** [comment]
Hi @MentalDisruptor,

Have you checked this [issue](https://github.com/zalando/zalenium/issues/679)? More specifically this [comment](https://github.com/zalando/zalenium/issues/679#issuecomment-433008829)?

**Comment by MentalDisruptor** [comment]
Hi @diemol,

I stumbled across the mentioned issue and skimmed over it, but apparently not thoroughly enough. Thank you very much, I think that will help resolving my issue.
