### ISSUE TITLE
Update documentation with SAUCE_LABS_API_URL

### ISSUE THREAD

**Issue by mcopjan** [zalando/zalenium#975]
## 🐛 Bug Report
I have tried to run tests using SauceLabs through Zalenium following official documentation https://opensource.zalando.com/zalenium/ and it took me a while to realize that because of using SauceLabs EU data center I need to override SAUCE_LABS_API_URL as per https://github.com/zalando/zalenium/issues/903
Please update the documentation to make information clearer.

This is working command:
``
docker run --rm -ti --env SAUCE_USERNAME="<my user name>" --env SAUCE_ACCESS_KEY="<my key>" --env SAUCE_LABS_URL="http://ondemand.eu-central-1.saucelabs.com/wd/hub" --env SAUCE_LABS_API_URL="https://eu-central-1.saucelabs.com/rest/v1/" --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel
/zalenium start --videoRecordingEnabled false --sauceLabsEnabled true --desiredContainers 1
``

Lastly thanks a lot for all the hard job and effort you put into this project.

**Comment by diemol** [comment]
@mcopjan it is already documented:
https://opensource.zalando.com/zalenium/#docker

![image](https://user-images.githubusercontent.com/5992658/58171607-aa8fcc00-7c96-11e9-9f18-64e585695438.png)

**Comment by mcopjan** [comment]
@diemol my apologies

**Comment by diemol** [comment]
No worries!
