### ISSUE TITLE
Be able to configure http proxy for reaching browserstack

### ISSUE THREAD

**Issue by davidkarlsen** [zalando/zalenium#979]
## 🚀 Feature Proposal

Some corp environments don't have direct access to internet and need to funnel requests through a http-proxy.

## Motivation

Be able to utilize browserstack (or other cloud providers) services even if running inside a locked down environment.

## Example

Define HTTP proxy values in the k8s chart, and make the cloud-services go through the defined proxy.

**Comment by diemol** [comment]
Merged into #654

**Comment by MarS919** [comment]
+1. We would need exactly the same capability.
