### ISSUE TITLE
It's hard to locate a test video in the dashboard

### ISSUE THREAD

**Issue by aalgarme** [zalando/zalenium#98]
![image](https://cloud.githubusercontent.com/assets/10726943/25151998/a8580ac4-2455-11e7-8643-3bf656fe2f01.png)

**Comment by diemol** [comment]
@aalgarme sure!
Those characters you see there are the `seleniumSessionId`, which is used when the test name is not available. You can make the test name available by passing it as a capability in your test.
Check the example [here](https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#test-name)

**Comment by diemol** [comment]
I'll close this one since it was a question which already has an answer. Please feel free to open more issues in case of errors or more questions.
