### ISSUE TITLE
Does Zalenium supports Perfecto mobile cloud ?

### ISSUE THREAD

**Issue by Elangopalakrishnan** [zalando/zalenium#986]
Hi ,

Zalenium is one of the coolest tool to organize the grid. Thanks a lot for this...

and I saw that zalenium supports cloud testing provider (Sauce Labs, BrowserStack, TestingBot, CrossBrowserTesting).

Is there any possibilities to have a perfecto cloud in this list ?

Please reply back, if any possibilities to have perfecto in this list.

So that I can suggest my business team to use Zalenium forever.

Thanks in advance.

**Comment by diemol** [comment]
Hi @Elangopalakrishnan,

It does not. Please be aware that support for other providers was mostly added by the providers themselves (TestingBot and CrossBrowserTesting). You could also send us a PR to add support.
