### ISSUE TITLE
java.io.IOException: Too many open files

### ISSUE THREAD

**Issue by megolee** [zalando/zalenium#998]
## 🐛 Bug Report
Running tests in parallel for more than 1 hour and than it will through Too many open files exception.

<img width="1425" alt="Many" src="https://user-images.githubusercontent.com/9957802/61121128-12150b80-a4d1-11e9-8c44-0ade3ef557aa.png">

## To Reproduce

Running tests in parallel for more than 1 hour 

## Expected behavior

Tests run without error

## Test script reproducing this issue (when applicable)

Running tests in parallel for more than 1 hour

## Environment

OS: CentOS7
Zalenium Image Version(s): 3.141.59n 
Docker version: latest
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
`docker run -d --rm -ti --name zalenium -p 7878:4444 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/videos:/home/seluser/videos \
    --privileged dosel/zalenium:3.141.59n start --screenWidth 1280 --screenHeight 960 --timeZone "Asia/Shanghai"`

**Comment by diemol** [comment]
I tried to reproduce and didn't run into the issue. Please provide a clear way to reproduce this issue.

**Comment by diemol** [comment]
Closing this issue as we didn't get a reply from the original poster. 

If someone is facing this issue, feel free to comment and provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).
